### ISSUE TITLE
documentation for deploying/installing to openshift

### ISSUE THREAD

**Issue by Gl4di4torRr** [tektoncd/dashboard#100]
Does documentation exist on how to deploy/install this on openshift?

**Comment by dibbles** [comment]
Documentation does not currently exist for installing on openshift ..... currently mostly only really been tested/developed with docker desktop.  Testing does need to be broadened and docs created for multiple providers.

**Comment by Gl4di4torRr** [comment]
@dibbles cool - i will play around with the running the dashboard locally and then try and push it to openshift. Maybe I can work on some docs for you all :)

**Comment by vtereso** [comment]
I have okd set up on a VM so I will also checking this as well. Will update this issue with my findings.

**Comment by vtereso** [comment]
@Gl4di4torRr Please see the following repo: https://github.com/vtereso/okd-tekton-dashboard-install. Let me know if that helps 😄

**Comment by Gl4di4torRr** [comment]
@vtereso i am thinking about doing this with a deployment config, custom resource definition or something like that.

**Comment by vtereso** [comment]
Regarding specifically the deployment of the dashboard, there is something currently in the works. As for the other pieces that that scripts automates, it uses operators, which use CRDs.

**Comment by Gl4di4torRr** [comment]
@vtereso can you elaborate more on what's in the works?

Currently I am just trying to run the dashboard locally... I've succeeded with the `npm start` of the development server, but still trying to get `ko` to work properly.. 

```
error: unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
```

However, I am new to this but high-level it would be nice to see some steps like

```
oc login ...
oc apply -f rbac.yml
oc apply -f dashboard-deploy.yml
```

I am thinking out-of-the-box functionality. But by deploying the dashboard, would that assume the pipeline is already deployed (pre-requisite)?

**Comment by vtereso** [comment]
Installation of the Dashboard deployment:
```
docker login
export KO_DOCKER_REPO=docker.io/<mydockername>
ko apply -f config
```
The npm commands are for the "front end" of the dashboard, which will eventually be served through the backend directly
A operator to install the dashboard is currently being looked into, but whether or not the prerequisites (that the above repo installs) will be included is uncertain

**Comment by mnuttall** [comment]
@akihikokuroda I know you've been looking at an Operator install for the Dashboard. I know we don't have an image in `gcr.io` yet but do you have work in a fork that you can link here to show what you've been doing please?

**Comment by akihikokuroda** [comment]
Here is my fork of the Tektoncd-pipeline-operator: https://github.com/akihikokuroda/tektoncd-pipeline-operator/tree/dashboard.  I added the dashboard install in the operator.  I've just changed /deploy/resoures/v0.3.1/release.yaml to include the dashboard deployment.  I hardcoded my private docker hub registry  as the dashboard image location for now.  I'll create another branch for the README update.

**Comment by akihikokuroda** [comment]
I created a PR for README update. https://github.com/openshift/tektoncd-pipeline-operator/pull/10

**Comment by Gl4di4torRr** [comment]
@akihikokuroda nice - i'll check it out

**Comment by Gl4di4torRr** [comment]
@akihikokuroda are you expecting the dashboard to be in the `tekton-pipelines` namespace? After deploying the tekton operator, I do not see the dashboard. Maybe I used the wrong config?

**Comment by akihikokuroda** [comment]
Yes, but not yet.  The image of the Tekton dashboard must be published first so the the pipelines operator can pull and install the dashboard.

**Comment by Gl4di4torRr** [comment]
@akihikokuroda @vtereso i have opened https://github.com/tektoncd/dashboard/pull/189 which installs the dashboard using a build and deploy template. works easily for me on openshift/minishift.

**Comment by Gl4di4torRr** [comment]
@akihikokuroda @mnuttall since #189 was merged, do you want to close this or leave it open until the operator does the full install?

**Comment by a-roberts** [comment]
Hey @Gl4di4torRr, thanks for your work on this - the docs are good and will certainly be of use! Let's close this out so it isn't lingering forever. You've titled this to be specifically around documentation and an operator doing the full install can be worked on outside of this.

🎉
