### ISSUE TITLE
Have known secrets clickable from ServiceAccounts page

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1009]
# Expected behavior
If it's a Tekton annotated secret (so one we have under the secrets page) it'd be helpful to have these linked to from the ServiceAccounts page where such secrets are displayed

# Actual behavior
As of March 2020:

No linking is done currently and we see a tiny amount of data
![image](https://user-images.githubusercontent.com/12814972/76203304-4ec70d00-61ee-11ea-979b-93c050a9d9da.png)

# Steps to reproduce the problem

1. Create a secret and have it patched to a ServiceAccount (e.g. make it through the Dashboard so it has the tekton.dev annotation)
2. Visit the ServiceAccounts page and select the ServiceAccount you patched said secret to
3. Realise it'd be nice to have a link back to view your full secret information

**Comment by a-roberts** [comment]
@AlanGreene FYI, there's currently no full page details page for secrets so the plan is to introduce something basic for now (a copy of the existing detail pages, such as for PipelineResources), so that the cilckable link to get more details can be provided. 

We do the same kinda thing already for EventListeners and their TriggerBindings/Templates so I'm suggesting we apply the same style as well for the links here.

I'm curious if you think there's anything else we should be displaying on a secrets details page, perhaps one we can open up to the design team - let us know if you've got anything in mind

**Comment by a-roberts** [comment]
Note that if we are to filter by name, we can use fieldSelector but IIRC there was a problem with it (perhaps not supported through the proxy, we've definitely tried something like this before) - we know labelSelector is good though and, worst case scenario, we could add labels to secrets we create as a not-ideal workaround.

**Comment by AlanGreene** [comment]
> what value would this page offer that our secrets page doesn't already?

Right now very little, but I think that's OK because we've chosen to provide a simple experience around secrets that allows users to create them with the required annotation for Tekton, it's not intended to be a general purpose secrets editor / explorer.

There are other parts of the experience missing, such as the ability to edit a secret / patch it onto a ServiceAccount after exiting the create flow. These are covered in https://github.com/tektoncd/dashboard/issues/727 and https://github.com/tektoncd/dashboard/issues/733

**Comment by a-roberts** [comment]
> > what value would this page offer that our secrets page doesn't already?
> 
> Right now very little, but I think that's OK because we've chosen to provide a simple experience around secrets that allows users to create them with the required annotation(s) for Tekton, it's not intended to be a general purpose secrets editor / explorer.
> 
> There are other parts of the experience missing, such as the ability to edit a secret / patch it onto a ServiceAccount after exiting the create flow. These are covered in #727 and #733

That's true and we would then have consistency as it's what we do for other resources, so having a minimal page displaying the info (and the usual yaml view) would be good I think
