### ISSUE TITLE
Dashboard doesnt look like its part of Tekton

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1010]
# Expected behavior
Dashboard should look like part of Tekton  

# Actual behavior
The dashboard doesn't look part of tekton 

# Steps to reproduce the problem

1.
2.
3.

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

# Additional Info
Add the colourful Tekton cat back so we look part of Tekton 
Our colour scheme looks nothing like its related to tekton

**Comment by a-roberts** [comment]
So specifically I can think of a reversion to the coloured cat image, is there anything else in particular you're thinking of @CarolynMabbott?

@kimholmes @AlanGreene @carrenelloyd what are your thoughts on this too?

**Comment by carrenelloyd** [comment]
@a-roberts @CarolynMabbott Can you please post a screengrab of what you are referring to exactly?

**Comment by kimholmes** [comment]
@CarolynMabbott It would be helpful to understand what the Tekton color scheme is. I wasn't aware of one. I know the cat logo had colors, but beyond that, I'm not aware of a color scheme.

**Comment by CarolynMabbott** [comment]
https://tekton.dev/

**Comment by kimholmes** [comment]
FYI - that site is currently under construction. It's being replaced by this:
https://tekton-website-258208.firebaseapp.com/

**Comment by AlanGreene** [comment]
Screenshot of the current content of that link for comparison, this is the current state of the new website design:
![image](https://user-images.githubusercontent.com/2829095/73895068-489fe280-4876-11ea-8c2c-2c6ff2a192e1.png)

**Comment by kimholmes** [comment]
Thanks @AlanGreene Yes. My point was that we should keep the dashboard neutral. And the Carbon design system does a good job of that.
