### ISSUE TITLE
Tekton Dashboard logo suggestion

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1012]
On the weekly working group call the **Triggers logo** was announced - looks pretty good!
![image](https://user-images.githubusercontent.com/12814972/73849604-22505780-4822-11ea-9fb0-a92fa185ee2a.png)

We could have a Tekton Dashboard logo too, my suggestion is as follows - have the Tekton cat with reading glasses on, looking at a screen or into a book displaying Tekton information (so it could be a screenshot of something that isn't likely to change, or perhaps something artistic like a PipelineRun failing spectacularly so we needn't keep updating it).

**Comment by AlanGreene** [comment]
CLI logo is in the works: `https://github.com/cdfoundation/foundation/issues/147`

Dashboard is also mentioned in the description of that issue, does anyone know if this is actively being worked or if not how we get the ball rolling?

**Comment by a-roberts** [comment]
> CLI logo is in the works: `https://github.com/cdfoundation/foundation/issues/147`
> 
> Dashboard is also mentioned in the description of that issue, does anyone know if this is actively being worked or if not how we get the ball rolling?

Not I, but worth officially asking for I think and running with

**Comment by AlanGreene** [comment]
There's been some activity on the CD Foundation issue linked above, let's see how it goes 🤞 😸

**Comment by AlanGreene** [comment]
Logo assets are available at https://github.com/cdfoundation/artwork/tree/main/tekton/additional-artwork/tekton_dashboard

/close

**Comment by AlanGreene** [comment]
and it's now used on the About page https://github.com/tektoncd/dashboard/pull/1940
