### ISSUE TITLE
Notifications errors for the dashboard only appear once

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1013]
# Expected behavior

If I try to create/delete something in the read-only version of the dashboard, I should get an error message displayed consistently.

# Actual behavior

If I try to create a PipelineRun or Resource etc, then close the error notification, when I press `submit` a second time I get no error displayed in the dashboard.

# Steps to reproduce the problem

1. Easiest way: Install read-only dashboard
2. Try to create a PipelineRun and observe error notification
3. Close the notification and try to create it again, observe no error

# Environment
- Kubernetes Platform:

OpenShift

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

# Additional Info

**Comment by a-roberts** [comment]
Here's the weird thing

![image](https://user-images.githubusercontent.com/12814972/73864750-14a6cc00-483a-11ea-90f7-2e60598aa7c7.png)


so it does enter the action, and it does have the message, so therefore it should be setting errorMessage state which is the controller of the notification being visible

If I augment render() to print the errorMessage prop I see it's always set accurately, but...


```
    return (
      <>
        {createSuccess &&
```

that deleteSuccess check is inside a createSuccess check 👀

**Comment by a-roberts** [comment]
Merged so closing
