### ISSUE TITLE
Full page refresh disrupts the user experience

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/dashboard#1021]
# Expected behavior
While I use the dashboard, only parts where content changes are re-rendered

# Actual behavior
At a fixed interval, the dashboard UI is fully re-rendered, which is rather frustrating, for instance while watching logs / progress on a pipeline run.

# Steps to reproduce the problem

1. Open the dashboard, wait 1min or so
2. See also attached gzipped video

# Environment
- Kubernetes Platform:
GKE (1.13.11-gke.14)

- Tekton Pipelines version:
v0.10.1

- Tekton Triggers version:
v0.2.1

- Tekton Dashboard version:
master + https://github.com/tektoncd/dashboard/pull/1017

# Additional Info
[Screen Recording 2020-02-06 at 21.06.25.mov.gz](https://github.com/tektoncd/dashboard/files/4167756/Screen.Recording.2020-02-06.at.21.06.25.mov.gz)

**Comment by AlanGreene** [comment]
hrmm this sounds similar to https://github.com/tektoncd/dashboard/issues/736

Have you noticed this on other pages or just when watching an active PipelineRun?

**Comment by AlanGreene** [comment]
OK seeing this on the dogfooding dashboard, pretty consistently every 34 or 35 seconds the content reloads. It's not a full page refresh, just the content section, but that doesn't make it any less disruptive or annoying for the user.

The websocket connection is being killed after 30 seconds, causing the client to reconnect and re-fetch data in case it's gone stale while disconnected. This is the same as a previous report where a proxy was killing long-lived connections causing this behaviour.

We should look at a more forgiving strategy for ensuring the content is fresh while tolerating frequent disconnects like this. Ideally we would keeping the existing content on screen while re-fetching in the background, so in cases like this it would be completely transparent to the user.

**Comment by afrittoli** [comment]
> hrmm this sounds similar to #736
> 
> Have you noticed this on other pages or just when watching an active PipelineRun?

I've seen refresh happening on other pages too, like the list of eventlisteners - even though there it's less disruptive (possibly because I only have a few defined).

**Comment by afrittoli** [comment]
Another aspect of this issue that makes it worse, is that if I'm looking at some details of an element of the pipeline run, the refresh brings me back to the default page for that pipelinerun, e.g.

<img width="1605" alt="image" src="https://user-images.githubusercontent.com/2205608/74149624-1a1c6180-4c00-11ea-8114-fc5d9c9c3c54.png">

is redirected back to 

<img width="1605" alt="image" src="https://user-images.githubusercontent.com/2205608/74149646-27395080-4c00-11ea-9227-de464cb51c57.png">

**Comment by AlanGreene** [comment]
Also related: https://github.com/tektoncd/dashboard/issues/487
This should allow us to stay on the correct Task/Step/tab even when the dreaded refresh hits...

**Comment by AlanGreene** [comment]
@afrittoli @vdemeester how is the dashboard being exposed from the cluster? I wonder if perhaps it's an ingress controller killing long-lived connections. If so maybe we can adjust the threshold or make an exception for the websocket connections (wss://)

I'll still take a look at improving the dashboard handling of this though, it could happen in other scenarios such as unreliable mobile network.

**Comment by AlanGreene** [comment]
If we can try increasing the timeout on the ingress controller that would be great. If there's not a setting specifically for `wss` then it would be the `https` timeout.

In the meantime I'm testing some changes on the dashboard to reduce the impact of the reconnect on the UI. Hopefully it'll make it a little more transparent to the user even if they do hit this, so far it's looking promising.

**Comment by AlanGreene** [comment]
We've just landed a change on master that makes the loading state much less disruptive, it will be available in the next nightly build.

@afrittoli it would still be great if we could increase the connection timeout on the ingress to reduce the number of requests we're making to the dogfooding and robotcat clusters.

**Comment by AlanGreene** [comment]
Verified the fix for the loading states is working on robotcat with the latest nightly build, will close this issue once 0.6.1 is deployed on dogfooding and verified there too.

**Comment by AlanGreene** [comment]
Verified on dogfooding! 🎉
