### ISSUE TITLE
ServiceAccount details page should auto update

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1024]
# Expected behavior
When i create a secret and patch it to a service account / delete a secret patched to a service account the list of secrets should update 
So should the yaml 

# Actual behavior
I have to manually refresh 

# Steps to reproduce the problem

1.
2.
3.

# Environment
- Kubernetes Platform:

docker 

- Tekton Pipelines version:

0.10.0

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info
Date cerated auto updates so would be good if the rest of the page does auto updates too

**Comment by AlanGreene** [comment]
This needs:
- `ServiceAccount*` events added to https://github.com/tektoncd/dashboard/blob/0046d16e87d62bad9798ffa651cfaea3de823437/pkg/broadcaster/broadcaster.go#L52 similar to the `Secret*` ones
  - the ServiceAccount reducer in the frontend code already supports these events (standard functionality provided via our `reducerCreator`)
- controller added to https://github.com/tektoncd/dashboard/tree/master/pkg/controllers/kubernetes (similar to secret.go) and registered in https://github.com/tektoncd/dashboard/blob/0046d16e87d62bad9798ffa651cfaea3de823437/pkg/controllers/controller.go#L37
- ensure the frontend ServiceAccount container is retrieving its data from the store
