### ISSUE TITLE
Clicking on labels on serviceaccounts detail page does nothing

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1025]
# Expected behavior
Clicking the label on details page of serviceaccount does something when clicked on 
Was expecting it to be similar to labels on other pages where click it and it goes back to servcieaccounts page and filters them based on label

# Actual behavior
Does nothing when clicked 

# Steps to reproduce the problem

1. On serviceaccounts page click on tekton dashboard
2. Click on the label 
3.

# Environment
- Kubernetes Platform:

docker

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info

**Comment by AlanGreene** [comment]
@CarolynMabbott the updated designs remove the pill treatment from the labels and display them as plain text, this should remove the expectation that they're interactive.

Can you give an example of where we currently have labels that act as clickable navigation?

**Comment by CarolynMabbott** [comment]
Was mistaking it for pipeline where you click and it brings up a filter on pipelineruns page already filtered on the pipeline name 
Also as its the same as the other filters such as on pipelineruns page where you click on it and the filter removes itself and brings up other info removed by the filter to start with 

Was really expecting it to do something when it was clicked on so when it didnt it felt broken

**Comment by AlanGreene** [comment]
OK that makes sense, thanks. Since the design updates should make this a lot clearer, and some of those are already underway, I'm going to close this issue.

PR for the first part already open: https://github.com/tektoncd/dashboard/pull/1023
