### ISSUE TITLE
Dashboard create secret error not very readable 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1028]
# Expected behavior
Error is readable and easy to understand
 
# Actual behavior
It is not very readable 

# Steps to reproduce the problem

1.
2.
3.

# Environment
- Kubernetes Platform:

docker

- Tekton Pipelines version:

0.10.0

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info
<img width="1605" alt="Screenshot 2020-02-07 at 11 38 04" src="https://user-images.githubusercontent.com/32342288/74026609-74b68300-499e-11ea-9de3-bb53889dc24c.png">

**Comment by AlanGreene** [comment]
This is fixed in recent nightlies 
![image](https://user-images.githubusercontent.com/2829095/76116273-9dec2280-5fe1-11ea-9c2d-ea5e7dd31b73.png)
