### ISSUE TITLE
Create Pipeline resource creation doesnt auto use namespace on the left

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1031]
# Expected behavior
create pipeline resource modal to auto select namespace on the left
The user can still change it but it gets auto selected instead of `select namespace`

# Actual behavior
It doesnt 

# Steps to reproduce the problem

1.
2.
3.

# Environment
- Kubernetes Platform:

docker

- Tekton Pipelines version:

0.10.0

- Tekton Triggers version:

- Tekton Dashboard version:

master

# Additional Info

**Comment by AlanGreene** [comment]
See https://github.com/tektoncd/dashboard/issues/975 for related discussion

**Comment by AlanGreene** [comment]
Closing in favour of https://github.com/tektoncd/dashboard/issues/1304 which is tracking a single consistent approach to resolving these namespace-related issues.
