### ISSUE TITLE
Augment about page to display Tekton Pipelines version when installed through operator

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1034]
With https://github.com/tektoncd/dashboard/pull/983 going in, we should augment this page for OpenShift Pipelines installs 

# Expected behavior
We should display the Tekton Pipelines version regardless of install location

# Actual behavior
We only look for the information in the the `tekton-pipelines` namespace currently, the operator installs into `openshift-pipelines`

# Steps to reproduce the problem

1. Install into OCP with the new About page and observe the Tekton Pipelines version is currently unknown

# Environment
- Kubernetes Platform:
OCP 4.3

- Tekton Pipelines version:
A version installed through the OpenShift Pipelines operator

- Tekton Triggers version:

- Tekton Dashboard version:

# Additional Info

**Comment by a-roberts** [comment]
@CarolynMabbott mentioned an interest in working on this, I didn't actually /lgtm (waiting for tests to pass) on the PR so perhaps we augment the existing PR to check

**Comment by mnuttall** [comment]
What about 
```
% k get config.operator.tekton.dev -n openshift-pipelines cluster -o yaml

apiVersion: operator.tekton.dev/v1alpha1
kind: Config
metadata:
  creationTimestamp: "2020-02-10T11:56:03Z"
  generation: 1
  name: cluster
  resourceVersion: "48571"
  selfLink: /apis/operator.tekton.dev/v1alpha1/config/cluster
  uid: 0113003c-28dd-4bf7-a62a-ac0d2f2dac4d
spec:
  targetNamespace: openshift-pipelines
status:
  conditions:
  - code: installed
    version: v0.10.1
  - code: validated-pipeline
    version: v0.10.1
  - code: applied-pipeline
    version: v0.10.1
  operatorUUID: eb931ec2-a893-4df0-af62-0d3b857eb45c
```
It might be worth checking in #openshift-pipelines if this is the 'best' way to get the version of Tekton installed by that operator.

**Comment by CarolynMabbott** [comment]
Have merged a PR in to fix this so closing
/close
