### ISSUE TITLE
Be able to filter for specific item / feature to select in createpipelinerun modal

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1037]
# Expected behavior
Can filter to find the correct pipelineresource / namespace / pipeline / serviceaacount etc 
When you have lots of resources named very similar in say pipelineresource then being able to filter these in the modal when your selecting it would be good 

Would be good to be able to do this by name or even by steps / RBAC permissions   

# Actual behavior
Have to scroll through 

# Steps to reproduce the problem

1. Go to createpipelinerun
2. Sclick on select pipelineresource
3. See you there is no way to filter / search these 

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info

**Comment by AlanGreene** [comment]
Addressed by https://github.com/tektoncd/dashboard/issues/711
