### ISSUE TITLE
Enforce session timeout on secure dashboard 

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#1044]
Secure dashboard sessions should time out after 15-30 minutes. 

This can hopefully be enforced on OpenShift via a change to https://github.com/tektoncd/dashboard/blob/master/overlays/openshift-patches/oauth-proxy-in-deployment.yaml, e.g. by setting the `-cookie-expire` parameter (see https://github.com/openshift/oauth-proxy.)

**Comment by Megan-Wright** [comment]
So I've had a look into this... the `--cookie-expire` parameter can be used, but it sets a timeout regardless of whether the user has actively been using the dashboard or not (so potentially the user could be in the middle of doing something and it could time out) instead of only timing out if they've been inactive for that period of time. Not sure if this is what we wanted or not?

**Comment by AlanGreene** [comment]
Can this be used with `cookie-refresh` set to 1 hour (or similar short timeframe) to regularly revalidate and extend the session?

**Comment by Megan-Wright** [comment]
@AlanGreene so I've tried using `cookie-refresh` but this seemingly has the same effect as `cookie-expire`, i.e when I set it to a minute the session just expired after a minute....

**Comment by akihikokuroda** [comment]
This may need to be set. https://github.com/openshift/api/blob/c99157bc6492218400b18cde7f66510f9ee56a9a/oauth/v1/types.go#L133 . But there is no configuration to make this set this via the proxy.

**Comment by mnuttall** [comment]
One option is to see whether a switch to https://github.com/oauth2-proxy/oauth2-proxy could provide an alternative solution to this problem.

**Comment by Megan-Wright** [comment]
Having reinvestigated using both oauth-proxy and ouath-proxy-2 (which is seemingly not much different), opened issues, talked to people who contribute to the repos, etc. I still can't make any progress on this one... see my comment above about `cookie-expire` and `cookie-refresh`... going to unassign myself for now and see if anyone else can get any further with this.
