### ISSUE TITLE
Account lockout and password policy enforcement

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#1046]
When installed onto a vanilla OpenShift, dashboard users have an unlimited number of attempts to login, and no strong password policy is enforced. This is more likely to be an OpenShift configuration issue more than a dashboard one, burt we can at least document what an administrator can do in order to ensure that login attempts are restricted and a suitable password policy enforced. 

IBM staff can find more details on this issue via https://github.ibm.com/IBMCloudPak4Apps/icpa-security/issues/4

**Comment by CarolynMabbott** [comment]
For Openshift it uses cookies to store the log in data
If you delete the cookies then try and log back in then you have to log back into openshift
Not sure if there is anything we can do about this in the dashboard configuration

**Comment by CarolynMabbott** [comment]
There appears to be no max amount of times a user can try and log in
Have opened an issue in oauth-proxy 
https://github.com/openshift/oauth-proxy/issues/155

**Comment by CarolynMabbott** [comment]
Have tried to recontact the maintainer in oauth-proxy, just waiting on a reply

**Comment by mnuttall** [comment]
One option is to see whether a switch to https://github.com/oauth2-proxy/oauth2-proxy could provide an alternative solution to this problem.
