### ISSUE TITLE
Input sanitisation

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#1047]
Requests made against the dashboard's REST API may not be thoroughly sanitised. 

IBM staff should see https://github.ibm.com/IBMCloudPak4Apps/icpa-security/issues/7 for more information.

**Comment by a-roberts** [comment]
Yeah, I'm hopeful there's a nice library we can use on the js side and fondly recall having code in the Microclimate space (this is more for IBMers) we could potentially leverage - so remember to sanitise at both ends (js an Go)

**Comment by AlanGreene** [comment]
We should already be OK on the client side as we don't dangerously set innerHTML anywhere and React ensures strings are treated correctly for display. It's still worth double-checking but we shouldn't have an issue.

As for injecting values in direct API calls, that's something we should address where those values might be stored / transmitted elsewhere. However, if the URL is just being echoed back in an error response (as is common in 404 responses) this is unlikely to be a problem.
