### ISSUE TITLE
Discourage or prevent browser cacheing of resources accessed via HTTPS 

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#1050]
Unless directed otherwise, browsers may store a local cached copy of content received from web servers. Some browsers cache content accessed via HTTPS. If sensitive information in application responses is stored in the local cache, then this may be retrieved by other users who have access to the same computer at a future time.

Applications should return caching directives instructing browsers not to store local copies of any sensitive data. Often, this can be achieved by configuring the web server to prevent caching for relevant paths within the web root. Alternatively, most web development platforms allow you to control the server's caching directives from within individual scripts. Ideally, the web server should return the following HTTP headers in all responses containing sensitive content:
```
Cache-control: no-store
Pragma: no-cache
```

IBM staff can find more information on this issue at https://github.ibm.com/IBMCloudPak4Apps/icpa-security/issues/11

**Comment by AlanGreene** [comment]
We should prevent caching of `/v1/*` and `/proxy/*` endpoints
