### ISSUE TITLE
/extensions returns internal IP addresses to client unnecessarily

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#1051]
The /extensions endpoint returns objects of the form, 

```
[
  {
    "name": "webhooks-extension",
    "url": "172.30.101.197",
    "port": "8080",
    "displayname": "Webhooks",
    "bundlelocation": "web/extension.f9d4eab7.js"
  }
]
```

The internal IP addresses for extension endpoints are needed by the dashboard service, but not by web clients. Discovering the private addresses used within an organization can help an attacker in carrying out network-layer attacks aiming to penetrate the organization's internal infrastructure. 

IBM staff can find more information on this issue at https://github.ibm.com/IBMCloudPak4Apps/icpa-security/issues/13

**Comment by a-roberts** [comment]
Yeah, not a fan of this, perhaps it's just a case of removing it from the struct? For whoever picks this up - check to see how that /extensions endpoint is used (it's fine to be an internally passed around object, I'm wondering though if the URL is needed in our Javascript code so we may need a more creative solution).

@AlanGreene @steveodonovan any thoughts here?

**Comment by AlanGreene** [comment]
We don't use `url` in the front end code so no need to pass it back on the API. We use the `name` and `bundlelocation` to build the correct URL to load the extension JS.

**Comment by dibbles** [comment]
Pull request in for review :- https://github.com/tektoncd/dashboard/pull/1110
