### ISSUE TITLE
Tekton Pipelines beta support

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1063]
There are changes at least [here](https://github.com/tektoncd/pipeline/pull/2035) for Tekton Pipelines itself to move up to beta, it'd be useful for the Tekton Dashboard to work with any features exclusive to the beta and to not break. 

Have a look at what needs to be done (so I'd build against master, check everything continues to work fine, and then build Pipelines using the referenced commit). It could be that there are no breaking changes.

**Comment by AlanGreene** [comment]
We'll need to update `getTektonAPI` in src/api/index.js to accept the version, defaulting to `v1alpha2` if none provided and only pass the override when required (e.g. PipelineResource APIs, maybe triggers?)

https://github.com/tektoncd/dashboard/blob/24eb823bfd4472d3fb1239dcf811d89b92f3f0a8/src/api/index.js#L91

**Comment by anneqm** [comment]
on beta community call, there was discussion about move to v1alpha2 or maybe to v1beta1-rc1. 
See https://docs.google.com/document/d/1JmRd0vbh2Q6Emu2DOk-LwLHfxd2V0zrN4WNawGzoNXw/edit#

**Comment by anneqm** [comment]
@a-roberts do we need a similar issue for the move up to pipelines 0.11 ? That's targeted for Feb 26, with beta then in March (March 13 as of last week beta call).

**Comment by a-roberts** [comment]
> @a-roberts do we need a similar issue for the move up to pipelines 0.11 ? That's targeted for Feb 26, with beta then in March (March 13 as of last week beta call).

Yep I think that's a good idea

**Comment by a-roberts** [comment]
I'll pick this up, will try out @vdemeester's super PR shortly

**Comment by a-roberts** [comment]
Upgraded my Docker Desktop version to pick up Kube 1.15.x, built and deployed perfectly with Vincent's latest commit

Checked out master of Dashboard and did a clean build, kicked the tires. Testing to do (comment will be updated with results):

1) Import resources (creating a PIpelineRun, then importing known resources in the PIpeline Hotel)
2) Creating and deleting Tekton secrets
3) Testing manual PipelineRun creation
4) Checking things render OK for Tekton resources (Tasks, Pipelines, PipelineRuns, PIpelineResources)
5) About page
Not 6) Webhooks extension - not testing this just yet

Then, repeat with the change for v1alpha2 in api/index.js:

1) Import resources (creating a PIpelineRun, then importing known resources in the PIpeline Hotel)
2) Creating and deleting Tekton secrets
3) Testing manual PipelineRun creation
4) Checking things render OK for Tekton resources (Tasks, Pipelines, PipelineRuns, PIpelineResources)
5) About page

**Comment by CarolynMabbott** [comment]
Cant check things off in your box but have tested and following things work:
Import Resources 
Creating and deleting secrets 
Things render okay - service accounts, secrets, task, takruns, pipelines, pipelineruns, pipelineresources 
Stopping pipelineruns works okay 
Deleting pipelineruns works okay  

My about page isnt displaying my pipeline version on docker desktop though

**Comment by a-roberts** [comment]
Update on this one, https://github.com/tektoncd/dashboard/compare/master...vdemeester:bump-v1beta1 builds great, rerun works, but PipelineResources don't display (an error mentioning we can't find the requested resource appears). @CarolynMabbott has noticed the label change we use to detect the Tekton Pipelines version and I'm going to look at making the JavaScript changes next on my branch, which will piggyback off Vincent's .toml changes.

**Comment by a-roberts** [comment]
Draft release at https://console.cloud.google.com/storage/browser/tekton-releases/dashboard/adambeta/adambeta/previous/beta/?project=tekton-releases (updated to use rc2, rebased)

**Comment by gpaul** [comment]
I've found that hitting "Re-Run" when viewing a failed pipelinerun (a `v1beta1.PipelineRun` to be exact) fails with a json decoding error.

```
{"level":"debug","msg":"Rerunning a pipelinerun that's not already been rerun"}
{"level":"debug","msg":"Found existing label(s), adding reruns label"}
{"level":"error","msg":"an error occurred rerunning the PipelineRun foo-ftgth in namespace bar: admission webhook \"webhook.pipeline.tekton.dev\" denied the request: mutation failed: cannot decode incoming new object: json: unknown field \"digest\""}
{"level":"error","msg":"Error: admission webhook \"webhook.pipeline.tekton.dev\" denied the request: mutation failed: cannot decode incoming new object: json: unknown field \"digest\""}
```

**Comment by AlanGreene** [comment]
Should we also update pipeline0 and our websocket code on the back end to use v1beta1?

**Comment by a-roberts** [comment]
`Should we also update pipeline0 and our websocket code on the back end to use v1beta1?`

yeah, I'll work on this, made issue https://github.com/tektoncd/dashboard/issues/1206

**Comment by a-roberts** [comment]
Main PR made https://github.com/tektoncd/dashboard/pulls

**Comment by a-roberts** [comment]
PR merged so any new bugs will be new issues, cheers all
