### ISSUE TITLE
Augment release pipeline to spot "version: development" in releases

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1067]
I've dun' goofed a couple times now (see: https://github.com/tektoncd/dashboard/issues/1065), so add a quick *up front* check for `version: development` - or, even better, automatically extract it from the tag we are on, and then fail the PipelineRun with a helpful message.

**Comment by AlanGreene** [comment]
Is this solved with https://github.com/tektoncd/dashboard/pull/1244?

We're already setting `versionTag` as part of the release process for the bucket location, and with the change from that PR the `publish-tekton-dashboard` task that's executed as part of the release process will automatically replace the version label.
