### ISSUE TITLE
Create PipelineRun modal view extra right padding

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#1068]
![Screen Shot 2020-02-17 at 3 21 12 PM](https://user-images.githubusercontent.com/16961496/74686146-941f8e00-519e-11ea-8ba0-fed077c38933.png)

Extra padding on the right side of the PipelineRun modal view.

# Environment
- Kubernetes Platform: OpenShift

- Tekton Dashboard version: master

**Comment by AlanGreene** [comment]
Depending on the screen sizes you're seeing this at it may be part of the Carbon design spec: https://www.carbondesignsystem.com/components/modal/style#margin-right

**Comment by ncskier** [comment]
Ok
