### ISSUE TITLE
Cannot search step logs

### ISSUE THREAD

**Issue by jbarrick-mesosphere** [tektoncd/dashboard#1075]
# Expected behavior

When I press control + F when browsing step logs, I should be able to search over the whole log.

# Actual behavior

Control + F can only search over the logs in the current view.

**Comment by AlanGreene** [comment]
Thanks for raising this, it's a request we've had from other users too and I agree that this would be great to have. The current implementation only renders the visible lines (plus a small buffer either side) for performance reasons based on feedback from a number of users with very large logs.

For now, you can download the logs by clicking the button in the upper right corner of the log container and search locally (not ideal I know). This is available in the latest nightly builds.

![image](https://user-images.githubusercontent.com/2829095/74872769-ccb59800-5355-11ea-9b18-1665393ab921.png)

**Comment by jbarrick-mesosphere** [comment]
Thanks!

We could add another button that loads the raw logs in a tab (instead of downloading)? That way the user can click into it (without needing to open a text editor) easily? I've had good luck with that on other CI systems.

**Comment by AlanGreene** [comment]
Great suggestion, PR here: https://github.com/tektoncd/dashboard/pull/1076

**Comment by jbarrick-mesosphere** [comment]
Awesome, thank you!

**Comment by AlanGreene** [comment]
PR open to render full logs up to 20k lines, after which we revert to the current virtualized list behaviour.

This should be sufficient for most users, re-enabling the browser-native 'find in page' (ctrl/cmd-f) functionality, and we still have the ability to open the logs in a new tab or download to search locally if required.

**Comment by justinbarrick** [comment]
Very cool 😎
