### ISSUE TITLE
Web panelling for 'manually create a pipelinerun'

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#108]
We have a REST API that supports the manual creation of pipelineruns. 

The parameters that a user must provide will be specific to the pipeline they're creating a run for - luckily they're all defined in the pipeline. 

The UI will need to obtain and parse the desired pipeline before populating the fields that need user entry.

**Comment by ncskier** [comment]
@mnuttall @AlanGreene 
What is the overall "plan" is for namespace selection? I saw that there was recently a namespace dropdown added to the side menu. Should I use the selected namespace for my paneling, or should I have my own namespace dropdown?

Also, what is the flow for how the user should access this page to create a PipelineRun? (what link does the user click to get them to this page, and what page is this link on?) My paneling could probably be linked to from the main menu. Or, if the user is on a Pipeline's page, should I add a button to create a PipelineRun for that Pipeline?

**Comment by ncskier** [comment]
Update: I just talked with Mark about the namespace selection, and we agreed to use the "global" namespace that was recently introduced.

**Comment by ncskier** [comment]
Here are a couple of approaches to how the user should access my Create PipelineRun page.

### Option 1: button in the PipelineRun list
In this approach, the Pipeline option on the Create PipelineRun page would be pre-populated with the Pipeline ref. So, in this example it would be  pre-populated with `pipeline0`
![createPipelineRun1](https://user-images.githubusercontent.com/16961496/57868361-d8759c00-77d0-11e9-9bf5-5a0009ec6618.png)

### Option 2: from the side menu
In this approach, there is always a button in the side menu that will bring the user to the Create PipelineRun page.
![createPipelineRun2](https://user-images.githubusercontent.com/16961496/57868386-e3303100-77d0-11e9-95f7-087b6015509a.png)

### Example barebones Create PipelineRun page:
![Screen Shot 2019-05-16 at 11 50 15 AM](https://user-images.githubusercontent.com/16961496/57868738-8b45fa00-77d1-11e9-8d49-05435b5cb59c.png)


@mnuttall @AlanGreene which option do you think is best for navigating to the Create PipelineRun page? Is there another approach that you had in mind? Should I do both option 1 and 2?

**Comment by AlanGreene** [comment]
Personally I'd prioritise option 2, and also consider adding it to the Pipeline list as described in https://github.com/tektoncd/dashboard/issues/38

For option 1 I'm concerned the nav could get a bit busy with all the create options added (Pipeline, PipelineRun, Resource, Credential, etc.). We should definitely have something easily accessible that doesn't require navigating through multiple layers of the application, so let's try option 2 first and see if we feel we need more.

**Comment by ncskier** [comment]
Ok, thanks for the feedback Alan. I'll put a button in the PipelineRun list.

**Comment by ncskier** [comment]
PR https://github.com/tektoncd/dashboard/pull/295 completes this issue
/close
