### ISSUE TITLE
Test Dashboard with Triggers 0.3

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1087]
# Expected behavior
@ncskier has just released triggers 0.3 🎈 so let's see what features continue to work and if any need to be added

# Steps to reproduce the problem

1. Install Triggers 0.3
2. Install master of the Tekton Dashboard

# Environment
- Kubernetes Platform:
Any

- Tekton Pipelines version:
master

- Tekton Triggers version:
0.3

- Tekton Dashboard version:
master

Follow-up issue todo for webhooks extension

**Comment by ncskier** [comment]
I've done some testing with Triggers v0.3.0 using the Dashboard and the Webhooks Extension, and I was able to view EventListener, TriggerTemplates, and TriggerBindings properly in the Dashboard. For testing, I used the Triggers resources defined [here](https://github.com/pipeline-hotel/example-pipelines/tree/master/triggers-resources/config/github/buildah), and viewed the EventListener created by the Webhooks Extension. So, from what I can tell, Triggers v0.3.0 does not introduce any regression bugs for the Dashboard.

However, there are a couple of new features in Triggers v0.3.0 that the Dashboard does not currently support:
- ClusterTriggerBindings (https://github.com/tektoncd/triggers/pull/358)
- CEL Interceptor `overlays` field (https://github.com/tektoncd/triggers/pull/329)

Plus, a version label was added to the controller & webhook pods (https://github.com/tektoncd/triggers/pull/428). I'm not sure if this affects the [Dashboard version](https://github.com/tektoncd/dashboard/issues/779)?

**Comment by ncskier** [comment]
FYI @a-roberts I created the follow-up issue for webhooks extension: https://github.com/tektoncd/experimental/issues/480

**Comment by a-roberts** [comment]
> I've done some testing with Triggers v0.3.0 using the Dashboard and the Webhooks Extension, and I was able to view EventListener, TriggerTemplates, and TriggerBindings properly in the Dashboard. For testing, I used the Triggers resources defined [here](https://github.com/pipeline-hotel/example-pipelines/tree/master/triggers-resources/config/github/buildah), and viewed the EventListener created by the Webhooks Extension. So, from what I can tell, Triggers v0.3.0 does not introduce any regression bugs for the Dashboard.
> 
> However, there are a couple of new features in Triggers v0.3.0 that the Dashboard does not currently support:
> 
> * ClusterTriggerBindings ([tektoncd/triggers#358](https://github.com/tektoncd/triggers/pull/358))
> * CEL Interceptor `overlays` field ([tektoncd/triggers#329](https://github.com/tektoncd/triggers/pull/329))
> 
> Plus, a version label was added to the controller & webhook pods ([tektoncd/triggers#428](https://github.com/tektoncd/triggers/pull/428)). I'm not sure if this affects the [Dashboard version](https://github.com/tektoncd/dashboard/issues/779)?

Thanks, yeah we want to display the Triggers version too, I'll make an issue for that and displaying 0.3 features
