### ISSUE TITLE
update oauth-proxy config to skip sign-in pop-up window

### ISSUE THREAD

**Issue by arunavemulapalli** [tektoncd/dashboard#1088]
background - 

Tekton UI is protected by OpenShift OAuth server via OAuth proxy,  Current configuration always display the sign-in page "Log in with Open Shift" before reaching OAuth login page. Since "login with OAuth" is the only option, we should skip this pop-up window, and go directly to OAuth login page.  Skipping the sign-in page is useful for SSO, if OpenShift OAuth server is configured to use one SSO server (like IBM ID, or google), user could access the UI securely and silently without clicking the button.

Jim and Chunlong have investigated and tested various SSO scenarios for platform applications, and believe that we should get rid of this unnecessary button (to avoid the click). 

To skip the button,  add the following property in oauth proxy configuration. 
skip-provider-button=true  (will skip sign-in-page to directly reach the next step: oauth/start)

**Comment by a-roberts** [comment]
Yeah, sounds good! Looks like you've done the hard work - would you do the honours of creating the pull request for us please? 😸

**Comment by arunavemulapalli** [comment]
Sure
