### ISSUE TITLE
Display new Triggers 0.3 features

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1095]
See https://github.com/tektoncd/dashboard/issues/1087 for details

# Expected behavior
@ncskier mentions a few new additions (detailed above) so render these in the dashboard under the appropriate page

# Steps to reproduce the problem

1. Install Triggers 0.3 and the latest dashboard
2. Use the latest Triggers 0.3 features (https://github.com/tektoncd/triggers/pull/358 for ClusterTriggerBindings, https://github.com/tektoncd/triggers/pull/329 for overlays)
3. Observe no details are displayed

# Environment
- Kubernetes Platform:
Any

- Tekton Pipelines version:
Any

- Tekton Triggers version:
0.3.0

- Tekton Dashboard version:
master

**Comment by a-roberts** [comment]
ClusterTriggerBindings are in so only the overlays work to go

**Comment by Megan-Wright** [comment]
Overlays PR merged now so closing
/close
