### ISSUE TITLE
Credential API doesn't support generic secret creation

### ISSUE THREAD

**Issue by carlos-logro** [tektoncd/dashboard#110]
for example:

`kubectl create secret generic github-secret \
  --from-literal=accessToken=$GITHUB_TOKEN \
  --from-literal=secretToken=$(cat /dev/urandom | LC_CTYPE=C tr -dc a-zA-Z0-9 | fold -w 32 | head -n 1) \
  --namespace $DASHBOARD_INSTALL_NS`

This command currently can't be turned into a curl command. The POST data might have a parameter that says something like "please invent a nice random secret token" for situations like these.

**Comment by mnuttall** [comment]
Closed by https://github.com/tektoncd/experimental/pull/30
