### ISSUE TITLE
Secret page tells you secrets are deleted successfully when trying to delete no secrets

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1101]
# Expected behavior
When press delete on batch delete secrets it doesnt come up with an notification saying secrets deleted successfully 

# Actual behavior
It says secret deletes successfully 

# Steps to reproduce the problem

1. Have no secrets 
2. Select all in batch table
3. Press delete 

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info

**Comment by AlanGreene** [comment]
So the delete button should be disabled and the modal should not be triggered if there are no secrets selected. Or even better would be to disable the 'select all' checkbox when the table is empty, I'm not sure if this is something Carbon supports.

**Comment by a-roberts** [comment]
Merged
