### ISSUE TITLE
Access token secrets don't appear in the secrets table after they've been created

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1102]
# Expected behavior

If I create a secret that uses an access token, I should then be able to view this secret in the secrets table.

# Actual behavior

The secret does not appear in the table. It does appear in the webhooks extension (if you have it installed) under the secrets you can use to create a webhook, however this doesn't seem like it would be obvious to the user unless they specifically looked there.

# Steps to reproduce the problem

1. Create a secret that uses an access token instead of a password
2. Observe that it is not displayed in the secrets table after creation
3.

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

# Additional Info

**Comment by a-roberts** [comment]
Discussed with @Megan-Wright, so actually this may not be a bug, just a bad user experience - we couldn't create access tokens through the Dashboard before the PR by Carlos, we think we should have an option to display access tokens created instead, or in addition to the normal password type secrets

@AlanGreene what do you think?

**Comment by AlanGreene** [comment]
Yep we should display them and allow the user to delete them. If we can display them in the current secrets table that would be great.

**Comment by a-roberts** [comment]
> Yep we should display them and allow the user to delete them. If we can display them in the current secrets table that would be great.

SGTM 👍

**Comment by a-roberts** [comment]
Merged so closing 🎉 thanks Megan, liking this approach
