### ISSUE TITLE
Notification for successfully patching secrets doesn't disappear

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1103]
# Expected behavior
If I create a secret, a success notification for patching the secret to the related service accounts appears. If I change to a different view on the dashboard and then change back to the secrets page, I expect this notification to have disappeared.

# Actual behavior

The notification doesn't ever disappear unless you manually refresh the page.

# Steps to reproduce the problem

1. Create a secret that is patched to at least one service account
2. Observe the notification for patching success
3. Change to a different page on the dashboard (e.g. PipelineRuns), then back to the secrets view, and see the notification is still there.

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

# Additional Info

**Comment by a-roberts** [comment]
Putting this one back on the backlog, @dibbles is off on holiday shortly and more pressing work's taking a priority atm so this one's up for anyone to grab - would be nice to get this in for the Dashboard Beta release

**Comment by AlanGreene** [comment]
One approach here might be to keep the notification state in the component's local state instead of going through the redux store, that way once the component is unmounted it's gone. The notification is only needed on this page anyway.

**Comment by a-roberts** [comment]
> One approach here might be to keep the notification state in the component's local state instead of going through the redux store, that way once the component is unmounted it's gone. The notification is only needed on this page anyway.

Working on this as it's what we do elsewhere, also exploring the option of simply catching the prop changing in componentDidUpdate and using clearNotification (this works in the case of the delete notifications now)

**Comment by a-roberts** [comment]
Merged
