### ISSUE TITLE
Secrets can be created with neither an access token nor a password

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1106]
# Expected behaviour

When creating a secret, it should be a requirement that the secret either needs an access token or a password associated with it.

# Actual behaviour

I can create a secret with just a name and a namespace, and without selecting to have a password or access token. The secret is created as an access token secret where the access token is an empty string.

# Steps to reproduce the problem

1. Create a secret without selecting to use an access token or password.
2. Observe the secret being created successfully

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

# Additional Info

**Comment by AlanGreene** [comment]
The 'Password' type radio button should probably be selected by default. That would prevent this from occurring as there's no way to unselect a radio button other than choosing another from the same group (i.e. access token).

Alternatively if we want to force the user to explicitly choose the type we could add validation on the create to ensure one option or other is chosen.
