### ISSUE TITLE
Selecting `x` in the namespace box breaks secrets page 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1132]
# Expected behavior
On create secret I tpyed in a namespace that didnt exist and clicked create 
When tried to press the x in the namespace box it broke and came up with error 
`Error loading page Cannot read property 'text' of null`

Inspector error is:
`ErrorBoundary.js?9c7c:68 ErrorBoundary Object
componentDidCatch @ ErrorBoundary.js?9c7c:68`

# Actual behavior

# Steps to reproduce the problem

1. Try create secret 
2. Put in a namespace doesnt exist
3. press submit 
4. press x on namespace to delete namespace 

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info

**Comment by AlanGreene** [comment]
`handleNamespace` assumes there's always a selected item, but this is not the case when clicking the 'X' to clear the combo box
https://github.com/tektoncd/dashboard/blob/3f6d8ff5208fcf4cceb0bb7700f045331f6abacd/src/containers/CreateSecret/CreateSecret.js#L94
