### ISSUE TITLE
Cannot type in the all namespace box on the left

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1133]
# Expected behavior
I can type in the All namespace box on the left to find a namespace 

# Actual behavior
I cant type in it 

# Steps to reproduce the problem

1. Select All Namespaces box 
2. Try and type in it 
3.

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info

**Comment by AlanGreene** [comment]
I don't think this ever worked, there's code in SideNav that forces the value to 'All Namespaces' if there's no item selected.

**Comment by CarolynMabbott** [comment]
You used to be able to type in the namespace box in the SidaNav to find a namespace

**Comment by AlanGreene** [comment]
Behaviour changed in Carbon 10.10, creating a pair of sandboxes to show before / after and open issue against Carbon.

**Comment by AlanGreene** [comment]
Fix delivered to Carbon, waiting for confirmation of which release it will be included in.

**Comment by AlanGreene** [comment]
Confirmed this is fixed in carbon-components-react 7.11.0 (carbon-components 10.11.0) which was just released.

I'll hold off on updating until after the dashboard 0.6.1 release so we have more time to test for any other potential regressions or changes.

**Comment by AlanGreene** [comment]
Carbon rolled back the release after reports of issues from multiple users... hopefully won't be too long before they fix those issues and release it again. I'll keep an eye on their release announcements and internal Slack channels so we're prepared to test it out when it lands.

**Comment by AlanGreene** [comment]
Still waiting for carbon-components 10.11.0 and carbon-components-react 7.11.0 to be re-released...

**Comment by AlanGreene** [comment]
carbon-components@10.11.1 and carbon-components-react@7.11.1 published

Some breaking changes compared to our current 10.10.1/7.10.1 that we'll need to account for when updating, also potentially some style / behaviour changes that we may want to review (e.g. DataTableSkeleton style changed, possibly some change in behaviour with DataTable overflow menus).
