### ISSUE TITLE
Secrets panelling is not clear as to how to use accesstokens

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#1136]
The dashboard UI does not clearly indicate that the secret of type accesstoken is to create an opaque secret creating an access token, rather than a basic-auth secret with the token in the password field.

This will potentially confuse new users.... the design around this needs work, as if users can specify the token in the user/password situation (in place of the password) - it is not clearly indicated.

![Screenshot 2020-03-11 at 15.46.18.png](https://images.zenhubusercontent.com/5809f18995e42b6c5baad615/e6621865-9a33-47d3-95b9-fe33069ff0db)

**Comment by a-roberts** [comment]
Merged
