### ISSUE TITLE
Can not delete webhook from UI if pipeline has been deleted

### ISSUE THREAD

**Issue by dacleyra** [tektoncd/dashboard#1137]
# Expected behavior

# Actual behavior

# Steps to reproduce the problem

1. Create a webhook in the ui, using an existing pipeline
2. Delete the pipeline
3. Navigate to the webhooks page. Find that the row exists, but the entry is blank. Unable to delete it.

# Environment
- Kubernetes Platform:
Openshift 4.3.1

- Tekton Pipelines version:
openshift-pipelines-operator.v0.10.4

- Tekton Triggers version:

- Tekton Dashboard version:
0.5.2

# Additional Info

**Comment by AlanGreene** [comment]
Thanks for raising this issue. Problems with the webhooks-extension should be reported in https://github.com/tektoncd/experimental.

This seems very similar to https://github.com/tektoncd/experimental/issues/489
@a-roberts fyi

**Comment by dacleyra** [comment]
Thanks. This looks like a duplicate, closing.
