### ISSUE TITLE
Get 2 identical errors when creating a secret that already exists 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1144]
# Expected behavior
I only get one error 

# Actual behavior
I get two which are identical 

# Steps to reproduce the problem

1. Create two secrets (the second being identical to the first)

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info
It's also strange that if you click `x` on the second one then only the second error disapeears but if you click on the first `x` then both disappear 
<img width="1410" alt="Screenshot 2020-03-13 at 11 48 28" src="https://user-images.githubusercontent.com/32342288/76618586-dd09fe80-6520-11ea-82cb-c68f615bd820.png">

**Comment by a-roberts** [comment]
![image](https://user-images.githubusercontent.com/12814972/76755792-679a6a00-677c-11ea-9197-afb7fd08818c.png)

on my code atm, git log being

```
0d8ecfbc (adam/secretcreatetooltip)
Author: a-roberts <aroberts@uk.ibm.com>
Date:   Thu Mar 12 15:38:26 2020 +0000

    Add tooltip for secret creation guidance

commit ce8b1c4ab85df23007f1058a139d8ea463f7d4b8 (origin/master, origin/HEAD)
Author: a-roberts <aroberts@uk.ibm.com>
Date:   Thu Mar 12 11:31:36 2020 +0000

    Don't always display secret notifications

commit b03c4b885ed8a6e54d2c0cf03c6afd6647585920
Author: Alan Greene <ALANGREE@ie.ibm.com>
Date:   Fri Mar 6 22:28:43 2020 +0000

    Extract Dropdown strings for transl
```

Have the same on master, going to close unless we get a reproduce on this one, @Megan-Wright and I really can't

**Comment by AlanGreene** [comment]
Reproduced this a couple of times just now, not 100% sure of the steps but I'll try to narrow it down and add details

**Comment by AlanGreene** [comment]
2 parts:

1. double error
  we have 2 separate props being passed to CreateSecret/Form with error messages: `errorMessageDuplicate` and `errorMessageCreated`. There should really just be one `errorMessage` that's set to the appropriate value, this way we simplify the Form code and avoid the possibility of displaying the same message for multiple reasons simultaneously.

1. not handling the duplicate with our cleaner custom error message in at least one case:
  i. on the Create Secret page create a secret in namespace A
  ii. in the left nav select namespace B
  iii. on the Create Secret page create another secret in namespace A with the same name from i.
  iv. observe the double error

**Comment by a-roberts** [comment]
PR https://github.com/tektoncd/dashboard/pull/1153, thoroughly testing this now

**Comment by a-roberts** [comment]
![image](https://user-images.githubusercontent.com/12814972/76851895-0f2da000-6842-11ea-833e-8bfb81aa3956.png)

there are three kind="error" notifications here, we've got one in Secrets.js, and two in the form 

Suspiciously there's also removeDuplicateErrorMessage so this is proving a pain to untangle

**Comment by a-roberts** [comment]
Removed from the 0.5.3 milestone as I'd like to get this published tomorrow to work on a beta release we can have for testing, I'm away from Friday until the 30th - this has proven trickier than I thought to fix

**Comment by a-roberts** [comment]
Merged now so closing
