### ISSUE TITLE
`No Secrets in namespace tekton-pipelines` under patch service account

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1145]
# Expected behavior
I get a list of service accounts to patch my secret to 

# Actual behavior
I get `No Secrets in namespace tekton-pipelines`

# Steps to reproduce the problem

1. Create secret and patch in any namespace to any service account
2. Try and create identical secret in other namespace as first secret without changing namespace on the left sidenav 
3. Get through to patch secret and not be able to have any service accounts to patch to

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info
The namespace on the left is causing this 
If you change it to All Namespaces or the namespace you want to create the new secret in then it works 

![Screenshot 2020-03-13 at 11 55 32](https://user-images.githubusercontent.com/32342288/76619142-1858fd00-6522-11ea-9a3d-af393b6b1bf9.png)

**Comment by a-roberts** [comment]
Yeah I see this too, and when you refresh and go through the flow again (e.g. wanting to create a secret in the namespace `default` the ServiceAccounts get listed OK

In doing the reproduce I didn't see any promise errors, here are the requests

![image](https://user-images.githubusercontent.com/12814972/76757852-56535c80-6780-11ea-8b46-fe39f7c2d490.png)

so we've definitely got a logic problem here

**Comment by a-roberts** [comment]
I see, it's retrieving the SA's in the tekton-pipelines namespace still, they're then filtered and the namespace I chose (default) != tekton-pipelines, I'll check how `serviceAccounts` is populated and passed in here.

**Comment by a-roberts** [comment]
@AlanGreene do you think creating a secret in, say, namespace `default` should change the selected namespace (on the left) to be `default`? Then the filter would return the secrets correctly

**Comment by AlanGreene** [comment]
We should already be switching namespace once a secret is created following this change https://github.com/tektoncd/dashboard/pull/1126/files

When a user creates a resource they should always end up in a state where they see it displayed without having to take additional steps (with the exception of the optional 'patch' step for secrets of course).

**Comment by a-roberts** [comment]
> We should already be switching namespace once a secret is created following this change https://github.com/tektoncd/dashboard/pull/1126/files
> 
> When a user creates a resource they should always end up in a state where they see it displayed without having to take additional steps (with the exception of the optional 'patch' step for secrets of course).

Good call, yep I've got that PR, definitely not seeing the selected namespace change on secret creation 🤔 that seems to only be for the close event

**Comment by AlanGreene** [comment]
ah yes good point, so we should actually be calling that earlier, once the secret is created instead of only when closing the create flow

**Comment by Megan-Wright** [comment]
@AlanGreene wouldn't both of these issues be solved by changing back to `all namespaces` after creating a secret?

**Comment by AlanGreene** [comment]
Technically yes, but they could be lost in a sea of noise, especially on busier clusters with many namespaces actively used.

If the user has explicitly chosen a namespace, we should do our best to bring them to a useful view of resources in that namespace as they're likely to want to perform other actions in that same namespace (e.g. trigger a PipelineRun)
