### ISSUE TITLE
Newly created secrets (regardless of type) should immediately display in the table

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1148]
# Expected behavior
If i create a password type secret, I have the password button selected when Its created so it can be seen in the table.

The same should apply for access token secrets too (so when its created have the Access Token selected so it can be seen).

If i cant see it if feels like it hasn't created.

# Actual behavior
Defaults back to the page it was on before (Password or Access Token)

# Steps to reproduce the problem

1.  From password create a access token 
2. Watch as it goes back to password and not access token 

# Environment
- Kubernetes Platform:
Any

- Tekton Pipelines version:
Any

- Tekton Triggers version:
n/a

- Tekton Dashboard version:

master

**Comment by AlanGreene** [comment]
https://github.com/tektoncd/dashboard/pull/1126#pullrequestreview-371299672
https://github.com/tektoncd/dashboard/issues/1121
