### ISSUE TITLE
Check we can display inline Pipelines in a PipelineRun spec

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1162]
I'm not sure we can (this was discussed on the WG call) - so kick off a PipelineRun with a Pipeline spec and see how the Dashboard handles this

@skaegi @AlanGreene FYI, this came about when discussing https://github.com/tektoncd/pipeline/issues/2223

(If we can display them, should we call that out? Perhaps a FAQ would be useful in the main readme? Things one can see and what one can't - e.g. results may be something we can't).

**Comment by AlanGreene** [comment]
This should work https://github.com/tektoncd/dashboard/issues/829

If it doesn't it's a bug we need to fix. I've tested with a few of the example PipelineRuns locally and it's working fine for me, https://github.com/tektoncd/pipeline/blob/master/examples/v1alpha1/pipelineruns/pipelinerun-with-pipelinespec.yaml for example

There are issues with inline Task specs tracked here https://github.com/tektoncd/dashboard/issues/1159

**Comment by a-roberts** [comment]
Excellent, yeah I noticed your comment around inlining on the Task issue too, we've confirmed master's indeed good and so should 0.5.3 then so let's close this and it's useful info to know (so even with Tekton 0.10.1 we're good, and the Pipeline info is all under the `details` tab).
