### ISSUE TITLE
Show Step Names In TaskRun Logs

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/dashboard#1173]
# Expected behavior

Similar to what is available with `tkn` logs command, it would be nice to know what step is producing the logs for a TaskRun. The format for `tkn` is `[taskName : stepName]`, but perhaps just the step name makes more sense for dashboard.

Example of `tkn` logs:
```
[build : build-and-push] INFO[0000] Resolved base name maven:3.6.2-jdk-11 to maven:3.6.2-jdk-11 
[build : build-and-push] INFO[0000] Resolved base name adoptopenjdk/openjdk11:latest to adoptopenjdk/openjdk11:latest 
[build : build-and-push] INFO[0000] Resolved base name maven:3.6.2-jdk-11 to maven:3.6.2-jdk-11 
[build : build-and-push] INFO[0000] Resolved base name adoptopenjdk/openjdk11:latest to adoptopenjdk/openjdk11:latest 
```

# Actual behavior

Only the Task name is shown without further detail into what step is running.

# Environment
- Kubernetes Platform:
`Kubernetes v1.17.3`

- Tekton Pipelines version:
`v0.11.0-rc2`

- Tekton Dashboard version:
`v0.5.3`

**Comment by AlanGreene** [comment]
The dashboard displays the logs for the selected step only, it does not have an aggregated view of logs for a TaskRun.

Do you think it would still be useful to include the step name?

**Comment by danielhelfand** [comment]
Ah, my apologies. First time using the dashboard and didn't look hard enough at where the information was. I think the current implementation makes sense for now. Thanks!

**Comment by AlanGreene** [comment]
No problem at all, it's good feedback to have. Hopefully some of the design updates planned for the PipelineRun and TaskRun details pages will help make this clearer.

Maybe at some point in the future we'll have an aggregated TaskRun log view so will definitely keep this in mind.
