### ISSUE TITLE
Dashboard 0.5.3 test / update to work with OCP 4.4 

### ISSUE THREAD

**Issue by anneqm** [tektoncd/dashboard#1183]
Dashboard version 0.5.x needs to work with Openshift OCP 4.4.

**Comment by AlanGreene** [comment]
@a-roberts any action required here or ok to close?

**Comment by a-roberts** [comment]
We're beginning to get access to OCP 4.4 clusters now through colleagues so this is still something worth being picked up

**Comment by rnapoles-tktn** [comment]
Tested, found https://github.com/tektoncd/dashboard/issues/1319
