### ISSUE TITLE
Cancelling secret creation leads to 'Select Namespace' in the SideNav namespace dropdown

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1186]
# Expected behavior
If I decide I no longer want to create a secret and press `cancel`, I should be returned to the secrets page in the state it was in before I pressed `create`

# Actual behavior
On pressing `cancel`, no namespace is selected in the dropdown box on the SideNav, and so no secrets are displayed in the table.
Further to this, if I then try to use any other part of the dashboard without selecting a namespace first, these have the same behaviour of no namespace selected and therefore no resources being displayed.

# Steps to reproduce the problem

1. Go to create a secret
2. Press cancel
3. Observe that you now cannot see any secrets and instead get `No secrets in namespace` in the table and `Select Namespace` in the namespace dropdown

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

# Additional Info

**Comment by AlanGreene** [comment]
> if I then try to use any other part of the dashboard without selecting a namespace first, these are broken as well...

Are you just referring to the empty namespace dropdown or are you actually seeing broken behaviour on the other pages?

**Comment by Megan-Wright** [comment]
> > if I then try to use any other part of the dashboard without selecting a namespace first, these are broken as well...
> 
> Are you just referring to the empty namespace dropdown or are you actually seeing broken behaviour on the other pages?

I just meant the empty namespace behaviour - I'll update the description to be more clear

**Comment by AlanGreene** [comment]
Cool, fix on the way
