### ISSUE TITLE
We should introduce byId for the secrets store

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1191]
We currently don't have `byId` for secrets and so shared functions in `utils.js` (such as `isStale`) that use `byId`, won't work for secrets unless we tailor the function call to be able to use the relevant part of `byNamespace` instead...

Introducing `byId` for secrets would mean they were in line with other resources we have within the dashboard and so could use shared functions much more easily.

See: https://github.com/tektoncd/dashboard/pull/1189

**Comment by AlanGreene** [comment]
This one would be nice to have for consistency with other resource types but is relatively low priority at the moment since the Secrets functionality is not under active development and the current structure is not causing any problems.

**Comment by AlanGreene** [comment]
Depending on the exact approach we take this may actually be superseded by https://github.com/tektoncd/dashboard/issues/1842 which is looking at significantly reducing our use of redux

**Comment by AlanGreene** [comment]
Secrets functionality may be going away soon so this may no longer be required. Track discussions / plan at https://github.com/tektoncd/dashboard/issues/1930

**Comment by AlanGreene** [comment]
#1931 is merged, closing this as obsolete.
/close
