### ISSUE TITLE
Triggers API group change

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#1193]
https://github.com/tektoncd/triggers/issues/332

Triggers will be changing its API group in version 0.4

We will need to update `src/api/index.js` to change `group: 'tekton.dev'` to `group: 'triggers.tekton.dev'` for the Triggers APIs once we're ready to release a dashboard version compatible with Triggers 0.4.

**Comment by a-roberts** [comment]
The Triggers change is in and we want master to work with master, thoughts on removing the WIP and getting this in @AlanGreene ?

**Comment by AlanGreene** [comment]
As long as the Triggers release isn't too far off I'm happy to get this in
