### ISSUE TITLE
Cannot open details page for Task- or PipelineRuns

### ISSUE THREAD

**Issue by christopherfrieler** [tektoncd/dashboard#1198]
# Expected behavior

A click on the name of TaskRun or PipelineRun in the list should lead to a page with details about this Run.

# Actual behavior
A click on the name of TaskRun or PipelineRun in the list leads to the following error:

> Error loading page Cannot read property 'params' of undefined

# Steps to reproduce the problem

1. Install tekton-dashoard
2. Run the simple Hello-World-Task from [https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md](https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md)
3. Open the dashboard in the browser, go to the list of TaskRuns and click on the name of the TaskRun

Same for PipelineRuns.

# Environment
- Kubernetes Platform:
minikube, locally on my MacBook

- Tekton Pipelines version:
v0.11.0-rc3

- Tekton Triggers version:
none

- Tekton Dashboard version:
v0.5.3

# Additional Info
I've also tried to add a param to the Task, because the error message mentioned that property of a TaskRun. Didn't help.

**Comment by AlanGreene** [comment]
Hey @christopherfrieler, thanks for reporting this. The Dashboard is not yet fully compatible with the v1beta1 APIs in the Pipelines 0.11 release candidate, but we're planning a release for next week once the final 0.11 is available and it will include updates for the remaining changes.

Dashboard 0.5.3 supports Pipelines 0.10, and its v1alpha1 resources still use `spec.inputs.params` as opposed to `spec.params`. https://github.com/tektoncd/pipeline/blob/v0.10.2/docs/taskruns.md#input-parameters

**Comment by christopherfrieler** [comment]
Thanks for the quick response. I'll try again with the next release.

By the way, tekton-cli seems to have a similar issue: https://github.com/tektoncd/cli/issues/817.

**Comment by christopherfrieler** [comment]
Finally found the time to retest this with version 0.6.1. Works perfectly. 👍
