### ISSUE TITLE
Issue displaying certain event listeners

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/dashboard#1199]
# Expected behavior
I should be able to look at any event listener in the cluster

# Actual behavior
Some are [displayed correctly](http://dashboard.robotcat.tekton.dev/#/namespaces/default/eventlisteners/image-builder), but I've got [one that does not work](http://dashboard.robotcat.tekton.dev/#/namespaces/default/eventlisteners/tekton-cd).

<img width="383" alt="image" src="https://user-images.githubusercontent.com/2205608/77750704-317ea500-701c-11ea-931b-1e16f555d0aa.png">

# Steps to reproduce the problem

1. This is the event listener: https://github.com/tektoncd/plumbing/blob/master/tekton/resources/cd/eventlistener.yaml
2. View through the dashboard: http://dashboard.robotcat.tekton.dev/#/namespaces/default/eventlisteners/tekton-cd

# Environment
- Kubernetes Platform:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.26", GitCommit:"525ce678faa2b28483fa9569757a61f92b7b0988", GitTreeState:"clean", BuildDate:"2020-03-06T18:47:39Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipelines version:
Nightly: v20200327-0df48d48e5

- Tekton Triggers version:
Nightly: v20200327-a0fd950080

- Tekton Dashboard version:
Beta release https://console.cloud.google.com/storage/browser/tekton-releases/dashboard/adambeta4/adambeta4/previous/beta/?project=tekton-releases

# Additional Info

**Comment by AlanGreene** [comment]
Thanks for reporting, should be fixed by https://github.com/tektoncd/dashboard/pull/1195

**Comment by afrittoli** [comment]
Great, thank you!
