### ISSUE TITLE
Readonly dashboard nightly release is broken

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/dashboard#1213]
# Expected behavior
Readonly dashboard nighly release is avaiable

# Actual behavior
Kustomize fails on the readonly release, so an empty release file is produced.

```
+ ko resolve --preserve-import-paths -f -
Error: builtin PatchStrategicMergeTransformer config: [112 97 116 104 115 58 10 45 32 46 46 47 114 101 97 100 111 110 108 121 47 114 101 97 100 111 110 108 121 45 100 101 112 108 111 121 109 101 110 116 45 112 97 116 99 104 46 121 97 109 108 10]: security; file '/workspace/go/src/github.com/tektoncd/dashboard/overlays/readonly/readonly-deployment-patch.yaml' is not in or below '/workspace/go/src/github.com/tektoncd/dashboard/overlays/dev-locked-down'
+ kustomize build overlays/dev-openshift --load_restrictor=LoadRestrictionsNone
```

# Steps to reproduce the problem

1. It runs nightly - see for instance https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelineruns/dashboard-release-nightly-5tf8n

# Environment
- Kubernetes Platform:
GKE
```
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.9", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T22:35:02Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipelines version:

v0.10.1

- Tekton Triggers version:

v0.3.1

- Tekton Dashboard version:

master

# Additional Info
There are other issues associated to this
- the release job does not fail. we should use `set -o pipefail` in the script
- the location where the release is published is not right, `previous` should be on the same level as `latest`, not under it:

```
+ mkdir -p /workspace/output/bucket-for-dashboard/latest/previous/v20200330-523ff7cbd7/
./previous/v20200209-77209b64f8/openshift-tekton-dashboard-release-readonly.yaml
./previous/v20200211-fa1236e9ad
./previous/v20200211-fa1236e9ad/tekton-dashboard-release-readonly.yaml
./previous/v20200211-fa1236e9ad/tekton-dashboard-release.yaml
./previous/v20200211-fa1236e9ad/openshift-tekton-dashboard-release.yaml
./previous/v20200211-fa1236e9ad/openshift-tekton-dashboard-release-readonly.yaml
+ cp /workspace/output/bucket-for-dashboard/latest/tekton-dashboard-release.yaml /workspace/output/bucket-for-dashboard/latest/previous/v20200330-523ff7cbd7/
+ cp /workspace/output/bucket-for-dashboard/latest/tekton-dashboard-release-readonly.yaml /workspace/output/bucket-for-dashboard/latest/previous/v20200330-523ff7cbd7/
+ cp /workspace/output/bucket-for-dashboard/latest/openshift-tekton-dashboard-release.yaml /workspace/output/bucket-for-dashboard/latest/previous/v20200330-523ff7cbd7/
+ cp /workspace/output/bucket-for-dashboard/latest/openshift-tekton-dashboard-release-readonly.yaml /workspace/output/bucket-for-dashboard/latest/previous/v20200330-523ff7cbd7/
```

**Comment by AlanGreene** [comment]
@afrittoli looks like the nightly job isn't using the latest version of https://github.com/tektoncd/dashboard/blob/master/tekton/publish.yaml

notice missing `--load_restrictor=LoadRestrictionsNone` for the dev-locked-down overlay

**Comment by afrittoli** [comment]
@AlanGreene @a-roberts I updated the dogfooding cluster and re-ran and it works fine, thank you!

https://console.cloud.google.com/storage/browser/tekton-releases-nightly/dashboard/latest/previous/v20200330-b1b43fab34/?forceOnBucketsSortingFiltering=false&project=tekton-nightly

I would still consider adding the `set -o pipefail` and fixing the folder location, but I'm happy to close this one if you prefer so.

**Comment by a-roberts** [comment]
Thanks @afrittoli, so would this simply be a case of adding it in https://github.com/tektoncd/dashboard/blob/e3548b579740550c841a4b32d4f3fbc5a610a9db/test/publish-images.sh? I did a search on nightly and noticed a different set up from Pipeline which uses https://github.com/tektoncd/pipeline/blob/35fbc8a47d80cec81f6c3cdf8f43629ab18bca47/hack/nightly.sh

**Comment by a-roberts** [comment]
Gonna close this one as I don't think there are any issues now (so the root issue is actually resolves and it was the pesky flag), happy for anyone to followup with the suggestions Andrea made above as well
