### ISSUE TITLE
Display Conditions in Tekton Dashboard

### ISSUE THREAD

**Issue by k** [tektoncd/dashboard#1217]
# Expected behavior
The user would be able to tell that a condition was checked when viewing a pipelinerun

# Actual behavior
Any conditions that are checked and resulting in a task not being run are not viewable and can leave the runner confused. This is especially confusing where there are *no* tasks run in a pipeline due to conditions

# Steps to reproduce the problem

1. Create a pipeline with conditions
2. Make a pipelinerun that results in running no tasks due to conditions
3. Observe how the pipelilnerun page is blank

# Environment
- Kubernetes Platform:

eks, docker, 1.15

- Tekton Pipelines version:

0.9.2

- Tekton Triggers version:

none

- Tekton Dashboard version:
0.4.1

# Additional Info

**Comment by AlanGreene** [comment]
This is included in recent nightly builds and will be in the 0.6.0 release, see https://github.com/tektoncd/dashboard/pull/1172#pullrequestreview-379366032
