### ISSUE TITLE
Apply finishing touches for beta release (Gopkg.lock/toml, APIs?)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1218]
Pipelines Beta is now live, we currently reference rc3 in our Gopkg toml when we can instead of use 0.11.0. 

In addition, we've got plenty of backend code still using v1alpha1 imports, see https://github.com/tektoncd/dashboard/blob/master/pkg/controllers/tekton/taskrun.go#L7 for example. @vdemeester remind me again please why these are OK to be alpha still, or should they change? 😸

**Comment by vdemeester** [comment]
I think they should change but as the controller does auto convert *and* the webhook serves both, it's "meant" to work still :stuck_out_tongue:

**Comment by a-roberts** [comment]
> I think they should change but as the controller does auto convert _and_ the webhook serves both, it's "meant" to work still 😛

Yeah I haven't noticed any problems with it, so gonna keep at least for now, thanks

**Comment by a-roberts** [comment]
Merged now so closing 🎂
