### ISSUE TITLE
Don't properly handle K8s lifecycle

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/dashboard#1223]
When I run the dashboard as a Knative service this really pops out because we run with a higher default `terminationGracePeriodSeconds`.

Basically K8s sends SIGTERM to tell the dashboard to drain, and then SIGKILL after the grace period.  `knative.dev/pkg/signals` has a way of getting a channel ad a context to facilitate adhering to this.

**Comment by mattmoor** [comment]
Looks like you are using the signal package from `k8s.io/sample-controller`, which is surely an interesting dependency :)

The informers seem to take the stopCh that sets up, but nothing ever drains the HTTP servers: https://github.com/tektoncd/dashboard/blob/4faecbc65ff0c0ee58269e100468f35b1018fa12/cmd/dashboard/main.go#L102-L103

**Comment by mattmoor** [comment]
We invoke `ListenAndServe()` in a goroutine and then we see the `stopCh` file we call `server.Shutdown(context.Background())`.

**Comment by mattmoor** [comment]
I'll take a crack at this, since at this point it should be plumbing.

**Comment by a-roberts** [comment]
Merged so closing
