### ISSUE TITLE
User is presented with Password/Access Token radio button selection twice

### ISSUE THREAD

**Issue by rnapoles-tktn** [tektoncd/dashboard#1239]
**Problem:**
The UI prompts the user twice for selection of secret type

**Versions:**
Pipelines v0.10.1,  Triggers 0.3.1, Dashboard and webhooks v0.5.3
OCP 4.4RC1

**Steps to reproduce:**
Install Tekton using versions listed above
Select Secrets Tab
Click Access Token to create an access token based secret (first prompt)
![image.png](https://images.zenhubusercontent.com/5db346d5b0111c0001df287a/d97da527-d3d9-466c-8efe-5c26733f6646)
Click the "Create +" button
The UI for the "Password" secret is rendered, the user is presented with the Secret Type radio button again
![image](https://user-images.githubusercontent.com/57016183/77758698-d04dd600-7009-11ea-9118-e10037397ef8.png)

**Expected:**
Since user selected the Access Token secret type in the Secrets Tab the expectation is that after clicking the "Create +" button the UI to create a secret using access token be displayed.

**Comment by AlanGreene** [comment]
Related: https://github.com/tektoncd/dashboard/issues/1121
This will give us a cleaner way to share the selected type between the list + create views ensuring consistency and avoiding having to duplicate this in state.

**Comment by AlanGreene** [comment]
it was still showing up in queries for open issues
