### ISSUE TITLE
Selected NameSpace is reset when cancelling creation of Secret (regression)

### ISSUE THREAD

**Issue by rnapoles-tktn** [tektoncd/dashboard#1241]
**Problem:**
After cancelling the creation of a Secret the Selected NameSpace is Reset to no NameSpace Selected in the NameSpace dropdown.
Does not happen on v0.5.2

**Versions:**
Pipelines v0.10.1,  Triggers 0.3.1, Dashboard and webhooks v0.5.3
OCP 4.3 / OCP 4.4 RC1

**Steps to reproduce:**
Clean install Tekton using versions listed above
Select a namespace
Select the Secrets Tab
Click Create + button
Click Cancel
Note that the selected NameSpace is deselected

**Comment by AlanGreene** [comment]
This is fixed in the 0.6.0 release
https://github.com/tektoncd/dashboard/issues/1186
