### ISSUE TITLE
Update release pipeline to use Tekton Pipelines 0.11

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1246]
# Expected behavior
The pipeline we use to create releases (building and pushing images) should work with Tekton 0.11

# Actual behavior
We use v1alpha resources everywhere so it likely doesn't work, Todo check. Basically it's a pain do switch between beta and not (doing an entirely clean reinstall each time which often requires deleting the install namespace, I'd really rather not)

**Comment by AlanGreene** [comment]
Updated on dogfooding and ran successfully. Resulting 'nightly' build is now deployed to both robotcat and dogfooding :tada:

![image](https://user-images.githubusercontent.com/2829095/79862526-21b17100-83ce-11ea-9d12-f645f6fa0ffb.png)
