### ISSUE TITLE
Feature request - panelling for creating TaskRuns too

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1247]
@mattmoor raised an interesting point here: https://twitter.com/mattomata/status/1246824264210112515?s=21

# Expected behavior
Users should be able to create TaskRuns too

# Actual behavior
One cannot

# Additional Info
Should be a low-hanging fruit with a clear benefit and we can reuse plenty of code for creating PipelineRuns, changing out the resource types. They'd be rerunnable too just like PIpelineRuns.

**Comment by mattmoor** [comment]
😍

**Comment by JustinKuli** [comment]
I noticed this at the end of last week, and I'm interested in taking a look at it.

**Comment by a-roberts** [comment]
Thanks @JustinKuli! I'm wondering if, implementation-wise, we want to take the existing PipelineRun creation modal and repurpose that since it's so similar (last time I checked anyway) to a TaskRun - changing the resource type and anything else that's only there for TaskRuns but not PipelineRuns. 

@AlanGreene especially, curious what your take is on getting this done as cleanly as possible from a code reuse perspective.

**Comment by AlanGreene** [comment]
We should also consider support for creating TaskRuns from ClusterTasks.

From a quick scan of the existing CreatePipelineRun there's definitely a lot that's reusable, probably most of it...

Differences:
- `PipelinesDropdown` vs. Task / ClusterTask dropdown
- API - `createPipelineRun` vs. `createTaskRun`
- strings - replace Pipeline with Task / ClusterTask
- `handlePipelineChange` would need to be swapped out or refactored to account for different types
  - this is probably the biggest piece, but hopefully still relatively straightforward

All of the code around validation, labels, params, resources, etc. looks like it should be fine, just some renaming to remove references to pipeline.

One approach here could be to extract the selection of Pipeline / Task / ClusterTask, pass that as `children` (or some other prop), and wire it in to the correct events along with the API + string props. The rest looks like it could essentially be left more or less as-is.

There are other options here so open to any and all suggestions.

**Comment by JustinKuli** [comment]
I think I should start off by saying that although this is approachable, this is bigger than I originally thought. Also it's been a while since I did any React, so I may need to brush up a bit...

> We should also consider support for creating TaskRuns from ClusterTasks.

I agree. I'm new here, but is there a major difference between the two? Assuming ClusterTasks are just Tasks that are available in every namespace, I think it would make sense to just handle it in the dropdown: display all ClusterTasks as well as any Tasks in the current namespace. Or should the ClusterTasks be specially handled or marked?

Regarding reuse, do you mean that the common pieces should go into a new Class (CreateRunsModal?), which both of these will use? Or do you mean some other way of adjusting this? (This is the bigger than expected part, which I need to re-learn React for.)

It seems like the first things that need to be done here are the createTaskRun API and the Task dropdown, so I'll work on getting those started.

**Comment by AlanGreene** [comment]
> this is bigger than I originally thought

Not a problem, and please don't feel obligated to take it all on yourself. If you want to carve it up and just address specific pieces that's absolutely fine.

> Assuming ClusterTasks are just Tasks that are available in every namespace

Yes that's it exactly. The reason I called it out is that we have a separate list view for ClusterTasks, they're not included with Tasks, so we would have 2 places to trigger the creation of TaskRuns. We could potentially list both `kind`s in a single dropdown on both pages with something to differentiate them but I think it would be clearer to keep them separate, i.e. only include ClusterTasks when creating a TaskRun from the ClusterTasks page.

Maybe in future we would have a separate route to creating a TaskRun that could combine them, but for now the Dashboard provides a very `kind`-centric experience and mixing things could be confusing or at least unexpected.

Interested in others' opinions on this.

> common pieces should go into a new Class (CreateRunsModal?), which both of these will use?

Essentially yes. I'd be happy to consider other approaches too, this was just the first one I thought of.

> createTaskRun API and the Task dropdown, so I'll work on getting those started.

Awesome, feel free to reach out here or on Slack if you have any questions.

**Comment by a-roberts** [comment]
@JustinKuli good points, my two cents especially as you mention being new and having to relearn React - it'd be easiest to copy and paste the existing PIpelineRun creation code and do the same thing for TaskRuns and have a side-task to do the refactor job (and perhaps that work could be split amongst multiple people).

Regarding ClusterTasks, I think having a chooser (like we do for secret types: password vs access token) would be useful, so when prompted to choose a Task it can be either.a regular (namespaced) Task versus a ClusterTask. 

Indeed getting the APIs in place is gonna be a great first anyway since we'll need this regardless 👍 I'm all for adding stuff that works well and doesn't touch other parts of code instead of doing a grand refactor here (even if it introduces duplication, I'm assuming it's going to be non-trivial to create a generic CreateRuns page). 

Sidenote though, perhaps you'll find by implementing the *copy it all and replace the PIpelineRun with TaskRun mentions* feels dirty and CreateRunsModal begins to look more attractive and manageable 😄  happy to help as well

**Comment by JustinKuli** [comment]
@AlanGreene I think we're imagining different things for where to create the TaskRuns. Currently PipelineRuns are created from the PipelineRuns page, not the Pipelines page, so I was going to base the work here off of that. In which case, I think the modal would have some way to choose either, and I think @a-roberts's suggestion to use a chooser would make the most sense to keep the experience cleaner. Did you have something else in mind?

It wasn't clear to me at first, so let me lay out an example of how a user would currently create a PipelineRun, starting from the Pipelines page:
1) Click on the specific pipeline's name
2) (get navigated to the PipelineRuns page, populated with a filter for the specific pipeline)
3) Click on the "Create +" button
4) (the CreatePipelineRuns modal appears, already specific to the pipeline, based on the label)
5) Fill in the form details and click Create in the modal

Only if the user goes directly to the PipelineRuns page (without a label) do they get the choice of pipeline and namespace via dropdowns. So I think it would be similar for TaskRuns: if they get to the modal without a label, then they need to choose Task or ClusterTask, and then they can choose a specific Namespace/Task or ClusterTask.

So as long as (4) still works for TaskRuns, and the Modal is pre-populated when they come from the Tasks or ClusterTasks page, I think the `kind`-centric experience is preserved.

Is that all correct, or did I miss some things?

**Comment by AlanGreene** [comment]
Ah yes my bad, I was working on something else related to the Tasks and ClusterTasks pages recently so that was stuck in my head 😆 ignore me...

That sounds good 👍
