### ISSUE TITLE
Set X-Content-Type-Options Header

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#1252]
X-Content-Type-Options header is missing in all responses of all the applications which are in scope for testing. The "X-Content-Type-Options" header (with "no sniff" value) prevents IE and Chrome from ignoring the content type of a response. This reduces exposure to drive-by download attacks and sites serving user uploaded content. It was observed that only for few post requests content type header is set. Ensure that this header is set throughout the application.

IBMers can refer to https://github.ibm.com/IBMCloudPak4Apps/icpa-security/issues/33 for more information.

**Comment by AlanGreene** [comment]
We definitely have inconsistent Content-Type headers in responses, for example sometimes logs are return with a JSON type, other times plain text.

We'd need to make sure any change to add `nosniff` doesn't break things.

**Comment by AlanGreene** [comment]
We've done additional work on the logs APIs so it would be good to revisit this and determine whether it's safe to enable the header now.
