### ISSUE TITLE
Insecure Path attribute

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#1253]
The URL path that the cookie is valid for can be specified. If the domain and path match, then the cookie will be sent in the request. Just as with the domain attribute, if the path attribute is set too loosely, then it could leave the application vulnerable to attacks by other applications on the same server. For example, if the path attribute was set to the web server root "/", then the application cookies will be sent to every application within the same domain.
Redhat OpenShift provides Authentication. Path Attribute is missing while setting the Cookie.

IBMers may refer to https://github.ibm.com/IBMCloudPak4Apps/icpa-security/issues/32 for more information.

**Comment by AlanGreene** [comment]
For this one the dashboard is deployed at the root of the domain so `path=/` is both correct and appropriate.
