### ISSUE TITLE
Session invalidation

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#1254]
The end of a web session is usually triggered by one of the following two events:

    The user logs out
    The user remains idle for a certain amount of time and the application automatically logs him/her out.
    In cases where these functionalities are not implemented properly are prone to session replay where an attacker gains access to session tokens (e.g.: cookies) and replays the session tokens in order to "resurrect" the session of a legitimate user and virtually impersonate him/her. The application assigns a session token to a user on login. This session token is used to identify the user's session till logout. The session token can be used to hijack a user's session if it is not properly invalidated on logout and an adversary obtains it. Below is the scenario.
    Scenario 1:
    This application does not invalidate the token when the user logs out from the dashboard. 

This defect is very likely blocked on https://github.com/tektoncd/dashboard/issues/1046 which is blocked on openshift/oauth-proxy#155.

**Comment by mnuttall** [comment]
One option is to see whether a switch to https://github.com/oauth2-proxy/oauth2-proxy could provide an alternative solution to this problem.

**Comment by a-roberts** [comment]
https://github.com/openshift/oauth-proxy/ looks too inactive for our requirements and see that the project it forked from has been archived, so indeed switching to https://github.com/oauth2-proxy/oauth2-proxy could be better - I've raised https://github.com/oauth2-proxy/oauth2-proxy/issues/506 with a couple of questions. Based on the response we can then look at whether switching is going to make sense (and perhaps we'll gain a few more benefits like improving our security story for other platforms too, that'd be cool).

Discussed with @AlanGreene previously and he's mentioned managing our own inactivity timer would be a nuisance.
