### ISSUE TITLE
Cross Site Request Forgery vulnerability

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#1255]
Cross-Site Request Forgery (CSRF) is an attack that forces an end user to execute unwanted actions on a web application in which they're currently authenticated.
CSRF attacks specifically target state-changing requests, not theft of data, since the attacker has no way to see the response to the forged request. 

A specific CSRF attack is detailed in https://github.ibm.com/IBMCloudPak4Apps/icpa-security/issues/24

**Comment by a-roberts** [comment]
I'll take a look, one suggested remedy is to:
 
> Generate a unique nonce for each form, place the nonce into the form, and verify the nonce upon receipt of the form. Be sure that the nonce is not predictable.

**Comment by AlanGreene** [comment]
We need a nonce on API requests that modify the system, i.e. any POST / PUT / PATCH / DELETE requests. Not sure if go-restful has any CSRF support built in or if we'd need to look into gorilla/csrf or other packages. We should avoid trying to implement something ourselves if possible.

The nonce directive on the CSP header is to allow for exceptions to rules in specific cases, for example enabling specific known inline scripts to be executed when unsafe-inline is blocked. To do this, the script tag would have the nonce attribute added and the browser must very it matches the value in the header before executing its content.

**Comment by a-roberts** [comment]
> We need a nonce on API requests that modify the system, i.e. any POST / PUT / PATCH / DELETE requests. Not sure if go-restful has any CSRF support built in or if we'd need to look into gorilla/csrf or other packages. We should avoid trying to implement something ourselves if possible.
> 
> The nonce directive on the CSP header is to allow for exceptions to rules in specific cases, for example enabling specific known inline scripts to be executed when unsafe-inline is blocked. To do this, the script tag would have the nonce attribute added and the browser must very it matches the value in the header before executing its content.

Not seeing any mentions of nonces or csrf protection for go-restful, we've put a lot of work into the current router set up so shifting away in favour of gorilla-mux (which is easy to use with gorilla/csrf) just for this wouldn't be ideal. 

gorilla/csrf seems reasonable enough to use, I've yet to figure out how to attach it our current set up though (snooping around in pkg/router/router.go looking at our restful/container objects)

**Comment by a-roberts** [comment]
@AlanGreene's been running with this one using a simplified approach from what I had 🥳
