### ISSUE TITLE
Wrong log format ?

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/dashboard#1258]
https://github.com/tektoncd/dashboard/blob/f6568713d1e81f64c74c715a47079e7614282099/pkg/endpoints/dashboard.go#L62

Shouldn't it be `logging.Log.Infof("Dashboard is in read-only mode: %t", asBool)` instead ?

**Comment by eddycharly** [comment]
@AlanGreene what’s your opinion on this one https://github.com/tektoncd/dashboard/issues/1257 ?

I could open a PR if you’re ok with it.

**Comment by AlanGreene** [comment]
I'll take a look now and respond over there
