### ISSUE TITLE
Add support for configurable triggers and pipeline namespaces

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/dashboard#1261]
The namespace where Pipelines and/or Triggers is deployed is hard coded in a few places, see below for an example:

https://github.com/tektoncd/dashboard/blob/f6568713d1e81f64c74c715a47079e7614282099/pkg/endpoints/dashboard.go#L112

This makes it difficult to deploy the dashboard in a different namespace than `tekton-pipelines` (it works but a few things are failing).

**Comment by a-roberts** [comment]
Merged so closing, thanks for this @eddycharly!
