### ISSUE TITLE
Check we really can show beta specific resources

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1264]
We've still got v1alpha1 references in our Go code, let's make sure we can display any beta specific Tekton resources OK. 

Related: https://github.com/tektoncd/experimental/pull/503#issuecomment-610938922

**Comment by AlanGreene** [comment]
Also related: https://github.com/tektoncd/dashboard/issues/1206

**Comment by a-roberts** [comment]
Copying what I accidentally mentioned on another issue 👀 

I'm wondering if https://github.com/tektoncd/catalog is the best option as it's now version tagged (e.g beta vs not) is the best way to do this, see https://github.com/tektoncd/catalog/blob/v1beta1/golang/build.yaml which mentions workspaces

**Comment by AlanGreene** [comment]
Think it's safe to close this one now.
