### ISSUE TITLE
Taskruns can still be deleted in the read-only dashboard

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1270]
# Expected behavior
On the read-only dashboard I should not be able to create or delete any resources

# Actual behavior
I can still delete taskruns 

# Steps to reproduce the problem

1. Install the read-only dashboard
2. Try to delete a taskrun and observe that this works successfully

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

0.11.1

- Tekton Triggers version:

0.4.0

- Tekton Dashboard version:

0.6.1

# Additional Info

**Comment by AlanGreene** [comment]
I couldn't reproduce the successful deletion, it was blocked by RBAC. Can you check the roles in your environment to make sure you don't somehow have 'delete' for tekton.dev/taskruns?

PR open to hide the actions in the UI at least.
