### ISSUE TITLE
Sidenav doesnt auto update for triggers install / uninstall

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1276]
# Expected behavior
Sidenav updates 

# Actual behavior
Doesnt update 

# Steps to reproduce the problem

1. Install triggers 
2.
3.

# Environment
- Kubernetes Platform:

docker 
- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

0.6.1
# Additional Info

**Comment by AlanGreene** [comment]
If we want to do this, one option would be to add a websocket handler for CRDs and detect when any of the triggers CRDs are added / deleted.

**Comment by eddycharly** [comment]
I’ll look at it, most of the UI has been plugged on the redux store, it’s just a matter of notifying the frontend when something changes. 

/assign
