### ISSUE TITLE
Expose dashboard UI store and selectors to extensions

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#128]
An extension should be able to access data provided by the core dashboard UI without having to duplicate API calls, state management, etc. itself.

We should expose the following for use by the extension UI code:
- [x] the redux store
- [x] root selectors
- [x] other useful functions:
  - ~~maybe API layer?~~ No, too much risk of inconsistency, expose action creators instead so store is updated as expected
  - [x] action creators
  - [x] router utils (i.e. get URL for specific list / resource)

Selectors and other functions exposed to extensions should be clearly documented.

**Comment by steveodonovan** [comment]
https://github.com/tektoncd/dashboard/pull/208/files#diff-64a5de7597cee66f6619d7f39d684e8eR237 to be cleaned up once url selectors are in place
