### ISSUE TITLE
v0.6.1 non-openshift k8s release looks for openshift routes and fails to display some taskruns 

### ISSUE THREAD

**Issue by bbhuston** [tektoncd/dashboard#1285]
# Expected behavior

The taskrun logs will properly display in the tekton dashboard.

# Actual behavior

Looks at logs of certain taskruns throws react error in tekton dashboard.  Dashboard appears to be looking for openshift networking despite being a standard k8s install.

# Steps to reproduce the problem

1. kubectl -n tekton-pipelines apply -f https://github.com/tektoncd/dashboard/releases/download/v0.6.1/tekton-dashboard-release.yaml
2. tkn task create -f https://raw.githubusercontent.com/tektoncd/pipeline/master/examples/v1beta1/taskruns/git-resource.yaml -n tekton-pipelines 
3. kubectl -n tekton-pipelines port-foward svc/tekton-dashboard 9097:9097 &
4. Go to "localhost:9097" and navigate to taskruns created upon.  Here you will see the following error message.

```
Error loading page

Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

5. In Chrome developer console I see the following 500 status code for the `/` endpoint.  Same error appears in firefox as well.  There appears to be an extra `/` getting tacked onto the request URL.

```
Request URL: http://localhost:9097/proxy/apis/route.openshift.io/v1//
Request Method: GET
Status Code: 500 
Remote Address: 35.224.93.161:443
Referrer Policy: no-referrer-when-downgrade
```

# Environment
- Kubernetes Platform:

GKE cluster v15.9.   Istio v1.5
 
- Tekton Pipelines version:

0.11.1

- Tekton Triggers version:

0.4.0

- Tekton Dashboard version:

0.6.1

# Additional Info

**Comment by a-roberts** [comment]
Thanks for the report @bbhuston! For the OpenShift route problem, yeah you're right and there's an issue for resolving it here https://github.com/tektoncd/dashboard/issues/778

Your TaskRun problem is more serious, I'll see if I can take a look today, @AlanGreene @steveodonovan  FYI 👀

**Comment by a-roberts** [comment]
I see it,

```

vendors.187b855….js:93 TypeError: Object(...) is not a function
    at TaskRunContainer.loadTaskRun (main.9943ff2….js:1)
    at TaskRunContainer.value (main.9943ff2….js:1)
    at _o (vendors.187b855….js:93)
    at Do (vendors.187b855….js:93)
    at wc (vendors.187b855….js:93)
    at ul (vendors.187b855….js:93)
    at cl (vendors.187b855….js:93)
    at Qc (vendors.187b855….js:93)
    at vendors.187b855….js:93
    at t.unstable_runWithPriority (vendors.187b855….js:9)
main.9943ff2….js:1 ErrorBoundary 
{error: TypeError: Object(...) is not a function
    at TaskRunContainer.loadTaskRun (http://localhost:8001…, info: {…}}

```

so the TaskRun itself runs fine and is reported as doing so in the dash

TaskRun details
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  annotations:
    pipeline.tekton.dev/release: devel
  creationTimestamp: "2020-04-14T08:46:15Z"
  generateName: git-resource-branch-
  generation: 2
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
  name: git-resource-branch-zqks5
  namespace: tekton-pipelines
  resourceVersion: "5082"
  selfLink: /apis/tekton.dev/v1beta1/namespaces/tekton-pipelines/taskruns/git-resource-branch-zqks5
  uid: 238bdcc0-6b70-44a1-a54c-071cebc99d14
spec:
  inputs: {}
  outputs: {}
  resources:
    inputs:
    - name: skaffold
      resourceSpec:
        params:
        - name: revision
          value: master
        - name: url
          value: https://github.com/GoogleContainerTools/skaffold
        type: git
  serviceAccountName: ""
  taskSpec:
    resources:
      inputs:
      - name: skaffold
        type: git
    steps:
    - image: ubuntu
      name: ""
      resources: {}
      script: cat skaffold/README.md
  timeout: 1h0m0s
status:
  completionTime: "2020-04-14T08:46:35Z"
  conditions:
  - lastTransitionTime: "2020-04-14T08:46:35Z"
    message: All Steps have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  podName: git-resource-branch-zqks5-pod-tpzkw
  resourcesResult:
  - key: commit
    resourceRef: {}
    value: b401d41235e525df13efca815a9c12a798ddf0cc
  startTime: "2020-04-14T08:46:15Z"
  steps:
  - container: step-git-source-skaffold-6qfdp
    imageID: docker-pullable://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init@sha256:599f634b71a5bd6cd5f83e0ec8f9ce56825640ff20f38a184a3c962df3024c6c
    name: git-source-skaffold-6qfdp
    terminated:
      containerID: docker://c1840e4e6e01fe486982e42dfbb60b1c8e0b43507d7d0c6e69e273c8d5a1bbf7
      exitCode: 0
      finishedAt: "2020-04-14T08:46:33Z"
      message: '[{"key":"commit","value":"b401d41235e525df13efca815a9c12a798ddf0cc","resourceRef":{}}]'
      reason: Completed
      startedAt: "2020-04-14T08:46:25Z"
  - container: step-unnamed-1
    imageID: docker-pullable://ubuntu@sha256:bec5a2727be7fff3d308193cfde3491f8fba1a2ba392b7546b43a051853a341d
    name: unnamed-1
    terminated:
      containerID: docker://d3d6821b2404661a29d50751e88b171d96a8347524790633770b1127860d8aa2
      exitCode: 0
      finishedAt: "2020-04-14T08:46:34Z"
      reason: Completed
      startedAt: "2020-04-14T08:46:34Z"
```

Adding this as a bug and something to hold up the 0.6.1 release for I say, thanks again

**Comment by a-roberts** [comment]
@AlanGreene I could do with some help on this one, so I've got
```
export function getParams({ params, inputs, resources }) {
  const foundParams = params || (inputs && inputs.params) || (resources && resources.inputs[0].resourceSpec.params);
  console.log(foundParams);
  return foundParams;
}
```

That gives me a max stack size problem though and breaks the other TaskRuns not using resource spec (but if I add a print, I do get the data appearing). Looks like breaking down the params by resource spec is a little trickier than I thought...

**Comment by a-roberts** [comment]
@AlanGreene and I had a good look into this one, documenting what we've came up with for transparency - we could do with overhauling the way we handle steps, their ordering, and tasks, to be able to accomodate for the different step types (e.g. inline with a resourceSpec and with unnamed steps) - potentially to go into 0.7.0 as that may end up being a big piece of work. 

Short of an overhaul we can look into capturing the error and providing a useful warning: e.g. to move away from using PipelineResources with a known worked example to reference, or perhaps to add names to the steps - I confirmed the latter works as well, so investigating if we can handle this in code instead so users can sit back and relax without modifying their code.

If we can't accomplish this in a reasonable timeframe, we'll publish with a known big gotcha in the readme and release notes mentioning the limitation, this is a worst case scenario though (0.6.1 fixes several large issues and it's useful for anyone looking to use Triggers 0.4).

FWIW - with my changes and added step names I have this rendering:
![image](https://user-images.githubusercontent.com/12814972/79227368-af81df00-7e57-11ea-8f43-c2dd59f67086.png)
but that's with the change to the Tekton example and my PipelineRuns fail to render instead.

**Comment by AlanGreene** [comment]
PR open to address this: https://github.com/tektoncd/dashboard/pull/1287

Issue is related to use of unnamed steps + pipeline resources. Since pipeline resource init steps are considered in the counting order by pipelines when naming unnamed steps, our assumption to start naming of these steps at 0 (based on their position in the spec steps) was not valid and led to no matching status being found for the step. As a result of this, we entered a loop where the client code thought it had successfully selected a step, but when checking for it before rendering found a falsy value (in this case an empty string) and triggered another update cycle which repeated these steps. Eventually React steps in to stop this loop with 'error 185' (Maximum update depth exceeded) and we catch it at a page-level error boundary meaning we display an error notification instead of the main page content.

The PR updates the approach we take to matching the unnamed steps with their corresponding status, avoiding the bad assumption.

**Comment by a-roberts** [comment]
Fix for this is now merged, @bbhuston please give it a go (I'm publishing the 0.6.1 release now which will have the fix, or you can check out our nightly builds or build from master) and close this out if you're good 🤞

**Comment by bbhuston** [comment]
@a-roberts @AlanGreene BOOM!  Just tested the example against your latest release candidate install and it works perfectly!  Thanks a million for the rapid response on this.  Closing this issue now.
