### ISSUE TITLE
pipeline_test.go needs refactoring (negative tests, confusing)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#129]
While reviewing https://github.com/tektoncd/dashboard/pull/122 I came across our code in pipeline_test.go. It's in need of a refactor and very confusing to interpret, and contains *lots* of code that could be split up.

# Expected Behavior
It should be simple enough to understand the tests in pipeline_test.go.

# Actual Behavior
There are weird negative checks going on and massive methods. It's in need of a good refactor.

# Steps to Reproduce the Problem

1. Take a look at my comment https://github.com/tektoncd/dashboard/pull/122#issuecomment-490423974
2. Then take a look at the entire file https://github.com/tektoncd/dashboard/blob/master/pkg/endpoints/pipeline_test.go
3. Realise it's massive, features massive methods and contains code such as
```
	if result.Items[0].Name != "Task1" && result.Items[1].Name != "Task1" {
		t.Errorf("Task1 is not returned: %s, %s", result.Items[0].Name, result.Items[1].Name)
	}
	if result.Items[0].Name != "Task2" && result.Items[1].Name != "Task2" {
		t.Errorf("Task2 is not returned: %s, %s", result.Items[0].Name, result.Items[1].Name)
	}
```
Why not check Task1 or Task2 is returned instead of not checks like this? When I'm reading it, I'm thinking we want result.Items[0].Name to be Task1 or we'll error, but it's not the case.

# Additional Info
The code at the moment all works, but I'm weary when we introduce more code that requires testing and this is going to become unwieldy and confusing very soon, especially to anybody new to the code.

**Comment by vtereso** [comment]
https://github.com/tektoncd/dashboard/issues/179
