### ISSUE TITLE
0.6.1 release candidate - constant unknown (get serviceaccounts) messages in logs

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1291]
# Expected behavior
Our logs should be a joy to behold - they're littered with this though, every second
```
ts)
E0415 14:07:06.246393       1 reflector.go:280] runtime/asm_amd64.s:1357: Failed to watch *v1.ServiceAccount: unknown (get serviceaccounts)
E0415 14:07:07.271171       1 reflector.go:280] runtime/asm_amd64.s:1357: Failed to watch *v1.ServiceAccount: unknown (get serviceaccounts)
E0415 14:07:08.296573       1 reflector.go:280] runtime/asm_amd64.s:1357: Failed to watch *v1.ServiceAccount: unknown (get serviceaccounts)

```

likely we have an informer somewhere for ServiceAccounts that's behaving differently on OpenShift

# Actual behavior
```
ts)
E0415 14:07:06.246393       1 reflector.go:280] runtime/asm_amd64.s:1357: Failed to watch *v1.ServiceAccount: unknown (get serviceaccounts)
E0415 14:07:07.271171       1 reflector.go:280] runtime/asm_amd64.s:1357: Failed to watch *v1.ServiceAccount: unknown (get serviceaccounts)
E0415 14:07:08.296573       1 reflector.go:280] runtime/asm_amd64.s:1357: Failed to watch *v1.ServiceAccount: unknown (get serviceaccounts)
```

# Steps to reproduce the problem

1. Install the 0.6.1 release candidate for OpenShift
2. Install Tekton through the OpenShift Pipelines operator (I've used version 0.10.7, dev channel)
3. Get your Tekton Dashboard pod logs

# Environment
- Kubernetes Platform:
OCP 4.3

- Tekton Pipelines version:
0.10.7 is the operator version which **uses Tekton 0.10.1 still - so I'll see if this is the same with beta, betting it will be **

- Tekton Triggers version:

- Tekton Dashboard version:

0.6.1 release candidate

# Additional Info
canary/dev channel both give 0.10.1 of Pipelines atm anyway

We don't see this in other environments

**Comment by AlanGreene** [comment]
Missing `watch` here? https://github.com/tektoncd/dashboard/blob/f30b1e66c7b62b407994e60079211e0c38feff3c/base/200-clusterrole.yaml#L22

**Comment by a-roberts** [comment]
Nice catch @AlanGreene, @CarolynMabbott has tested this out on her OCP install and confirmed the problem's gone

I'll update our release yaml now 👍

**Comment by a-roberts** [comment]
Actually, yeah we need this change going into master 😄

**Comment by a-roberts** [comment]
(closing for real, actually merged to master now 🐑 )
