### ISSUE TITLE
Changing namespaces on namespaced Secrets url changes from access token to password

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1299]
# Expected behavior
I can change from namespace docker to namespace default when access token is selected and it stays on access token 
So same behaviour as when it doesnt have /namespace/default in the url 

# Actual behavior
It changes from access token to password when namespace is changed on the left

# Steps to reproduce the problem

1. go to http://localhost:9097/#/namespaces/default/secrets
2. select access token 
3. switch namespace on the left to a different namespace 

# Environment
- Kubernetes Platform:

docker 

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

0.6.1

# Additional Info
This acts normally when on `http://localhost:9097/#/secrets`
When you switch from a namespace to a different namespace while access token is selected then access token stays selected

**Comment by AlanGreene** [comment]
Related https://github.com/tektoncd/dashboard/issues/1121
