### ISSUE TITLE
Automate running of go tests

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#13]
There are a number of test files for the go code, but no automation kicking off these tests.  

Automated testing of the code is a pretty fundamental requirement.... this may mean working out how to integrate with prow which much of tekton seems to use already?

**Comment by vdemeester** [comment]
@dibbles this is being working on by @skaegi, me and other tekton's… :angel:

**Comment by a-roberts** [comment]
Awesome, thanks @vdemeester!

Given that's the case I'm going to use my newfound assign powers...

/assign vdemeester
/assign skaegi

I would assign anyone else but not sure who 😄 please let us know as well if there are any gotchas so we'd know how to do this ourselves. We're just adding the Dockerfile_test now to be used.

**Comment by vdemeester** [comment]
/close

It is done !
