### ISSUE TITLE
Changing namespace to All Namespaces while on create secret cancels create secret

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1300]
# Expected behavior
Can change to all namespaces on the left while crating a secret without it cancelling my create secret and taking me back to secrets page 

# Actual behavior
When I change to all namespaces on the left to all namespaces while on a url which contains /namespaces/default then it cancels my create secret 

# Steps to reproduce the problem

1. http://localhost:9097/#/namespaces/default/secrets
2. Press create secret and input some data 
3. Change namespace on left to all namespaces before pressing create 

# Environment
- Kubernetes Platform:

docker 

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

0.6.1

# Additional Info
While on a url not including /namespaces/default then this doesnt cause any issue

**Comment by AlanGreene** [comment]
I think we really need to start moving towards the new design where the namespaces dropdown is only present on the list views. Having it on the details / create views is causing too many problems as we've been adding targeted workarounds for each instance and that approach just doesn't scale in the long term.

**Comment by CarolynMabbott** [comment]
I agree, I've found alot of issues where changing namespace causes issues and breaks things

**Comment by AlanGreene** [comment]
Related to https://github.com/tektoncd/dashboard/issues/1271, could be addressed by moving Create Secret to a separate URL addressable page.

Tracking the overhaul of the namespaces filter in https://github.com/tektoncd/dashboard/issues/1304 and linked to this issue so we still have the detail.
