### ISSUE TITLE
Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=30s: context deadline exceeded

### ISSUE THREAD

**Issue by shibumi** [tektoncd/dashboard#1303]
# Expected behavior

A tekton dashboard deployment should work as expected:

`curl -L "https://github.com/tektoncd/dashboard/releases/download/v0.6.0/tekton-dashboard-release.yaml" -o tekton-dashboard-0.6.0yml`
`kubectl apply -f tekton-dashboard-0.6.0.yml`

# Actual behavior

```
❯ kubectl apply -f tekton-dashboard-0.6.0.yml 
customresourcedefinition.apiextensions.k8s.io/extensions.dashboard.tekton.dev created
serviceaccount/tekton-dashboard created
clusterrole.rbac.authorization.k8s.io/tekton-dashboard-minimal created
clusterrolebinding.rbac.authorization.k8s.io/tekton-dashboard-minimal created
service/tekton-dashboard created
deployment.apps/tekton-dashboard created
Error from server (InternalError): error when creating "tekton-dashboard-0.6.0.yml": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=30s: context deadline exceeded
```

# Steps to reproduce the problem

1. Deploy Tekton Pipelines 0.11.2 as mentioned in the installation guide
2. Deploy Tekton Triggers 0.4.0 as mentioned in installation guide
3. Deploy Tekton Dashboard 0.6.0 as mentioned in the README

# Environment
- Kubernetes Platform: Rancher

- Tekton Pipelines version: 0.11.2

- Tekton Triggers version: 0.4.0

- Tekton Dashboard version: 0.6.0

# Additional Info

**Comment by a-roberts** [comment]
Hey @shibumi thanks for the report! 0.6.0 is the Triggers 0.3.1 supported release, can you see if you get the same error with 0.6.1 please? I plan to be removing the pre-release tag shortly unless anyone raises an issue in the next few hours, we think it's good to go and that's the one where we can display Triggers 0.4 objects (as the API group has changed)

**Comment by shibumi** [comment]
Hi @a-roberts same behavior. What I did is:
```
kubectl apply -f tekton-pipeline-0.11.2.yml
kubectl apply -f tekton-triggers-0.4.0.yml #I don't know if this is necessary, looks like most of this is included in the tekton-pipeline yml
kubectl apply -f tekton-dashboard-0.6.1.yml 
```

any idea how I can debug this further?

**Comment by a-roberts** [comment]
> Hi @a-roberts same behavior. What I did is:
> 
> ```
> kubectl apply -f tekton-pipeline-0.11.2.yml
> kubectl apply -f tekton-triggers-0.4.0.yml #I don't know if this is necessary, looks like most of this is included in the tekton-pipeline yml
> kubectl apply -f tekton-dashboard-0.6.1.yml 
> ```
> 
> any idea how I can debug this further?
> 
> ```
> customresourcedefinition.apiextensions.k8s.io/extensions.dashboard.tekton.dev created
> serviceaccount/tekton-dashboard created
> clusterrole.rbac.authorization.k8s.io/tekton-dashboard-minimal created
> clusterrolebinding.rbac.authorization.k8s.io/tekton-dashboard-minimal created
> service/tekton-dashboard created
> deployment.apps/tekton-dashboard created
> Error from server (InternalError): error when creating "tekton-dashboard-0.6.1.yml": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=30s: context deadline exceeded
> ```

Yeah, so installing Triggers isn't mandatory (we work without it), with regards to the issue going on there

If you have a look at the webhook pods in the tekton-pipelines namespace (so, there'll be a tekton-webhook pod as well as a tekton-controller one), if you get those logs - do you see anything interesting? Perhaps some RBAC or unknown field error? Anything of that nature?

My suspicion is, it's trying to install pipeline0 (either the Pipeline itself or Task) that comes with the Dashboard and is used to import resources, and there's an error in there or you have some existing resources that might be conflicting - having a look in the webhook pod logs should reveal the true error and we can go from there

**Comment by shibumi** [comment]
`k logs po/tekton-pipelines-webhook-6cd9bff9f6-kcbhp -n tekton-pipeline`
```
{"level":"info","logger":"webhook","caller":"controller/controller.go:363","msg":"Reconcile failed. Time taken: 30.051µs.","commit":"33e0847","knative.dev/traceid":"94eb82ca-0f89-4716-bc7b-f0ab6b9e43b0","knative.dev/key":"config.webhook.pipeline.tekton.dev"}
{"level":"error","logger":"webhook","caller":"controller/controller.go:376","msg":"Reconcile error","commit":"33e0847","error":"secret \"webhook-certs\" is missing \"ca-cert.pem\" key","stacktrace":"github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:376\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:362\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).Run.func2\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:310"}
{"level":"info","logger":"webhook","caller":"controller/controller.go:363","msg":"Reconcile failed. Time taken: 19.67µs.","commit":"33e0847","knative.dev/traceid":"2ae08542-3a8a-495e-8d0a-59b563081f37","knative.dev/key":"tekton-pipelines/webhook-certs"}
{"level":"info","logger":"webhook","caller":"controller/controller.go:370","msg":"Reconcile succeeded. Time taken: 735.439866ms.","commit":"33e0847","knative.dev/traceid":"9e208c92-2063-4e1b-aefd-73033cbb8981","knative.dev/key":"tekton-pipelines/webhook-certs"}
{"level":"info","logger":"webhook","caller":"configmaps/configmaps.go:145","msg":"Updating webhook","commit":"33e0847","knative.dev/traceid":"ce18e3cf-e956-4967-b131-2fce0569811f","knative.dev/key":"tekton-pipelines/webhook-certs"}
{"level":"info","logger":"webhook","caller":"defaulting/defaulting.go:182","msg":"Updating webhook","commit":"33e0847","knative.dev/traceid":"50d4b074-6c04-4a07-be78-700e2c522a9f","knative.dev/key":"tekton-pipelines/webhook-certs"}
{"level":"info","logger":"webhook","caller":"controller/controller.go:370","msg":"Reconcile succeeded. Time taken: 8.157µs.","commit":"33e0847","knative.dev/traceid":"e6974fb7-82c5-4ec5-bd91-3f75fe558f37","knative.dev/key":"tekton-pipelines/webhook-certs"}
```

This is just a short snippet from it.. I've tested the dashboard and it's there and working, it's just weird that the deployment failed. What is missing now?

**Comment by a-roberts** [comment]
> `k logs po/tekton-pipelines-webhook-6cd9bff9f6-kcbhp -n tekton-pipeline`
> 
> ```
> {"level":"info","logger":"webhook","caller":"controller/controller.go:363","msg":"Reconcile failed. Time taken: 30.051µs.","commit":"33e0847","knative.dev/traceid":"94eb82ca-0f89-4716-bc7b-f0ab6b9e43b0","knative.dev/key":"config.webhook.pipeline.tekton.dev"}
> {"level":"error","logger":"webhook","caller":"controller/controller.go:376","msg":"Reconcile error","commit":"33e0847","error":"secret \"webhook-certs\" is missing \"ca-cert.pem\" key","stacktrace":"github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:376\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:362\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).Run.func2\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:310"}
> {"level":"info","logger":"webhook","caller":"controller/controller.go:363","msg":"Reconcile failed. Time taken: 19.67µs.","commit":"33e0847","knative.dev/traceid":"2ae08542-3a8a-495e-8d0a-59b563081f37","knative.dev/key":"tekton-pipelines/webhook-certs"}
> {"level":"info","logger":"webhook","caller":"controller/controller.go:370","msg":"Reconcile succeeded. Time taken: 735.439866ms.","commit":"33e0847","knative.dev/traceid":"9e208c92-2063-4e1b-aefd-73033cbb8981","knative.dev/key":"tekton-pipelines/webhook-certs"}
> {"level":"info","logger":"webhook","caller":"configmaps/configmaps.go:145","msg":"Updating webhook","commit":"33e0847","knative.dev/traceid":"ce18e3cf-e956-4967-b131-2fce0569811f","knative.dev/key":"tekton-pipelines/webhook-certs"}
> {"level":"info","logger":"webhook","caller":"defaulting/defaulting.go:182","msg":"Updating webhook","commit":"33e0847","knative.dev/traceid":"50d4b074-6c04-4a07-be78-700e2c522a9f","knative.dev/key":"tekton-pipelines/webhook-certs"}
> {"level":"info","logger":"webhook","caller":"controller/controller.go:370","msg":"Reconcile succeeded. Time taken: 8.157µs.","commit":"33e0847","knative.dev/traceid":"e6974fb7-82c5-4ec5-bd91-3f75fe558f37","knative.dev/key":"tekton-pipelines/webhook-certs"}
> ```
> 
> This is just a short snippet from it.. I've tested the dashboard and it's there and working, it's just weird that the deployment failed. What is missing now?

So do you have the Pipeline called pipeline0, or the Task? 

I think this is what errored and so you won't be able to use the import resource functionality, I would have a look in the tekton pipelines controller pod to see if the clues actually lie there instead

**Comment by Megan-Wright** [comment]
```
(base) Megans-MacBook-Pro:services megan.wright@ibm.com$ kubectl apply  --filename https://github.com/tektoncd/dashboard/releases/download/v0.5.3/tekton-dashboard-release.yaml
customresourcedefinition.apiextensions.k8s.io/extensions.dashboard.tekton.dev created
serviceaccount/tekton-dashboard created
clusterrole.rbac.authorization.k8s.io/tekton-dashboard-minimal created
clusterrolebinding.rbac.authorization.k8s.io/tekton-dashboard-minimal created
service/tekton-dashboard created
deployment.apps/tekton-dashboard created
pipeline.tekton.dev/pipeline0 created
task.tekton.dev/pipeline0-task created
(base) Megans-MacBook-Pro:services megan.wright@ibm.com$ kubectl apply --filename https://github.com/tektoncd/dashboard/releases/download/v0.6.1/tekton-dashboard-release.yaml
customresourcedefinition.apiextensions.k8s.io/extensions.dashboard.tekton.dev unchanged
serviceaccount/tekton-dashboard unchanged
clusterrole.rbac.authorization.k8s.io/tekton-dashboard-minimal configured
clusterrolebinding.rbac.authorization.k8s.io/tekton-dashboard-minimal unchanged
service/tekton-dashboard configured
deployment.apps/tekton-dashboard configured
pipeline.tekton.dev/pipeline0 configured
task.tekton.dev/pipeline0-task configured
```
@a-roberts Just tried with pipelines 0.11.2 triggers 0.4.0 and dashboard 0.5.3 then 0.6.1 on top of that so shouldn't be any left over resources causing problems I don't think :eyes:

**Comment by a-roberts** [comment]
Thanks @Megan-Wright, so I don't see this should hold up the 0.6.1 release then atm, I am curious to see what the error is though so let's keep this open

**Comment by shibumi** [comment]
@a-roberts is pipeline0 a pod? I have the following resources:
```
NAME                                               READY   STATUS    RESTARTS   AGE
pod/tekton-dashboard-5995985f86-mwgrp              1/1     Running   1          10h
pod/tekton-pipelines-controller-5dc67b5bf5-bk54x   1/1     Running   1          10h
pod/tekton-pipelines-webhook-6cd9bff9f6-kcbhp      1/1     Running   1          10h

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/tekton-dashboard              1/1     1            1           10h
deployment.apps/tekton-pipelines-controller   1/1     1            1           10h
deployment.apps/tekton-pipelines-webhook      1/1     1            1           10h

NAME                                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/tekton-dashboard-5995985f86              1         1         1       10h
replicaset.apps/tekton-pipelines-controller-5dc67b5bf5   1         1         1       10h
replicaset.apps/tekton-pipelines-webhook-6cd9bff9f6      1         1         1       10h

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                     AGE
service/tekton-dashboard              ClusterIP   xxx.xxx.xxx.xxx   <none>        9097/TCP                    10h
service/tekton-pipelines-controller   ClusterIP   xxx.xxx.xxx.xxx   <none>        9090/TCP                    10h
service/tekton-pipelines-webhook      ClusterIP   xxx.xxx.xxx.xxx    <none>        9090/TCP,8008/TCP,443/TCP   10h


```

**Comment by AlanGreene** [comment]
`pipeline0` refers to the Pipeline and Task created by the Dashboard install and used for the 'Import Tekton Resources' feature.

- `pipeline.tekton.dev/pipeline0`
- `task.tekton.dev/pipeline0-task`

You can find these in the namespace where the Dashboard is installed, `tekton-pipelines` by default.

**Comment by shibumi** [comment]
I don't see this resources, but I can see these CRDs:

```
pipelineresources.tekton.dev                  2020-04-20T11:36:25Z
pipelineruns.tekton.dev                       2020-04-20T11:36:25Z
pipelines.tekton.dev                          2020-04-20T11:36:25Z
taskruns.tekton.dev                           2020-04-20T11:36:26Z
tasks.tekton.dev                              2020-04-20T11:36:25Z
```

is there a way to show them? If I do `kubectl get taskruns` I get nothing in the namespace, so it's them what is missing and couldn't be created.

**Comment by shibumi** [comment]
@a-roberts ok I don't know what happens, but I tried applying the dashboard again, after deploying a simple ingress for it, and not it works. I can see the pipeline0 and pipeline0-task in the dashboard now.  My ingress looks like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
spec:
  rules:
  - host: tekton.company.tld
    http:
      paths:
      - backend:
          serviceName: tekton-dashboard
          servicePort: 9097
  tls:
  - hosts:
    - tekton.company.tld
    secretName: secretname
```

Is it possible, that this ingress solved my problem? Is this maybe 'rancher' related? We are using rancher as Kubernetes plattform.

Just one thing is odd, when I do `kubectl get pipelines -A` or any other tekton resource I don't get the resources back, although they are created and I can see them in the pipeline. Shouldn't they pop up in the namespace as resource?

**Comment by shibumi** [comment]
Sorry for the, double posts:

Ok `k get task.tekton.dev -A` works, the pipeline0-task is there now. I think tekton should be usable from now on. I have no idea what was going on here.

**Comment by a-roberts** [comment]
> @a-roberts ok I don't know what happens, but I tried applying the dashboard again, after deploying a simple ingress for it, and not it works. I can see the pipeline0 and pipeline0-task in the dashboard now. My ingress looks like this:
> 
> ```
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: tekton-dashboard
>   namespace: tekton-pipelines
> spec:
>   rules:
>   - host: tekton.company.tld
>     http:
>       paths:
>       - backend:
>           serviceName: tekton-dashboard
>           servicePort: 9097
>   tls:
>   - hosts:
>     - tekton.company.tld
>     secretName: secretname
> ```
> 
> Is it possible, that this ingress solved my problem? Is this maybe 'rancher' related? We are using rancher as Kubernetes plattform.
> 
> Just one thing is odd, when I do `kubectl get pipelines -A` or any other tekton resource I don't get the resources back, although they are created and I can see them in the pipeline. Shouldn't they pop up in the namespace as resource?

Yeah, they should (and I see in your later post they now do)

I haven't tested on rancher personally (the core Dashboard team works mainly on Docker Desktop or OpenShift), I don't think adding an Ingress manually fixes anything - your pods looked stable at the time but it's as though the webhooks service was unreachable.

I'm thinking it's more to do with your cluster set up or networking at this point as opposed to anything we could potentially fix through the Dashboard through code, @shibumi what are your thoughts, are things reliable now (so, without having to manually create an ingress first)? I'm wondering if there's anything we can at least document to help users in future.

**Comment by a-roberts** [comment]
Going to close as it's been a few days and confident there isn't code we can add to improve it, but if anyone else sees this please do comment and let us know

**Comment by cocktailer** [comment]
I am getting the same error while adding a task. 

kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.15.2/release.yaml
 kubectl apply --filename https://storage.googleapis.com/tekton-releases/dashboard/previous/v0.9.0/tekton-dashboard-release.yaml
kubectl apply -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.7.0/release.yaml
![Screenshot 2020-09-01 at 8 56 13 PM](https://user-images.githubusercontent.com/45057114/91872545-9ad2a600-ec95-11ea-9948-29a6e1264036.png)
