### ISSUE TITLE
Tekton Dashboard Documentation

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/dashboard#1345]
This is not an issue. Looking for the below information . It would be good if the below information is included in detail in Tekton Dashboard github. Thanks!

1. What are the advantages for the Developer when using Tekton Dashboard  instead of using Kubernetes Dashboard or Octant?

2. What are the advantages for the Admin when using Tekton Dashboard  instead of using Kubernetes Dashboard or Octant?

**Comment by eddycharly** [comment]
Not sure I understand your question correctly.

Tekton dashboard is showing tekton pipeline/triggers in an opinionated way, it’s built specifically for tekton business.

Other tools you mention are general purpose and allow viewing any kind of resource in a cluster.

**Comment by 2020testuser** [comment]
@eddycharly - Thanks!
Got tekton dashboard installed and was able to compare.
