### ISSUE TITLE
Tekton Pipelines 0.12 support

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1347]
# Expected behavior
We should be able to do everything we can in 0.11 with 0.12 too

# Actual behavior
Hasn't been proven, so go ahead and prove it and then let's create a 0.6.2 release 🎉  - create Tekton resources, check everything renders, can be created, and can be rerun successfully. You can keep Triggers at 0.4.0 (with a view to having 0.5.0 support in, say, Dashboard 0.6.3).

https://github.com/tektoncd/pipeline/releases/tag/v0.12.0

**Comment by AlanGreene** [comment]
As far as I know our 0.6.1.4 release covers this, so closing. Please reopen if I'm mistaken.
