### ISSUE TITLE
Triggers not showing up as installed when port-forwarding the dashboard

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1350]
# Expected behavior
When I use the dashboard by port-forwarding and have triggers installed on my cluster, I should be able to view the triggers panels and it should show up as installed on the about page.

# Actual behavior
When I am using port-forward, I cannot see triggers or use any of its functionality... however when using `npm run start` to view the dashboard everything works ok (triggers 0.4.0 is installed and everything shows up properly).

# Steps to reproduce the problem

1. Port-forward the dashboard with triggers 0.4.0 installed on your cluster and try to view triggers resources.

# Environment
- Kubernetes Platform:

Docker desktop

- Tekton Pipelines version:

- Tekton Triggers version:

0.4.0

- Tekton Dashboard version:

master

# Additional Info

**Comment by AlanGreene** [comment]
Working for me on both Docker Desktop and CRC (OpenShift version: 4.3.8)

Property | Value
-- | --
InstallNamespace | tekton-pipelines
DashboardVersion | devel
PipelineVersion | v0.11.3
TriggersVersion | v0.4.0

dashboard is on master@9dc5777567e5fa26c63d8a95136ade417883f217 ("Add panelling to create TaskRuns")

1. `kubectl --namespace tekton-pipelines port-forward service/tekton-dashboard 9097:9097`
2. access http://localhost:9097 in my browser
3. see Triggers options in nav as expected, resources load correctly
4. `npm start`
5. access http://localhost:8000 in my browser
6. also working

**Comment by AlanGreene** [comment]
@Megan-Wright are you still seeing this?

**Comment by Megan-Wright** [comment]
Nope, all looking good now 😸 
/close
