### ISSUE TITLE
Triggers resources display errors on Openshift

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1363]
# Expected behavior
I should be able to view triggers resources without an error

# Actual behavior
An error appears on every trigger resource page (TriggerBindings, ClusterTriggerBindings, TriggerTemplates and EventListeners)

# Steps to reproduce the problem

1. Access the dashboard from an OpenShift cluster 
2. Try to view triggers resources
3. Observe this error: 
<img width="1671" alt="Screenshot 2020-05-07 at 16 53 35" src="https://user-images.githubusercontent.com/52741262/81316290-520e3600-9083-11ea-8b9e-c0775109e6bb.png">

# Environment
- Kubernetes Platform:

OpenShift 4.3

- Tekton Pipelines version:

0.12.0

- Tekton Triggers version:

0.4.0

- Tekton Dashboard version:

master

# Additional Info

**Comment by eddycharly** [comment]
@Megan-Wright is this with dashboard master ?

**Comment by Megan-Wright** [comment]
Not seeing this anymore with master
/close
