### ISSUE TITLE
0.6.1.2: can't create/modify/delete resources, invalid CSRF token provided error (API route 404s with kubectl proxy)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1373]
# Expected behavior
I should be able to create/modify/delete resources when accessing the dash through the kube proxy

# Actual behavior
Failed to create *resource name* with invalid CSRF token error consistently - gonna be the same for deletes, updates, etc too

# Steps to reproduce the problem

Easiest one:
1. Try to create any secret
2. Observe the error
3. All is well in port-forward mode, probably over Routes too, but over the proxy - no

# Environment
- Kubernetes Platform:
I'm using Docker Desktop, todo check others

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:
0.6.1.2 (release candidate)

Note, there is no available release candidate to the public yet, so this is for those working on a security issue to pick up (as that's needed for the 0.6.1.2 release)

Whatever fix we have should be tested on master too

**Comment by a-roberts** [comment]
![image](https://user-images.githubusercontent.com/12814972/81804130-8f097b00-9510-11ea-9ccb-59542e494715.png)


Spoke with @alangreene about this, we're missing the API prefix, the token retrieval is done to

![image](https://user-images.githubusercontent.com/12814972/81804179-9f215a80-9510-11ea-9402-2c80

**Comment by AlanGreene** [comment]
Missing API root prefix on the request, testing the fix now. Thanks for catching this.
