### ISSUE TITLE
0.6.1.2 - SA and Secrets page that should be hidden in read-only mode can be accessed through URL still

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1374]
# Expected behavior
If in read-only mode, we're omitting them from the sidenav atm but they can still be accessed through the URL

# Steps to reproduce the problem

1. Access /secrets or /serviceaccounts for example - you can still, as we're not conditionally creating the URL route/path I assume

# Environment
- Kubernetes Platform:
Using Docker Desktop here, likely any

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:
0.6.1.2 release candidate

# Additional Info
As with https://github.com/tektoncd/dashboard/issues/1373, note, there is no available release candidate to the public yet, so this is for those working on a security issue to pick up (as that's needed for the 0.6.1.2 release)

Whatever fix we have should be tested on master too

**Comment by AlanGreene** [comment]
Ah so the routes are still registered. There's no content returned from the APIs but we should still clean this up since it could cause confusion if someone hits an old link and gets an incomplete page.
