### ISSUE TITLE
npm run build_ko taking upwards of 5 minutes to complete

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1387]
# Expected behavior
I should be able to build the dashboard code in a (relatively) short amount of time

# Actual behavior
Every time I try to build the dashboard using `npm run build_ko` it is taking upwards of 5 minutes to complete... this definitely didn't used to happen - it used to take a minute at the most.

# Steps to reproduce the problem

1. Run `npm run build_ko` on the dashboard code
2. Notice how long it takes to build

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

# Additional Info

**Comment by AlanGreene** [comment]
```
real	1m35.113s
user	1m47.277s
sys	0m10.611s
```

Ran both `npm run build` and `npm run build_ko` (only difference should be the output location) a number of times each, getting pretty consistent results about 1.5-2mins.

This is on a mid-2015 MacBook Pro with 2.5GHz quad core i7 and 16GB RAM
node v10.19.0

Tested against dashboard master @ 901237a8ffb4d298c4841122d6440884dd9ae1f9

Can you watch the node process in Activity Monitor to determine if the issues you're having are CPU or memory bound? There are a number of configuration changes we could make to the webpack build that might improve build times in some scenarios, but knowing what issues you're facing would help validate they're having the desired outcome.

**Comment by Megan-Wright** [comment]
yeah I've been building master this morning several times and it's actually got a lot quicker (no idea what was happening, might've just been my laptop).. will close this one for now
/close

**Comment by AlanGreene** [comment]
OK glad(ish) to hear 😸 If you do notice it slow down again give me a shout and we can take a look.
