### ISSUE TITLE
Constant "JSON.parse: unexpected character" errors

### ISSUE THREAD

**Issue by jpds** [tektoncd/dashboard#1405]
# Expected behavior

I'm able to view output in Tekton Dashboard pages.

# Actual behavior

I've deployed Tekton Pipelines v0.12.1 and Tekton Dashboard v0.6.1.4 and on every single page I view on the dashboard I get:

```
Error loading Pipelines
JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

# Steps to reproduce the problem

1. Deploy GKE cluster (I used regular channel, version currently at 1.16.8-gke.15)
2. Deploy pipelines and dashboard:

```
kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.12.1/release.yaml
kubectl apply --filename https://github.com/tektoncd/dashboard/releases/download/v0.6.1.4/tekton-dashboard-release.yaml
```

3. Apply task and taskrun from tutorial: https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#creating-and-running-a-task

4. Access Tekton Dashboard:

```
kubectl port-forward -n tekton-pipelines deploy/tekton-dashboard 8080:9097
```

5. Observe that all dashboard pages return a JSON.parse error.

# Environment
- Kubernetes Platform:
GKE regular channel 1.16.8-gke.15

- Tekton Pipelines version:
v0.12.1

- Tekton Triggers version:
Not deployed.

- Tekton Dashboard version:
v0.6.1.4

**Comment by AlanGreene** [comment]
This sounds like the APIs are returning unexpected content, potentially a HTML error page or similar.

Can you check the network tab of the browser dev tools and see if there's more information about the failure that could help?

For example, on the Pipelines page you should see a request to `/proxy/apis/tekton.dev/v1beta1/pipelines/` that returns a JSON response containing a PipelineList

![image](https://user-images.githubusercontent.com/2829095/82440914-02713680-9a95-11ea-920f-111b952bba5d.png)

You should also be able to hit the API directly in your browser and inspect the response:
http://localhost:8080/proxy/apis/tekton.dev/v1beta1/pipelines/

**Comment by jpds** [comment]
Google Cloud's Cloud Shell integration seems to hijack the requests behind a "/?authuser=0/" thing, but I do see a "200 OK GET" to `/?authuser=0/proxy/apis/tekton.dev/v1beta1/pipelines/` - the Preview section is empty.

If I manually go to the URL `/proxy/apis/tekton.dev/v1beta1/pipelines/`, I see the correct raw JSON:

```
{"apiVersion":"tekton.dev/v1beta1","items":[],"kind":"PipelineList","metadata":{"continue":"","resourceVersion":"35481","selfLink":"/apis/tekton.dev/v1beta1/pipelines"}}
```

**Comment by jpds** [comment]
Ah, interesting - I just removed the `/?authuser=0/` from the default [web preview](https://cloud.google.com/shell/docs/using-web-preview) URL and now I can view the pages correctly as it sends me to `/#/pipelineruns`.

**Comment by AlanGreene** [comment]
Nice find, I can reproduce it locally on other platforms by adding a query string to the URL before the fragment used for client side routing. We're not expecting a query string to be present, so when we construct the URLs for the API calls it's getting included before the API path.

Can you confirm what happens if you call the API directly with the `?authuser=0` query appended?

http://localhost:8080/proxy/apis/tekton.dev/v1beta1/pipelines/?authuser=0

Since it works without the query string it might be safer to remove it rather than trying to preserve it in case that causes issues in other scenarios / other platforms.

**Comment by jpds** [comment]
> Can you confirm what happens if you call the API directly with the `?authuser=0` query appended?
> 
> http://localhost:8080/proxy/apis/tekton.dev/v1beta1/pipelines/?authuser=0

This returns the JSON correctly.

**Comment by AlanGreene** [comment]
OK great. For now I think we'll just remove the query string, hopefully a simple enough change.

Thanks for reporting and finding the cause 👍 

/kind bug
/assign
