### ISSUE TITLE
No option to change what pipeline /taskrun to create when filter is applied

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1409]
# Expected behavior
I can change the taskrun / pipelinerun without having to close the modal and remove the filter

# Actual behavior
I have to close the modal, remove the filter than go back to the create modal

# Steps to reproduce the problem

1. have a filter on pipeline / taskrun
2. click on create 
3. not be able to change pipelinerun / taskrun 

# Environment
- Kubernetes Platform:

docker

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info

**Comment by AlanGreene** [comment]
This is consistent with the behaviour of the Create PipelineRun page, so if we want to change this we should change both.

**Comment by AlanGreene** [comment]
This is working as designed, but I agree it would be better to default the selection to the filtered Pipeline / Task but still allow the user to change this in the dialog without having to close, remove the filter, and open the dialog again.
