### ISSUE TITLE
Credentials Endpoint

### ISSUE THREAD

**Issue by carlos-logro** [tektoncd/dashboard#141]
Currently I'm creating a page in the dashboard where all the secrets already created will show up in a nice table. My problem right know is that the API's endpoints related to secrets ends with the credentials (plural) keyword which results in a 404 error. But when I use credential (singular) I get the results I want. I spoke with @mnuttall about this & he said it in past it was agreed that we'd be using the plural version in the API endpoints.

**Comment by akihikokuroda** [comment]
Right now. All APIs except “/v1/extensions” are singular
https://github.com/tektoncd/dashboard/blob/80e6f6522bab01e359496ad97cdb3386db2d358c/pkg/endpoints/router.go#L60

**Comment by mnuttall** [comment]
Any input here or in https://tektoncd.slack.com/archives/CHTHGRQBC/p1557821541003700 much appreciated. We'll give it a few days and see if there's any general preference one way or the other.

**Comment by mnuttall** [comment]
Ant change to APIs will need to ensure function is maintained across the go, go tests, javascript, javascript tests, and the scripting in https://github.com/tektoncd/experimental/tree/master/webhooks-extension/test plus anywhere else things are used.
