### ISSUE TITLE
Add view for taskRun details

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/dashboard#1413]
# Expected behavior

At the moment the taskRuns view is per step with no way to see taskRun level inputs and status outside of error cases. The goal is to allow users view taskRun level information

inputs sample

<img width="1078" alt="Screenshot 2020-05-20 at 21 55 55" src="https://user-images.githubusercontent.com/18128367/82496672-062ca980-9ae5-11ea-9a11-d168c573df26.png">

Where the taskRun has an error

<img width="800" alt="Screenshot 2020-05-20 at 21 56 01" src="https://user-images.githubusercontent.com/18128367/82496736-18a6e300-9ae5-11ea-8687-b73583928067.png">

# Additional Info

Builds on work started in https://github.com/tektoncd/dashboard/issues/1196

**Comment by a-roberts** [comment]
PR for this is merged so let's close this
