### ISSUE TITLE
Dashboard shouldn't allow timeout of 0 for PipelineRuns/TaskRuns

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1418]
# Expected behavior
We dont allow a timeout of 0

# Actual behavior
We allow it but timeout does nothing, the pipelinerun / taskrun never times out 

# Steps to reproduce the problem

1.
2.
3.

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info

/assign

**Comment by AlanGreene** [comment]
https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#configuring-a-failure-timeout
> If you set the timeout to 0, the PipelineRun fails immediately upon encountering an error.

https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#configuring-the-failure-timeout
> If you set the timeout to 0, the TaskRun fails immediately upon encountering an error.

The Pipelines docs seem to suggest that "0" is a valid value for the timeout, so we should allow it and ensure it's sets correctly.

**Comment by CarolynMabbott** [comment]
It does get set correctly 

Did not realise that it had that functionality if you set it to 0
Would it be useful to add a tooltip or something similar to inform people that this functionality is available?

**Comment by AlanGreene** [comment]
I think it's enough that it's documented in the Pipelines docs for now. Once we get the Dashboard docs on the website we can provide more user guides to point at with this type of detail since it can be hard to capture enough detail in a one line tooltip.

**Comment by a-roberts** [comment]
So based on

```
Actual behavior
We allow it but timeout does nothing, the pipelinerun / taskrun never times out
```

@CarolynMabbott is this issue still valid then? Have I missed something?

**Comment by AlanGreene** [comment]
Closing. Feel free to reopen if there's more needed here.
