### ISSUE TITLE
Look into backporting any security fixes to the 0.5.2 stream

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1419]
We've had a couple of awesome security fixes go into master and the 0.6.1.3 and 0.6.1.4 releases, so it would be useful to do the same as an older release that may be in use by customers.

Under this issue, have a look at cherry-picking the relevant security fixes so we could do, what I'm suggesting, is a 0.5.2.1.

I'm wondering if we should do it against 0.5.3 as well just because it's got a lot of fixes too (and maybe it'll make it easier).

@AlanGreene FYI, fingers crossed this is a nice easy one!

The commits I am thinking of are

Update from Alan: https://github.com/tektoncd/dashboard/commit/ddd6c4f5d109f5d81d84388fe30a6eb22f0e51c2 
https://github.com/tektoncd/dashboard/commit/410c7cacb3d4559f0143ab050ca0dbf8f1746f58
https://github.com/tektoncd/dashboard/commit/36ee2da0cd94ac098341b8657032b51181e397ae

https://github.com/tektoncd/dashboard/commit/01e7c5b40163ca3f3be40850bf338cdfe60e6ead
https://github.com/tektoncd/dashboard/commit/922eb8518823f4d1313c9885649c6d5019c02f80

There may be some others we can get easily too. So, I'd suggest checking out the v0.5.2 tag, branching off that, applying these five commits at least, and seeing what breaks. If nothing breaks, do a release.

**Comment by AlanGreene** [comment]
I think the filtering relies on https://github.com/tektoncd/dashboard/commit/ddd6c4f5d109f5d81d84388fe30a6eb22f0e51c2 for a clean cherry-pick, otherwise the list looks good to me.

**Comment by a-roberts** [comment]
> I think the filtering relies on [ddd6c4f](https://github.com/tektoncd/dashboard/commit/ddd6c4f5d109f5d81d84388fe30a6eb22f0e51c2) for a clean cherry-pick, otherwise the list looks good to me.

Good shout, updated to add

**Comment by a-roberts** [comment]
@AlanGreene I didn't spend much time resolving conflicts - wanted to get something that at least had the security problems in, but I've got something that builds, functions, and doesn't have the security issue you worked on for the 0.6.x stream. 

It's at https://github.com/a-roberts/dashboard/tree/adam0521candidate so please take a look and kick the tires (this requires Pipelines 0.10.x - I'm using 0.10.2, so if like me you use Docker Desktop you'll likely end up resetting your cluster removing your beta install of Tekton).
