### ISSUE TITLE
Productivity - add AlanGreene as a releaser and eddycharly as a reviewer?

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1421]
Hey everyone, I wanted to make this in the open for transparency - I've been working a lot of other issues/projects outside of the Tekton Dashboard, and I've been unable to get as many reviews/features in as I'd have liked.

On the contrary...
@AlanGreene has been exceptionally prolific since the very start of this project and continues to come forward with awesome new ideas. Currently, only myself and @mnuttall can do Tekton Dashboard releases, so it'd be helpful to have another that's in the know.

@eddycharly has been especially prolific as of late with issues, reviews, and getting awesome PRs/features in as well as fixes and test improvements.

To that end, I propose:
1) Adding @AlanGreene  as someone who can also do Tekton Dashboard releases (would need a release secret/approval through the governing board I believe? How is this done again? @bobcatfish @vdemeester)
2) Adding @eddycharly as a reviewer (any of us can make this happen, if they are interested in stepping up) - requiring a PR into OWNERS

Alan/Charles, would this be something you'd like? If I'm talking a load of rubbish or you've got plenty other things on your plate - that's cool just lemme know!

@mnuttall @skaegi @Megan-Wright @CarolynMabbott @steveodonovan FYI.

**Comment by eddycharly** [comment]
Thanks @a-roberts !

No objections on my side.
I came here mostly to contribute with the code but no problems helping in reviews too.

**Comment by AlanGreene** [comment]
1. Yes I'd be happy to share in the release fun :+1: Release docs seem pretty detailed and I've run through them locally before with the final publish steps disabled so hopefully that means I won't run into any problems once I have access. It would be good to have one of you look over my shoulder for the first release just in case though.

2. @eddycharly has been making solid contributions to the Dashboard and other projects for at least a couple of months now and has been a welcome addition to the team. If he's interested in becoming a reviewer I'd definitely support that.

   Feel free to reach out if you have questions about the context of any previous decisions (hopefully most of it's captured in the code / issues / commit messages already) that may be relevant or anything else you may not be sure about.

**Comment by a-roberts** [comment]
@eddycharly has been added as a reviewer and we can follow up with the governing folks on getting @AlanGreene the credentials, let's close this one, thanks all
