### ISSUE TITLE
Tekton dashboard About output not displaying expected TriggersVersion info

### ISSUE THREAD

**Issue by bconey** [tektoncd/dashboard#1424]
# Expected behavior
Tekton dashboard About output should display value formatted like "0.3" for TriggersVersion

# Actual behavior
Tekton dashboard About output displays "devel" for TriggersVersion

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/31766760/82595434-8c8fcc80-9b73-11ea-8f01-e5f5fc1f9d8a.png">

# Steps to reproduce the problem

1. 
2.
3.

# Environment
- Kubernetes Platform: OCP 4.4.3

- Tekton Pipelines version: V0.11.3

- Tekton Triggers version: devel ?

- Tekton Dashboard version: 
imageID: gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256:89f8c9e4ac5c7a602e4c9227c26614b1610bd731f12ce00407944b9aabfa3e64

# Additional Info

**Comment by JustinKuli** [comment]
From what I understand, the dashboard searches for the triggers deployment, and then gets the version number from its labels. On OpenShift, as a backup in case it is missing the right label, it checks the container image.

I tried installing Kabanero 0.9.0 in my cluster, and I found this:
```
# oc get deploy tekton-triggers-controller -n openshift-pipelines --show-labels
NAME                         READY   UP-TO-DATE   AVAILABLE   AGE   LABELS
tekton-triggers-controller   1/1     1            1           11m   app.kubernetes.io/component=controller,app.kubernetes.io/name=tekton-triggers,triggers.tekton.dev/release=devel
# oc get deploy tekton-triggers-controller -n openshift-pipelines -o yaml | grep image:
        image: quay.io/openshift-pipeline/tektoncd-triggers-controller:v0.4.0
```

It's running the correct triggers image (v0.4.0) but the deployment is specifically labelled for development: `triggers.tekton.dev/release=devel`. I think the `openshift-pipelines-operator` is what deploys triggers and which gives it the labels that the dashboard is finding.

**Comment by AlanGreene** [comment]
@bconey how did you install Triggers and what version were you expecting? As Justin mentioned the Dashboard relies on the labels on the Triggers controller to retrieve the version information. 

It's possible that a Triggers release was made that didn't properly replace the default "devel" value with the release version.

**Comment by anneqm** [comment]
@AlanGreene via the openshift-pipelines-operator.   Expecting v0.4.0 per Justin's comment above.

**Comment by AlanGreene** [comment]
Closing this as there's nothing further for the Dashboard to do. It's displaying the value declared by the Triggers install.

@JustinKuli @bconey did you resolve your issue? If so it might be helpful to others to share details of the fix.
