### ISSUE TITLE
PipelineRuns created and duration randomly just stop updating

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1444]
# Expected behavior
It is accurate and updates consistently whilst running PipelineRuns 

# Actual behavior
It just randomly stops updating the duration and created 
It does resume at some point but not together 
Gets to the state where created was 2 mins ago and duration is 25 seconds even though it started running at creation 

# Steps to reproduce the problem
I was using a pipeline created from a webhook being triggered 
Pipeline being used is simple-pipeline from https://github.com/pipeline-hotel/example-pipelines/triggers-resources/config/github/simple-pipeline

1.  Get webhook to trigger a pipelinerun 
2. In pipelineruns page watch the Duration and Created
3.

# Environment
- Kubernetes Platform:

docker
- Tekton Pipelines version:

0.12.1

- Tekton Triggers version:

0.4.0

- Tekton Dashboard version:

0.6.1.5

# Additional Info
Have seen this on multiple PipelineRuns 
Has been seen by not just me but Megan as well (we both were using different Pipelines)

**Comment by AlanGreene** [comment]
The times are not updated continuously, instead on a variable interval. From the react-intl [docs for FormattedRelativeTime](https://formatjs.io/docs/react-intl/components/#formattedrelativetime) (used for the Created column):

> The updating is smart and will schedule the next update for the next interesting moment.
> 
> An interesting moment is defined as the next non-fractional value for that unit. For example:
> 
> `<FormattedRelativeTime value={-59} updateIntervalInSeconds={1} />`
> This will initially renders 59 seconds ago, after 1 second, will render 1 minute ago, and will not re-render until a full minute goes by, it'll render 2 minutes ago. It will not try to render 1.2 minutes ago.

This is a fairly common pattern for relative timestamps.

@CarolynMabbott Does this match the behaviour you're seeing for the created column or are you seeing something else?

For the Duration column we do appear to have a problem, in some cases it's not being updated at all after the initial render.

/assign

**Comment by CarolynMabbott** [comment]
It does seem to match what im seeing 
However it does seem very bad when I've got a long pipelinerun going on that nothing "interesting" has happenned in the last over 10 minsutes I get this

![Screenshot 2020-06-12 at 14 07 09](https://user-images.githubusercontent.com/32342288/84505764-39aebe00-acb6-11ea-8579-1ae0f0c77001.png)

Maybe we could add some code to update the duration time in between interesting events so we dont see things like this (to me it just seems dashboard is broken if the duration isnt increasing even though I know its not just as its such a difference between creation and duration)
