### ISSUE TITLE
Cannot deeplink to task / step details in pipelinerun view

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/dashboard#1460]
# Expected behavior
I can deeplink to task / step details in pipelinerun view

# Actual behavior
I can only link to the pipelinerun. When I select a task / step the URL is not updated, nor there is no option in the dashboard to copy a deeplink to the current view.

# Steps to reproduce the problem

1. https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelineruns/pipeline-release-nightly-tqgdd
2.
3.

# Environment
- Kubernetes Platform:
Kubernetes on GKE

- Tekton Pipelines version:
v0.12.x

- Tekton Triggers version:
v0.5.x

- Tekton Dashboard version:
v0.6.1.4

# Additional Info

**Comment by AlanGreene** [comment]
I agree this is something we need, and it's being tracked in https://github.com/tektoncd/dashboard/issues/487

We made some changes to the components in the last release that should make this a little easier to implement now but there's still more work needed to complete it.
