### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/dashboard#1473]
Docs are somewhat not well organized.

I create this issue to initiate and track efforts to improve our docs.

`/README.md`: PR -> #1476 

- badges
- brief intro
- screenshot
- Start using Tekton Dashboard
  - link to `/docs/install.md`
  - link to `/docs/extensions.md`
  - link to katacoda tutorial
  - link to `roadmap.md`
  - link to create bug reports / feature request issues
- Read the docs
  - announcements
  - releases list with links to release, docs and supported pipelines / triggers versions
- Browser support
- Want to contribute
  - link to `CONTRIBUTING.md`
  - link to `DEVELOPMENT.md`
  - link to `good first issue` and `help wanted` issues

`/docs/install.md`: PR -> #1478 

- Table of Contents
- Before you begin
- Pre-requisites
- Which version should I use
- Installing Tekton Dashboard on Kubernetes
- Installing Tekton Dashboard on OpenShift
- Accessing the Dashboard on Kubernetes
- Accessing the Dashboard on OpenShift
- Uninstalling the Dashboard on Kubernetes
- Uninstalling the Dashboard on OpenShift
- Next steps

`/docs/extensions.md`: PR -> #1487 

- Before you begin
- Resource based extensions
   - Extension CRD (apiVersion: dashboard.tekton.dev/v1alpha1)
   - Example: Register a CronJob extension
   - Example: Extend Tekton Dashboard service account permissions
- Service based extensions
   - Example: Create a simple nodejs backend
   - Example: Add and serve frontend code
- Next steps

`/docs/walkthrough-kind.md`: PR -> #1480 

- Table of Contents
- Before you begin
- Creating a local Kubernetes cluster
- Installing NGINX ingress controller
- Installing Tekton Pipelines
- Installing Tekton Triggers
- Installing Tekton Dashboard
- Setting up an Ingress rule to access the Dashboard
- Importing resources from a Github repository
- Viewing and managing resources from the Dashboard
- Cleaning up

`/docs/walkthrough-ouath2-proxy.md`: PR -> #1484 

- Table of Contents
- Before you begin
- Overview
- Installing a working Tekton Dashboard locally from scratch
- Creating a Github OAuth App
- Installing and configuring oauth2-proxy
- Setting up Dashboard Ingress rule for authentication
- Cleaning up

Maybe organize walkthroughs in `/docs/walkthrough` folder with a readme in it and links to individual walkthroughs ?

I will update  the issues as things go.
Feedback and ideas for improvement welcome.

/assign

**Comment by AlanGreene** [comment]
Yes this is something we've been meaning to get to for a while now but it kept getting pushed out and more content added.

I think we should keep the README relatively short:
- brief intro
- screenshot
- links:
  - install
  - config
  - roadmap
  - contributing / development

Both Pipelines and Triggers already take this approach, and I think it makes it easier to find the relevant information when it's broken out into separate pieces like this instead of having to wade through one very large document.

We also need to consider what content we want to have published on the website once https://github.com/tektoncd/website/pull/90 is merged.

**Comment by eddycharly** [comment]
I agree that the README should be short and link to dedicated pages.

I started making changes here https://github.com/eddycharly/dashboard/tree/docs

I didn't think about the website part, will look at the linked PR.

**Comment by eddycharly** [comment]
I'm going to follow pipelines layout, it looks great !

**Comment by AlanGreene** [comment]
All of the items in the description are complete/merged thanks to excellent work by @eddycharly 

Closing this issue, any remaining doc updates are tracked in more specific issues, e.g. https://github.com/tektoncd/dashboard/issues/1498 and https://github.com/tektoncd/dashboard/issues/1507
