### ISSUE TITLE
Namespace flags for installs of pipelines and triggers don't work on Openshift

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1491]
# Describe the bug
For openshift installs of the dashboard, triggers is not being displayed and the pipelines version cannot be found, even when using flags to point to the correct namespace for both triggers and pipelines (in my case `tekton-pipelines`), instead pointing to the namespace in which the dashboard is installed (`openshift-pipelines`) to look for installs of pipelines and triggers.

# Expected behaviour
When using these flags in `300-deployment.yaml` I expect that the dashboard will know to look for pipelines and triggers in the `tekton-pipelines` namespace:
``` 
args:
            - --port=9097
            - --web-dir=/var/run/ko/web
            - --pipelines-namespace=tekton-pipelines
            - --triggers-namespace=tekton-pipelines
```

# Steps to reproduce the bug

# Environment details

- Kubernetes Platform:

OpenShift
- Kubernetes or OpenShift version:

OCP 4.3
- Install mode (if on OpenShift):
Non-operator

- Cloud-provider/provisioner:

- Versions:
   - Tekton Dashboard:
   
master
   - Tekton Pipelines:
   
   - Tekton Triggers:
   
- Install namespaces:
   - Tekton Dashboard:
openshift-pipelines
   
   - Tekton Pipelines:
tekton-pipelines
   
   - Tekton Triggers:
tekton-pipelines
   

# Additional Info

**Comment by eddycharly** [comment]
Will look at it now
/assign

**Comment by eddycharly** [comment]
Ok, it's probably an RBAC issue, changing the flags can't be enough the dashboard service account needs to be allowed to access resources in the target namespace.

The real issue here is using `RoleBinding' instead of `ClusterRoleBinding`.
I will change that to get back to `ClusterRoleBinding`, as of now we have no solution to keep runtime args and install consistent.
