### ISSUE TITLE
About page tables don't line up correctly when namespaces differ

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1495]
# Describe the bug
When using different namespaces for installs of the dashboard, pipelines and triggers, the about page tables do not line up exactly in terms of column width:
<img width="1631" alt="Screenshot 2020-06-09 at 15 13 29" src="https://user-images.githubusercontent.com/52741262/84158475-d0377100-aa63-11ea-882c-44b892b7f16e.png">

# Expected behaviour
All the table cells should line up.

# Steps to reproduce the bug
Installs the dashboard in a separate namespace to where pipelines and triggers are installed, and navigate to the about page.

# Environment details

- Kubernetes Platform:

- Kubernetes or OpenShift version:

- Install mode (if on OpenShift):

- Cloud-provider/provisioner:

- Versions:
   - Tekton Dashboard:
   
   - Tekton Pipelines:
   
   - Tekton Triggers:
   
- Install namespaces:
   - Tekton Dashboard:
   
   - Tekton Pipelines:
   
   - Tekton Triggers:
   

# Additional Info

**Comment by AlanGreene** [comment]
This is standard table behaviour, layout of each table is independent.

If we want to align them we could set a consistent width for the first column on each of these tables.
