### ISSUE TITLE
README needs more documentation regarding Openshift installs

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1498]
# Is your feature request related to a problem ?
It is not clear to the user how to install the dashboard on Openshift without using the operator.

# Describe the solution you'd like

We currently have this information regarding OpenShift installs: 
<img width="966" alt="Screenshot 2020-06-09 at 16 22 44" src="https://user-images.githubusercontent.com/52741262/84166960-80f63e00-aa6d-11ea-88fe-c8947d0af150.png">

As the operator in its current state is using Pipelines 0.11.3 and Triggers 0.4.0, if the user wants to use newer versions of these there are no instructions on how to do so. My suggestion is that we should include information on how to install on OpenShift without using the operator, as well as the need to use namespace flags in the deployment yaml if doing so.

# Additional context

**Comment by AlanGreene** [comment]
We can review this after https://github.com/tektoncd/dashboard/issues/1473 as discussed on the WG call this week.

**Comment by AlanGreene** [comment]
https://github.com/tektoncd/dashboard/blob/master/docs/install.md#installing-tekton-dashboard-on-openshift

Currently includes a note about non-operator installs and the required dashboard flags:

> ## Installing Tekton Dashboard on OpenShift
> 
> To install Tekton Dashboard on an OpenShift cluster:
> 
> 1. Install the Openshift Pipeline Operator from the operator hub.
> 
> 1. Assuming you want to install the Dashboard into the `openshift-pipelines` namespace, which is the default one:
> 
>    ```bash
>    kubectl apply --filename https://storage.googleapis.com/tekton-releases/dashboard/latest/openshift-tekton-dashboard-release.yaml --validate=false
>    ```
> 
> 1. Access the dashboard by determining its route with `kubectl get route tekton-dashboard -n openshift-pipelines`
> 
> Congratulations! You have successfully installed Tekton Dashboard on your OpenShift cluster.
> 
> **Note for users installing Tekton Pipelines and Triggers outside the OpenShift Pipelines operator:**
> 
> Tekton Dashboard on OpenShift works out of the box with the OpenShift Pipelines operator. If you installed Tekton Pipelines and Triggers without using the OpenShift Pipelines operator, you will need to change the following args `--pipelines-namespace=openshift-pipelines` and `--triggers-namespace=openshift-pipelines` and set their values to the namespace where Pipelines and Triggers were respectively deployed.

The Pipeline and Triggers docs already provide their own install instructions so I don't think we need to duplicate them here.
However, reading back over this I think the wording / structure could be tweaked a bit to make it clearer that the operator isn't required to install the dashboard itself.
