### ISSUE TITLE
Document single namespace visibility installs for release (experimental first)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1507]
As discussed in this week's Dashboard weekly working group call https://docs.google.com/document/d/1bG4mbjycmFtIBezA6AJoQvaB4-v3874dhX7n-DhGAx0/edit# we should ensure whatever's included in our readme mentions single namespace installs and that it's considered an experimental feature for now - until we're happy we can remove the disclaimer.

**Comment by AlanGreene** [comment]
Depends on the completion of https://github.com/tektoncd/dashboard/issues/1018 / should be handled alongside that issue.

We've had a [report](https://tektoncd.slack.com/archives/CHTHGRQBC/p1602167113007100) of a user running into trouble trying this recently so it would be great to provide some troubleshooting / diagnostic steps as part of the documentation.

**Comment by AlanGreene** [comment]
This is still something we'd like to do, freezing so it doesn't get auto-closed.
/lifecycle frozen

**Comment by AlanGreene** [comment]
This will be available in the next nightly release ~4am UTC tomorrow, and will be included in the v0.39.0 release in the next week or so.
