### ISSUE TITLE
New staged 0.7 release is empty for OpenShift

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1512]
See https://console.cloud.google.com/storage/browser/tekton-releases/dashboard/koo/mytestbucket/previous/v0.7.0, which is only five bytes - this is based on https://github.com/tektoncd/dashboard/tree/070cand4

The build job itself doesn't show problems, here's the release job
[releaserun.txt](https://github.com/tektoncd/dashboard/files/4763707/releaserun.txt)

**Comment by eddycharly** [comment]
From the logs: `open /workspace/go/src/github.com/tektoncd/dashboard/overlays/openshift-patches/flags-deployment.yaml: no such file or directory`

**Comment by a-roberts** [comment]
> From the logs: `open /workspace/go/src/github.com/tektoncd/dashboard/overlays/openshift-patches/flags-deployment.yaml: no such file or directory`

Yeah I'm wondering if we need a follow-up PR to do with the build Pipeline next to handle recent changes, see https://github.com/tektoncd/dashboard/blob/master/tekton/publish.yaml

**Comment by eddycharly** [comment]
What was the commit id for the build ?

**Comment by eddycharly** [comment]
Ok, wrong file name, flags-patch.yaml not flags-deployment.yaml 🙃

**Comment by eddycharly** [comment]
We need to test that in presubmits...

**Comment by eddycharly** [comment]
/assign

gonna fix
