### ISSUE TITLE
Dashboard webui did not render on Firefox 60.6.1esr 

### ISSUE THREAD

**Issue by dacleyra** [tektoncd/dashboard#156]
# Expected Behavior

Dashboard webui does render on Chrome 74.0.3729.157 
RHEL 7.6 x86_64

# Actual Behavior

Dashboard webui did not render on Firefox 60.6.1esr 
RHEL 7.6 x86_64

# Steps to Reproduce the Problem

0. Deploy operator from Aki's fork, which includes the dashboard https://github.com/akihikokuroda/tektoncd-pipeline-operator/tree/dashboard
1. `kubectl -n tekton-pipelines port-forward tekton-dashboard-6c777fb5c9-sz7lp 9097:9097`
2. open browser to http://localhost:9097
3.

# Additional Info

**Comment by AlanGreene** [comment]
Can you provide more information about the behaviour you're experiencing?

Do you get a blank page? Are there any warnings / errors in the browser console? We delivered a fix for an issue affecting older browsers (including Firefox ESR) 10 days ago. The dashboard image referenced in that operator branch (akihikokuroda/backend:v64) is 14 days old so does not contain the fix.

Can you reproduce the issue using a build based on tektoncd/dashboard master?
@akihikokuroda can you update the image your branch references?

I don't have access to a RHEL environment right now but will try tomorrow. In the meantime I've verified FF ESR successfully loads the dashboard from master on other platforms.

**Comment by dacleyra** [comment]
Working in new image provided by @akihikokuroda 
thanks
