### ISSUE TITLE
Is there a swagger/openapi spec for the dashboard api definition?

### ISSUE THREAD

**Issue by Tomcli** [tektoncd/dashboard#1571]
/questions

We are trying to understand the api definition of the tektoncd/dashboard. There was a swagger for the dashboard api definition few months ago. Has the swagger definition been moved to a different directory or deprecated? Thank you.

**Comment by AlanGreene** [comment]
As far a I recall we never merged the swagger definition. There was some discussion and a PR open but we ended up taking a different approach and removed most of the dashboard's custom APIs. See https://github.com/tektoncd/dashboard/issues/42 for some of the related discussion, issues, and PRs.

We have a small number of remaining custom APIs documented at https://github.com/tektoncd/dashboard/blob/master/docs/dev/api.md.

For most other functionality we use the kubernetes API and expose it to the frontend via a proxy. This is not intended for general use by other applications and is considered an implementation detail of the dashboard.

Can you share more information about why you're looking for the dashboard API definitions? What use case are you trying to address? There may be another approach we can recommend, or an enhancement that could be made to the dashboard to help.

**Comment by Tomcli** [comment]
We are trying to build a Tekton nodejs service based extension and we want to reuse the kubernetes API in the main server. The information we need is actually available in the dashboard backend, so we think we don't have to implement the k8s client in nodejs to do the same job.

**Comment by AlanGreene** [comment]
The dashboard may change how it accesses the kubernetes API in future so I would advise against relying on the proxy.

The extension frontend JS code has access to the main dashboard's redux store and also to some of the redux actions used to make API calls: https://github.com/tektoncd/dashboard/blob/f1c1e465065c47816fab216b32fc8b7120537ec9/src/containers/Extension/Extension.js#L56-L57

Can you provide more details about the data you're trying to access? Depending on what data you require and how you're intending to use it this approach may be suitable.

**Comment by Tomcli** [comment]
The information we would need is the pipelineruns yaml and some custom CRD extension yaml we are going to add. Since the pipelineruns and extension api are available, we are hoping to reuse them if possible.

**Comment by AlanGreene** [comment]
For the PipelineRuns:

You can call `actions.fetchPipelineRuns({ filters, namespace })` from your extension's frontend code. This will make the API request to get the data, then process and store it in the dashboard's redux store so it's available to all parts of the dashboard for realtime updates.
- `namespace` is optional
  - if not specified, it will request PipelineRuns for all namespaces
  - if specified, it will request PipelineRuns for that namespace only
- `filters` is optional
  - array of `labelSelector`s, e.g. `["tekton.dev/pipeline=my-pipeline"]` to request PipelineRuns associated with the Pipeline `my-pipeline`

Similarly to read the data from the redux store and use it in your components via a standard [react-redux `connect`-ed component](https://react-redux.js.org/using-react-redux/connect-mapstate):
```js
function mapStateToProps(state) {
  const filters = ...
  const namespace = ...

  return {
    pipelineRuns: getPipelineRuns(state, {
      filters,
      namespace
    })
  };
}
```

Assuming you pass this `mapStateToProps` to `connect` and use it to wrap your component, you can access the PipelineRuns data via `props.pipelineRuns`.

This approach ensures you'll also get any updates to these PipelineRuns as the dashboard receives them.

For any data not exposed in this way I would recommend retrieving it using your own backend APIs.

**Comment by Tomcli** [comment]
Thanks @AlanGreene, but if we want to do some extra processing with the yaml in our backend code, then it's recommended for us to build it using our own backend client?

**Comment by AlanGreene** [comment]
Depending on what processing you need to do, it may be possible to do it in the frontend.

If you do need to do this processing in the backend then yes you would need to build it using your own client.

**Comment by AlanGreene** [comment]
Closing since the question about API documentation has been answered. Feel free to join us on the [tektoncd slack](https://github.com/tektoncd/community/blob/master/contact.md#slack) or open a new issue if you have any more questions.
