### ISSUE TITLE
feature: ability to hide/show conditional tasks in pipelinerun view

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/dashboard#1574]
I have a lot of conditions in my pipelinerun. 90% of the time the pipelines run fine and I don't care about seeing all the conditional tasks, all I care about are the tasks that actually do the work. Would be nice to have a toggle switch in the UI to hide conditional based tasks, and just leave the rest. Having to wade through all the conditional tasks in the view just clutters things imho

**Comment by AlanGreene** [comment]
Thanks for the request @bitsofinfo, I agree that our current display of Conditions needs to be improved. We're already tracking a very closely related enhancement in https://github.com/tektoncd/dashboard/issues/1445 so I've updated that to include the concern about heavy use of Conditions and will close this one as a duplicate.

Feel free to add any additional thoughts or suggestions on that issue.
