### ISSUE TITLE
TaskRun parameters truncation, should be able to see full value

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/dashboard#1580]
Long TaskRun parameters are truncated. Would be nice to be able to see the full literal value

![image](https://user-images.githubusercontent.com/1743646/86084442-280d3a80-ba5a-11ea-9b7a-6565b41d4c94.png)

**Comment by AlanGreene** [comment]
The full value is displayed in a tooltip on hover:
![image](https://user-images.githubusercontent.com/2829095/86169874-33bc3800-bb12-11ea-8512-12580bb592e3.png)

We have also made some changes in [v0.7.1](https://github.com/tektoncd/dashboard/releases/tag/v0.7.1) (currently available as a pre-release for testing) to improve the display of params, including multiline and array params.

**Comment by bitsofinfo** [comment]
yeah not super natural to hover over and wait for a tooltip, its not intuitive that is there. any way to make some kind of expander control or little icon to bring up the full detail please.
