### ISSUE TITLE
feature: need way to obfuscate or hide task/pipeline params that contain sensitive data

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/dashboard#1602]
feature: need way to obfuscate or hide task/pipeline params that contain sensitive data

right now all the params are just displayed in the UI, need a way to identify and not show certain task/pipeline params if they contain data that should not be viewable to anyone in the dashboard view.

**Comment by AlanGreene** [comment]
Kubernetes Secrets are a standard approach to storing and referencing sensitive information. A common pattern is for a param to contain the Secret name, then use this to reference the Secret as needed.

See for example the [slackmessage tasks](https://github.com/tektoncd/catalog/blob/7a481c53c58ddde60390d7723d52fc33247996cd/slackmessage/send-to-channel-slack.yaml#L26) in the catalog.

**Comment by bitsofinfo** [comment]
I get that, but this is a in-flight value coming through via an inbound POST triggering a pipeline, I have to pass this value as a param into my pipeline.

**Comment by AlanGreene** [comment]
How are you triggering the PipelineRun? Using some custom mechanism or via Tekton Triggers?

If you can expand further on your use case we may be able to suggest an alternative approach, or at least understand the use case better and determine if / how we can address this in the Dashboard.

**Comment by bitsofinfo** [comment]
a) there is a form in an app where an operator inputs a single use token

b) this token is transmitted from an app, embedded in a json POST, over TLS to a tekton triggers eventlistener endpoint

c) this token is relayed into a task via params which uses it for a one-time use to authorize itself against something it needs to invoke 

d) I suppose a custom interceptor could be coded to grab this token and create a one-off k8s secret, then relay this secret name via the params, but Id like to avoid having to code yet another thing, and deal w/ the cleanup of these transient secrets.

**Comment by AlanGreene** [comment]
Secrets should be used for any sensitive information. Passing the values as params is insecure as they're exposed in clear text in a number of places and users with read access to the PipelineRuns, TaskRuns, containers, etc. by any means (e.g. kubectl, tkn) can easily view them.

Closing as this is not something the dashboard will address.
