### ISSUE TITLE
Ability to rerun a TaskRun

### ISSUE THREAD

**Issue by ClouDevops101** [tektoncd/dashboard#1619]
# Hi am missing a rebuild button to launch the previous task with the same previous parameters?
Like this : 
<img width="1183" alt="Capture d’écran 2020-07-13 à 11 26 12" src="https://user-images.githubusercontent.com/15829825/87289721-4b75c200-c4fd-11ea-91b4-c81965d70886.png">

Each time i check the dashboard and the task or pipeline is failing, i try to restart the same Task with the same parameters, but the UI only suggest to STOP or delete the TaskRun 

It would be nice to have a rebuild button like other Ci-tool

**Comment by AlanGreene** [comment]
@LinuxArchitects thanks for the feature request. This is already supported on PipelineRuns today.

On the PipelineRuns list:
![image](https://user-images.githubusercontent.com/2829095/87296969-92fd4d80-c4ff-11ea-9b78-fc046b2b812d.png)

It's also available in the header of the PipelineRun details page, see the 'Rerun' button:
![image](https://user-images.githubusercontent.com/2829095/87297019-ac9e9500-c4ff-11ea-93da-ea350502b78c.png)


Adding the same rerun option for standalone TaskRuns is something we want to do.

**Comment by AlanGreene** [comment]
The rerun TaskRun API should be handled via the frontend rather than following the existing pattern used by rerun PipelineRun (which will be moved to the frontend code soon). We already have all of the necessary information available on the page where the action is being triggered.

**Comment by AlanGreene** [comment]
This is included in the [Dashboard 0.10.1 release](https://github.com/tektoncd/dashboard/releases/tag/v0.10.0)
