### ISSUE TITLE
0.8.0: Last TaskRun in PipelineRun view is non-existant, can't view logs

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/dashboard#1641]
this started as of v0.8.0, works fine with v0.7.1

pipelines: 0.14.2
triggers: 0.6.1

The last TaskRun displayed in the PipelineRun view displays a ID that does not exist, and I can't view logs for it.

![image](https://user-images.githubusercontent.com/1743646/88554047-015c0880-cff4-11ea-9a13-2616073c0c18.png)

![image](https://user-images.githubusercontent.com/1743646/88553895-ce197980-cff3-11ea-93bf-3ccc7f456200.png)

**Comment by AlanGreene** [comment]
From the screenshot this looks like it may be related to the rendering of conditions. The latest nightly build includes a fix for display of conditions, can you try that and see if it resolves your issue?

If not, can you provide a simplified pipeline that reproduces the issue so we can debug it further?

**Comment by bitsofinfo** [comment]
appears fixed by 0.8.2, thanks!
