### ISSUE TITLE
Add support for 'all namespaces' option

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#166]
Current UI only displays resources from a single namespace at a time, controlled by the namespace dropdown in the side nav.

We should add an 'all namespaces' option to the dropdown so that a user can choose to view all resources of a given type (e.g. Pipeline, TaskRun, etc.) defined in the cluster regardless of namespace.

- Option 1:
  - front end makes an API call per namespace to get the requested resources
  - will need to handle loading / error states for multiple in-flight requests for a single resource type (not currently supported)
- Option 2:
  - back end API provides support for retrieving resources from all namespaces, perhaps using a reserved namespace value (e.g. '*') or by some other means
  - for example, looking at the approach taken by the kube API server (accessed via kube proxy below)
    - get pipelines for a particular namespace:
      - http://localhost:8001/apis/tekton.dev/v1alpha1/namespaces/default/pipelines
    - get pipelines for all namespaces (drop the `/namespaces/{name}`)
      - http://localhost:8001/apis/tekton.dev/v1alpha1/pipelines

Regardless of which option we pursue there are some front end changes that will need to be made:
- [x] 'success' actions should no longer include the namespace directly in the payload as results could come from multiple namespaces
- [x] reducers should read the namespace directly from the resource's metadata when processing

**Comment by steveodonovan** [comment]
Backend api will be `.../v1/namespaces/*/<resource>` 

However one issue here `.../v1/namespaces/*/<resource>/<resourceName>`  will be invalid. A namespace must be provided when requesting a specific resource by name. The above will return an 404 and the message `an empty namespace may not be set when a resource name is provided` This is coming from the pipelineClient, not our application. Queryparameter filtering will still work though `/pipelineRuns?name=pipelinename` for example.

**Comment by AlanGreene** [comment]
Updated description to include example of how this is handled by the kube API server.

**Comment by vtereso** [comment]
The all namespaces option should be specific to get all CRD routes?

**Comment by vtereso** [comment]
I favor anything except for the additional routes where we `(drop the /namespaces/{name})`

**Comment by vtereso** [comment]
Updates @steveodonovan @AlanGreene ?

**Comment by AlanGreene** [comment]
@vtereso we're going with the `*` approach for now to unblock the front end work and to avoid making multiple requests from the browser. https://github.com/tektoncd/dashboard/pull/174

**Comment by ncskier** [comment]
@AlanGreene @steveodonovan the latest PR for this issue has broken the "Import Tekton resources" page. When the "All Namespaces" option is selected, we can't allow the user to create any Tekton resources (because they fail to be created). Right now the "Import Tekton resource" page does not provide the user with any feedback in this failure case. We could probably solve this problem by displaying an error message such as "Please select a namespace from the left navigation menu." What do you think?

Also, are you going to fix this under your issue here, or should I create a new one for it?

**Comment by AlanGreene** [comment]
The import page should have a namespace dropdown, that was the approach we discussed for this and other panels including the extensions. I missed its absence during reviews, my bad.

I've already discussed this with Carlos in relation to the secrets work and changes needed to the APIs to support 'all namespaces'.

**Comment by ncskier** [comment]
Ok... so the namespaces dropdown in the Side Nav is only for Read operations? Then each Create operation page will need to have its own namespace dropdown?

**Comment by AlanGreene** [comment]
Exactly, that was the reason for the creation of the NamespacesDropdown component.
The dropdowns used elsewhere can default to the value selected in nav where that makes sense.
