### ISSUE TITLE
Dashboard should not require cluster-admin role by default

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#1670]
# Is your feature request related to a problem ?

As raised by @nikhil-thomas on August 10th Dashboard Working Group: https://github.com/tektoncd/operator/issues/131

A default Tekton Dashboard install should not require cluster-admin role. This is currently required for Dashboard extensions since we use an [`aggregationRule`](https://github.com/tektoncd/dashboard/blob/8acf15acc6c17a5ee972394a21f59be5c3016101/base/200-clusterrole-extensions.yaml#L24) to aggregate roles required by Dashboard extensions (e.g. the webhooks-extension).

# Describe the solution you'd like

The ClusterRole related to Dashboard extensions should be optional since many users install the Dashboard without using this functionality.

If a user is installing a cluster-scoped Dashboard and wants to use Dashboard extensions, enabling this ClusterRoleBinding would be a prereq and the consequences are more justifiable and should be understood by the user.

In the case of a namespace-scoped Dashboard install, this should not be required.

# Describe alternatives you've considered

# Additional context

**Comment by eddycharly** [comment]
Closing, not getting feedback in the operator issue.
