### ISSUE TITLE
dev README has outdated  information

### ISSUE THREAD

**Issue by barthy1** [tektoncd/dashboard#1686]
# Describe the bug

I try to install latest dashboard on my k8s cluster. I use master branch for it. I followed the https://github.com/tektoncd/dashboard/blob/master/docs/dev/README.md#build-yaml-manifests and https://github.com/tektoncd/dashboard/blob/master/docs/dev/README.md#build-yaml-manifests for Plain Kube.
I've got errors like
```
no such file or directory, get: invalid source string: overlays/dev
```
when  I tried to run `kustomize build overlays/dev`

# Expected behaviour

`kustomize build overlays/dev` command should be executed successfully

# Steps to reproduce the bug

Install prerequisites following https://github.com/tektoncd/dashboard/blob/master/docs/dev/README.md#pre-requisites and run `kustomize build overlays/dev`

# Environment details
- Versions:
   - Tekton Dashboard:
      - master
   
# Additional Info
`overlays/dev` directory just doesn't exist in the latest code, as well as `overlays/dev-openshift` for installation on top of Openshift.

**Comment by AlanGreene** [comment]
@barthy1 good catch, thanks for opening the issue. The instructions for using `kustomize` have been replaced by the new installer script: https://github.com/tektoncd/dashboard/blob/master/docs/dev/README.md#build-and-deploy-with-the-installer-script

We'll need to remove the outdated instructions on using `kustomize` and `ko`
