### ISSUE TITLE
Pipeline0 should accept a folder name parameter

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#169]
**Background**

We currently have folders in the hotel and our pipeline0 relies on resources to apply being in the `config` folder. We should remove this restriction.

We could start with just having one arbitrary parameter for now, because we want our "pipeline0" pipeline, at https://github.com/pipeline-hotel/example-pipelines, to be able to apply arbitrary yaml for a repository: including folders.

**Proposal**

**I'm proposing an additional optional PipelineRun parameter for pipeline0, and we use that in our kubectl apply for "pipeline0" (which lets us apply arbitrary yaml from a Git repository after checking it out).**

@jessm12 is adding paneling now so that users can trigger pipeline0 in our dashboard, pointing to a repository, but it relies on yaml being in a `config` directory currently.

Under this issue:
- [ ] Add additional parameter FOLDER_NAME to pipeline0
- [ ] Add `parameter` (for now) to our existing PipelineRun API for POSTing
- [ ] Run pipeline0 with FOLDER_NAME set to, for example, `microclimate`, using the pipeline hotel
- [ ] Verify the `microclimate` resources were applied

**Comment by ncskier** [comment]
Hi @a-roberts, I might be misunderstanding your proposal, but I think what you are proposing already exists. Pipeline0 has an `apply-directory` parameter (https://github.com/tektoncd/dashboard/blob/master/config/pipeline0.yaml#L13) which specifies the directory from which resources will be applied. It's used in the task here:
```command:
    - kubectl
    args:
    - apply
    - -f
    - ${inputs.params.pathToResourceFiles}/${inputs.params.apply-directory}
```
(https://github.com/tektoncd/dashboard/blob/master/config/pipeline0-task.yaml#L25)

**Comment by a-roberts** [comment]
Hey @ncskier - yeah, @jessm12 actually added it as a parameter, we can close this (and I made the issue title far too general when really I was looking for it to be used in pipeline0).

Let's close this 😄.
