### ISSUE TITLE
Dashboard can be developed on Windows

### ISSUE THREAD

**Issue by yamaken1343** [tektoncd/dashboard#1697]
# Is your feature request related to a problem ?

Currently, developing Tekton Dashboard on Windows requires some file modifications.
There is a Linux dependency on the npm script.
So when running on Windows, it gets stoped during the bootstrap process at `npm ci`.

# Describe the solution you'd like

I want to be able to develop the front end even on Windows.

Dependencies can be resolved by dynamically changing the script executed on Linux and Windows using [run-script-os](https://www.npmjs.com/package/run-script-os).

# Describe alternatives you've considered

Since the changes are few (2 lines), it is easy for the user to modify them.
In this case, they only need to describe the changing lines in the development documentation.

# Additional context

Git for Windows rewrites line feeds to `CRLF` by default on checkout.
Therefore, prettier throws up an error when you run `npm start`. (occurs `error Delete ␍ prettier/prettier`)
To get around this, you need to fuzzy up the prettier rules.
Specifically, add `endOfLine: "auto"` to `.prettierrc`.
Should I include this code in PR?

If you need this feature, I'll create PR.
Thanks.

**Comment by AlanGreene** [comment]
Thanks for the issue @yamaken1343, can you share more information about the steps / commands that are failing on Windows?

Examples of the commands you're running and the error output would be very helpful.

**Comment by yamaken1343** [comment]
## Errors in `npm ci`

Errors in `npm ci`, the following errors occurred.
The user only runs `npm ci`.
Then `lerna ERR! npm run prepare stderr: 'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.` occurred.

We think the cause is as the following.
When `npm-ci` is running, `npm run bootstrap` is executed after the module installation is finished.  
In the `npm run bootstrap`, the `build` which is described in the `dashboard\packages\utilsutilspackage.json` is run.  
In the `build`, `rimraf dist && NODE_ENV=production babel src --out-dir dist --root-mode upward --ignore "src/**/*.test.js,src/**/*.stories.js" --no -copy-ignored` is executed.  
I think there is an error caused by an unrecognized format on Windows. (`NODE_ENV=production babel` command)

NOTE: A similar problem is contained in the file `dashboard\packages\componentspackage.json`.

Here is the full text.

```cmd
npm run bootstrap

> @tektoncd/dashboard@0.1.0 bootstrap C:\parentDirectory\dashboard
> lerna bootstrap

lerna notice cli v3.22.1
lerna info bootstrap root only

> @tektoncd/dashboard@0.1.0 postinstall C:\parentDirectory\dashboard
> npm run bootstrap


> @tektoncd/dashboard@0.1.0 bootstrap C:\parentDirectory\dashboard
> lerna bootstrap

lerna notice cli v3.22.1
lerna WARN bootstrap Skipping recursive execution

> @tektoncd/dashboard@0.1.0 prepare C:\parentDirectory\dashboard
> lerna run prepare

lerna notice cli v3.22.1
lerna info Executing command in 2 packages: "npm run prepare"
lerna ERR! npm run prepare exited 1 in '@tektoncd/dashboard-utils'
lerna ERR! npm run prepare stdout:

> @tektoncd/dashboard-utils@0.1.0 prepare C:\parentDirectory\dashboard\packages\utils
> npm run build


> @tektoncd/dashboard-utils@0.1.0 build C:\parentDirectory\dashboard\packages\utils
> rimraf dist && NODE_ENV=production babel src --out-dir dist --root-mode upward --ignore "src/**/*.test.js,src/**/*.stories.js" --no-copy-ignored


lerna ERR! npm run prepare stderr:
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tektoncd/dashboard-utils@0.1.0 build: `rimraf dist && NODE_ENV=production babel src --out-dir dist --root-mode upward --ignore "src/**/*.test.js,src/**/*.stories.js" --no-copy-ignored`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tektoncd/dashboard-utils@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hoge\AppData\Roaming\npm-cache\_logs\2020-08-27T01_43_46_626Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tektoncd/dashboard-utils@0.1.0 prepare: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tektoncd/dashboard-utils@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hoge\AppData\Roaming\npm-cache\_logs\2020-08-27T01_43_46_696Z-debug.log

lerna ERR! npm run prepare exited 1 in '@tektoncd/dashboard-utils'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tektoncd/dashboard@0.1.0 prepare: `lerna run prepare`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tektoncd/dashboard@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hoge\AppData\Roaming\npm-cache\_logs\2020-08-27T01_43_46_882Z-debug.log
lerna ERR! npm install exited 1 in '@tektoncd/dashboard'
lerna ERR! npm install exited 1 in '@tektoncd/dashboard'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tektoncd/dashboard@0.1.0 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tektoncd/dashboard@0.1.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hoge\AppData\Roaming\npm-cache\_logs\2020-08-27T01_43_47_052Z-debug.log

```

## Errors in `npm start`

Errors in `npm start`, the following errors occurred.
The user only has to run `npm start`.
After a while, you'll get a bunch of the following errors.

```cmd
ERROR in ./src/containers/PipelineResources/PipelineResources.js
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

C:\parentDirectory\dashboard\src\containers\PipelineResources\PipelineResources.js
    1:3   error  Delete `␍`                                                    prettier/prettier
    2:39  error  Delete `␍`                                                    prettier/prettier
    3:64  error  Delete `␍`                                                    prettier/prettier
    4:65  error  Delete `␍`                                                    prettier/prettier
    5:40  error  Delete `␍`                                                    prettier/prettier
    6:47  error  Delete `␍`                                                    prettier/prettier
    7:68  error  Delete `␍`                                                    prettier/prettier
    8:66  error  Delete `␍`                                                    prettier/prettier
    9:73  error  Delete `␍`                                                    prettier/prettier
   10:68  error  Delete `␍`                                                    prettier/prettier
   11:31  error  Delete `␍`                                                    prettier/prettier
```

There are too many to show them all.

We think this is because, as I mentioned above, Git for Windows has rewritten the line endings and prettier is detecting them.

If you have Git for Windows configured properly, the error won't happen, but many users may not be able to do set.
You can confirm if your setting is appropriate by the following command.

```cmd
git config --global -l
```

If it contains `core.autocrlf=input` or `core.autocrlf=false`, this problem does not occur.

**Comment by AlanGreene** [comment]
@yamaken1343 thanks so much for the detailed update.

1. cross-platform support for the npm scripts
  I will update this to ensure we're correctly setting environment variables in a cross-platform compatible way

2. line endings
  as you mentioned, this can be resolved using git config
  https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#:~:text=core.autocrlf
  git recommends setting `core.autocrlf` to `true` on Windows when working on a cross-platform project

    I'll add a note to the dev readme mentioning this

**Comment by yamaken1343** [comment]
Thanks @AlanGreene.
The thing is, I already have the code to solve 1.
Could you assign it to me?
It's on the company's computer, so I will create a PR after Monday.

**Comment by AlanGreene** [comment]
Sorry I didn't see your message until after I opened the PR: https://github.com/tektoncd/dashboard/pull/1707

Is this similar to the change you made?

**Comment by yamaken1343** [comment]
No problem.
I used `run-script-os`, but that would be redundant.
I think your code is cleaner!
