### ISSUE TITLE
Rerunning a pipeline ignores taskRunSpecs

### ISSUE THREAD

**Issue by cezarguimaraes** [tektoncd/dashboard#1702]
# Describe the bug

`PiepelineRuns` triggered through the Dashboard do not mirror the original `PipelineRun`'s `taskRunSpecs`.

If I had to guess, this is related to the fact that one can't specify `taskRunSpecs` when creating a `PipelineRun` through the Dashboard either.

# Expected behaviour

The pipeline run triggered via a rerun should have the same `taskRunSpecs` as the original one.

# Steps to reproduce the bug

1. Trigger a pipeline run with a task run spec
2. Click rerun on the dashboard

# Environment details

- Kubernetes Platform: Rancher

- Kubernetes or OpenShift version:

- Install mode (if on OpenShift):

- Cloud-provider/provisioner: AWS

- Versions:
   - Tekton Dashboard: v0.8.2
   
   - Tekton Pipelines: v0.15.1
   
   - Tekton Triggers: v0.7.0
   
- Install namespaces:
   - Tekton Dashboard: tekton-pipelines
   
   - Tekton Pipelines: tekton-pipelines
   
   - Tekton Triggers: tekton-pipelines
   

# Additional Info

```console
> kubectl get pr builders-pipeline-run-fxr5d -o yaml | grep taskServiceAccountName
    taskServiceAccountName: start-nginx-task

~~> exit code 0

> kubectl get pr builders-pipeline-run-fxr5d-r-dvgs4 -o yaml | grep taskServiceAccountName

~~> no output and exit code 1
```

**Comment by eddycharly** [comment]
Thanks for reporting the issue @cezarguimaraes .

It looks like we need to clear the `tekton.dev/pipeline` label when creating the rerun, the `PipelineRun` gets created but immediately deleted by the pipeline controller.

@vdemeester is there a requirement that the `tekton.dev/pipeline` label matches the name of the pipeline run ?

**Comment by vdemeester** [comment]
> @vdemeester is there a requirement that the `tekton.dev/pipeline` label matches the name of the pipeline run ?

`tekton.dev/pipeline` should be automatically added to the controller based on the pipeline it runs. So I don't think it has to match the name of the pipeline run, it doesn't even need to be there. I think deleting it when re-running (and thus copying the run spec) is a good fix :+1:

**Comment by eddycharly** [comment]
The question is more like, can it cause trouble if it is present and set to a value that references another pipeline run ?

In this case it looks like it is set to a reference of another pipeline run that is in failed state, the pipeline run gets created and immediately deleted right after (maybe the label confuses the controller ?).

**Comment by vdemeester** [comment]
> The question is more like, can it cause trouble if it is present and set to a value that references another pipeline run ?
> 
> In this case it looks like it is set to a reference of another pipeline run that is in failed state, the pipeline run gets created and immediately deleted right after (maybe the label confuses the controller ?).

Yep it might confuse the controller :sweat:

**Comment by eddycharly** [comment]
Thanks ! That’s good to know.
