### ISSUE TITLE
Steps are not ordered correctly and message is therefore incorrect

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/dashboard#1708]
# Describe the bug

In the exemple below, `make-package` should come after `make-unit-tests`:
![image](https://user-images.githubusercontent.com/47974576/91731782-962fc400-eba7-11ea-83cd-a9c9835d1950.png)
The `make-unit-tests` step actually failed and the `make-package` step didn't run at all.

In the screen shot, it looks like the opposite.

**Comment by eddycharly** [comment]
But time stamps on the pipeline run status are not ordered correctly, maybe it's an issue with pipelines. IIRC i'm using v0.11 or somethings like this.

**Comment by AlanGreene** [comment]
This is a known issue with older version of Tekton Pipelines. It's fixed by https://github.com/tektoncd/pipeline/pull/2455 which is included in v0.13.0 or later.

**Comment by eddycharly** [comment]
Thanks, i will try updating our Tekton Pipelines deployment.

**Comment by AlanGreene** [comment]
@eddycharly have you had a chance to test this with a newer Tekton Pipelines version?

**Comment by eddycharly** [comment]
Not yet, will do my best to do it tomorrow.

**Comment by eddycharly** [comment]
Let's close this, i didn't have a chance to test it and probably won't come back to it anyway.

/close
