### ISSUE TITLE
Add PipelineRun diagram support

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/dashboard#1714]
This issue tracks the addition of PipelineRun diagram support to the Tekton Dashboard.

Right now, the Tekton Dashboard does not show the `PipelineRun` diagram.
The diagram view could be displayed in a separate tab.

There was some [previous work in this area](https://github.com/tektoncd/dashboard/issues/675), some components already exist to extract/show a digram.
They will probably need to be updated and included somewhere in the Dashboard containers.

**Comment by AlanGreene** [comment]
Closing this issue, the visualisation work is still being tracked in #675
