### ISSUE TITLE
External logs not working

### ISSUE THREAD

**Issue by shinji62** [tektoncd/dashboard#1715]
Hello, 
I follow and use the exact same provided example to use with the logging-operator last version  but it doesn’t work.

I am wondering if the provided yaml are correct, not sure the escaping on the ‘ouputs’ one is correct, and if there is any step that wasn’t share.

Error is the config is not valid .. so I am really wondering was is wrong ..

I   Guess @eddycharly worked on this topic. 
Thanks

**Comment by eddycharly** [comment]
Hey, let me try, maybe the `logging-operator` helm chart changed something...

**Comment by eddycharly** [comment]
@shinji62 at what point are you having troubles ?

**Comment by shinji62** [comment]
Pretty much when I apply the S3 config  the operator just complain the configuration is not valid then the fluentd pod is failing and that’s all.

**Comment by eddycharly** [comment]
I observe an issue too `2020-09-08 13:32:59 +0000 [error]: config error file="/fluentd/etc/generated.conf" error_class=Fluent::ConfigError error="Missing <match> sections in <label @ee48ddc4afe13369031ac8183198a19b> section"`

**Comment by eddycharly** [comment]
breaking change from the `v3.6.0` https://github.com/banzaicloud/logging-operator/releases/tag/3.6.0

Breaking changes ⚠️ outputRefs is now deprecated!
For clarity we introduce:

use globalOutputRefs for ClusterOutputs
use localOutputRefs for Outputs

**Comment by eddycharly** [comment]
I will update the walkthrough, you can use `3.5.0` until then.

```
helm upgrade --install --version 3.5.0 --wait --create-namespace --namespace tools logging-operator banzaicloud-stable/logging-operator --set createCustomResource=false
```

**Comment by shinji62** [comment]
That could be the issue ...
