### ISSUE TITLE
Allow PipelineRuns created by PipelineRun -> Create to embed ownerReference information.

### ISSUE THREAD

**Issue by mhaddon** [tektoncd/dashboard#1722]
### Feature request

For compatibility with ArgoCD it will need to know the owner of created resources: https://github.com/tektoncd/pipeline/issues/3202

Otherwise they will be automatically pruned.

### Use case

Either as a default when creating a pipelinerun or a tickbox option.

**Comment by AlanGreene** [comment]
We could potentially use similar controls to those for adding labels in the Create PipelineRun/TaskRun UI, although this may not be the best solution, especially if we need to handle non-string values as this could get complex quite quickly.

I'd also be reluctant to add a raw JSON / YAML input field for the user to enter the entire ownerReferences block, although maybe this could be an option in an 'Advanced Configuration' section similar to the one we have for Import Resources. It doesn't seem like this is a feature most users would need in normal use.

Similar to the CLI, we'll follow the Pipelines issue to see if there's a common solution we can all adopt. At the very least we should aim to be relatively consistent so users know what's expected regardless of which tool they use to trigger a run.
