### ISSUE TITLE
number of steps in pipeline runs view

### ISSUE THREAD

**Issue by didier-durand** [tektoncd/dashboard#1729]
Hello,

Possible to add the number of steps executed in pipeline run view?

I'd see it for example before or after "Duration" in screenshot below. Maybe they should be displayed as X/Y where X is the number of successful steps and Y the total.

Thanks!

Didier

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/2927957/94332653-40e4a800-ffd7-11ea-887f-b6ca1c9094b2.png">

**Comment by AlanGreene** [comment]
Thanks for the request @didier-durand. We already provide this information in a number of places.
![image](https://user-images.githubusercontent.com/2829095/94427054-695ed480-0186-11eb-9ebd-2221eb2a5e9d.png)

This is the same message displayed on the PipelineRun details page
![image](https://user-images.githubusercontent.com/2829095/94427205-9f03bd80-0186-11eb-9115-1499215f2008.png)

The message comes from the PipelineRun status field:
```sh
$ kubectl get -ojson pr check-pr-labels-rf8nw | jq '.status.conditions[0].message'
"Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0"
```

Is this sufficient for your needs or are you looking for a more prominent display of this information on the PipelineRuns list specifically?

**Comment by didier-durand** [comment]
Hi @AlanGreene,

I have seen that I can zoom on a PipelineRun via a click to get a list of tasks that were run as part of this pipeline. It's ok when you have a few pipelines. But, when you've many of them, you want a synthetic view of each pipeline at top level. That's why I believe that the PipelineRuns view should also provide the total number of tasks and the successful ones at top level in the dashboard : you want to make most efficient for DevOps teams.

If I may, I would also suggest some improvements for the task view when you click on a given PipelineRun: I would suggest something very much like display of tracing spans by Jaeger with time axis as horizontal as tasks represented on this time axis according to their start and stop time to provide a view where tasks are positionned on the time line.

Didier

**Comment by AlanGreene** [comment]
Note to self / future developers: Also relevant here is some of the previous discussion / design exploration around presentation of the status and status message: https://github.com/tektoncd/dashboard/issues/775 and other issues. This might be a good opportunity to revisit this and see what additional information would make sense here and how best it can be displayed without making the list views overly busy.

@didier-durand can you expand on your second point about the 'tracing spans'? We're planning a [PipelineRun visualisation](https://github.com/tektoncd/dashboard/issues/675) which would show the directed acyclic graph generated by the Pipeline execution. This would be similar in function to visualisations provided in many other CD/CI tools.

Do you see the 'tracing spans' fulfilling a similar function? What additional / alternative benefit do they provide? How would a user make use of them? I'd love to understand this better so we can make more informed decisions about the future designs for the Dashboard.

**Comment by didier-durand** [comment]
@AlanGreene : I have seen the PipelineRun visualisation that you prepare. It is clearly a good thing to show a pipeline as a DAG. My point is different and complementary: basically, I suggest to add a time axis to the DAG in order to see how long after start a Task X was started and how much it lasted. 

That is the reason of my analogy with distributed trace spans 

![distributed-trace](https://user-images.githubusercontent.com/2927957/96554872-62277400-12b7-11eb-8314-24c31a894c76.png)

In the above image, you can see when an additional trace happens and how long the interaction lasts. 

That's what I would like to see in Tekton UI in order to spot easily the tasks that make the pipeline run  for (too) long.

In your current DAG view, you can probably achieve that by correlating the length of the arrow with the delay until start and the length of the box with the task duration.

If I remain unclear, please, don't hesitate to ask additional questions

Didier

**Comment by AlanGreene** [comment]
Thanks for the additional information, that helps to understand a possible use case for something like this.

**Comment by didier-durand** [comment]
@AlanGreene : any progress / decision regarding the implementation of this use case? Best,Didier
