### ISSUE TITLE
how container logs though websocket to webui

### ISSUE THREAD

**Issue by sunnoy** [tektoncd/dashboard#1730]
i see this code
https://github.com/tektoncd/dashboard/blob/e27e89b430d96fc04f72d0b76b576cb1365e7e56/pkg/controllers/utils/controller.go#L28

it just give channel obj ，not container logs

**Comment by AlanGreene** [comment]
@sunnoy we do not use the websocket connection to retrieve the logs. Instead there are 2 modes available:

1. by default the UI polls the logs API by periodically making a GET request to the logs endpoint for the container while the step is in progress and the logs view is open

2. streaming mode makes a long-lived GET request to the logs endpoint with the [`follow` query param](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#read-log-pod-v1-core) set and will display updated logs as they are received on the response stream. This can be enabled by passing the [`--stream-logs` flag](https://github.com/tektoncd/dashboard/blob/master/docs/dev/installer.md) to the installer script.

**Comment by sunnoy** [comment]
so we use websoket publish obj to webUI  useing display ？
i am new  golanger 
one more thing，the broadcaster design is so beautiful ！
think you answer ！

**Comment by AlanGreene** [comment]
Yes we use the websocket to send the Tekton / other Kubernetes resource updates to the UI, so for example [the PipelineRun controller](https://github.com/tektoncd/dashboard/blob/e27e89b430d96fc04f72d0b76b576cb1365e7e56/pkg/controllers/tekton/pipelinerun.go#L28) will send updates to the UI for any PipelineRun resource that is created, deleted, or updated.

Glad I could help! 😸 

/close
