### ISSUE TITLE
Clarify that repository URLs must be hosted on github when importing them

### ISSUE THREAD

**Issue by drsm79** [tektoncd/dashboard#1743]
# Describe the bug

I can paste a valid URL to a repository hosted on, e.g. gitlab, and the UI fails to import with "Please submit a valid URL". There is nothing to say that the repo must be hosted on github, but that's the _actual_ requirement:

https://github.com/tektoncd/dashboard/blob/9a0a888603386f6655ba8d9a90365c1bae701963/src/containers/ImportResources/ImportResources.js#L55-L57

# Expected behaviour

Either:
- support repos hosted on !github
- make clear that the dashboard can only import from github

# Steps to reproduce the bug

- Open the dashboard
- Put a gitlab URL in
- Watch it fail

# Environment details

- Kubernetes Platform:

- Kubernetes or OpenShift version:

- Install mode (if on OpenShift):

- Cloud-provider/provisioner:

- Versions:
   - Tekton Dashboard:
   
   - Tekton Pipelines:
   
   - Tekton Triggers:
   
- Install namespaces:
   - Tekton Dashboard:
   
   - Tekton Pipelines:
   
   - Tekton Triggers:
   

# Additional Info

I found it while trying to debug an issue, using https://gitlab.com/nmeisenzahl/tekton-demo/-/blob/master/pipeline.yaml as a sample pipeline.

**Comment by AlanGreene** [comment]
@drsm79 thanks for reporting this. When the Import Resources functionality was added we only supported GitHub, however I no longer see any reason for this restriction and have successfully imported your sample Pipeline on a modified dashboard build.

I'll make the required updates and open a PR shortly.

/assign

**Comment by AlanGreene** [comment]
PR open to remove the GitHub restriction from the UI validation since the Git PipelineResource now actually supports other providers, not just GitHub: https://github.com/tektoncd/dashboard/pull/1744

**Comment by drsm79** [comment]
Nice one :)

**Comment by AlanGreene** [comment]
This is included in the [Dashboard 0.10.0 release](https://github.com/tektoncd/dashboard/releases/tag/v0.10.0)
