### ISSUE TITLE
question：how dashboard proxy request to kubernetes apiserver in code ？

### ISSUE THREAD

**Issue by sunnoy** [tektoncd/dashboard#1758]
i see the code
https://github.com/tektoncd/dashboard/blob/8b1f04a48fcb116352a17afa84ca9fc9efd8bcd5/pkg/utils/proxy.go#L10

it is just http client methed and how to handle x509: certificate?

thks

**Comment by AlanGreene** [comment]
The Dashboard uses `k8s.io/client-go/rest` as the REST client with `InClusterConfig` by default.

https://github.com/tektoncd/dashboard/blob/abbd6c1cd29b3d08c515c813c8db2be5db360a4f/cmd/dashboard/main.go#L124

Here's an example showing the approach from the kubernetes/client-go repo: https://github.com/kubernetes/client-go/blob/60a0346672170c8e9f65795fb33e41527980c583/examples/in-cluster-client-configuration/main.go

**Comment by sunnoy** [comment]
think a lot !
i see the code
1 init httpclient transport
https://github.com/tektoncd/dashboard/blob/abbd6c1cd29b3d08c515c813c8db2be5db360a4f/cmd/dashboard/main.go#L124
2 init endpoints.Resource.HttpClient
https://github.com/tektoncd/dashboard/blob/abbd6c1cd29b3d08c515c813c8db2be5db360a4f/cmd/dashboard/main.go#L143
3 proxy reqest by Resource.HttpClient
https://github.com/tektoncd/dashboard/blob/abbd6c1cd29b3d08c515c813c8db2be5db360a4f/pkg/endpoints/cluster.go#L69
