### ISSUE TITLE
Add namespace field to credentials 

### ISSUE THREAD

**Issue by carlos-logro** [tektoncd/dashboard#178]
Currently our struct in credentials.go does not include the namespace it was created in. For the upcoming `all namespaces` option in the sidebar dropdown to work we need the namespace field to be specified in the returned value.

**Comment by vtereso** [comment]
This is a no go IIUC since the push is to remove Credential and use native secrets?

**Comment by carlos-logro** [comment]
@mnuttall should we go ahead and implement this?

**Comment by a-roberts** [comment]
This is now merged, thanks @carlos-logro 😄 

/meow sunglasses
