### ISSUE TITLE
Error in Evenlistener page  in Dashboard

### ISSUE THREAD

**Issue by aii-ssvinoth22** [tektoncd/dashboard#1780]
# Describe the bug

Click EventListeners--> <Name>
getting below error 
`Error loading page

Expected "triggerTemplateName" to match "[^\/]+?", but received ""
 `

# Expected behaviour

# Steps to reproduce the bug

# Environment details

- Kubernetes Platform:

- Kubernetes or OpenShift version:

- Install mode (if on OpenShift):

- Cloud-provider/provisioner:

- Versions:
   - Tekton Dashboard:  v0.10.1
   
   - Tekton Pipelines: v0.16.3
   
   - Tekton Triggers: v0.9.1
   
- Install namespaces:
   - Tekton Dashboard:  tekton-pipelines
   
   - Tekton Pipelines:
   
   - Tekton Triggers:
   

# Additional Info

**Comment by AlanGreene** [comment]
@aii-ssvinoth22 thanks for reporting. Can you share the EventListener that produced this error?

**Comment by aii-ssvinoth22** [comment]
It is when click on viewing each listener.

**Comment by aii-ssvinoth22** [comment]
I've only one listener running, when I click on that got this error

**Comment by AlanGreene** [comment]
Can you share the EventListener resource you're using to reproduce the issue? This would be very helpful in debugging. I suspect you may be using a Triggers feature that was introduced in 0.9 which is not yet supported by the Dashboard.

**Comment by AlanGreene** [comment]
Dashboard v0.10.2 is available now with support for Triggers 0.9.
Closing this issue. If the new release doesn't resolve your issue please feel free to reopen it and provide additional details to help reproduce it and debug further.

/close
