### ISSUE TITLE
Dashboard displays task steps incorrectly after step failure

### ISSUE THREAD

**Issue by kyledwilson** [tektoncd/dashboard#1790]
# Describe the bug

During a pipelinerun, if a task fails then occasionally the steps will appear in the wrong order. Additionally, the wrong step will be marked as failed even though it has not ran yet. The step that actually failed is marked as not run yet.

# Expected behaviour

During a pipelinerun, if a task step fails then that step should be marked as failed and appear in the correct order of steps listed.

# Steps to reproduce the bug

Apply a pipelinerun that fails and occasionally the steps display incorrectly.. not much more to it.

# Environment details

- Kubernetes Platform:
kubespray
- Kubernetes version:
v1.18.6
- Cloud-provider/provisioner:
on-prem
- Versions:
   - Tekton Dashboard:
   v.10.0
   - Tekton Pipelines:
   v0.11.3
   - Tekton Triggers:
   v0.8.1
- Install namespaces:
   - Tekton Dashboard:
   tekton-pipelines
   - Tekton Pipelines:
   tekton-pipelines
   - Tekton Triggers:
   tekton-pipelines

# Additional Info

An example:
In our setup, we build an image then scan for vulnerabilities.

The step scan-container shows as failed even though it has not actually ran. The build step has failed due to unit tests not passing, but shows as not ran and it is displayed after scan-container step.

![dashboard](https://user-images.githubusercontent.com/27834712/97025655-60171c80-1526-11eb-8c6b-a07a2b29e612.jpeg)

![pipelinerun_logs](https://user-images.githubusercontent.com/27834712/97026353-462a0980-1527-11eb-8fc7-dbc97899e7e9.jpeg)

The steps should look like the following:
![dashboard-correct](https://user-images.githubusercontent.com/27834712/97026892-03b4fc80-1528-11eb-9577-80ab9c9448e4.jpeg)

**Comment by AlanGreene** [comment]
This is a known issue with older Pipelines releases. Pipelines 0.12 and newer use higher resolution timestamps for the step status among other changes to help ensure the steps can be ordered correctly. Previous issue with links to a number of the relevant Pipelines issues: https://github.com/tektoncd/dashboard/issues/1367

Can you try upgrading to a newer Pipelines version and see if that resolves the issue for you?
