### ISSUE TITLE
POST requests should return "201 Created"

### ISSUE THREAD

**Issue by seabaylea** [tektoncd/dashboard#18]
Currently a `POST` request to create a new gitresource returns `204 No Content`, whereas the general best practise for successful `POST` requests is to return `201 Created` and to set the both data to the created data (ie, the POSTed data plus any additional fields like an ID that has been set).

An optional best practise is to also set the Location header to the URL that you would use to interact with that resource (ie. the URL you would use to `GET` or `DELETE` the resource).

**Comment by vtereso** [comment]
I'm working on this now as a temporary assignee since I am not yet in the group. Looking to manage the routes in a way that will make this functionality easy to apply to routes.

**Comment by a-roberts** [comment]
/assign vtereso

Vincent's done this in #48 and it's merged, closing, thanks Vincent!

**Comment by a-roberts** [comment]
Retrospectively assigning @vtereso as he implemented this and he's now a member of our org.

/assign vtereso
