### ISSUE TITLE
Dashboard requires optional pipeline arguments to be specified

### ISSUE THREAD

**Issue by JPEWdev** [tektoncd/dashboard#1815]
# Describe the bug

When creating a PipelineRun in the dashboard, the UI will not let me create the pipeline unless I specify an value for a an optional empty Pipeline argument

# Expected behaviour

I should be able to create the PipelineRun without specifying a value for the optional argument and it will default to the empty string

# Steps to reproduce the bug

1. Create a Pipeline with an optional argument. In my case: https://github.com/JPEWdev/kube-battlestar-cluster/blob/3e33bef12e2c6c2902d251f97de1cab44b0b0736/kubernetes/pipelines/yocto-whisk-pipeline.yaml#L14
2. Try to create a PipelineRun for the Pipeline in the dashboard without specifying a value for the optional argument. The dashboard will not let you create the pipeline without specifying a value

# Environment details

I'm new to Kubernetes, so apologies if I misunderstand some of these

- Kubernetes Platform:
K8s 1.19.3
- Cloud-provider/provisioner:
Bare Metal Ubuntu 20.04
- Versions:
   - Tekton Dashboard:
     0.10.2
   - Tekton Pipelines:
     0.17.3
   - Tekton Triggers:
    Not installed
- Install namespaces:
   - Tekton Dashboard:
     tekton-pipelines
   - Tekton Pipelines:
     tekton-pipelines
   - Tekton Triggers:
     Not installed

# Additional Info

**Comment by AlanGreene** [comment]
Thanks for reporting the issue. I've reproduced it locally and confirmed it only appears to be affecting params where the default value is an empty string, thanks for narrowing it down. Fix on the way 👷
