### ISSUE TITLE
Display pending task on pipelinerun view

### ISSUE THREAD

**Issue by sickyoon** [tektoncd/dashboard#1835]
# Is your feature request related to a problem ?

Pipelinerun only displays completed tasks and the currently running task.
This can be an issue if you want to know how many pending tasks are left in the pipeline.

# Describe the solution you'd like

Display pending tasks in the pipelinerun view

# Describe alternatives you've considered

Resort to look at pipeline yaml file to see what tasks are available

# Additional context

N/A

**Comment by AlanGreene** [comment]
Thanks for the feature request @sickyoon, this is already tracked in https://github.com/tektoncd/dashboard/issues/1263 so I'm closing this as a duplicate.
