### ISSUE TITLE
Websocket-Connection does not work in safari

### ISSUE THREAD

**Issue by wwu-cx** [tektoncd/dashboard#1836]
# Describe the bug

Console logs 

`Refused to connect to wss://tekton.example.com/v1/websockets/resources because it does not appear in the connect-src directive of the Content Security Policy.`

# Expected behaviour

PipelineRun View should refresh automatically

# Steps to reproduce the bug

View a PipelineRun in safari browser.

# Environment details

- Versions:
   - Tekton Dashboard:
      v0.11.0
   - Tekton Pipelines:
      v0.18.0
   - Tekton Triggers:
      v0.9.1
   - Safari:
      v14.0.1

# Additional Info

Might be fixed using the tip from https://stackoverflow.com/a/41389590

`connect-src 'self' ws:;`

**Comment by AlanGreene** [comment]
Thanks for reporting. It looks like this is a Safari bug as detailed in https://github.com/w3c/webappsec-csp/issues/7 and https://bugs.webkit.org/show_bug.cgi?id=201591

I'll test out the proposed workaround and evaluate whether this is something we can add to the default configuration.

**Comment by AlanGreene** [comment]
@wwu-cx thanks again for raising this. It's fixed in the [v0.11.1 release](https://github.com/tektoncd/dashboard/releases/tag/v0.11.1) which is available now.
