### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by amoravek** [tektoncd/dashboard#1848]
# Is your feature request related to a problem ?

I cannot use the dashboard on ARM64 clusters

# Describe the solution you'd like

docker images built for ARM64 platform

# Describe alternatives you've considered

build from source is complicated

**Comment by AlanGreene** [comment]
Now that `ko` supports multi-arch builds this should be doable.

/assign

**Comment by AlanGreene** [comment]
Previous related issue https://github.com/tektoncd/dashboard/issues/542
Docker image could be built for other platforms by e.g. `docker build --no-cache --build-arg GOARCH=ppc64le .`

This will still be an option for users to target additional platforms, however I'm hoping the change in #1849 will allow us to publish multi-arch images so this step is no longer needed for the most common ones at least.

Testing...

**Comment by AlanGreene** [comment]
The next nightly build (~3am UTC) should publish a multi-arch image supporting:

- `linux/amd64`
- `linux/arm`
- `linux/arm64`
- `linux/ppc64le`
- `linux/s390x`

**Comment by AlanGreene** [comment]
Multi-arch images are live 🎉 

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 919,
         "digest": "sha256:e4f6882a6e481c6ba37897fdfe41f83871677e363820d810d12bf4636aeea3ae",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 919,
         "digest": "sha256:90a091b2f41d28f82f44c8005c3e19abad797730d686d2df2b70f72e15de17fb",
         "platform": {
            "architecture": "arm",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 919,
         "digest": "sha256:04fb20f5e03f40a1a6284168cd648f88140a9ea50c871c9a5c85271a86649a5c",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 919,
         "digest": "sha256:21047e593686a8b400ddaf13abdadea8c1b41baa7edff9f6a69da04a9a5d5244",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 919,
         "digest": "sha256:57f8033c684fba4bfcc346ab11bf1433c8bad689a2ae3941538ecefb18da6804",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

@amoravek the nightly builds now produce multi-arch images so you should be able to run the dashboard on arm64. The standard manifest for the latest nightly build is available at https://storage.cloud.google.com/tekton-releases-nightly/dashboard/latest/tekton-dashboard-release.yaml (or change the filename to match the version you normally use).

**Comment by amoravek** [comment]
Great, thank you. I've used this image and it works: gcr.io/tekton-nightly/github.com/tektoncd/dashboard/cmd/dashboard:latest
