### ISSUE TITLE
Dashboard does NOT work

### ISSUE THREAD

**Issue by qiuxin** [tektoncd/dashboard#1880]
Hi There，
I run Tekton on a virtual machine in the Cloud. I use KIND to set up a local K8S cluster.
I execute each command depicted in https://tekton.dev/docs/dashboard/. But I can NOT connect to the dashboard from my laptop via “Public IP address: Port No（8080 or 9097）”.  Some help!
```shell
[root@VM-0-10-centos]# kind version
kind v0.9.0 go1.15.5 linux/amd64

[root@VM-0-10-centos]# kubectl get pods --namespace tekton-pipelines
NAME                                           READY   STATUS    RESTARTS   AGE
tekton-dashboard-56c78f485b-p9mtc              1/1     Running   0          25h
tekton-pipelines-controller-5cdb46974f-4qqc4   1/1     Running   0          29h
tekton-pipelines-webhook-6479d769ff-rnn42      1/1     Running   0          29h
```
Many thanks in advace!

Best,
Robert Q

**Comment by qiuxin** [comment]
[root@VM-0-10-centos ~]# tkn version
Client version: 0.15.0
Pipeline version: v0.19.0
Dashboard version: v0.12.0

**Comment by jordanbailes** [comment]
Are you making sure to follow one of the steps in the usage section (e.g. port-forwarding)? 

If you try port-forwarding, what do the port-forwarding logs say? Do you get logs similar to these? 

```
$ kubectl --namespace tekton-pipelines port-forward svc/tekton-dashboard 9097:9097
Forwarding from 127.0.0.1:9097 -> 9097
Forwarding from [::1]:9097 -> 9097
Handling connection for 9097
```

**Comment by qiuxin** [comment]
The following is the print information when I run that command.   I try to visit "Cloud IP address:9097" via chroma on my laptop, the website return "  (111) Connection refused, The remote host or network may be down. Please try the request again."  Anything else I  should do to make it work?

‘‘’
[root@VM-0-10-centos ~]# kubectl --namespace tekton-pipelines port-forward svc/tekton-dashboard 9097:9097
Forwarding from 127.0.0.1:9097 -> 9097
Forwarding from [::1]:9097 -> 9097
‘‘’

**Comment by qiuxin** [comment]
My MacBook firewall is shutdown. The port(8080,9097) policy of Cloud Virtual Machine is set to be available(open) for all IP address visits.

**Comment by AlanGreene** [comment]
If using the `port-forward` command above you would access the Dashboard on `localhost:9097` as described in the docs, NOT using your cluster's public IP address.

If you wish to provide access to the Dashboard to other users without them needing to use either the `kubectl proxy` or `kubectl port-forward` options you can implement that using an Ingress. See [Accessing the Dashboard > Using an Ingress rule](https://github.com/tektoncd/dashboard/blob/master/docs/install.md#using-an-ingress-rule). **NOTE**: the Dashboard does not handle authentication, so beware when exposing the Dashboard publicly via this method. We have a number of walkthroughs that provide sample setups adding authentication in front of the Dashboard, see for example https://github.com/tektoncd/dashboard/blob/master/docs/walkthrough/walkthrough-oauth2-proxy.md

Closing this issue since it's not actually a bug in the Dashboard.

Feel free to reach out with any other questions.

/close

**Comment by qiuxin** [comment]
Hi Alan,
I install "NGINX Ingress controller" in my cluster itemized below:
'''
[root@VM-0-10-centos ~]# POD_NAME=$(kubectl get pods -l app.kubernetes.io/name=ingress-nginx -o jsonpath='{.items[0].metadata.name}')
[root@VM-0-10-centos ~]# kubectl exec -it $POD_NAME -- /nginx-ingress-controller --version
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       v0.43.0
  Build:         f3f6da12ac7c59b85ae7132f321bc3bcf144af04
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.19.6

-------------------------------------------------------------------------------
'''

And then, I create Ingress resource itemized below.
'''
[root@VM-0-10-centos ~]# hostname robertqiu
[root@VM-0-10-centos ~]# hostname
robertqiu
[root@VM-0-10-centos ~]# DASHBOARD_URL=robertqiu
[root@VM-0-10-centos ~]# kubectl apply -n tekton-pipelines -f - <<EOF
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: tekton-dashboard
>   namespace: tekton-pipelines
> spec:
>   rules:
>   - host: robertqiu
>     http:
>       paths:
>       - backend:
>           serviceName: tekton-dashboard
>           servicePort: 9097
> EOF
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
ingress.extensions/tekton-dashboard configured
[root@VM-0-10-centos ~]#
[root@VM-0-10-centos ~]# kubectl --namespace tekton-pipelines port-forward svc/tekton-dashboard 9097:9097
Forwarding from 127.0.0.1:9097 -> 9097
'''
Could you pls let me know the way to visit the deshboard?  My public IP address: 150.109.193.157.
Many thanks in advance!

Best,
Robert Q

**Comment by AlanGreene** [comment]
@qiuxin if you want to make the Dashboard available via your public IP, the value of `DASHBOARD_URL` in the example above (and in the ingress configuration) should be a valid domain name that resolves to that public IP. If you don't have access to such a domain you can use the freely available https://nip.io/ service or something similar, in that case you would have `DASHBOARD_URL=150.109.193.157.nip.io` and you would access it in your browser at http://150.109.193.157.nip.io

After creating / updating the Ingress you may need to wait a few minutes for it to be ready for use. See the instructions in the [nginx ingress controller troubleshooting guide](https://kubernetes.github.io/ingress-nginx/troubleshooting/) for how to check the status / logs and verify the ingress controller is working correctly.

At the end of your example I see you're also running `kubectl port-forward`. This is not required if you're using an Ingress, it provides an alternative method to access the Dashboard if you have access to the cluster via `kubectl`. While the port forward is running you can access the Dashboard in your browser at http://localhost:9097

**Comment by qiuxin** [comment]
I buy a domain name(www.robertqiu.net) and make sure the domain name attached to my cloud virtual machine. You can visit
http://www.robertqiu.net:8080/view/test to double check as well. But still no luck when I visist http://www.robertqiu.net, I throught the dash board will come out when I visist http://www.robertqiu.net. The following is the configuration for ingress.

`[root@robertqiu ~]# DASHBOARD_URL=www.robertqiu.net`
`[root@robertqiu ~]# kubectl apply -n tekton-pipelines -f - <<EOF`
`> apiVersion: extensions/v1beta1`
`> kind: Ingress`
`> metadata:`
`>   name: tekton-dashboard`
`>   namespace: tekton-pipelines`
`> spec:`
`>   rules:`
`>   - host: www.robertqiu.net`
`>     http:`
`>       paths:`
`>       - backend:`
`>           serviceName: tekton-dashboard`
`>           servicePort: 9097`
`> EOF`
`Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`
`ingress.extensions/tekton-dashboard configured`

**Comment by qiuxin** [comment]
More informaiton for troubleshooting.
`[root@robertqiu ~]# kubectl get ing -n tekton-pipelines`
`Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`
`NAME               CLASS    HOSTS               ADDRESS      PORTS   AGE`
`tekton-dashboard   <none>   www.robertqiu.net   172.18.0.2   80      4h28m`

**Comment by AlanGreene** [comment]
Is the Dashboard running and available?
`kubectl get svc tekton-dashboard -n tekton-pipelines`

When you run the kubectl port-forward command can you access the Dashboard at http://localhost:9097 ?
`kubectl -n tekton-pipelines port-forward svc/tekton-dashboard 9097:9097`

Have you followed the steps in the ingress controller troubleshooting guide that I linked in my last comment? https://kubernetes.github.io/ingress-nginx/troubleshooting/

Check the ingress has been created successfully and is ready:
`kubectl get ing -n tekton-pipelines`
`kubectl describe ing tekton-dashboard -n tekton-pipelines`

Check the ingress controller logs for any errors

**Comment by qiuxin** [comment]
[root@robertqiu ~]# kubectl describe ing tekton-dashboard -n tekton-pipelines
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Name:             tekton-dashboard
Namespace:        tekton-pipelines
Address:          172.18.0.2
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host               Path  Backends
  ----               ----  --------
  www.robertqiu.net
                        tekton-dashboard:9097 (10.244.0.11:9097)
Annotations:         <none>
Events:
  Type    Reason  Age                  From                      Message
  ----    ------  ----                 ----                      -------
  Normal  Sync    32m (x5 over 4h37m)  nginx-ingress-controller  Scheduled for sync
  Normal  UPDATE  32m (x4 over 4h36m)  nginx-ingress-controller  Ingress tekton-pipelines/tekton-dashboard

**Comment by qiuxin** [comment]
[root@robertqiu ~]# kubectl get svc tekton-dashboard -n tekton-pipelines
NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
tekton-dashboard   ClusterIP   10.109.36.184   <none>        9097/TCP   23d
[root@robertqiu ~]#

**Comment by qiuxin** [comment]
[root@robertqiu ~]# kubectl get ing -n tekton-pipelines
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
NAME               CLASS    HOSTS               ADDRESS      PORTS   AGE
tekton-dashboard   <none>   www.robertqiu.net   172.18.0.2   80      4h40m
[root@robertqiu ~]#

**Comment by qiuxin** [comment]
[root@robertqiu ~]# kubectl get pods --namespace tekton-pipelines
NAME                                           READY   STATUS    RESTARTS   AGE
tekton-dashboard-56c78f485b-p9mtc              1/1     Running   0          23d
tekton-pipelines-controller-5cdb46974f-4qqc4   1/1     Running   0          23d
tekton-pipelines-webhook-6479d769ff-rnn42      1/1     Running   0          23d
[root@robertqiu ~]#

**Comment by qiuxin** [comment]
I guess this is probably the reason. I do NOT follow the instructions in the link:https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx
Instead, I install the NGINX controller in the way itemized below:
`[root@VM-0-10-centos~]# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx`
`"ingress-nginx" has been added to your repositories`
`[root@VM-0-10-centos ~]# helm repo update`
`Hang tight while we grab the latest from your chart repositories...`
`...Successfully got an update from the "ingress-nginx" chart repository`
`...Successfully got an update from the "stable" chart repository`
`Update Complete. ⎈Happy Helming!⎈`
`[root@VM-0-10-centos ~]# helm install ingress-nginx ingress-nginx/ingress-nginx`

**Comment by qiuxin** [comment]
> kubectl describe ing tekton-dashboard -n tekton-pipelines

I restore my virtual machine and reinstall everything. The way I install Nginx follows https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx.   But still no luck.

`[root@VM-0-3-centos ~]# kubectl wait --namespace tekton-pipelines \`
`>   --for=condition=ready pod \`
`>   --selector=app.kubernetes.io/component=controller \`
`>   --timeout=90s`
`pod/tekton-pipelines-controller-769bcc6996-cgjbq condition met`
`[root@VM-0-3-centos ~]# kubectl wait --namespace tekton-pipelines   --for=condition=ready pod   -`selector=app.kubernetes.io/component=controller   --timeout=90s`
`pod/tekton-pipelines-controller-769bcc6996-cgjbq condition met`
`[root@VM-0-3-centos ~]# kubectl get svc tekton-dashboard -n tekton-pipelines`
`NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE`
`tekton-dashboard   ClusterIP   10.104.100.42   <none>        9097/TCP   3h3m`
`[root@VM-0-3-centos ~]# kubectl get ing -n tekton-pipelines`
`Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`
`NAME               CLASS    HOSTS               ADDRESS   PORTS   AGE`
`tekton-dashboard   <none>   www.robertqiu.net             80      28m`
`[root@VM-0-3-centos ~]# kubectl describe ing tekton-dashboard -n tekton-pipelines`
`Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`
`Name:             tekton-dashboard`
`Namespace:        tekton-pipelines`
`Address:`
`Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)`
`Rules:`
  `Host               Path  Backends`
 `----               ----  --------`
 `www.robertqiu.net`
`                        tekton-dashboard:9097 (10.244.0.12:9097)`
`Annotations:         <none>`
`Events:              <none>`
`[root@VM-0-3-centos ~]# curl www.robertqiu.net`
`curl: (7) Failed connect to www.robertqiu.net:80; Connection refused`
