### ISSUE TITLE
Missing error handling for cancelling a run

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#1884]
We're missing error handling for cancelling a run :see_no_evil:

https://github.com/tektoncd/dashboard/blob/266f8030f92a3d321ba648b1d97512f8c2280dfe/src/containers/PipelineRuns/PipelineRuns.js#L115

_Originally posted by @steveodonovan in https://github.com/tektoncd/dashboard/pull/1877#discussion_r552587809_

**Comment by kobaji** [comment]
Hi @AlanGreene and all,
I thought I should implement it in the same way as the following part, but is it correct?

https://github.com/tektoncd/dashboard/blob/266f8030f92a3d321ba648b1d97512f8c2280dfe/src/containers/PipelineRuns/PipelineRuns.js#L127-L139

If so, our team would try this issue.

**Comment by AlanGreene** [comment]
@kobaji yes a similar approach to that would be good 👍

**Comment by kobaji** [comment]
My team would like to work on this issue.
The document [process.md](https://github.com/tektoncd/community/blob/master/process.md#assigning-yourself-an-issue) says non collaborators like me cannot assign myself, but I'll try to assign haha.

/assign @kobaji
