### ISSUE TITLE
Show a graph view of pipeline in dashboard

### ISSUE THREAD

**Issue by rivlinp** [tektoncd/dashboard#1914]
# Is your feature request related to a problem ?

Currently in tekton dashboard `v0.13.0` for pipelines you dont see a graph like view of what the pipeline would do. You can see this option in projects like circleci or openshift

<img width="937" alt="Screen Shot 2021-01-21 at 8 20 37 PM" src="https://user-images.githubusercontent.com/791799/105432759-48832900-5c26-11eb-85ff-9828a5928b45.png">

# Describe the solution you'd like

Show graph view of the pipeline run.

# Describe alternatives you've considered

None

# Additional context

None

**Comment by AlanGreene** [comment]
Hey @rivlinp, thanks for the feature request. We've already done some work on this and are tracking it in https://github.com/tektoncd/dashboard/issues/675. I'll be updating that issue in the next few weeks with the current plans / new design and we hope to pick it up again soon.

Closing this as a duplicate.
