### ISSUE TITLE
Error handling/display when using the external logs feature

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/dashboard#1918]
Hi,

I just configured our dashboard to use the '--external-logs' feature 🥳. In case the external logs service fails, it currently displays something like `{"timestamp":"2021-01-26T16:22:30.182+00:00","path":"/logs/site-it-mobile/uiveri5-sapitcloud-m7ktl-uiveri5-2sh4x-pod-tq6ts/step-find-uiveri5-config","status":500,"error":"Internal Server Error","message":"","requestId":"df3c9584-16"}`. Visually, you can´t distinguish if this is actually the log output or if something went wrong during log retrieval.

![image](https://user-images.githubusercontent.com/862577/105874339-bfd90400-5ffc-11eb-8652-cd1c5d39b57c.png)

Thanks, Fabian

**Comment by AlanGreene** [comment]
@Fabian-K what version of the Dashboard are you seeing this on? Is your log service returning a non-200 response status when it fails to retrieve the logs?

**Comment by Fabian-K** [comment]
Thanks for the quick reply! We are currently using `v0.12.0`.

I think in this case it ran into a timeout, I´d have to double-check. I can see the following log output of tekton dashboard:

```
{
  "level": "error",
  "ts": 1611674903.1913311,
  "caller": "utils/proxy.go:30",
  "msg": "Failed to execute request: Get \"http://dashboard-logs.loki.svc.cluster.local:8080/logs/site/honeycomb-beekeeper-ci-4q6kh-merge-xzcw6-pod-8btd4/step-merge?\": dial tcp 100.64.251.152:8080: i/o timeout",
  "stacktrace": "github.com/tektoncd/dashboard/pkg/utils.Proxy\n\tgithub.com/tektoncd/dashboard/pkg/utils/proxy.go:30\ngithub.com/tektoncd/dashboard/pkg/endpoints.Resource.LogsProxy\n\tgithub.com/tektoncd/dashboard/pkg/endpoints/externallogs.go:20\ngithub.com/emicklei/go-restful.(*Container).dispatch\n\tgithub.com/emicklei/go-restful@v2.12.0+incompatible/container.go:285\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2042\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2417\ngithub.com/emicklei/go-restful.(*Container).ServeHTTP\n\tgithub.com/emicklei/go-restful@v2.12.0+incompatible/container.go:300\ngithub.com/gorilla/csrf.(*csrf).ServeHTTP\n\tgithub.com/gorilla/csrf@v1.7.0/csrf.go:301\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2843\nnet/http.(*conn).serve\n\tnet/http/server.go:1925"
}
```

**Comment by AlanGreene** [comment]
Thanks for the extra detail. I've confirmed that the client code wasn't correctly handling some error cases, including timeouts, and have a PR with a fix: https://github.com/tektoncd/dashboard/pull/1919

Once that's merged it'll be available in the following nightly release. We may also schedule a 0.13.1 patch release in the next week or so and bundle a few other fixes.
