### ISSUE TITLE
Error loading PipelineRuns  Not Found

### ISSUE THREAD

**Issue by patsevanton** [tektoncd/dashboard#1942]
Hello! Thanks for TektonCD
I try install TektonCD by article https://docs.ventuscloud.eu/docs/tutorials/tekton-pipelines

```
kubectl apply --filename https://storage.googleapis.com/tekton-releases/latest/release.yaml
kubectl apply --filename https://github.com/tektoncd/dashboard/releases/download/v0.14.0/tekton-dashboard-release.yaml
kubectl patch service tekton-dashboard -n tekton-pipelines -p '{"spec": {"type": "NodePort"}}'
```
![image](https://user-images.githubusercontent.com/10828883/108044059-fe963300-706b-11eb-9e92-0194c4c704dc.png)
![image](https://user-images.githubusercontent.com/10828883/108044092-06ee6e00-706c-11eb-91e0-e5bcf2ac7395.png)

- Kubernetes Platform:
Yandex Cloud
- Kubernetes or OpenShift version:
```
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.12", GitCommit:"5ec472285121eb6c451e515bc0a7201413872fa3", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud-provider/provisioner:
Yandex Cloud

**Comment by AlanGreene** [comment]
@patsevanton thanks for reporting this. It looks like that article is quite old and many of the instructions are no longer valid.

To install the latest release of Tekton Pipelines, the correct command is:
`kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml`

(notice the addition of 'pipeline' in the URL)

Once you have the latest Pipelines and Dashboard installed, you can try [accessing the Dashboard](https://github.com/tektoncd/dashboard/blob/master/docs/install.md#accessing-the-dashboard) following one of the options in the docs.

**Comment by patsevanton** [comment]
Thanks!
