### ISSUE TITLE
extension the service resource successfull, but how can I create service on dashboard

### ISSUE THREAD

**Issue by soulseen** [tektoncd/dashboard#1961]
I followed the doc https://github.com/tektoncd/dashboard/blob/master/docs/extensions.md extension the service resource success, but how can I create a service use dashboard.
I can not find any create button on the dashboard.

**Comment by AlanGreene** [comment]
The Tekton Dashboard does not provide the ability to create a Service via the UI, its main focus is to provide a view of and ability to manipulate Tekton resources.

Can you provide some more information about what you're trying to achieve?
