### ISSUE TITLE
Update release pipeline to use workspaces and results

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#1969]
Remove use of PipelineResources, switching to Tasks with workspaces and results instead.

See [tektoncd/pipeline](https://github.com/tektoncd/pipeline/blob/0a08cdca1290423fe176e9facd2e7d9396a7c65c/tekton/release-pipeline.yaml) and [tektoncd/operator](https://github.com/tektoncd/operator/blob/e12d59a388f11c906ae359b74f339797d29db495/tekton/operator-release-pipeline.yaml) release pipelines for example.

It may also make sense to adopt some of the other improvements to the release pipeline such as using `crane cp` instead of `gcloud images add-tag`.

Also see `https://github.com/tektoncd/triggers/pull/1000`

**Comment by AlanGreene** [comment]
Also need to update template for nightly release: https://github.com/tektoncd/plumbing/blob/2c1808d75b38d6fcaae0a37f5a9dda50545af4c8/tekton/resources/nightly-release/overlays/dashboard/template.yaml

See Pipelines / Triggers equivalent for reference.

**Comment by AlanGreene** [comment]
Hey @nikhil-thomas, have you had a chance to look at updating the Dashboard release pipeline yet? No worries if you haven't, I was just wondering if you had run into any problems or had any questions about it.

**Comment by nikhil-thomas** [comment]
hi, i haven't started on it yet. I shall definitely pick it up this week. 🧑‍💻 👍

**Comment by AlanGreene** [comment]
This is done. Nightly releases are successfully using the new pipeline and are signed with Chains 🎉 

The v0.22 release (due next week) will also use this new pipeline and be signed.
