### ISSUE TITLE
Syntax highlighting for YAML display

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#1972]
# Is your feature request related to a problem ?

Large blocks of YAML can be difficult to scan quickly.

# Describe the solution you'd like

Add syntax highlighting for the `ViewYAML` component to make it easier to read.

We could use something like [`react-syntax-highlighter`](https://www.npmjs.com/package/react-syntax-highlighter) to achieve this. It's already used by [tektoncd/hub](https://github.com/tektoncd/hub/blob/eae5fc9461c451ea77b6c9745af5460d4db9c4c7/ui/src/components/Yaml/index.tsx).

Can we adapt our existing colour palette from the `LogFormat` component to work here or is there a suitable preset theme we can use that matches the Dashboard reasonably well (with or without tweaking)?

# Describe alternatives you've considered

https://www.npmjs.com/package/highlight.js
https://www.npmjs.com/package/prismjs

`react-syntax-highlighter` has support for both of these and provide a nice React API.

# Additional context

**Comment by wingyplus** [comment]
I've tried it with the atom dark theme.

<img width="1667" alt="Screen Shot 2564-04-28 at 22 20 13" src="https://user-images.githubusercontent.com/484530/116429267-ee6eb100-a86f-11eb-8058-0c1edc5f54f4.png">

After I try to fix the background color to match with previous output. It become:

<img width="1673" alt="Screen Shot 2564-04-28 at 22 50 43" src="https://user-images.githubusercontent.com/484530/116433965-3263b500-a874-11eb-9bb2-ab5fec525119.png">

This is diff that I try (I'm not expert at JS and CSS but I try my best):

```diff
diff --git a/packages/components/package.json b/packages/components/package.json
index 87e3fa3..a14045e 100644
--- a/packages/components/package.json
+++ b/packages/components/package.json
@@ -4,7 +4,12 @@
   "author": {
     "name": "The Tekton Authors"
   },
-  "keywords": ["tekton", "tektoncd", "components", "react"],
+  "keywords": [
+    "tekton",
+    "tektoncd",
+    "components",
+    "react"
+  ],
   "license": "Apache-2.0",
   "private": false,
   "main": "./dist/components/index.js",
@@ -26,6 +31,7 @@
     "linkify-it": "^3.0.2",
     "prop-types": "^15.7.2",
     "react-intl-formatted-duration": "^4.0.0",
+    "react-syntax-highlighter": "^15.4.3",
     "react-window": "^1.8.5",
     "tlds": "^1.208.0"
   },
diff --git a/packages/components/src/components/ViewYAML/ViewYAML.js b/packages/components/src/components/ViewYAML/ViewYAML.js
index d651142..582113e 100644
--- a/packages/components/src/components/ViewYAML/ViewYAML.js
+++ b/packages/components/src/components/ViewYAML/ViewYAML.js
@@ -15,6 +15,8 @@ import React from 'react';
 import PropTypes from 'prop-types';
 import jsYaml from 'js-yaml';
 import classNames from 'classnames';
+import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
+import { atomDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
 
 import './ViewYAML.scss';
 
@@ -30,6 +32,18 @@ const ViewYAML = props => {
       <code>
         <pre>{jsYaml.dump(resource)}</pre>
       </code>
+
+      <SyntaxHighlighter
+        language="yaml"
+        useInlineStyles={true}
+        className={classNames('bx--snippet--multi', className, {
+          'tkn--view-yaml--dark': dark
+        })}
+        style={atomDark}
+        codeTagProps={{}}
+      >
+        {jsYaml.dump(resource)}
+      </SyntaxHighlighter>
     </div>
   );
 };
diff --git a/packages/components/src/components/ViewYAML/ViewYAML.scss b/packages/components/src/components/ViewYAML/ViewYAML.scss
index d31731d..649b1a1 100644
--- a/packages/components/src/components/ViewYAML/ViewYAML.scss
+++ b/packages/components/src/components/ViewYAML/ViewYAML.scss
@@ -14,6 +14,6 @@ limitations under the License.
 @import '~carbon-components/scss/globals/scss/vars';
 
 .bx--snippet--multi.tkn--view-yaml--dark {
-  background-color: $gray-90;
-  color: $gray-10;
+  background-color: $gray-90 !important;
+  color: $gray-10 !important;
 }
```

I want to hear your feedback about this. I can send a PR with some tweaks. :)

**Comment by wingyplus** [comment]
I'll pick this issue and show the prototype to see the feedback.

**Comment by AlanGreene** [comment]
Thanks @wingyplus. There's also some discussion in the Carbon Design System (which we use for our underlying base styles and components) about syntax highlighting so it might be worth checking that and keeping an eye on progress: https://github.com/carbon-design-system/carbon-website/issues/965

**Comment by wingyplus** [comment]
> Thanks @wingyplus. There's also some discussion in the Carbon Design System (which we use for our underlying base styles and components) about syntax highlighting so it might be worth checking that and keeping an eye on progress: [carbon-design-system/carbon-website#965](https://github.com/carbon-design-system/carbon-website/issues/965)

@AlanGreene Thanks for pointing to the issue. So we need to pause the work until that issue resolve right?

**Comment by AlanGreene** [comment]
I've added a comment to that issue asking for an update and can follow up internally in IBM if we don't hear anything back soon. Let's see if we get a response in the next couple of days and we can decide where to go from there.

In the short term we could make the syntax highlighting optional (and disabled by default) so the YAML component could still be used by 3rd party consumers of the Dashboard components without affecting styles, and we could then enable it only when used in the Dashboard application itself.

**Comment by wingyplus** [comment]
That's sounds great. How about we start putting `react-syntax-hightlight` and add attribute something like `syntaxHighlightEnabled` to the `ViewYAML` to toggle the color?

**Comment by AlanGreene** [comment]
Sounds good 👍 Let's go with `enableSyntaxHighlighting` for the prop name.

**Comment by wingyplus** [comment]
Wow. Finally it’s landed. 🎉

**Comment by AlanGreene** [comment]
Thank you for your work on this @wingyplus, it made finally enabling this much easier 😸
