### ISSUE TITLE
Pagination in Tekton Dashboard UI

### ISSUE THREAD

**Issue by hprateek43** [tektoncd/dashboard#1978]
# Is your feature request related to a problem ?
Tekton UI becomes unresponsive if a large number of pipelineruns or taskruns exist in a namespace.

We use tekton to run github checks for our org. We create close to 200 pipelineruns everyday, and even more task runs in a common namespace. The tekton UI takes a long time to load, and crashes and becomes unresponsive on a frequent basis. The solution is cleaning up the pipelineruns, which we dont want as we want to retain data for atleast a week.

# Describe the solution you'd like
Tekton dashboard should support pagination. Users should have control on how many pipelineruns should be visible in a page, as well as sorting pipelineruns by date.

The dashboard should introduce pagination as bottom, and a date filter.

# Describe alternatives you've considered

# Additional context

**Comment by hprateek43** [comment]
@bobcatfish cc

**Comment by AlanGreene** [comment]
Thanks for the feature requet @hprateek43. We agree that this is very important and it's come up a number of times in the past and been discussed at length at various working group meetings. Ultimately we're limited by the Kubernetes API in terms of the level of sorting / filtering we can provide, see previous issue tracking this here https://github.com/tektoncd/dashboard/issues/842

When the number of resources on the cluster becomes very large it's not just the Dashboard that's affected, any tool that queries resources can be affected, including `kubectl`. For our dogfooding cluster we run nightly cleanup to remove older resources and keep the numbers in check, see for example https://github.com/tektoncd/plumbing/blob/main/tekton/cronjobs/dogfooding/cleanup/tekton-ci-nightly/cronjob.yaml

With the introduction of the new Tekton Results project we will have access to a more flexible / powerful API to query for resources and should have an opportunity to introduce pagination and more advanced filtering when that integration is available. Work on integrating Results is being tracked in https://github.com/tektoncd/results/issues/82 for now. Closing this issue.
