### ISSUE TITLE
UI crashes when showing a PipelineRun with a PipelineResource error

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#198]
# Expected Behavior
When I selected the link to view my PipelineRun that had failed, I expected it to show the logs view where I could debug what went wrong with my PipelineRun.
![Screen Shot 2019-05-29 at 4 19 27 PM](https://user-images.githubusercontent.com/16961496/58588406-9404ea00-822d-11e9-802a-8332f3ac3f2b.png)

# Actual Behavior
Instead, my view went completely blank, and I got some errors:
![Screen Shot 2019-05-29 at 4 20 47 PM](https://user-images.githubusercontent.com/16961496/58588494-c57db580-822d-11e9-9576-5ab4b3883348.png)
Here are the logs from the Chrome inspector (they're unformatted, so it might be easier to recreate the issue and view the logs in the browser inspector): [error-report-pipelinerun-view.txt](https://github.com/tektoncd/dashboard/files/3234311/error-report-pipelinerun-view.txt)

# Steps to Reproduce the Problem

1. Create a PipelineRun with a PipelineResource that does not exist (I input a `gitresource` that did not exist). This was my PipelineRun creation request:
```
dataPipelineRun='{
  "pipelinename": "simple-pipeline",
  "serviceaccount": "default",
  "namespace": "default",
  "gitrepositoryurl": "https://github.com/ncskier/go-hello-world",
  "gitresource": "na"
}'
curl -d "${dataPipelineRun}" -H "Content-Type: application/json" -X POST http://localhost:9097/v1/namespaces/default/pipelineruns
```
2. Open the Dashboard
3. Click the link to view the logs for your failed PipelineRun

**Comment by jessm12** [comment]
https://github.com/tektoncd/dashboard/pull/214 PR to fix this, may want to do a more functional change than this in the future

**Comment by a-roberts** [comment]
Merged, closing 🎉
