### ISSUE TITLE
Add Collapsable Log Sections

### ISSUE THREAD

**Issue by stevesoaress** [tektoncd/dashboard#1980]
# Is your feature request related to a problem ?

Provide the ability for job logs to be divided into sections that can be collapsed or expanded.  Travis and Gitlab CI have good examples. 

# Describe the solution you'd like

Sample raw job log: 
```
\e[0Ksection_start:1560896352:my_first_section\r\e[0KHeader of the 1st collapsible section
this line should be hidden when collapsed
\e[0Ksection_end:1560896353:my_first_section\r\e[0K
```

This example would create 1 collapsible job section. The difference in timestamps would display the time taken to run the commands in the section. 

See https://docs.gitlab.com/ce/ci/jobs/#expand-and-collapse-job-log-sections for examples OR 
https://blog.travis-ci.com/2013-05-22-improving-build-visibility-log-folds

**Comment by AlanGreene** [comment]
Thanks for the feature request @stevesoaress. I'm not sure if this is something that makes sense to implement specifically for the Dashboard. One of the reasons I think GitLab and Travis can do this is that they control the full end to end experience and can manipulate the log content to inject their magic strings at the desired boundaries (command, stage, etc.) to be displayed by their own UI which supports these.

With Tekton things are a little different. The user may use any number of clients to view details of their runs, including the logs. In some cases Tekton may not be exposed directly and instead used as the underlying engine (e.g. as in Jenkins X). Supporting a feature like this would require additional effort and agreement by more interested parties as Tekton does not necessarily control the full end to end experience. Even for the parts that Tekton does control, it's quite unopinionated about how you write the scripts that run in your steps. Mandating a particular format for logs seems like a bit of a leap from what we have today.

The implementations by GitLab and Travis are specific to their own products, there doesn't seem to be agreement on a standard approach / format. Do Octant, other alternative kubernetes UIs, or other CI/CD systems support anything like this?

**Comment by stevesoaress** [comment]
I think this would have to be specific to the Tekton dashboard client and not other clients or tools like Jenkins X.  Adding collapsible sections shouldn't be mandated and would benefit users that want to easily navigate in the tekton dashboard log viewer.  

Github Actions seems to support something similar as well but there doesn't seem to be a standard approach /format. https://github.com/actions/toolkit/blob/master/docs/commands.md#group-and-ungroup-log-lines

Feel free to close it if you think this isn't suitable for now.

**Comment by AlanGreene** [comment]
Closing this since it would be Dashboard specific, require changes to the way logs are produced in users' steps (not always possible or desired), and produce unwanted noise in the logs for other clients.

**Comment by jkremser** [comment]
Imho not having this feature kills the UX of the dashboard a lot. Basically any long enough pipeline makes finding the right place a nightmare :D
