### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by Hokwang** [tektoncd/dashboard#1982]
Hi,

I have some(?) tr, prs.
```
$ tkn pr list -n tekton-trivy | wc -l
2865
$ tkn tr list -n tekton-trivy | wc -l
2843
```
I think this is quite small numbers.

when access dashboard first, it is pr page. here's few seconds waiting.
and then I click tr page. chrome shows below alert message.
![image](https://user-images.githubusercontent.com/1247030/110924251-2c1d8600-8365-11eb-8ce9-da3e5c79d45c.png)

I edited dashboard deployment resources like
```
        resources:
          requests:
            cpu: "1"
            memory: 4Gi
```
but it does not work.

If you need more information, please let me know.

- Kubernetes Platform:
vanilla kubernetes
- Kubernetes or OpenShift version:
v1.17.17
- Install mode (if on OpenShift):
no-operator
- Cloud-provider/provisioner:
baremetal
- Versions:
   - Tekton Dashboard:
v0.14.0
   - Tekton Pipelines:
v0.22.0
   - Tekton Triggers:
v0.12.0
- Install namespaces:
   - Tekton Dashboard:
tekton-pipelines
   - Tekton Pipelines:
tekton-pipelines
   - Tekton Triggers:
tekton-pipelines

**Comment by AlanGreene** [comment]
Thanks for raising this issue. It's a known problem at the moment, see this comment from yesterday for more details: https://github.com/tektoncd/dashboard/issues/1978#issuecomment-796636018

The Tekton Results project will give us more flexibility in querying the resources than the existing Kubernetes API which does not support pagination or advanced filtering.

Closing this for now, integration of Tekton Results is being tracked in https://github.com/tektoncd/results/issues/82
