### ISSUE TITLE
Dashboard works very slow when I have more than 100 taskRuns/pipelineRuns

### ISSUE THREAD

**Issue by cybul7** [tektoncd/dashboard#2035]
# Describe the bug
When I have more than ~100 taskRuns/pipelinesRuns then dashboard works very very slow. It loads taskRuns/pipelineRuns page ~5-10 seconds.

# Expected behaviour

It should load faster.

# Environment details

- Kubernetes Platform:
 k3s
- Kubernetes version:
 v1.18.8+k3s1
- Versions:
   - Tekton Dashboard:
   v.0.16.1
   - Tekton Pipelines:
   v0.24.1
   - Tekton Triggers:
   v0.13.0
- Install namespaces:
   - Tekton Dashboard:
   tekton-pipelines
   - Tekton Pipelines:
   tekton-pipelines
   - Tekton Triggers:
   tekton-pipelines

# Additional Info

I don't know if I have problem with hardware or if it is something else. 
I have k3s cluster with 2 nodes (64GB of ram and 8 vCPU each one), and there is only tekton running.

**Comment by AlanGreene** [comment]
Thanks for reporting this issue. The loading times you're reporting certainly seem excessive for about 100 TaskRuns / PipelineRuns.

For comparison, on our [dogfooding cluster](https://dashboard.dogfooding.tekton.dev/) which we use for Tekton's own CI/CI, we have:
- ~700 PipelineRuns, loading in ~3s
- ~1700 TaskRuns, loading in <5s

Of course these times will depend on your machine's specs, your network connection, and the load on your cluster.

We do have some work in progress to improve the performance of the Dashboard by breaking the requests into smaller chunks but I wouldn't expect to see 5-10s for only 100 resources.

Can you share some more information about the times you're seeing? If you open your browser's developer tools and take a look at the network tab you should see some additional information on the request timing, sizes, etc. This would be helpful information to narrow down where the issue might be for your environment.

**Comment by uqix** [comment]
I want to share our numbers:

* PipelineRun: 1267
* TaskRun: 10956
* Avg PipelineRun details page load time: ~6s

<img width="996" alt="image" src="https://github.com/tektoncd/dashboard/assets/10142314/cd7607fa-aceb-428b-b910-e0d7e3df979e">

**Comment by uqix** [comment]
Maybe we can cache the response of those finished runs.
