### ISSUE TITLE
Layout shifts when adding / removing filters on list pages

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#2050]
# Describe the bug

The content below the filter shifts up / down slightly (maybe 1 or 2px) as filters are removed / added.

# Expected behaviour

Content should be positioned consistently and layout shouldn't shift as I'm using the Dashboard.

# Steps to reproduce the bug

- Navigate to https://dashboard.robocat.tekton.dev/#/pipelineruns
- In the same tab, navigate to https://dashboard.robocat.tekton.dev/#/namespaces/tutorial/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dtutorial-pipeline (paste into the address bar or click 'tutorial-pipeline' in the Pipeline column)
- Switch back and forth between these pages using the browser back/forward buttons and see the layout shift slightly

# Environment details

- Versions:
   - Tekton Dashboard: `main`

# Additional Info

![May-21-2021 16-21-23](https://user-images.githubusercontent.com/2829095/119160939-aac32d80-ba50-11eb-8519-adfc965e7900.gif)

**Comment by wingyplus** [comment]
I try inspecting this issue. It seems `min-height` is not enough. After I change from `2px` to `4px`. The issue is disappear.

<img width="479" alt="Screen Shot 2564-05-25 at 18 32 18" src="https://user-images.githubusercontent.com/484530/119491069-b7fd5680-bd87-11eb-9fd4-aa3bc3cd2e4d.png">

**Comment by wingyplus** [comment]
I see that it use `calc(#{$spacing-08} + #{$button-border-width})`. If I understand it correctly, `button-border-width` come from lib `carbon`, right?. Maybe it doesn't fit with filter tag?

**Comment by AlanGreene** [comment]
> `button-border-width` come from lib `carbon` which is 2px value, right?

yes that's right, it's defined here https://github.com/carbon-design-system/carbon/blob/30d28f9e4c87d0494fc2e098dfef6a842adf88d0/packages/components/src/globals/scss/_theme-tokens.scss#L228

**Comment by wingyplus** [comment]
I guess that because of tag and clear all button is quite bigger a little bit. The workaround might increase the `min-height` offset (~2px) on the `tkn--filters` can be fixed.

What do you think?

**Comment by AlanGreene** [comment]
yes that seems reasonable 👍
