### ISSUE TITLE
Fix container prefix in Tekton

### ISSUE THREAD

**Issue by vtereso** [tektoncd/dashboard#206]
As mentioned by @AlanGreene, Tekton recently changed the container prefix. Since this is an unexported field, everything relying upon this will break and needs to reflect the recent [change](https://github.com/tektoncd/pipeline/commit/3d87e2e18174f1d7b088bdd14065d5f06ef86462).

**Comment by AlanGreene** [comment]
Once https://github.com/tektoncd/pipeline/issues/1027 is resolved we can remove the hardcoded prefix and read the container name from the container status.

Until then, change the prefix to reflect the value used in the Tekton 0.5 release.
