### ISSUE TITLE
Update to Carbon 10.36

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#2067]
Update to the latest Carbon release (10.36) once available. There's currently a pre-release available so the official release should be available in the next day or so.

https://github.com/carbon-design-system/carbon/releases

When updating we need to ensure our tests still pass and that there's no functional regression or unwanted style changes in the UI.

**Comment by LyndseyBu** [comment]
updated will be included as part of https://github.com/tektoncd/dashboard/pull/2084/files

**Comment by wingyplus** [comment]
The carbon design was released to 10.37. Do we need to upgrade it?

**Comment by AlanGreene** [comment]
Hi @wingyplus. We updated to 10.36 in https://github.com/tektoncd/dashboard/pull/2084 which was merged yesterday, and I just spoke to @LyndseyBu about the 10.37 release this morning. We have a few other updates to make but will probably consider Carbon 10.37 as part of those too :+1:

Closing this issue now since the original requirement to move to 10.36 is complete.

/close
