### ISSUE TITLE
Add support for stopping and starting a PipelineRun created with status 'PipelineRunPending'

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#2069]
# Is your feature request related to a problem ?

If I create a PipelineRun with status 'PipelineRunPending' it appears in the Dashboard but I am unable to either stop or start it. The only options available are 'Rerun' and 'Delete'. The 'Stop' option is disabled and there's no 'Start' option provided at all.

# Describe the solution you'd like

The 'Stop' option should be enabled for these pending runs.
There's should be a new 'Start' option provided.

# Describe alternatives you've considered

# Additional context

![image](https://user-images.githubusercontent.com/2829095/119863258-494c0480-bf11-11eb-8c73-ba5f3c662890.png)

The API is the same as the existing 'Stop' action for PipelineRuns that are in the running state.
https://tekton.dev/docs/pipelines/pipelineruns/#pending-pipelineruns

> To start the PipelineRun, clear the .spec.status field. Alternatively, update the value to PipelineRunCancelled to cancel it.

**Comment by lilley2412** [comment]
Wondering if it makes sense to not use stop and have a new action "Cancel" to be consistent with the pending pipeline functionality and status?

When a pipelineRun is in the pending state, the options are to start or cancel (and of course delete):

> To start the PipelineRun, clear the .spec.status field. Alternatively, update the value to PipelineRunCancelled to cancel it.

I actually came here looking for an a feature to _start_ a pending pipelineRun from the action menu.  Would it make sense to implement cancel and start under a single issue, or would you prefer I open a new feature request?

**Comment by AlanGreene** [comment]
Using 'Cancel' as the action name was problematic in the past as it's the same as the option to dismiss the confirmation dialog, so that's why we originally went with 'Stop', otherwise we end up with something like this:

![image](https://user-images.githubusercontent.com/2829095/122673618-1ff95e00-d1c9-11eb-8ca0-5b887ace329b.png)

I think we'll have to revisit this anyway given the new [graceful termination alpha feature](https://github.com/tektoncd/community/blob/0ccd5f907bde2452f76330bf5f7bf8a0a14e8bf2/teps/0058-graceful-pipeline-run-termination.md) added in Pipelines v0.25 which provides three different ways to terminate a PipelineRun, differentiating between 'Stop' and 'Cancel'.

> - "StoppedRunFinally" - To stop (i.e. let the tasks complete, then execute finally tasks) a PipelineRun
> - "CancelledRunFinally" - To cancel (i.e. interrupt any executing non finally tasks, then execute finally tasks)
> - "Cancelled" - replaces today's "PipelineRunCancelled" - i.e. interrupt any executing tasks without running finally tasks
>
> Support for existing statuses has been left unchanged. The status "PipelineRunCancelled" is deprecated and replaced by "Cancelled" (it would be removed in v1). The new states are released as alpha API features.

We can track that in a separate issue since there's a little more involved, and keep this one specifically for the 'PipelineRunPending' cases.

> Would it make sense to implement cancel and start under a single issue

Yes I think so. I'll update the title and description of this issue to cover both :+1:

**Comment by lilley2412** [comment]
Thanks for the context @AlanGreene , makes sense to me.  I have this implemented locally for the pipelineRun page, but not for the action menu.  Happy to finish it if someone else isn't working on it already.

**Comment by AlanGreene** [comment]
@lilley2412 that would be great, thanks 🙏

**Comment by AlanGreene** [comment]
This was added in #2106, thanks @lilley2412
/close
