### ISSUE TITLE
View yaml doesn't expand to full content of tab

### ISSUE THREAD

**Issue by wingyplus** [tektoncd/dashboard#2083]
# Describe the bug

When I click status tab from task in pipeline run. I found that view yaml expand to the end of yaml content with no right padding or expand to full content of status tab content.

Screenshot capture from my local machine, test against my company cluster:

<img width="1632" alt="Screen Shot 2564-06-08 at 13 48 32" src="https://user-images.githubusercontent.com/484530/121137557-f81d0880-c860-11eb-83a1-e95ad9b0125d.png">

The another example in dogfood site https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelineruns/publish-catalog-tekton-lj7rr?pipelineTask=git-clone&step=clone&view=status.

# Expected behaviour

View YAML should have the right padding or expand to status tab content. Not sure which one should have.

# Steps to reproduce the bug

1. Click pipeline run.
2. Select pipeline run in the list.
3. Click task in pipeline run 
4. Click `Status` tab.

# Environment details

Tested on dashboard main branch revision `1f29bc533bc58fa0f966696128dcc59f19e8514d`.

# Additional Info

This may be related to #2071 according to change the implementation of the ViewYAML component.

**Comment by AlanGreene** [comment]
The ViewYAML component uses the `bx--snippet--multi` styles from the [Carbon Design System](https://www.carbondesignsystem.com/) code snippet component, this is to ensure consistency in styling with the rest of the UI. Carbon sets a max-width of 48rem for this component.

We could choose to override this in the Dashboard styles and allow it to expand to the full width of its container.

**Comment by wingyplus** [comment]
Thanks for your guide. Let me take a look at it tomorrow. :D
