### ISSUE TITLE
Add a configmap which contains dashboard version

### ISSUE THREAD

**Issue by sm43** [tektoncd/dashboard#2089]
Currently, we fetch version of dashboard through labels present on the
deployments which is read by tools such as `tkn` cli and display the
version. This version may not be displayed to users if they don't have
permission to view the deployment.

So, to allow all authenticate users to fetch dashboard version, add a configmap
and necessary role to access it.

This is part of [TEP-0041](https://github.com/tektoncd/community/blob/main/teps/0041-tekton-component-versioning.md).

Similarly, this is implemented in [Pipelines](https://github.com/tektoncd/pipeline/pull/3971) and [Triggers](https://github.com/tektoncd/triggers/pull/1114).

**Comment by cpanato** [comment]
Can i try this one?

**Comment by AlanGreene** [comment]
@sm43 thanks for opening the issue, this was on my list but I hadn't gotten around to opening an issue for it yet 👍 

@cpanato yes of course, please let me know if you have any questions.
