### ISSUE TITLE
Update README to install latest docker image

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#211]
A dashboard image `gcr.io/tekton-nightly/dashboard:latest` built from the last good build on master is now available for download. 

- Add a new kube.yaml document that installs the latest image
- Make this yaml available via a GitHub release of dashboard
- Update the installation section of the Readme to indicate that users can `kubectl apply -f https://url.to.released.kube.yaml`

**Comment by vtereso** [comment]
https://github.com/tektoncd/dashboard/pull/216

**Comment by a-roberts** [comment]
https://github.com/tektoncd/dashboard/pull/216 is now merged, closing 😄
