### ISSUE TITLE
Move About to the bottom of the SideNav

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#2115]
Move the link to the About page to the bottom of the SideNav component so it's positioned consistently regardless of other items that are conditionally displayed (e.g. Triggers resource links, Import resources, extensions)

In future we may add a 'Settings' page, so having this positioned consistently will be important, especially if we restore the SideNav rail behaviour when collapsed (waiting for a Carbon fix). This is also a very common pattern in other applications, where settings / help etc. are located at the bottom of the side nav.

Also ensure all links are reachable when using a large font setting (OS / browser settings) or the browser is zoomed in (200%).

**Comment by taechonkim** [comment]
@AlanGreene Hi :) 
I haven't found reference that you said as 'common pattern'.
Where can I find reference site that you said as 'common pattern'? (help/settings menu placed bottom)

**Comment by AlanGreene** [comment]
> I haven't found reference that you said as 'common pattern'.
Where can I find reference site that you said as 'common pattern'? (help/settings menu placed bottom)

Here are some examples from popular apps / services showing either a settings / profile option at the bottom of the nav, or other useful links separate from the main navigation items.

<div>
<img alt="Twitter navigation" src="https://user-images.githubusercontent.com/2829095/126526988-a349cde7-ba47-4cf7-bd88-febbca05db6e.png" width="200px" />
<img alt="Discord navigation" src="https://user-images.githubusercontent.com/2829095/126527014-6c03827a-2005-427c-832c-0fca89f64219.png" width="200px" />
<img alt="CodeSandbox navigation" src="https://user-images.githubusercontent.com/2829095/126527069-efb0daa6-e0a3-4349-b605-931dfd0e8e59.png" width="200px" />

<img alt="Spotify navigation" src="https://user-images.githubusercontent.com/2829095/126527090-03cb4399-ca15-4c27-bdf5-c87c114bef81.png" width="200px" />
<img alt="GMail navigation" src="https://user-images.githubusercontent.com/2829095/126527149-17c3793d-2194-4d23-9984-ca53498b1b8c.png" width="200px" />
<img alt="Google Cloud Platform navigation" src="https://user-images.githubusercontent.com/2829095/126527184-fc6b9c31-acd6-4d90-97a3-007fce1dd36b.png" width="200px" />
</div>

**Comment by taechonkim** [comment]
> > I haven't found reference that you said as 'common pattern'.
> > Where can I find reference site that you said as 'common pattern'? (help/settings menu placed bottom)
> 
> Here are some examples from popular apps / services showing either a settings / profile option at the bottom of the nav, or other useful links separate from the main navigation items.
> 
> <img alt="Twitter navigation" width="200px" src="https://user-images.githubusercontent.com/2829095/126526988-a349cde7-ba47-4cf7-bd88-febbca05db6e.png"> <img alt="Discord navigation" width="200px" src="https://user-images.githubusercontent.com/2829095/126527014-6c03827a-2005-427c-832c-0fca89f64219.png"> <img alt="CodeSandbox navigation" width="200px" src="https://user-images.githubusercontent.com/2829095/126527069-efb0daa6-e0a3-4349-b605-931dfd0e8e59.png"> <img alt="Spotify navigation" width="200px" src="https://user-images.githubusercontent.com/2829095/126527090-03cb4399-ca15-4c27-bdf5-c87c114bef81.png"> <img alt="GMail navigation" width="200px" src="https://user-images.githubusercontent.com/2829095/126527149-17c3793d-2194-4d23-9984-ca53498b1b8c.png"> <img alt="Google Cloud Platform navigation" width="200px" src="https://user-images.githubusercontent.com/2829095/126527184-fc6b9c31-acd6-4d90-97a3-007fce1dd36b.png">

@AlanGreene Thanks for reply :) 
I worked on an issue yesterday using flexbox, justify-content properties.
I checked GCP console, it uses flexbox, flow-grow properties. 
Please check if (https://github.com/tektoncd/dashboard/pull/2139) you have time :) Thank you
