### ISSUE TITLE
Move display of PipelineResources from StepDetails to TaskRunDetails

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#2116]
PipelineResources are specified at the Task level, not at the step level, and this should be reflected in the UI.

Our current display of Input / Output PipelineResources in the StepDefinition component should be moved to a 'Resources' tab in the TaskRunDetails component, between the existing 'Parameters' and 'Results' tabs.

**Note:** the `showIO` prop in the PipelineRun component should be respected so that the new TaskRunDetails tab will only be displayed when `showIO === true`, and the prop should also be set in the TaskRun container.

**Comment by taechonkim** [comment]
@AlanGreene Hi I want to work on this issue, I'll appreciate to assign to me 🙂

**Comment by AlanGreene** [comment]
Thanks @taechonkim, feel free to work on this. Let me know if you have any questions.

**Comment by taechonkim** [comment]
@AlanGreene Hi Alan :) I worked on this issue at https://github.com/tektoncd/dashboard/pull/2135
It would be appreciated if you could check it out. 
And, I wonder how can i trigger prow test jobs. (pull-tekton-dashboard-***-tests)
I look forward to hearing from you. :) 
Thank you 🙂

**Comment by AlanGreene** [comment]
Closed by #2135
