### ISSUE TITLE
Add timestamps fo console log

### ISSUE THREAD

**Issue by hokadiri** [tektoncd/dashboard#2145]
# Is your feature request related to a problem ?
Lack of timestamps in console log makes it impossible to know how long each command run making it difficult to profile & find bottlenecks in a step

# Describe the solution you'd like
Include timestamps to console log outputs.

# Describe alternatives you've considered
Prepending each cmd line call with [moreutils](http://joeyh.name/code/moreutils/)

# Additional context
[sample dogfood console showing no timestamp](https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelineruns/publish-catalog-tekton-vjvdg?pipelineTask=git-clone&step=clone)
![Screen Shot 2021-07-26 at 8 01 45 AM](https://user-images.githubusercontent.com/678342/127011711-4f2d1077-d215-4fbe-9daf-257aa81e63f8.png)

**Comment by AlanGreene** [comment]
Thanks for the feature request @hokadiri.

This should be relatively straightforward to add as a preference in the UI. The Kubernetes API already supports this and we just need to pass the correct query param on the request for the logs (`&timestamps=true`).

We're already working on a settings UI for dark mode, so it would make sense to include this preference in the same place.

/assign
