### ISSUE TITLE
Dynamic discovery of extensions with a listener

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#215]
# Expected Behavior

We shouldn't need extensions to be running before the dashboard pod starts.  We should be able to start up some extension when the dashboard is already running and the dashboard should find the extension.

The dashboard looks for service with the relevant annotation in order to register the extension, this could be replaced with a listener that discovers new extensions/updates to extensions.

# Actual Behavior

Currently deploying or updating an extension requires the dashboard pod to be restarted in order for the extension be available.

**Comment by vtereso** [comment]
https://github.com/tektoncd/dashboard/pull/259

**Comment by vtereso** [comment]
Merged.

**Comment by AlanGreene** [comment]
@dibbles @vtereso can this be closed or is there more work remaining? Are we planning any updates to notify the front end of changes to extensions?

**Comment by vtereso** [comment]
I don't have close permissions, but I believe it should be fine to do so. @dibbles is out until Wednesday IIRC

**Comment by AlanGreene** [comment]
We can always reopen / create a new one if needed 👍
