### ISSUE TITLE
external-logs broken since 0.19.0

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/dashboard#2168]
# Describe the bug

We use the --external-logs feature to retrieve logs. This was working fine, however, it stopped working after we upgraded to 0.19.0. Our log service does not seem to receive any requests any more.

Looking at the network tab of the browser, I can see a request to `proxy/api/v1/namespaces/site-tpt/pods/uiveri5-bsw6l-uiveri5-f22xp-pod-pss2b/log?container=step-uiveri5` returning 404 with

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "pods \"uiveri5-bsw6l-uiveri5-f22xp-pod-pss2b\" not found",
  "reason": "NotFound",
  "details": {
    "name": "uiveri5-bsw6l-uiveri5-f22xp-pod-pss2b",
    "kind": "pods"
  },
  "code": 404
}
```

And following a request to `/v1/logs-proxy/site-tpt/uiveri5-bsw6l-uiveri5-f22xp-pod-pss2b/step-uiveri5` also returning 404 with `404 page not found`

The UI just displays `Unable to fetch log`

Let me know if you need more information!

Thanks, Fabian

# Environment details
- Versions:
   - Tekton Dashboard: `0.19.0`

**Comment by Fabian-K** [comment]
We have Istio running in the cluster and expose the dashboard via a `VirtualService`

**Comment by mike-sirs** [comment]
I can confirm, we have the same issue with external logs.

**Comment by AlanGreene** [comment]
Fix was merged and will be available in the next nightly build.
