### ISSUE TITLE
Support displaying a subset of resources

### ISSUE THREAD

**Issue by dippynark** [tektoncd/dashboard#2172]
There are a few issues similar to this but none of them are quite suitable for our use case.

# Describe the solution you'd like

We are running a platform, using Tekton Pipelines to drive the automation, and we want to expose PipelineRun logs to each customer without them being able to see the logs of other customers. The simplest way I could see of achieving this is supporting a Tekton Dashboard flag to filter the resources it displays (e.g. using a label selector) and run a Dashboard instance per customer (guarding access to each instance using external authentication/authorisation).

# Describe alternatives you've considered

If Dashboard authentication/authorisation/permissions was supported, we could specify what each user/group is allowed to view, however this sounds like significantly more work.

Kubernetes RBAC based authorisation would not work for us since it can only go to Namespace granularity and all of our pipelines run in the same Namespace (and it'd be tedious to create a Namespace per customer).

**Comment by AlanGreene** [comment]
Thanks for the feature request @dippynark however this is not something the Tekton Dashboard will support directly. The Dashboard relies on Kubernetes RBAC for access control, and using label selectors is not possible. A number of the reasons for this are discussed in detail in https://github.com/kubernetes/kubernetes/issues/44703, https://github.com/kubernetes/kubernetes/issues/56582, https://github.com/kubernetes/kubernetes/issues/93845#issuecomment-671610700, https://github.com/openshift/origin/pull/8610#issuecomment-369237224, and many other similar issues.

The recommendation from Kubernetes' sig-auth is to either grant access to a particular set of named resources, or all instances of that resource in a namespace.

If you want to implement custom access controls you may be interested in https://kubernetes.io/docs/reference/access-authn-authz/webhook/, however this presents its own problems.

If a user is given access to 'list' resources of a given kind, this includes all instances of that kind (potentially namespace-scoped), not just those granted by your custom rules. As a result the 'list' verb would have to be denied. This presents obvious problems for discoverability as any UI would need to know the full set of resources in advance and request them individually or implement an alternative mechanism to retrieve lists of resources to display to the user based on their current permissions / labelling. This is not something the Dashboard will be pursuing in the core application.

In the near future we will be working on integration with tektoncd/results as an alternative back end for loading historical resources, however that project also relies on Kubernetes RBAC for access control. As part of that work we may consider a plugin-based approach to consuming alternative APIs for the resources, leaving the question of access control up to the API provider.

Closing this feature request.

/close
