### ISSUE TITLE
Update the design and content of the About page

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#2243]
Update the design and content of the about page to provide more useful information to the user and make better use of the available space.

We should continue to provide information about the Tekton projects installed in the cluster (Dashboard, Pipelines, Triggers) as well as any particular configuration of interest, e.g. Dashboard read-only mode.

It would also be helpful to provide additional information, such as links to Tekton documentation or other resources that may benefit the user.

**Comment by kamilzal** [comment]
### Final outcome
Assets:

1. **[robocat_zoom.svg.zip](https://github.com/tektoncd/dashboard/files/7660720/robocat_zoom.svg.zip)**
2.  **[pictograms.zip](https://github.com/tektoncd/dashboard/files/7660753/pictograms.zip)**


<img width="1312" alt="home_1" src="https://user-images.githubusercontent.com/35368089/144847603-00e1db36-e2db-4edd-962e-2a5834ad9e81.png">
---
</br>

### Spacing and Alignment

<img width="1312" alt="home_2" src="https://user-images.githubusercontent.com/35368089/144847613-7e335eb7-63b5-4b4e-b846-968d9811b03d.png">
---
</br>

### Text sizes

<img width="1312" alt="home_3" src="https://user-images.githubusercontent.com/35368089/144847619-29f77b0d-25e0-45d1-a287-7c23e2de330a.png">
---
</br>

### Cards details

<img width="1312" alt="home_4" src="https://user-images.githubusercontent.com/35368089/144847622-c3b224cc-f03d-4db6-a07b-d375bc9177b5.png">

**Comment by AlanGreene** [comment]
PR #2264 open to implement most of this. The tiles for the docs links are slightly different in that PR but we will revisit this early in the new year to fully implement the remainder of the design.

**Comment by AlanGreene** [comment]
Just a few small pieces remaining as described in the previous comment.
/remove-lifecycle stale
