### ISSUE TITLE
Update error page

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#2244]
Update and unify our current error handling to display more useful content to the user in case they hit a bad link, or try to access some feature or resource to which they do not have access.

This will be particularly useful when we make more progress on https://github.com/tektoncd/dashboard/issues/1420 and related issues.

**Comment by kamilzal** [comment]
### **Final outcome**
Assets: **[robocat_404.svg.zip](https://github.com/tektoncd/dashboard/files/7660707/robocat_404.svg.zip)**


<img width="1312" alt="404_1" src="https://user-images.githubusercontent.com/35368089/144846077-f2f614b3-92f2-4187-adbe-79213e613361.png">
---

### **Illustration size @ 1312px width**

<img width="1312" alt="404_2" src="https://user-images.githubusercontent.com/35368089/144846092-d67d7798-4a88-4a63-9c01-110056eb6343.png">
---

### **Text and Spacing**

<img width="1312" alt="404_3" src="https://user-images.githubusercontent.com/35368089/144846095-5d35f77f-4e9f-4bb1-8134-ba3c9f1efcaf.png">
---

### **Alignment**

1. Align text to columns.
2. Align illustration to start at the middle of gutter between 2 columns.
3. Grouping of illustration + message should be centered inside the content area.

<img width="1312" alt="404_4" src="https://user-images.githubusercontent.com/35368089/144846099-4271e0a8-f40f-42a6-8d00-4102e3bac92f.png">
