### ISSUE TITLE
Error state briefly shows before loading state when opening PipelineRun or TaskRun

### ISSUE THREAD

**Issue by briangleeson** [tektoncd/dashboard#2247]
# Describe the bug
When opening a PipelineRun or TaskRun (and possibly other resources), the error state briefly shows on the page before the loading state takes effect, and then the pages finishes loading. 

# Expected behaviour
We shouldn't render any error state when opening a resource until after all the loading has been completed

# Steps to reproduce the bug

1. Click on the link to open a PipelineRun or TaskRun
2. Observe the error box that appears momentarily

# Environment details

- Kubernetes Platform:

- Kubernetes or OpenShift version:

- Install mode (if on OpenShift):

- Cloud-provider/provisioner:

- Versions:
   - Tekton Dashboard:
   
   - Tekton Pipelines:
   
   - Tekton Triggers:
   
- Install namespaces:
   - Tekton Dashboard:
   
   - Tekton Pipelines:
   
   - Tekton Triggers:
   

# Additional Info

**Comment by AlanGreene** [comment]
One issue resolved by https://github.com/tektoncd/dashboard/pull/2311/files#diff-deb04a3e9f6cab68fd916aa300983e5a7f4dcc2773b7734d0b4faa306c3d338aL39
However there's still an issue with a brief error flash during the loading state on both PipelineRun and TaskRun pages.

/remove-lifecycle stale
