### ISSUE TITLE
Interactive debug shell for TaskRun 

### ISSUE THREAD

**Issue by waveywaves** [tektoncd/dashboard#2268]
# Is your feature request related to a problem ?

No, it's related to a the debug feature in Tekton Pipelines.

# Describe the solution you'd like

The UI for the debug shell would look something similar to the GCP's cloud shell.
1. Make it possible for users to run/rerun a TaskRun after enabling the following spec via a button called (rerun with debug enabled: on failure).
```
spec:
  debug:
    breakpoints: ["onFailure"]
``` 
2. If halted at a step, user should be able to mark the step as a success or a failure and continue the step from there. Currently there is no indication by the TaskRun controller (via TaskRunStatus) to show that the TaskRun has been halted due to failure. 
3. Button allowing user to open a debug shell via a button (with a shell icon) located beside currently running step.

# Describe alternatives you've considered

TBD

# Additional context

- https://tekton.dev/docs/pipelines/debug/

**Comment by AlanGreene** [comment]
Closing as this is not something we're currently planning to add. We may revisit this in future.
