### ISSUE TITLE
Times on the dashboard are too imprecise to be useful

### ISSUE THREAD

**Issue by daira** [tektoncd/dashboard#2276]
The PipelineRuns view has a "Created" column which says, for example, "yesterday" for any creation time between... well, I don't know exactly. Is it between 24 and 48 hours ago, or yesterday as a calendar day? In which timezone? In any case it's not very useful, and I can't see any way to get a more precise time. Even the page for the specific PipelineRun just says "yesterday" in this case.

Example of what this ends up looking like in practice:
![image](https://user-images.githubusercontent.com/643204/148764896-7be6a007-bd05-40ed-ba8a-dc85d5a78e69.png)

Ideally, just change this, and all other timestamps in the dashboard to minute or second precision in ISO 8601 or RFC 3339 format, either with explicit timezone or always in UTC.

If you really must show relative time (which is a bad idea IMHO), then:
* make the threshold for using day precision *at least* 48 hours ago; and
* show the absolute timestamp (as described above) when mousing over the field, or have a toggle to switch between absolute and relative time.

**Comment by AlanGreene** [comment]
Thanks for raising the issue @daira and sharing your feedback and opinion.

> show the absolute timestamp (as described above) when mousing over the field

This is how it's currently implemented. Anywhere in the Dashboard UI that a relative time is displayed, you can hover over it to see a tooltip with the full date/time.

We originally displayed the full date/time by default but switched to relative times based on overwhelming user feedback.

**Comment by str4d** [comment]
An alternative could be to use "hours ago" as the metric for any relative times that would currently show up as "yesterday"; that would give 24-48x more granularity than at present, while keeping the UX spirit of the current relative time display.
