### ISSUE TITLE
Dashboard doesn't work on localhost with Safari

### ISSUE THREAD

**Issue by doctorpangloss** [tektoncd/dashboard#2299]
# Describe the bug

Visiting a proxied or forwarded `localhost` path to view the dashboard shows an error in Safari:

`Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.`

# Expected behaviour

You should be able to visit the dashboard in `localhost` on Safari.
# Steps to reproduce the bug

```
kubectl --namespace tekton-pipelines port-forward svc/tekton-dashboard 9097:9097
open http://localhost:9097
```

Observe the error `Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.`

# Environment details

- Kubernetes Platform: Amazon EKS
- Kubernetes or OpenShift version: v1.21
- Cloud-provider/provisioner: EKS
- Versions:
   - Tekton Dashboard: v0.24.0
   - Tekton Pipelines: main
   - Tekton Triggers: main
- Install namespaces:
   - Tekton Dashboard: tekton-pipelines
   - Tekton Pipelines: tekton-pipelines
   - Tekton Triggers: tekton-pipelines

# Additional Info

Works fine in Chrome.

**Comment by AlanGreene** [comment]
Thanks for reporting the issue @doctorpangloss. I haven't been able to reproduce it as you described, i.e. I'm not seeing any Content Security Policy related errors. However, I did reproduce a different issue preventing the page from loading in Safari and should have a fix for that soon, related to an update in one of our transitive dependencies that's not compatible with Safari. Perhaps the same update will address your issue 🤞 

Just in case it doesn't, can you share some more info that may help debug further?
- macOS version
- Safari version
- did previous Dashboard releases work in this same browser for you?

**Comment by AlanGreene** [comment]
Fix for the issue I mentioned is available in the latest nightly build: https://storage.googleapis.com/tekton-releases-nightly/dashboard/latest/tekton-dashboard-release.yaml

Hopefully this will fix your issue too and we'll do a v0.24.1 patch release later today with this change once testing is complete.

**Comment by AlanGreene** [comment]
v0.24.1 release is out now: https://github.com/tektoncd/dashboard/releases/tag/v0.24.1

Let me know if this resolves your issue.

**Comment by doctorpangloss** [comment]
Problem solved on Safari thank you

**Comment by AlanGreene** [comment]
Thanks for confirming and apologies for the disruption 🙏
