### ISSUE TITLE
Would like to see old logs at least for 24 hours past

### ISSUE THREAD

**Issue by alhazred** [tektoncd/dashboard#232]
# Expected Behavior
Possibility to view all pipelines/logs at least for the current day and the previous one

# Actual Behavior
only when related pods are live

# Steps to Reproduce the Problem

1. jx start pipeline foo
2. would like to see logs for any run for a day for example
3. "Unable to fetch log" or even "Error loading pipeline run  "Not Found" for old runs after some time

# Additional Info
I understand that pods has a short live time but would be nice to keep their logs at least for last 24 hours

**Comment by AlanGreene** [comment]
https://github.com/tektoncd/pipeline/issues/107 is tracking a proposal that may be of interest for persistence of logs

**Comment by alhazred** [comment]
It seems like solid approach, thanks

**Comment by mnuttall** [comment]
Hi @alhazred thank you for raising this. The dashboard currently shows logs for as long as the associated PipelineRun and TaskRun objects exist. Deleting those objects deletes the logs. If tektoncd/pipeline#107 leads to a general persistence mechanism then we'll have to decide whether or not dashboard should use it.

**Comment by arzarif** [comment]
Seems like the linked ticket has been closed in favor of standard pod log collection practices. Given that centralized log collection can vary from implementation to implantation, what recourse would the dashboard have as far as being able to present historical data?

**Comment by AlanGreene** [comment]
This could be an interesting one to watch: https://github.com/tektoncd/experimental/tree/master/results

**Comment by eddycharly** [comment]
Why not add something like `ExternalAgentLogs` in prow ?

**Comment by eddycharly** [comment]
/assign
Related PR https://github.com/tektoncd/dashboard/pull/1586

**Comment by AlanGreene** [comment]
Logs can be persisted externally and displayed in the dashboard after the pods have been deleted by following https://github.com/tektoncd/dashboard/blob/master/docs/walkthrough/walkthrough-logs.md
