### ISSUE TITLE
Add a Fallback function to read External Pod Specs just like what we did for external log

### ISSUE THREAD

**Issue by TianxiangShen** [tektoncd/dashboard#2323]
# Is your feature request related to a problem ?

Hi Community, I recent setup a external log server to provide logs when original logs are not available. But I noticed in most cases when pod logs are missing, the Pod's Specs are also missing (maybe due to the pod is deleted). Since now Tekton dashboard can only fetch external Logs, I think it's better to add a method to fetch External Pod Specs because sometimes Pod Specs can be really useful when debugging a taskrun/pipelinerun failure. (for example, we missconfigure the args of a container)

# Describe the solution you'd like

As similar to `ExternalLogsURL`, we can add a fallback function `useExternalPodURL` when the original function `usePod` failed to get the pod specs.

# Describe alternatives you've considered

# Additional context

**Comment by AlanGreene** [comment]
Thanks for the feature request @TianxiangShen. The external logs support is still experimental and subject to change, so any future integration of external sources may not take the same form as the logs solution and there are other considerations in terms of caching, client processing, etc. that are not applicable to logs in the same manner.

Right now I would be reluctant to start adding support for loading individual resource types from some other external source as this could quickly become unmanageable, both in terms of the code/maintenance overhead in the Dashboard and ensuring correct authentication/authorization on the part of the provider(s).

For long-term storage of non-log resources we're most likely going to leverage [Tekton Results](https://github.com/tektoncd/results). Integration between Results and Dashboard is being tracked in https://github.com/tektoncd/results/issues/82 and is on the roadmap.

**Comment by TianxiangShen** [comment]
Thanks for the reply, I remember Tekton Results doesn't support Pod's Specs storage right, please correct me if I'm wrong.
