### ISSUE TITLE
Minishift dashboard install instructions unclear

### ISSUE THREAD

**Issue by jessm12** [tektoncd/dashboard#235]
Came across when working #212 

# Expected Behavior

For it to be trivial to install the dashboard on Minishift following the instructions at https://github.com/tektoncd/dashboard#install-on-minishift

# Actual Behavior

In attempting to install the dashboard on Minishift following these instructions I have hit a few problems and haven't yet managed to install and access the dashboard successfully. I think the documentation could do with a bit more detail e.g. how can I access the dashboard, there is also an error with the name of the build file being .yml as opposed to .yaml 

@Gl4di4torRr as you added the work for this install I was hoping you might be able to give me some guidance please 😅I am new to using openshift/Minishift and I was unsure on some steps, for example accessing the dashboard after install and how I could debug the install effectively. Any help you could give would be much appreciated! 

# Steps to Reproduce the Problem

1. Follow the install instructions at https://github.com/tektoncd/dashboard#install-on-minishift
2. Try to access your dashboard install 

# Additional Info

From `oc status` command

```
http://tekton-dashboard-openshift-pipelines-operator.192.168.64.2.nip.io to pod port dashboard (svc/tekton-dashboard)
  dc/tekton-dashboard deploys istag/tekton-dashboard:latest <-
    bc/tekton-dashboard docker builds https://github.com/tektoncd/dashboard.git#master 
      not built yet
    deployment #1 waiting on image or update
```
Is there an additional step to trigger this image/update?

At the `route` endpoint

<img width="1152" alt="Screenshot 2019-06-11 at 11 21 31" src="https://user-images.githubusercontent.com/32932155/59264538-36b06600-8c3b-11e9-9759-3a245bfeaca4.png">

**Comment by Gl4di4torRr** [comment]
@jessm12 I walked back through the steps... I found two items that were an issue.

1. `build.yml` should be `build.yaml`
2. There is no [trigger](https://docs.openshift.com/container-platform/3.5/dev_guide/builds/triggering_builds.html) on the [build config](https://github.com/tektoncd/dashboard/blob/master/config/templates/build.yml) so I had to manually click the build button to start a build. 

I will open a PR for these two issues. Hope this helps! :)

**Comment by jessm12** [comment]
Thanks @Gl4di4torRr that's great! I just noticed the `trigger` issue when I was investigating what was going on and trying to understand all the different resources that are created 😅

**Comment by Gl4di4torRr** [comment]
@jessm12 yep! i'll clean up my git history later today so we can get the PR merged and this issue resolved.

**Comment by a-roberts** [comment]
@CarolynMabbott suggests we can close this now as we've merged https://github.com/tektoncd/dashboard/pull/338 and I agree, let us know if it's still unclear and we'll reopen - thanks all 🎈
