### ISSUE TITLE
logs are not streaming/updating in realtime

### ISSUE THREAD

**Issue by Ben-Mark** [tektoncd/dashboard#2373]
# Describe the bug
when I open a taskRun, the logs aren't streaming in real time, i see the logs only when the step is completed

# Expected behaviour
I expect the logs to be streamed and updated in real time , out of the box..

# Steps to reproduce the bug
install the latest tekton dashboard version ... 

# Environment details

- Kubernetes Platform:
aws eks (managed)
- Kubernetes or OpenShift version:
kubernetes version 1.21

- Cloud-provider/provisioner:
EKS
- Versions:
   - Tekton Dashboard:
     v0.25.0
   - Tekton Pipelines:
   0.34.1
   - Tekton Triggers:
  0.19.1
- Install namespaces:
   - Tekton Dashboard: tekton-pipelines
   - Tekton Pipelines: tekton-pipelines
   - Tekton Triggers: tekton-pipelines

# Additional Info
streamLogs is true from the main.go options
is there any other flags i need to enable?

**Comment by AlanGreene** [comment]
Can you share more details about how you installed the Dashboard and how you're accessing it? e.g.:
- which release manifest / install method did you use?
- any customisations to RBAC / the Dashboard deployment?
- are you accessing via `kubectl port-forward`, `kubectl proxy`, Ingress, etc.?

I haven't been able to reproduce the problem with v0.25 or newer on Kubernetes 1.21 - 1.23.

**Comment by Ben-Mark** [comment]
I use my own custom install via dockerfile, instead of the ko/go docker creation/deployment
the dashboard has a cluster-admin role connected to its serviceAccount
I'm accessing via kubectl portforward only 

All other functionalities are working great except for the logs streaming in real time
Do I need any other component for that requirement ?

**Comment by Ben-Mark** [comment]
**I can confirm that the link you sent shows that the logs are streaming in in real-time.**
I went further and debugged the fetchLogs function, it has streaming enabled 
but still from the dashboard, i see the react skeleton loader waiting for the logs to load

I'll dig more, I'll probably get to the root cause

soon to update

**Comment by Ben-Mark** [comment]
Got some progress, 

It appears that via the localhost:9097/api/v1... I'm able to see the logs streaming but not via localhost:8000/api/v1...

When the dashboard executes that via the proxy through for example from my dev webserver on localhost:8000/api/v1 
The logs are not seen, and the browser is loading until all of the logs are there..

Given this new progress I'm focused now on the proxy area where it looks like to be the case

will update..

**Comment by AlanGreene** [comment]
@Ben-Mark I've opened a PR to resolve the issue with log streaming via the webpack-dev-server: https://github.com/tektoncd/dashboard/pull/2376

Let me know if that works for you.
