### ISSUE TITLE
Tekton pipeline should support a task with an drop-down option.

### ISSUE THREAD

**Issue by sagaraivale** [tektoncd/dashboard#2374]
# Is your feature request related to a problem ?

Suppose, my tekton pipeline consists of cascade connection of multiple builds and deploy tasks. Now, I need to build/deploy only one task from the pipeline, then there should be a drop-down task option. Where users can select one specific build app and next deploy that app to a specific env etc. 

# Describe the solution you'd like

There will be an option in tekton pipeline where users can select a particular task option based on a drop-down menu. 

# Describe alternatives you've considered

# Additional context

**Comment by AlanGreene** [comment]
Thanks for the feature request @sagaraivale but I'm not quite sure I follow what you're asking for. Can you elaborate on your use case and/or provide an example of how you expect a user to use this in the Tekton Dashboard? It would also be helpful if you used the feature request issue template, I've updated the description to include it.

Tekton `Pipeline` resources define a graph of `Task`s to execute. You can use [when expressions](https://tekton.dev/docs/pipelines/pipelines/#guard-task-execution-using-when-expressions) to conditionally execute `Task`s only when certain conditions are met. These conditions could be based on `PipelineRun` params, results of previous `Task`s etc. Is this what you're trying to achieve?

**Comment by andrewpolemeni** [comment]
This would be a rather easy feature to support. It's just a list of options and just iterate over it. We should be able to provide a parameter list. Jenkins is able to do this with no issues.

**Comment by AlanGreene** [comment]
Thanks for your interest in this feature @andrewpolemeni.

This is not something the Dashboard is currently planning to support. The Dashboard today provides a view of the current state of Tekton resources on the cluster, and provides a few options for interacting with them, for example deleting resources, basic options for creating runs, etc. however it is not intended to be a full-blown CI/CD hub. You can think of it more like a Tekton-focused version of something like the Kubernetes Dashboard.

As mentioned in [a previous response to a similar request](https://github.com/tektoncd/dashboard/issues/2259#issuecomment-985429447), Tekton Dashboard relies on the Tekton CRDs for the data it displays. It does not have its own storage etc., so while adding a dropdown in the UI is indeed easy, providing the data to populate that dropdown is much more involved.

If you believe there would be use in having something like enum support for params, you could start a discussion / issue in the [tektoncd/pipeline](https://github.com/tektoncd/pipeline) repo with more details of your use case to gauge interest, gather feedback, etc. You could also join us on [Slack](https://github.com/tektoncd/community/blob/main/contact.md#slack) and post in some of the relevant channels to see if there are other approaches people have taken that may be of use to you.

You can also formally propose an enhancement to Tekton Pipelines, more details about the process at https://github.com/tektoncd/community/blob/main/process/README.md#proposing-features

**Comment by AlanGreene** [comment]
A new TEP was added a few days ago proposing enum params: https://github.com/tektoncd/community/pull/1072
Feel free to comment on that pull request if the proposal does not address your use case or if you have any other input on the design of the feature.

**Comment by sagaraivale** [comment]
Hey @andrewpolemeni : Thanks for adding your comment here! @AlanGreene : making enum params will also help show the drop-down option. I will check the MR and will update you. Meanwhile, thanks for putting these links here, appreciate it!
