### ISSUE TITLE
Custom Trigger Information for PipelineRuns

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/dashboard#2390]
# Is your feature request related to a problem?

Since [0.27.0](https://github.com/tektoncd/dashboard/releases/tag/v0.27.0) the PipelineRun list shows trigger information in case the run was created using tekton triggers. This is cool, however not all PipelineRuns are created via triggers. I´m thinking of cron jobs (although there is an example of how to do that via triggers as well) or any other client, maybe even just `kubectl create`. For those PipelineRuns, the dashboard does not show trigger information.

# Describe the solution you'd like

It would be cool to be able to attach trigger information which is then displayed by the dashboard to any PipelineRun. Maybe a certain annotation that - if present - is displayed?

# Describe alternatives you've considered

n/a

# Additional context

![image](https://user-images.githubusercontent.com/862577/174802789-2c23b78b-995f-4672-b0c7-5d283031b5f9.png)

Thanks, Fabian

**Comment by AlanGreene** [comment]
Thanks for the feature request @Fabian-K. Can you please update the description to use the feature request issue template provided? https://raw.githubusercontent.com/tektoncd/dashboard/main/.github/ISSUE_TEMPLATE/feature-request.md

This helps us to understand the motivation behind a request, the problem it's addressing, alternative that might be considered, etc.

This template should be presented when you create a new issue and choose 'Feature request' from the provided options.
