### ISSUE TITLE
REST API for creating PipelineRuns

### ISSUE THREAD

**Issue by jessm12** [tektoncd/dashboard#24]
Under this issue add a REST API endpoint that will take parameters and create a new `PipelineRun` for a specified `Pipeline`

When creating a new `PipelineRun` the information that will need to be provided to the POST method is as follows:

- The name of the `Pipeline` to use for that `PipelineRun`
- Information relating to the `PipelineResources` for a `PipelineRun`, if required 
- Information relating to the repository for that `PipelineRun`
- Helm and Registry secret names, if required

The request will be namespaced and this is the namespace that the PipelineRun will occur in

**Comment by a-roberts** [comment]
/assign

I've worked on this too with @jessm12 and we should have a PR coming up soon for folks to try and test 😸

**Comment by a-roberts** [comment]
Merged, thanks all for taking a look too 🎉 we're adding the API definition next.
