### ISSUE TITLE
Document permissions setup for resources access by Dashboard

### ISSUE THREAD

**Issue by jessm12** [tektoncd/dashboard#240]
Came across while investigating #212 

# Expected Behavior

Our docs should advise users how to setup the required access control to allow them to run the dashboard and see their Tekton resources in the UI

# Actual Behavior

In order to view Tekton resources through the dashboard, the service account that it is running under must have the relevant permissions against it to access Tekton resources -  for example the `tekton-pipelines-controller` has these permissions set against it, Clusterroles and Bindings. 

When I was trying to get the dashboard up and running on Minishift following https://github.com/tektoncd/dashboard#install-on-minishift the default service account was used and no resources were displayed as it didn't have the permissions to get Tekton resources. 

# Steps to Reproduce the Problem

1. Install on Minishift or any environment using a service account that doesn't have the required permissions to access Tekton resources 
2. Observe the the errors in fetching the resources

**Comment by a-roberts** [comment]
@steveodonovan and I were discussing Openshift/Minishift permissions just now, he's pointed out his changes [here](https://github.com/tektoncd/dashboard/pull/268/files#diff-6ce617087fa9cd260ef0f682b7602619R1) should certainly be of use - I'd try running with said cluster role/binding etc

**Comment by steveodonovan** [comment]
@CarolynMabbott We might have some overlap here. This access is a prerequisite for the proxy. Complete in the PR below but still needs testing on openshift

https://github.com/tektoncd/dashboard/pull/268/files#diff-6ce617087fa9cd260ef0f682b7602619R1

**Comment by a-roberts** [comment]
I've tested this on OpenShift and all is well with roles I've added for the extension and that we've modified for the dashboard, gonna close this off, cheers all
