### ISSUE TITLE
Is is possible to embed dialog box and features of extensions within tekton dashboard?

### ISSUE THREAD

**Issue by hillbun** [tektoncd/dashboard#2412]
I install of automatiko-approval-task, an extension of tekton (https://github.com/automatiko-io/automatiko-approval-task)

Is is possible to embed dialog box and features of extensions within tekton dashboard?  tekton resource or extension menus.

**Comment by mswiderski** [comment]
essentially this would mean to have more advanced support for custom tasks as automatiko-approval-task is an implementation of custom task. 
What we are looking for is to have some standard contract that implementation of custom tasks could provide so dashboard could render it to make the interaction with these tasks more integrated.

I think there were some points on the roadmap to tackle it but not sure if there was any work done so far?

**Comment by AlanGreene** [comment]
Thanks for raising this feature request.

Custom task support is being tracked in https://github.com/tektoncd/dashboard/issues/1970, however no real work has been done on this so far. As you mentioned and as discussed on that issue, a solution for this would likely require custom task developers to provide content to handle display of their runs.

If you have a proposal or any suggestions please add it to that issue so we can keep related conversations together.
Closing this to avoid forking the discussion.
