### ISSUE TITLE
Document release processes for Dashboard

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/dashboard#2428]
Document what the release process looks like:

- the release manager role
- how version numbers are used and their meaning
- the release frequency 
- the steps to perform a major and a minor release

Include the links to existing / new documents in the issue.

**Comment by AlanGreene** [comment]
See https://github.com/tektoncd/pipeline/pull/5586 for reference.

We currently maintain a list of releases at https://github.com/tektoncd/dashboard/blob/3e024f742d957bea83f23c0f2fb8a38ebb4b9b6c/docs/README.md#which-version-should-i-use and document legacy releases in https://github.com/tektoncd/dashboard/blob/3e024f742d957bea83f23c0f2fb8a38ebb4b9b6c/docs/legacy-releases.md. We'll need to update these following the new LTS process (EOL dates etc.) and should probably restructure them to simplify maintenance (combine into a single doc? future automation?).

Steps to perform major and minor releases are at https://github.com/tektoncd/dashboard/tree/main/tekton#readme
