### ISSUE TITLE
can dashboard display pipelinerun tasks diagram similar to gitlab pipeline?

### ISSUE THREAD

**Issue by hillbun** [tektoncd/dashboard#2432]
can dashboard display pipelinerun tasks diagram similar to gitlab pipeline?

**Comment by AlanGreene** [comment]
Not yet but it's on the roadmap and we have some work already done and tracked in https://github.com/tektoncd/dashboard/issues/675

You can find some examples of the most recent explorations in https://54h4e.csb.app/
![image](https://user-images.githubusercontent.com/2829095/188110565-e2b15edd-ff2f-4a60-b60a-42adc133743c.png)
![image](https://user-images.githubusercontent.com/2829095/188110632-23096bc1-7e5a-4a30-a609-7a07fb5c9dd8.png)
