### ISSUE TITLE
Back-end to create a PipelineResource

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#246]
Implement a POST API endpoint for creating a PipelineResource.

PipelineResources are now viewable in the front-end (https://github.com/tektoncd/dashboard/pull/234). A new API endpoint is required for front-end paneling to create new PipelineResources.

**Comment by vtereso** [comment]
@steveodonovan has an [outstanding PR](https://github.com/tektoncd/dashboard/pull/268) to add a proxy to the kube api, which allows us to leverage its functionality rather than adding things into the dashboard.

**Comment by vtereso** [comment]
We should be able to close this one out? @ncskier @a-roberts

**Comment by a-roberts** [comment]
Yeah let's do that
