### ISSUE TITLE
v0.29.x has a regex in the `vendors` chunk which causes a `SyntaxError` in Safari

### ISSUE THREAD

**Issue by jbg** [tektoncd/dashboard#2465]
# Describe the bug

After upgrading from `v0.28.0` to `v0.29.1`, the Tekton Dashboard fails to load in Safari 16 (a blank page is shown). Disabling cache doesn't help. I haven't tried other browsers.

The following error appears in the JS console:

```
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
	(anonymous function) (vendors.4cad84fe7cb5fd068c1a.js:2)
```

Downgrading to `v0.29.0` does not help, but downgrading to `v0.28.0` resolves the problem.

`vendors.4cad84fe7cb5fd068c1a.js` is minified and there doesn't seem to be a source map, but downloading it and running it through prettier and then using a response override to get the browser to run the formatted version reveals the location of the syntax error, which is in this regex:

```
/(?<!\b(?:[a-z][a-z\d+\-.]{1,50}:))\/{2,}/g
```

Pasting this regex into Safari's JS console gives the same `SyntaxError`, but Chrome's JS console accepts it just fine.

# Expected behaviour

The dashboard loads and no `SyntaxError` is found in the JS console.

# Steps to reproduce the bug

1. Upgrade to `v0.29.0` or `v0.29.1`
2. Open the dashboard in Safari

# Environment details

- Kubernetes Platform: Amazon EKS
- Kubernetes or OpenShift version: `v1.23.7-eks-4721010`
- Versions:
   - Tekton Dashboard: `v0.29.1`
   - Tekton Pipelines: `v0.39.0`
   - Tekton Triggers: `v0.21.0`
- Install namespaces:
   - Tekton Dashboard: `tekton-pipelines`
   - Tekton Pipelines: `tekton-pipelines`
   - Tekton Triggers: `tekton-pipelines`

**Comment by jbg** [comment]
The issue is probably the lookbehind, which is [not supported by any version of Safari yet](https://caniuse.com/js-regexp-lookbehind).

**Comment by AlanGreene** [comment]
Thanks for reporting this @jbg. We had a similar issue earlier in the year and put a fix in place to pin the affected dependency to a supported version: https://github.com/tektoncd/dashboard/pull/2300

That fix is still in place but either doesn't appear to be working any more or this is now coming from a different package. I'll take a look later today, hopefully an easy fix and we'll publish a patch release 🤞

**Comment by AlanGreene** [comment]
A new patch release with the fix should be available in about an hour, I'll post here once it's ready.

**Comment by AlanGreene** [comment]
https://github.com/tektoncd/dashboard/releases/tag/v0.29.2

Let us know if you run into any more issues.

**Comment by jbg** [comment]
Thanks, it works great!
