### ISSUE TITLE
Front-end paneling to create a PipelineResource

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#247]
Add paneling to create a new PipelineResource.

This issue depends on issue https://github.com/tektoncd/dashboard/issues/246.

PipelineResources are now viewable in the front-end (#234). Use the back-end API endpoint from issue https://github.com/tektoncd/dashboard/issues/246 to create paneling for creating a new PipelineResource.

**Comment by carlos-logro** [comment]
@AlanGreene after seeing the front-end for the pipelineResources, I assume that this issue can be done with an add button & a modal form just like all the other work that has been done right?

**Comment by AlanGreene** [comment]
Is there a design for this or description of the intention? There are a number of different PipelineResource types with their own sets of required and optional fields so this could be quite a complex UI depending on how it's approached
 https://github.com/tektoncd/pipeline/blob/master/docs/resources.md

**Comment by carlos-logro** [comment]
@AlanGreene don't think there is a design at the moment. And as for a description of the intention probably @ncskier can give us a better overview. 

Now, I had in mind something similar to the add new secret modal where with a some inline logic based on the users inputs components appear or disappear to fully get all the necessary information for the particular resource the user chose.

**Comment by carlos-logro** [comment]
since this issue is not priority at the moment, ill be unassigning myself 

/unassign @carlos-logro
