### ISSUE TITLE
Docker Extension for Tekton Dashboard

### ISSUE THREAD

**Issue by amyb12345** [tektoncd/dashboard#2495]
# Is your feature request related to a problem ?

No, Docker Extension users have been reaching out to us as they'd like to see an extension for Tekton Dashboard in our Marketplace. 

# Describe the solution you'd like

Docker Extensions are a way to integrate additional functionality and tools into Docker Desktop. Developers using Docker Desktop have been requesting that an extension be built for Tekton Dashboard. Docker Extensions have an [open SDK](https://github.com/docker/extensions-sdk) and can be built by anyone. We'd love to see one created to help improve developers workflows. The Docker Extensions team is available to help support anyone interested in building this extension. We can be reached via [email](mailto:extensions@docker.com), on [our community form](https://forums.docker.com/) or on our [SDK repo](https://github.com/docker/extensions-sdk).

# Describe alternatives you've considered

N/A

# Additional context

I'm the product manager for Docker Extensions.

**Comment by AlanGreene** [comment]
Thanks for the feature request @amyb12345. Can you share some more details to help us understand what users are looking for here?

- What features / functionality are users expecting to see in such an extension?
- How is the extension expected to be used in their use case / workflow?
- What are the benefits of an extension over the current development environment?

If possible it would be great to point these users at this issue so they can comment directly rather than you acting as a relay.

**Comment by AlanGreene** [comment]
Can you please also clarify the following requirements I've found in the Docker Desktop Extensions documentation:

> We require extensions to match the wider Docker Desktop UI to a certain degree, and reserve the right to make this stricter in the future.
>
> …
> 1. Choose your framework
> …
> Not recommended: Some other framework
> You may prefer to use another framework, perhaps because you or your team are more familiar with it or because you have > existing assets you want to reuse. This is possible, but highly discouraged. It means that:
>
> You’ll need to manually replicate the look and feel of Docker Desktop. This will take a lot of effort, and if you don’t match our theme closely enough, users will find your extension jarring and we may ask you to make changes during a review process.
> You’ll have a higher maintenance burden. Whenever Docker Desktop’s theme changes (which could happen in any release), you’ll need to manually change your extension to match it.
> If your extension is open-source, deliberately avoiding common conventions will make it harder for the community to contribute to it.

Reading this it sounds like a Tekton Dashboard extension would need to provide an entirely new UI to comply with these requirements, or at the very least invest significant effort in producing and maintaining a custom theme compatible with the Docker Desktop Extension styleguide.

Have I understood this correctly?

**Comment by amyb12345** [comment]
@AlanGreene  I've reached out to the users requesting this extension and asked them to contribute to this issue answering the questions that you've outlined above!  I definitely agree that we'll have a better end product if they contribute rather than having me act as a relay!

As for the request, it is not driven by Hacktoberfest.  In product, we have a link for users to make suggestions on what other extensions they'd like to see in the Marketplace. It's a text field where users are free to suggest what they'd like.  We've had several users request Tekton Dashboard as an extension so we thought it made sense to follow up.  Our goal is to help developers who use Docker Desktop achieve a better developer experience so we try to follow up on these requests when possible.

As for the UI requirements, you can consider these as suggestions. As extensions are in the beta phase, we had strong developer feedback early on that when extensions didn't match the theme, it wasn't a great developer experience for users.  Since then, we have several extensions where matching the Docker Desktop theme would have been a considerable burden and have still added them to our marketplace based on developer demand and have seen them be successfully adopted. It's unlikely that we'll change the UI guidelines to be stricter as we are seeing these successes. Since this is also the case for Tekton Dashboard, we can definitely take that into consideration when reviewing the extension. I'll make a note to discuss this strong language in our documentation with the team as well.

**Comment by AlanGreene** [comment]
Closing due to lack of feedback from users. We may revisit this in future.
