### ISSUE TITLE
Import Tekton Resources panel errors on latest image 

### ISSUE THREAD

**Issue by jessm12** [tektoncd/dashboard#253]
# Expected Behavior

The import Tekton resources panel renders as expected 

# Actual Behavior

Using the latest nightly install image or `ko apply` of latest code and accessing the Import Resources page of the dashboard leads to an error 
![Screenshot 2019-06-14 at 15 59 10](https://user-images.githubusercontent.com/32932155/59519155-26102200-8ebf-11e9-8201-1d68c821a343.png)
and the page fails to render
 

# Steps to Reproduce the Problem

1. Install the Dashboard following either instruction set from latest code https://github.com/tektoncd/dashboard
2. navigate to import resources 
3. observe the error and page that has not rendered

**Comment by ncskier** [comment]
I have recreated this error, and it looks like the error was introduced with commit `50a006ca7d5179ecb549e79fd7bcd1ae06160550`

**Comment by ncskier** [comment]
It looks like the recent change to generalize "namespaced reducers" is the source of the error. On the Import Tekton Resources page, the error is generated from the serviceAccounts reducer, so I have created a small PR to fix this problem. However, we might need some additional work done in another PR assuming the other "namespaced reducers" have a similar bug.
