### ISSUE TITLE
tekton-dashboard: is forbidden: violates PodSecurity 

### ISSUE THREAD

**Issue by chmouel** [tektoncd/dashboard#2552]
# Expected behavior

cannot run dashboard

# Actual behaviour

Deployment shows this 

```
    message: 'pods "tekton-dashboard-659dcf698f-c5pf5" is forbidden: violates PodSecurity
      "restricted:latest": allowPrivilegeEscalation != false (container "tekton-dashboard"
      must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities
      (container "tekton-dashboard" must set securityContext.capabilities.drop=["ALL"]),
      seccompProfile (pod or container "tekton-dashboard" must set securityContext.seccompProfile.type
      to "RuntimeDefault" or "Localhost")'
```

# Steps to reproduce the bug

1. Installed kind, with 1.24 server, 1.25 client
2.installed dashboard from  	https://storage.googleapis.com/tekton-releases/dashboard/latest/tekton-dashboard-release.yaml 

3. % k get deployments.apps -n tekton-pipelines tekton-dashboard -o yaml

# Additional info

- Kubernetes version:

  **Output of `kubectl version`:**
  ```
% k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.0
  ```

- Tekton versions:

  **Output of `tkn version` or**
  ```sh
  kubectl get deploy tekton-pipelines-controller -n tekton-pipelines -o=jsonpath="{\"Pipeline version: \"}{.metadata.labels.version}{\"\n\"}"

  kubectl get deploy tekton-triggers-controller -n tekton-pipelines -o=jsonpath="{\"Triggers version: \"}{.metadata.labels.version}{\"\n\"}"

  kubectl get deploy tekton-dashboard -n tekton-pipelines -o=jsonpath="{\"Dashboard version: \"}{.metadata.labels.version}{\"\n\"}"
  ```

  ```
  (paste your output here)
  ```

**Comment by AlanGreene** [comment]
@chmouel Thanks for reporting this. I haven't been able to reproduce the issue so suspect there's a version / config difference at play.

The Dashboard dev scripts have been using Kubernetes 1.24 for a while now and I haven't seen this issue before.

This is what I'm using locally at the moment: https://github.com/tektoncd/dashboard/blob/0c6041f19c73b14e9608d0f95048ef86fbe49eff/scripts/prepare-kind-cluster#L21-L52

```
$ kind version
kind v0.15.0 go1.19 darwin/arm64

$ k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.1
Kustomize Version: v4.5.7
Server Version: v1.24.4
```

How are you creating your Kind cluster? Just a straight `kind create cluster` or are you providing some custom config?

**Comment by AlanGreene** [comment]
Ah I see the label `pod-security.kubernetes.io/enforce: restricted` was added to the `tekton-pipelines` namespace in Pipeline master recently: https://github.com/tektoncd/pipeline/pull/5652/files#diff-d98ea73731da6e49a8552d6917d796aab6613198b269eda1b4bbfb4b53d90111R22

To unblock yourself you could temporarily remove that label:
`kubectl label namespace tekton-pipelines pod-security.kubernetes.io/enforce-`

We'll need to update the Dashboard deployment to be compatible with this, likely similar changes to those made in the Pipeline PR: https://github.com/tektoncd/pipeline/pull/5652/files#diff-497e160f3c1001518d420d83981ea56d99f64ec126ba2dd569430664b94faf3cR122-R131

**Comment by chmouel** [comment]
No worries I'll wait for the update thanks for investigating

**Comment by AlanGreene** [comment]
Doesn't look like this is going to be the quick fix I hoped for, I'll need to dig into it more but likely won't have time until tomorrow at the earliest.

```
ValidationError(Deployment.spec.template.spec.securityContext): unknown field "allowPrivilegeEscalation" in io.k8s.api.core.v1.PodSecurityContext
ValidationError(Deployment.spec.template.spec.securityContext): unknown field "capabilities" in io.k8s.api.core.v1.PodSecurityContext
```

**Comment by AlanGreene** [comment]
TIL: SecurityContext and PodSecurityContext overlap in their supported fields but are not the same…

This seems to do the trick but will need more testing tomorrow.

```diff
diff --git a/base/300-deployment.yaml b/base/300-deployment.yaml
index 7f752f87..65a0886f 100644
--- a/base/300-deployment.yaml
+++ b/base/300-deployment.yaml
@@ -48,9 +48,6 @@ spec:
     spec:
       serviceAccountName: tekton-dashboard
       volumes: []
-      securityContext:
-        runAsNonRoot: true
-        runAsUser: 65532
       nodeSelector:
         kubernetes.io/os: linux
       containers:
@@ -73,3 +70,13 @@ spec:
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.namespace
+          securityContext:
+            allowPrivilegeEscalation: false
+            capabilities:
+              drop:
+              - "ALL"
+            runAsUser: 65532
+            runAsGroup: 65532
+            runAsNonRoot: true
+            seccompProfile:
+              type: RuntimeDefault
```

**Comment by AlanGreene** [comment]
The next nightly release will have the change above. Doc and walk-through updates to follow…

**Comment by AlanGreene** [comment]
Fix released in https://github.com/tektoncd/dashboard/releases/tag/v0.30.0

**Comment by CJCShadowsan** [comment]
Just a heads-up - This also exists inside tekton-triggers. I'll go and raise an issue now...

**Comment by CJCShadowsan** [comment]
https://github.com/tektoncd/triggers/issues/1479 refers
