### ISSUE TITLE
Bug: PipelineRuns show running indefinitely

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#257]
# Expected Behavior
I expect the UI to show that my PipelineRuns have terminated when the PipelineRuns have terminated.
# Actual Behavior
Instead, the UI shows the status as running even after my PipelineRuns have terminated.
![Screen Shot 2019-06-14 at 3.18.44 PM.png](https://images.zenhubusercontent.com/5cc0668def180a20792767af/b860031c-22ec-4c74-9c82-c508b0ecf0f1)
```
$ kubectl get pods
NAME                                                                READY   STATUS      RESTARTS   AGE
pipeline0-run-1560534847556549300-pipeline0-task-fcqvt-pod-074457   0/3     Completed   0          1h
pipeline0-run-1560536106702470900-pipeline0-task-5bjb6-pod-ee4257   0/3     Completed   0          1h
pipeline0-run-1560539713658549500-pipeline0-task-576h6-pod-4c2572   0/3     Completed   0          15m
tekton-dashboard-68ffd4cf6d-2ls62                                   1/1     Running     0          33s
```
![Screen Shot 2019-06-14 at 3 31 36 PM](https://user-images.githubusercontent.com/16961496/59533463-8603ca00-8eb9-11e9-813d-3e29d8b6c935.png)

# Steps to Reproduce the Problem

1. Navigate to the Import Tekton Resources page
2. Submit the form which will create a PipelineRun
3. Wait for the PipelineRun to complete, and navigate to the PipelineRuns page where the PipelineRun will show that it is running.

Note: I have only tested this with PipelineRuns created from the Import Tekton Resources page.

# Additional Info

**Comment by jessm12** [comment]
@ncskier I followed the steps above and wasn't able to reproduce this problem 🤔for me everything looks as expected 
![Screenshot 2019-06-17 at 11 25 19](https://user-images.githubusercontent.com/32932155/59597888-c8fcb200-90f2-11e9-81b7-5d27c84bc2f4.png)
![Screenshot 2019-06-17 at 11 25 41](https://user-images.githubusercontent.com/32932155/59597897-cd28cf80-90f2-11e9-96a9-068ba87a3533.png)

**Comment by steveodonovan** [comment]
@ncskier Could you send on the actual pipelineRun yaml on the cluster ?

**Comment by ncskier** [comment]
```
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineRun
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"tekton.dev/v1alpha1","kind":"Pipeline","metadata":{"annotations":{},"name":"pipeline0","namespace":"default"},"spec":{"params":[{"default":"/workspace/git-source","description":"The path to the resource files to apply","name":"pathToResourceFiles"},{"default":"","description":"The directory from which resources are to be applied","name":"apply-directory"}],"resources":[{"name":"git-source","type":"git"}],"tasks":[{"name":"pipeline0-task","params":[{"name":"pathToResourceFiles","value":"${params.pathToResourceFiles}"},{"name":"apply-directory","value":"${params.apply-directory}"}],"resources":{"inputs":[{"name":"git-source","resource":"git-source"}]},"taskRef":{"name":"pipeline0-task"}}]}}
    clusterName: ""
    creationTimestamp: "2019-06-14T19:15:13Z"
    generation: 1
    labels:
      app: tekton-app
      gitOrg: pipeline-hotel
      gitRepo: example-pipelines
      gitServer: github.com
      tekton.dev/pipeline: pipeline0
    name: pipeline0-run-1560539713658549500
    namespace: default
    resourceVersion: "66032"
    selfLink: /apis/tekton.dev/v1alpha1/namespaces/default/pipelineruns/pipeline0-run-1560539713658549500
    uid: bc6d8366-8ed8-11e9-91c9-025000000001
  spec:
    params:
    - name: target-namespace
      value: default
    - name: apply-directory
      value: config
    pipelineRef:
      name: pipeline0
    resources:
    - name: git-source
      resourceRef:
        name: git-source-1560539713658549500
    serviceAccount: default
    timeout: 1h0m0s
  status:
    conditions:
    - lastTransitionTime: "2019-06-14T19:15:13Z"
      message: Not all Tasks in the Pipeline have finished executing
      reason: Running
      status: Unknown
      type: Succeeded
    startTime: "2019-06-14T19:15:13Z"
    taskRuns:
      pipeline0-run-1560539713658549500-pipeline0-task-576h6:
        pipelineTaskName: pipeline0-task
        status:
          podName: ""
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by steveodonovan** [comment]
Just to clarify it's the above that determines that a pipeline run has terminated and its status is showing running. Looks like it could be a tekton issue. Maybe check the logs for the controller, looks like it might have failed to update the status for some reason. Might be worth checking the status for the individual tasks too.

**Comment by ncskier** [comment]
Ok, my mistake. I'll close the issue.

**Comment by ncskier** [comment]
I updated my Docker for Desktop from the latest `Stable` release, to the latest `Edge` release, so now it's running kube version `v1.14.3`, and I no longer see the problem documented in this issue.
