### ISSUE TITLE
Kubernetes Managed Fields - Hide

### ISSUE THREAD

**Issue by darktempla** [tektoncd/dashboard#2595]
# Feature request

When viewing a Tekton resource (Task, Pipeline etc) in the UI using the YAML tab hide the `managedFields` attributes.

This would also have an option in the `Settings` section to choose if you wish to hide or not. 

# Use case

Makes the UI cleaner. 
Removes noise.

# Alternatives

Rather than hiding I have seen other apps just collapse the `managedFields` into a single line which is expandable.

# Additional context

<img width="971" alt="image" src="https://user-images.githubusercontent.com/4919068/203396310-28fe04c9-f1ed-4e3c-b01a-07939b088962.png">

**Comment by AlanGreene** [comment]
Thanks for raising this issues @darktempla. We've already made a number of changes in v0.29.0 and v0.30.0 to remove `managedFields` anywhere we display YAML. What version of the Dashboard are you seeing this on?

**Comment by darktempla** [comment]
Ah okay right thanks for the prompt reply @AlanGreene.
So I thought I was running the latest and greatest. 
Seem if you install via the Tekton operator by default is not using the latest version of the dashboard.

I will install the latest version and enjoy this feature. Thanks.

<img width="703" alt="image" src="https://user-images.githubusercontent.com/4919068/203404086-f0e7196b-1808-4847-af78-7ee1a48a155c.png">

**Comment by AlanGreene** [comment]
Ah ok, glad to help 😸
