### ISSUE TITLE
v1 Release Dashboard Support

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/dashboard#2598]
### Feature request

V1 CRDs are released in https://github.com/tektoncd/pipeline/pull/5579 and this issue tracks down the according requests for the v1 support in dashboard.

**Comment by AlanGreene** [comment]
The Dashboard will move to requesting v1 Pipeline resources when the minimum supported Pipeline release serves v1 resources, so that's likely another 3 or more releases.

When the time comes the actual code change should be relatively small, updating the default version used on requests from `v1beta1` to `v1` in src/api/utils.js getTektonAPI, and overriding this for any resources remaining at `v1beta1`.

There may also be some opportunity for cleanup, removing fields that are no longer used, etc.

**Comment by afrittoli** [comment]
> The Dashboard will move to requesting v1 Pipeline resources when the minimum supported Pipeline release serves v1 resources, so that's likely another 3 or more releases.

I think it may be confusing for users, if they install the latest pipeline and dashboard, convert their resources to v1 and see the v1beta1 resources through the dashboard.

Is it possible to customise the behaviour of dashboard based on the version of pipeline installed?
If so, dashboard could start displaying `v1` resources if the version of pipeline installed is at least the one where we start storing `v1` in etcd.

**Comment by AlanGreene** [comment]
It's the same process we followed for the move from `v1alpha1` to `v1beta1`. The conversion works in both directions, so no matter which version we choose it may cause confusion for some users, for example If I'm still using `v1beta1` resources I might be surprised to see them as `v1` in the Dashboard.

> Is it possible to customise the behaviour of dashboard based on the version of pipeline installed?

Maybe, but it would not be a simple task. The Dashboard currently assumes it's dealing with a single version for any given resource kind, and the APIs would need to be dynamically updated based on additional information from the back end.

2 options I currently see for this:
- hardcode the apiVersion based on Pipelines release version
  - I'm generally not a fan of hardcoding versions / capabilities where it can be avoided
- dynamically determine the served resource versions by requesting the CRDs and inspecting the `served` field on each version
  - can we load all Tekton CRDs in a single request or would we require a request per kind?

Both of these would require changes to how the API calls are currently made, delaying them until this additional information is available.

Another option that might be a little easier to implement, would be to add a toggle in the settings to enable `v1` resources. A temporary opt-in until it becomes the default in a later release.
