### ISSUE TITLE
Display ClusterTasks in the dashboard

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#262]
https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#clustertask

- New top-level nav item for ClusterTasks (similar to Tasks)
- Update existing code for TaskRuns to support them
  - store with Tasks or separately? Either way containers will need to be updated to filter / combine the correct data.

**Comment by steveodonovan** [comment]
Going for ClusterTasks as a top level navigation

/assign
