### ISSUE TITLE
Stop pipeline default option should be CancelledRunFinally instead of Cancelled

### ISSUE THREAD

**Issue by marniks7** [tektoncd/dashboard#2623]
# Feature request

# Use case

Right now when user clicks "stop" button it see the following dialog.
![image](https://user-images.githubusercontent.com/9289172/206309222-eb50d64c-01e1-46ca-b083-0fb310726b88.png)

`Cancelled` options is the first one and selected by default, I believe that this option should be moved to the bottom and `CancelledRunFinally` should be the first one and selected by default. The reason behind that - it is much more graceful option for those pipelines with `Finally` task

**Comment by AlanGreene** [comment]
This option was chosen as the default to maintain backwards compatibility with the previous behaviour. We may consider changing this depending on feedback from users.

**Comment by AlanGreene** [comment]
Closing for now since we're not currently planning to change this. We can revisit in future if more users request it or if the Tekton CLI is similarly updated.
