### ISSUE TITLE
External Logs URL data is not displayed

### ISSUE THREAD

**Issue by quant-daddy** [tektoncd/dashboard#2624]
# Expected behavior
The external Log URL is returning data but it is not displayed. In the screenshot below, the original log URL is returning 404 which results in the fallback URL getting called. Even after the data is fetched with 200 response code, it is not displayed.

# Actual behaviour
Data fetched from `--external-logs` URL parameter is not displayed.

<img width="947" alt="Screenshot 2022-12-07 at 10 47 58 PM" src="https://user-images.githubusercontent.com/10248760/206355902-315c4587-302a-4329-8b51-40c3ff36e215.png">

# Additional info

- Kubernetes version:
```
  WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.5-gke.600", GitCommit:"fb4964ee848bc4d25d42d60386c731836059d1d8", GitTreeState:"clean", BuildDate:"2022-09-22T09:24:55Z", GoVersion:"go1.18.6b7", Compiler:"gc", Platform:"linux/amd64"}
```

  ```
  Client version: 0.26.0
Pipeline version: v0.40.1
Triggers version: v0.21.0
Dashboard version: v0.29.2
  ```

Container args in the deployment:
```
containers:
      - args:
        - --port=9097
        - --logout-url=
        - --pipelines-namespace=tekton-pipelines
        - --triggers-namespace=tekton-pipelines
        - --read-only=false
        - --log-level=info
        - --log-format=json
        - --namespace=
        - --stream-logs=true
        - --external-logs=http://tekton-log-viewer.devops.svc.cluster.local/logs
```

**Comment by AlanGreene** [comment]
There should be an error in the browser console with more information on the failure reason. The most common cause is that the log request did not return a plain text response.

**Comment by quant-daddy** [comment]
You're right! Once I set the ContentType to 'text/plain', it works!

**Comment by AlanGreene** [comment]
Glad it's working! 😸

**Comment by quant-daddy** [comment]
For those looking to fetch logs from GCP, here's the link to deploy a pod: 

https://github.com/Kollate/gke-pod-logs
