### ISSUE TITLE
Add proxy rest api which will delegate calls to kube apiserver set up restricted service account

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/dashboard#267]
There has been a few issues opened asking why we aren't using the kube api server. Exposing the actual kube apiserver and handling credentials client side is a little too heavy. Also the kube api server does not provide all the functionality we need. Also there would be cross origin request issues. Proposed solution is to use a proxy in place of some of our back end api calls.

Large caveat to this is that it essentially exposes the kube api server via the dashboard service account. However we already have the issue where the api as it is today exposes a cluster which its installed on. The wider access control story is still being worked but we could restrict this access based on the dashboards service account.

@mnuttall @skaegi @AlanGreene 

Service account with cluster role binding will be a prereq to this -

Right now the dashboard has no service account, role bindings or restrictions applied with its install. As a starting point to limit the proxys access to kubernetes native resources the dashboard should install its own service account with a minimal set of roles (see [here](https://github.com/tektoncd/pipeline/blob/master/config/200-clusterrole.yaml) for the roles available to tekton pipelines)

**Comment by a-roberts** [comment]
This is now complete and merged, thanks @steveodonovan!
