### ISSUE TITLE
Tekton pipeline run should support a params with an drop-down option

### ISSUE THREAD

**Issue by sivachandran-s** [tektoncd/dashboard#2677]
### Feature request

There can be an option in tekton pipeline run where users can select a parameter value based on a drop-down menu.

### Use case

Suppose, my tekton pipeline consists of multiple parameters in one of the parameters I am expecting the user to choose the list of components name from the drop-down instead of entering the component name manually.

**Comment by AlanGreene** [comment]
Thanks for the feature request @sivachandran-s. Can you elaborate on how you expect this to be used and how it would be configured?

The Dashboard displays data based on the resources present in the cluster. What would be the source of the options presented in the dropdown? Would it be the same for all Tasks / Pipelines? Would it be the same for all users? etc.

**Comment by sivachandran-s** [comment]
Hi @AlanGreene 
I am trying to trigger the pipeline from the Tekton Dashboard, and below is my sample YAML file.

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy-pipeline
  namespace: tekton
spec:
  params:
    - name: branch
      description: GIT branch to be checked out

    **- name: component
      description: Example:amicroservice,bmicroservice,cmicroservice,dmicroservice,emicroservice**

    - name: image-tag
      description: image tag version by default image build with the tag YY-MM-DD
      default: ''    
    - name: build-image-pushto-ecr
      default: ''
      description: true or false default is false
  tasks:
    - name: build-deploy-task
      taskRef:
        name: build-deploy-task 
      params:
        - name: url
          value: "test.git"
        - name: branch
          value: "$(params.branch)"
        - name: component
          value: "$(params.component)"
        - name: build-tag
          value: "$(params.image-tag)"     
        - name: build-ecrimage
          value: "$(params.build-image-pushto-ecr)"

In the Tekton dashboard, I would like to get the list of component names in a drop-down with the check box enabled to select the single or multiple components and I will pass those values to the task(build-deploy-task) in the task, I have multiple steps to build the functionality based on the component.

This is not a blocker I have figured out the alternative way just checking here if it is possible to have this option in Tekton.

**Comment by AlanGreene** [comment]
> I would like to get the list of component names in a drop-down with the check box enabled to select the single or multiple components and I will pass those values to the task

It sounds like these values would vary depending on the Pipeline or other criteria (user, organisation, project, etc.) and would need to be configured elsewhere for consumption by the Dashboard. The behaviour would likely also vary depending on a particular user / organisation's needs, e.g. allowing multiple selections vs. single, array params vs. comma separated string, dependencies between selected values, etc.

As the Dashboard functionality is based entirely on the Tekton resources present in the cluster there's no current mechanism for providing this functionality. It sounds like something that could be desirable across all Tekton clients though, not just the Dashboard.

This might be worth opening an issue in the [community repo](https://github.com/tektoncd/community) to gauge interest, and if it's something the community thinks would be useful then creating a TEP: https://github.com/tektoncd/community/tree/main/teps#tekton-enhancement-proposals-teps

Closing as there's nothing for the Dashboard to do at the moment but we may revisit in the future based on the outcome of the above.
