### ISSUE TITLE
Add websocket eventing when secret is created

### ISSUE THREAD

**Issue by carlos-logro** [tektoncd/dashboard#269]
# Expected Behavior
When a secret is created the websocket should be fed eventing for creating, updating & deleting secrets. 

# Actual Behavior
Currently, there is no eventing in the websocket for this particular case. When creating a secret through the API & getting a successful status code then the fetchSecrets action is called to access the API & get the new list of secrets. For deleting we just call the API with the specified secret & when done we just delete that secret from the redux store. Lastly, there is still no functionality for updating a secret in the UI.

**Comment by a-roberts** [comment]
@vtereso and @carlos-logro, is there anything we still need to do for this or can we close?

**Comment by vtereso** [comment]
It can be closed.

**Comment by AlanGreene** [comment]
I don't see any handling for secret-related websocket events in the front end, this would still need to be added. Is there another issue tracking this?

**Comment by vtereso** [comment]
Ah, I was reading this very literally "websocket should be fed", which sounded like backend, but fair point. I am not sure about that side @AlanGreene

**Comment by vtereso** [comment]
To complete this issue: Add front-end handler to the websocket for secret notifications.
