### ISSUE TITLE
Migrate off `pipelineResources` for Dashboard

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/dashboard#2694]
Since the  `pipelineResources` are going to be removed in pipeline _v0.45_  as designed in [TEP074](https://github.com/tektoncd/community/blob/main/teps/0074-deprecate-pipelineresources.md) and according to [deprecation.md](https://github.com/tektoncd/pipeline/blob/main/docs/deprecations.md),  _(some have already been removed eg. [cloudevent ](https://github.com/tektoncd/pipeline/pull/5995)and [cluster](https://github.com/tektoncd/pipeline/pull/5996) PipelineResources)_, we need to migrate off the `pipelineResources` for the related in dashboard.

Related issue: [Handle PipelineResources when swapping v1 to the storage version #5967](https://github.com/tektoncd/pipeline/issues/5967)

**Comment by AlanGreene** [comment]
Thanks for raising this issue @JeromeJu. We've already removed use of and support for PipelineResources in the most recent Dashboard release: https://github.com/tektoncd/dashboard/releases/tag/v0.32.0

**Comment by JeromeJu** [comment]
Thanks @AlanGreene for the instant response, much appreciated to get confirmed.
