### ISSUE TITLE
Dashboard Not Available After Following Install Directions

### ISSUE THREAD

**Issue by jbeuckm** [tektoncd/dashboard#2744]
# Expected behavior
Dashboard is port forwarded

# Actual behaviour
`Error from server (NotFound): services "tekton-dashboard" not found`

# Steps to reproduce the bug

1.  curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-arm64\nsudo install minikube-darwin-arm64 /usr/local/bin/minikube\n
1.  minikube start
1.  minikube start --profile tekton-dashboard-tutorial
1.  kubectl cluster-info
1.  kubectl apply --filename \\nhttps://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
1.  kubectl get pods --namespace tekton-pipelines --watch
output:
```
NAME                                          READY   STATUS    RESTARTS   AGE
tekton-pipelines-controller-9675574d7-n9v5t   1/1     Running   0          145m
tekton-pipelines-webhook-58b5cbb7dd-7c9ll     1/1     Running   0          145m
```
1.  kubectl port-forward -n tekton-pipelines service/tekton-dashboard 9097:9097

# Additional info
OSX 12.5.1

- Kubernetes version:
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.24) and server (1.26) exceeds the supported minor version skew of +/-1
```

- Tekton versions:
```
Error from server (NotFound): deployments.apps "tekton-dashboard" not found
```

**Comment by AlanGreene** [comment]
Hi @jbeuckm, I don't see the Dashboard being installed in your steps to reproduce the bug. Can you confirm that you've installed the Dashboard? What method did you use to install it?

**Comment by jbeuckm** [comment]
Thanks! I somehow missed the actual line to install it. Works now.
