### ISSUE TITLE
Developers should use `npm ci` when installing the dashboard from source

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#277]
# Expected Behavior
package-lock.json should be adhered to

# Actual Behavior
We suggest `npm installing`. We should suggest Node.js 10.x I believe and `npm ci` instead so our package-lock.json is taken into account.

@dibbles noticed bold font styling and a scrollbar on the delete dialog for the extension when using Node 12 with a newly generated package-lock.json as a result of npm installing

**Comment by jessm12** [comment]
https://github.com/tektoncd/dashboard/pull/317
