### ISSUE TITLE
Pass timeframe to external-logs service

### ISSUE THREAD

**Issue by AverageMarcus** [tektoncd/dashboard#2908]
# Feature request

When calling to the `external-logs` proxy it'd be useful to have the approx timeframe that the logs should be found within.

# Use case

Currently we use Loki as our long-term log storage and for efficiency reasons we limit the dashboard logs proxy to only look back for ~3 days to ensure the result returns quick enough to be useful. If we had the start / completion time of the expected logs we could craft much more specific queries that would return much quicker and can be from far in the past.

# Alternatives

* Limit the period that logs can be retrieved from (this is what we currently have)

# Additional context

**Comment by AlanGreene** [comment]
Thanks Marcus for this great suggestion. I agree that it makes sense to include this in the Dashboard. Thanks for submitting the PR too.
