### ISSUE TITLE
Minishift install deploy yaml doesn't have Pipeline0

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#292]
Minishift install instructions point to config/templates/deploy.yaml but this doesn't include Pipeline0 in the yaml. This then means import tekton resources from repository doesnt work. 

I noticed when i installed tekton on minishift and it didnt get pipeline0 it gave me this error when I tried to Import and Apply 
`:9097/v1/namespaces/tekton-pipelines/pipelineruns/:1 Failed to load resource: the server responded with a status of 412 (Precondition Failed)`

This would be useful if it was a error which showed up to the user rathe than no response

**Comment by a-roberts** [comment]
Merged so closing
