### ISSUE TITLE
Google storage has not been updated with latest 0.36.1 release

### ISSUE THREAD

**Issue by rouke-broersma** [tektoncd/dashboard#2946]
# Expected behavior

Downloading [latest from google storage ](https://storage.googleapis.com/tekton-releases/dashboard/latest/release.yaml) give you the latest release on the github releases page.

# Actual behaviour

Downloading latest release gives you v0.36.0

**Comment by AlanGreene** [comment]
Thanks for reporting this @rouke-broersma, it should give v0.36.1 now.
