### ISSUE TITLE
The `apiVersion` displayed in the dashboard does not match the `apiVersion` used

### ISSUE THREAD

**Issue by AliDev0ps** [tektoncd/dashboard#2967]
# Expected behavior
`apiVersion` corresponds to the actual one used

# Actual behaviour
The `apiVersion` displayed in the dashboard does not match the `apiVersion` used

# Steps to reproduce the bug

1. Create `task` or `pipeline` of `tekton.dev/v1` apiVersion
2. Check yaml in `dashboard` and you'll see `apiVersion` shown as `tekton.dev/v1beta1`

# Additional info

- Kubernetes version:

  ```
  Client Version: v1.24.6
  Kustomize Version: v4.5.4
  Server Version: v1.24.6
  ```

- Tekton versions:

  ```
  Client version: 0.31.1
  Pipeline version: v0.49.0
  Triggers version: v0.24.1
  Dashboard version: v0.37.0
  ```

**Comment by AlanGreene** [comment]
Hi @AliDev0ps, you can configure this in the settings, see the option 'Use Tekton Pipelines API version v1'

![image](https://github.com/tektoncd/dashboard/assets/2829095/ec79e54e-8f94-4910-96d1-1b26ce75bd37)

When enabled this will use the v1 APIs for any resources that support it, falling back to v1beta1 as needed. This option was provided to allow for backwards compatibility with older Tekton Pipelines releases where v1 was not yet enabled by default.

A future Dashboard release will switch the default value for this toggle to enabled, and eventually it will be removed.

**Comment by AliDev0ps** [comment]
> Hi @AliDev0ps, you can configure this in the settings, see the option 'Use Tekton Pipelines API version v1'
> 
> ![image](https://user-images.githubusercontent.com/2829095/249127207-ec79e54e-8f94-4910-96d1-1b26ce75bd37.png)
> 
> When enabled this will use the v1 APIs for any resources that support it, falling back to v1beta1 as needed. This option was provided to allow for backwards compatibility with older Tekton Pipelines releases where v1 was not yet enabled by default.
> 
> A future Dashboard release will switch the default value for this toggle to enabled, and eventually it will be removed.


@AlanGreene  Thank you for your reply, I'm sorry, I didn't notice the switch, when I turned it on the dashboard showed as expected !
