### ISSUE TITLE
Websocket test is flaky

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#30]
**dibbles fixed this, we've got assigning problems atm**

Run the Go unit tests in our Dockerfile several times in a row, sometimes you observe:

```
DeletionsRecorded not equal to 10, recorded only 9--- FAIL: TestPipelineRunWebsocket (17.00s)
    websocket_test.go:75: Enter TestPipelineRunWebsocket...
    websocket_test.go:239: DeletionsRecorded not equal to 10, recorded only 9
FAIL
exit status 1
FAIL	github.com/tektoncd/dashboard/pkg/endpoints	24.096s
The command '/bin/sh -c CGO_ENABLED=0 NAMESPACE=default GOOS=linux go test -v' returned a non-zero code: 1
```

I ran this in a loop with the following straight from a stackoverflow Bash example. 

**I saw the failure twice in 18 failures**, then stopped my script to make said issue.

```
i=0
output_file=tests.txt
rm -f $output_file
touch $output_file

while [ $i -lt 20 ] ; do
  echo "Running test $i"
  docker build -t foo -f Dockerfile_test . >> $output_file.txt
  i=$[$i+1]
done
```

First seen [here](https://github.com/tektoncd/dashboard/pull/19). @dibbles thinks this may be due to incrementing the counter variables in a non-atomic way and as such it's a test problem.

Interesting code in question: https://github.com/tektoncd/dashboard/blob/master/pkg/endpoints/websocket_test.go#L126 and the vars are declared:

```
// Counters for pipelineruns websocket test
var CreationsRecorded = 0
var UpdatesRecorded = 0
var DeletionsRecorded = 0
```

**Comment by dibbles** [comment]
Adding in mutex to lock around counter updates - testing doing 20 iterations of go test -run TestPipelineRunWebsocket -v

**Comment by dibbles** [comment]
FWIW - this has been fixed under https://github.com/tektoncd/dashboard/pull/39 .... if anyone can work out how to assign this to me or to close it as it is now done... that would be great

**Comment by a-roberts** [comment]
@dibbles I'll close it and once we figure out how to assign others it'll be all yours 😅  thanks for the fix
