### ISSUE TITLE
Error loading pipelines

### ISSUE THREAD

**Issue by poloHex** [tektoncd/dashboard#303]
HI guys,

after installed the dashboard followed the guide. when i entered the dashboard i find it can't load any pipelines.
 there's an error: Error loading pipelines Unexpected token < in JSON at position 0 

and i can only find the "default" namespace in the "Namespace" list. other namespace lost.

**Comment by steveodonovan** [comment]
Hi @poloHex, I tried to reproduce this but can't. Could I ask what kubernetes version are you running on ? Also Is this a completely fresh install or did you have the dashboard running in the cluster previously ? And lastly are you accessing the dashboard through kube proxy, port forward or another means ?

After a recent change the dashboard is now expected to run in the tekton-pipelines namespace with a restricted role. This might impact an older install.

**Comment by poloHex** [comment]
the k8s version is 1.12, never installed before, i create an route for the service and access it via 
the route.

**Comment by poloHex** [comment]
error output:
WebSocket connection to 'ws://teykton-dashboard.cdbf250cf1f9044c3bbd734c9bf43fc5b.cn-shanghai.alicontainer.com/?spm=5176.2020520152.0.0.16bc16ddtvZyFl/v1/websockets/resources' failed: Error during WebSocket handshake: Unexpected response code: 200

Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by poloHex** [comment]
now i can confirm that it works with kubectl proxy but didn;t work with the route.

but for history tasks, seems it can't get the history, it showed "Unable to fetch log"

**Comment by AlanGreene** [comment]
A version of tektoncd/pipeline shortly after the 0.4 release introduced a backwards incompatible change to the container names that affected the dashboard's ability to load logs: https://github.com/tektoncd/pipeline/pull/818
This change is now released in 0.5, and yesterday we updated the dashboard to reflect this.

**Comment by AlanGreene** [comment]
@poloHex did the update above resolve your issue loading logs?

**Comment by AlanGreene** [comment]
Closing stale issue
