### ISSUE TITLE
[Translation] Support more languages

### ISSUE THREAD

**Issue by jisoolee** [tektoncd/dashboard#3068]
# Feature request

Need to support more languages and maintain the current ones 

# Use case

Supporting more languages would be helpful for users globally.

# Alternatives

Users might be able to google website translation feature, but it would be great if we can provide the translation internally based on the browser/OS language.

# Additional context

Currently supporting
- [x] English
- [x] Japanese
  - #3069
  - currently enabled but stale / incomplete
- [x] Chinese (Simplified)
  - currently enabled but stale / incomplete
- [x] Korean - ~~will be supported soon~~
  - #3051 
  - #3054 
  - #3066
  - enabled
- [ ] German
- [ ] Spanish
- [ ] Italian
- [ ] Portuguese
  - #3070
  - #3098
  - incomplete
- [ ] Chinese (Traditional)

**Comment by Ratheshan03** [comment]
@AlanGreene ,  Is it okay to add Tamil language support?

**Comment by AlanGreene** [comment]
Thanks for your interest @Ratheshan03. I'm not sure we've had any requests for Tamil support before, but if you're willing to contribute the translations and maintain them in future as the Dashboard is updated we could consider it.
