### ISSUE TITLE
Update front end create pipeline run API to consume kube API

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#321]
Continuation of https://github.com/tektoncd/dashboard/issues/290

The front end code currently uses the REST APIs provided by the back end.
Now that #268 has been merged we should begin migrating the front end APIs to use the APIs provided by the kube API server where possible / appropriate.

This issue is to track the following APIs:
- [ ] createPipelineRun

Also:
- [ ] delete any unused backend code once these are migrated

## Notes

There's already a [createPipelineRunAtProxy](https://github.com/tektoncd/dashboard/blob/47ae481e7ba856d85496715e3014d5ef1ac53c5f/src/api/index.js#L133) API that's used for the manual create pipeline run UI.

The legacy `createPipelineRun` is used by the import resources UI. This is the one that should be migrated.

Once this happens the `AtProxy` API should be renamed.

**Comment by vtereso** [comment]
I picked up this issue from Carlos, but didn't realize there was still front-end work to be done. To migrate to the proxy url, the git pipelineresouce used within [pipeline0](https://github.com/tektoncd/dashboard/blob/master/config/pipeline0.yaml), will need to be created ahead of time. Someone feel free to finish up the work I have done on [my branch](https://github.com/tektoncd/dashboard/pull/439).
