### ISSUE TITLE
Pipelines Status of the pipelinerun does not auto refresh if there is multiple running

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#322]
Noticed whilst running multiple PipelineRuns of the same pipeline on Minishift. 

In the Pipelines tab after creating multiple PipelineRuns via the "Create PipelineRun" button the Status of the PipelineRuns does not auto refresh / update. It stays stuck on 
`Not all Tasks in the Pipeline have finished executing`

Even once the PipelineRuns have finished executing which is shown if you go the PipelineRun tab, they stay stuck on `Not all Tasks in the Pipeline have finished executing` on the Piplelines page unless you refresh the page 

Pipelines Page below 
```
Pipeline Run	Status	Last Transition Time	
hello-pipeline-run-1562665872169	All Tasks have completed executing	2019-07-09T09:51:48Z	
hello-pipeline-run-1562665919912	Not all Tasks in the Pipeline have finished executing	2019-07-09T09:52:02Z	
hello-pipeline-run-1562665918111	Not all Tasks in the Pipeline have finished executing	2019-07-09T09:52:02Z	
hello-pipeline-run-1562665926861	Not all Tasks in the Pipeline have finished executing	2019-07-09T09:52:11Z	
hello-pipeline-run-1562665934453	Not all Tasks in the Pipeline have finished executing	2019-07-09T09:52:19Z
```

**Comment by AlanGreene** [comment]
Can you provide the pipeline yaml used to reproduce this? I've tried with a number of pipelines in my dev environment, including pipeline0, and cannot reproduce this.

The status is updated as expected both on the PipelineRuns page and on the Pipelines page filtered to show the runs for the selected Pipeline.

> Even once the PipelineRuns have finished executing which is shown if you go the PipelineRun tab, they stay stuck on Not all Tasks in the Pipeline have finished executing on the Piplelines page unless you refresh the page

Do you mean that clicking on the nav to view the PipelineRuns page shows them as completed, but then clicking back to the previous page still shows them in progress? This is definitely unexpected as both pages use data from the same source to render the status.

**Comment by AlanGreene** [comment]
@CarolynMabbott are you still seeing this issue?

**Comment by CarolynMabbott** [comment]
Not seeing this issue anymore while running on latest dashboard and pipelines so closing the issue
