### ISSUE TITLE
Ability to add filtering labels when manually creating PipelineRuns 

### ISSUE THREAD

**Issue by jessm12** [tektoncd/dashboard#323]
In order to achieve https://github.com/tektoncd/dashboard/issues/223 filtering of `PipelineRuns`, we need for the dashboard UI to allow users to add labels to their manual PipelineRuns.

We could suggest some pre-canned ones that they would be likely to want such as repository or branch but otherwise we should leave it open to them to apply whichever labels they wish to filter by. 

Under this issue:
- Implement the UI changes on the manual `PipelineRun` panel to facilitate selecting labels
- Code the backend to apply these labels to the `PipelineRun` resource

**Comment by AlanGreene** [comment]
If labels are only applied to pipeline runs manually created via the dashboard, how would we provide filtering for runs triggered via webhooks or other mechanisms?

**Comment by jessm12** [comment]
https://github.com/tektoncd/experimental/issues/140 is open to address the extension/webhooks case, this issue is purely around the work that is required for the manual creation panel and comes under wider issues (https://github.com/tektoncd/experimental/issues/37, https://github.com/tektoncd/dashboard/issues/223)

**Comment by AlanGreene** [comment]
Bear in mind pipeline runs can be triggered via other mechanisms too, not just via the dashboard (inc. extension). It might be worth beginning a discussion with the broader community in slack as I'd imagine this may be of interest for the CLI and potentially others. One option might be to have the labels added similar to how the existing `tekton.dev/*` labels are added to various resources (e.g. `tekton.dev/pipeline={pipelineName}` on PipelineRuns). Perhaps others have already considered this or alternatives.

**Comment by jessm12** [comment]
That's true! It would definitely be good to start a discussion like you say to get other ideas on the topic.  Perhaps we could bring it up at a working group meeting to start some discussion also.

**Comment by ncskier** [comment]
I created an issue about automatically adding labels based on PipelineResources: https://github.com/tektoncd/pipeline/issues/1553
