### ISSUE TITLE
Error Messages should be consistent 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#324]
The error messages should be consistent throughout the dashboard. Some tabs when failing to get the resources have the text `Failed to Fetch` and some have `"Failed to fetch"`
Also some have the name correctly like `Error loading PipelineResources` and some have name inncorrectly like `Error loading cluster tasks`  

ClusterTasks has a X on the error to close it but the others dont, if the close button is clicked on the error message the user is left with a blank page with no errors or no ClusterTasks Found text

**Comment by AlanGreene** [comment]
@CarolynMabbott I can't seem to find / reproduce any errors with the `failed to fetch` messages, they are not provided by the front end code. Can you provide an example of where these can be seen?

**Comment by CarolynMabbott** [comment]
Easiest way to bring up the errors is to port forward the dashboard, go to localhost:9097, then stop portforwarding the pod. Then click on the different tabs 
The code may be located in the code around the `src/containers/ClusterTasks/ClusterTasks.js` location

**Comment by AlanGreene** [comment]
@CarolynMabbott I have done that, and see the following (with my changes from the PR linked above)
![image](https://user-images.githubusercontent.com/2829095/61055414-56c57780-a3e9-11e9-8b47-ada575bfc0fc.png)

However I cannot find any scenario for any of the views that yields a `failed to fetch` error message. That string does not appear anywhere in the dashboard code, and I cannot find it anywhere in tektoncd/pipeline that would cause it to be surfaced in the dashboard.

**Comment by CarolynMabbott** [comment]
I haven't come across that error that you got about the GatewayTimeout. Is that a PR that got added in very recently? If so, that may be why I get the error and you dont 

![Screenshot 2019-07-11 at 14 40 32](https://user-images.githubusercontent.com/32342288/61055930-68f3e580-a3ea-11e9-9ad1-fb3c6204078f.png)


![Screenshot 2019-07-11 at 14 44 17](https://user-images.githubusercontent.com/32342288/61055943-6f825d00-a3ea-11e9-9440-0d618157bfd4.png)


These are the errors I get

**Comment by AlanGreene** [comment]
The `Gateway Timeout` message is coming from the browser (response status text on the failed request), I suspect your `Failed to fetch` is too so there's not really anything we can do about that if the casing is inconsistent in different scenarios.

I do see that some of the error messages are surrounded in quotes though, I'll address that.

**Comment by CarolynMabbott** [comment]
I have a feeling that it may be somewhere in the code because the error message i get for PipelineResource is correctly formatted as it says `PipelineResources' whereas the others are not formatted correctly like the PipelineRuns error message 

![Screenshot 2019-07-11 at 15 10 49](https://user-images.githubusercontent.com/32342288/61057971-44017180-a3ee-11e9-9112-b6ccf23b558c.png)

**Comment by AlanGreene** [comment]
I think we may be talking about 2 different things here.

- For the casing of `pipeline runs` vs `PipelineResources`, I have a PR open above addressing that
- You mentioned in the description that some message have `Failed to fetch` while others have `Failed to Fetch`. This is not something we control as that text is coming from the browser.

There's also the issue of inconsistent use of quotes around the messages which I'm currently working on.

**Comment by CarolynMabbott** [comment]
I maybe did try to address too many different issues in one issue, I thought they were all possibly very closely related in the same few files
