### ISSUE TITLE
Filter by label on the PipelineRuns panel

### ISSUE THREAD

**Issue by jessm12** [tektoncd/dashboard#326]
In order to achieve https://github.com/tektoncd/dashboard/issues/223 filtering of `PipelineRuns` we must allow label filters to be selected on the `PipelineRuns` table view. 

Relies on https://github.com/tektoncd/dashboard/issues/323 for `PipelineRuns` that are manually created through the dashboard UI and https://github.com/tektoncd/experimental/issues/140 for experimental extension triggered `PipelineRuns`

Under this issue:
- Filter the request to fetch `PipelineRuns` by label selector, displaying only `PipelineRuns` that have these labels

**Comment by aunderw** [comment]
Here is a PDF of the search/filter flow:

[search-scenario-github.pdf](https://github.com/tektoncd/dashboard/files/3398221/search-scenario-github.pdf)

**Comment by jessm12** [comment]
Maybe https://material-ui.com/components/chips/ could be an option to use here 🙂

**Comment by AlanGreene** [comment]
@jessm12 Carbon provides http://react.carbondesignsystem.com/?path=/story/tag--filter but it looks like there's an issue with the storybook at the moment. I've posted in #carbon-react to let them know.

**Comment by jessm12** [comment]
@AlanGreene I was looking for filtering in carbon but couldn't find it anywhere as the storybook is broken and it's not listed there properly like you say, thanks for raising that 😅is this the right filtering that you're referring to? https://www.carbondesignsystem.com/patterns/filtering/#selecting-filters

**Comment by AlanGreene** [comment]
The UI samples provided in that pattern are more for predefined filters where a user simply selects from a list. Our approach requires additional input so I wouldn't worry too much about the UI presentation in that particular pattern, although some of the other recommendations are still valid (e.g. ability to reset / clear filters).

**Comment by aunderw** [comment]
This is the same scenario I posted yesterday except that it includes example results as well as a more explicit example of how filters could be passed by the URL. 

[tekton-search-and-filter-results.pdf](https://github.com/tektoncd/dashboard/files/3402275/tekton-search-and-filter-results.pdf)

**Comment by jessm12** [comment]
Thank you for those @aunderw 😄

**Comment by jessm12** [comment]
https://github.com/tektoncd/dashboard/issues/37 @kimholmes has linked some additional designs here with comments 🙂Though these extra features for the `PipelineRuns` filtering have not been implemented under this issue there could definitely be scope to enhance this feature in the future

**Comment by jessm12** [comment]
PR for this is here https://github.com/tektoncd/dashboard/pull/427 😄
