### ISSUE TITLE
Show latest logs and/or follow feature

### ISSUE THREAD

**Issue by castlemilk** [tektoncd/dashboard#327]
In the Pipeline/Task log view a large number of logs can be produced, which can become unwieldy as a user scrolls.

Would be nice from a UX perspective to either have a fixed height & scrollable window for logs that can be set to follow mode (showing latest logs as they are recieved), or a tick-box to show latest logs first.

Additionally, it might be worth investigating an optimised mechanism for rendering a sub-set window of logs, instead of fetching the entire log and attempting to render. Could possible default to showing last 1000 lines and then as user scrolls, fetch more by increase the sinceTimestamp value. Potentially utilise `react-virtualized` for this optimization.

I've seen some page freezing on large logs (>5MB), which can then be triggered to re-occur as you change between Logs|Status|Details.

**Comment by AlanGreene** [comment]
Thanks for the feedback and suggestions @castlemilk, they're much appreciated.

We're currently working on some significant design updates for the details view (which includes the logs) and will keep these in mind.

**Comment by tomhau01** [comment]
We have users viewing logs live so having a "follow" feature would be super convenient. Think of it like a console type of view :)

**Comment by eddycharly** [comment]
There was some changes/improvements around logs recently.
It would be nice to get this one too !

**Comment by AlanGreene** [comment]
Agreed this would be really nice, and with the streaming changes should also give a better UX.

@stevesoaress is currently working on some [changes to the processing and display of the log content](https://github.com/tektoncd/dashboard/issues/895) so I think it would be a good idea to hold off on implementing this until those changes stabilise to avoid conflicts / rework.

**Comment by AlanGreene** [comment]
Design notes:
- default behaviour: should it follow logs by default, and stop when the user scrolls or should it be opt-in?
- should there be some UI control to toggle the following?
- if there is a UI control, when should it be displayed and where should it be located? Should it affect just the current logs or persist globally?
- review common patterns in existing solutions for reference.

Investigate existing libraries such as `react-lazylog` which provide follow functionality and determine if they're suitable as replacements for our existing logs component or whether we should keep our own and enhance it with the scroll / follow functionality.

**Comment by AlanGreene** [comment]
We should keep this simple and follow by default, stopping when the user scrolls. This shouldn't require any additional dependencies.

**Comment by AlanGreene** [comment]
Mostafa will be working on this.

**Comment by AlanGreene** [comment]
Autoscroll was added in https://github.com/tektoncd/dashboard/pull/2119. It's included in the latest nightly builds since 2021/07/13 and will be included in the next Dashboard release (v0.19.0 due in ~1-2 weeks).
