### ISSUE TITLE
Missing permissions for Secrets

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#328]
The secret management panel, appearing soon, shows up the need for some extra permissions when running outside of a permissive environment such as Docker Desktop. 

- Creating secrets fails due to the lack of ability to 'patch' servicaccounts
- Deleting secrets fails due to the lack of ability to 'delete' secrets

These roles appear in two files; gcr-tekton-dashboard.yaml and dev-tekton-dashboard.yaml.

To reproduce the problem:
- Enable the 'Secrets' panel via SideNav.js
- Install on OpenShift
- Create and delete secrets

**Comment by jessm12** [comment]
PR here https://github.com/tektoncd/dashboard/pull/355, tested with POST and DELETE calls and works 🙂

**Comment by jessm12** [comment]
/close
Merged into master 🚀
