### ISSUE TITLE
How to configure tekton dashboard pod log outputPath

### ISSUE THREAD

**Issue by Dairy-cn** [tektoncd/dashboard#3375]
# Feature request

How to configure tekton dashboard pod log outputPath

# Alternatives

I need to add Sidecars on the tekton dashboard deployment, such as the tekton pipelines controller or tekton pipelines webhook, and configure outputPaths and errorOutputPaths on the configmap (config logging) so that log information can be collected on Sidecars. Now I don't know if Tekton dashboard has such a feature that can output pod logs to a file. If so, how should it be configured? Thank you very much.

**Comment by AlanGreene** [comment]
Hi @Dairy-cn, the log output path is not currently configurable.

Can you elaborate on how you plan to use this / why changing the output location is important to you? It's not clear to me if what you've listed under 'alternatives' is actually an alternative you've considered or if it's really just describing what you're currently trying to do.
