### ISSUE TITLE
"Import Tekton resources" requires `.` for directory

### ISSUE THREAD

**Issue by gcharters** [tektoncd/dashboard#339]
# Expected Behavior

Should be able to leave it blank.  The description says, "Repository directory (optional)".  When I'm importing from a github repo and the yaml files are in the root I should be able to leave this field blank.

As an aside, I also found the description a little confusing.
"The path from which resources will be applied at the specified repository" could just say something like. "The location of the Tekton resources in the repository (if not at the root)"

# Actual Behavior

If I leave it blank nothing happens when I click the "Import and Apply" button.

# Steps to Reproduce the Problem

1.  Select "Import Tekton resources" in the dashboard.
2. Fill in the details for a github repo that contains resources in the root of the repo.
3.  Click "Import and Apply"

# Additional Info

None

**Comment by Megan-Wright** [comment]
<img width="1379" alt="Screenshot 2019-07-15 at 10 35 23" src="https://user-images.githubusercontent.com/52741262/61210302-fb023380-a6f3-11e9-811a-7d423b61f5a9.png">

We observed that a pipeline run was kicked off but the above was reported in its logs. The fix will be to update pipeline-0 to apply resources from "." 
PR here: https://github.com/tektoncd/dashboard/pull/349 (pending CLA)

**Comment by a-roberts** [comment]
Fixed by https://github.com/tektoncd/dashboard/pull/349 which is now merged, closing
