### ISSUE TITLE
Investigate Using watcher api through proxy for streaming logs

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/dashboard#350]
Kube api server supports http streaming. This ticket is to prototype using this through the api proxy for logs and possible other events.

**Comment by AlanGreene** [comment]
Related https://github.com/tektoncd/dashboard/issues/327

**Comment by eddycharly** [comment]
Related #1576 
/assign

**Comment by eddycharly** [comment]
/close

Fixed by https://github.com/tektoncd/dashboard/pull/1578
