### ISSUE TITLE
Configuration of Tekton Dashboard service url content path

### ISSUE THREAD

**Issue by Romanecek** [tektoncd/dashboard#3606]
# Feature request

Consider url content path when calling Tekton Dashboard service API

# Use case

Tekton Dashboard service might be exposed on nonroot content path for example `https://my-server/ci/tekton` . 
When falling back for external logs the API call from browser is made to `https://my-server/v1/logs-proxy` instead of `https://my-server/ci/tekton/v1/logs-proxy` .

It would be helpful to have a configuration property to specify the correct path for API calls.

# Alternatives

Here I created some raw solution which works for as at this moment: [https://github.com/tektoncd/dashboard/pull/3607](https://github.com/tektoncd/dashboard/pull/3607)

**Comment by AlanGreene** [comment]
Thanks for raising this @Romanecek. It's actually a bug in the client. For some reason the external logs requests weren't using the correct context root like other APIs. PR opened to address this: https://github.com/tektoncd/dashboard/pull/3614

**Comment by AlanGreene** [comment]
Fix is available in the latest nightly release:
- [release.yaml (read-only)](https://storage.googleapis.com/tekton-releases-nightly/dashboard/previous/v20240916-2efc34c79f/release.yaml)
- [release-full.yaml (read-write)](https://storage.googleapis.com/tekton-releases-nightly/dashboard/previous/v20240916-2efc34c79f/release-full.yaml)

It will be included in v0.51.0 due in the next ~1-2 weeks.
