### ISSUE TITLE
Consistent ordering of Matrix TaskRuns

### ISSUE THREAD

**Issue by AverageMarcus** [tektoncd/dashboard#3613]
# Feature request

I'd like to have the ordering of dynamic TaskRuns generated as part of a Matrix to have a consistent ordering between PipelineRuns. Ideally these would be alphabetical (based on the display name) but currently they use the following logic:

It currently makes 2 passes to determine the order it should display things on the PipelineRun details page:
1. pipelinetask order from the Pipeline definition
2. TaskRun order from `PipelineRun.status.childReferences`

# Use case

We currently use Matrix to run various different test suites in parallel. When tests fail we often re-run the Pipeline after changes are made. It would be very useful to be able to quickly see at a glance if the same test suite failed each time based on their positioning in the list on the dashboard. This is especially useful when the TaskRun's `displayName` is longer than can be displayed on the dashboard causing it to be cut off.

# Alternatives

N/A

# Additional context

* [Slack discussion](https://tektoncd.slack.com/archives/CHTHGRQBC/p1726049369331979)

**Comment by AlanGreene** [comment]
Thanks @AverageMarcus. I discussed this with a few other people last week after our Slack coversation and agree this would be a big improvement to the user experience and should also be safe to do 👍

**Comment by AlanGreene** [comment]
I have some changes in progress to support this new ordering. It needs a good bit of testing to verify it's safe but so far it's looking like less work than anticipated and should be included in the upcoming v0.51.0 release 🤞 I can also provide a nightly release for you to verify the behaviour before then.

> This is especially useful when the TaskRun's displayName is longer than can be displayed on the dashboard causing it to be cut off.

Can you share some more info about this? What's the typical pipeline task name or display name length in your pipelines? What's your typical window size?

We have some design changes planned for other parts of the PipelineRun details page so it could be a good opportunity for us to revisit how these are displayed too.

**Comment by AverageMarcus** [comment]
🤦  It had never occured to me that it was cut off because of my window size. 😆 

I have an ultra-wide monitor but tend to have 3 windows side-by-side. It's not too bad on my setup but I get a little bit of cut-off on a some display names, e.g.

![Screenshot 2024-09-17 at 8 19 02 AM](https://github.com/user-attachments/assets/be6456d3-b4a1-45fc-bc68-6363af9a36b2)

Although in my case I could also rename them to be shorter so this is really a non-issue and not something I would focus on.

**Comment by AlanGreene** [comment]
It's easy to miss the simple things 😸 You can also collapse the left nav for even more space if you weren't already aware. I do that sometimes if I'm watching a particularly long-running pipeline.

**Comment by AlanGreene** [comment]
This is available in the latest nightly release:
- [release.yaml (read-only)](https://storage.googleapis.com/tekton-releases-nightly/dashboard/previous/v20240917-611fbe2ceb/release.yaml)
- [release-full.yaml (read-write)](https://storage.googleapis.com/tekton-releases-nightly/dashboard/previous/v20240917-611fbe2ceb/release-full.yaml)

and will be included in v0.51.0 due in the next week or so.

**Comment by AlanGreene** [comment]
v0.51.0 was released today including this change
Thanks again for the suggestion @AverageMarcus
