### ISSUE TITLE
Allow manual intervention to Tekton pipelines

### ISSUE THREAD

**Issue by fpt-dylan-datnt305** [tektoncd/dashboard#3656]
# Feature request

Allow manual intervention to Tekton pipelines

# Use case

Currently we are defining several tasks for a pipeline, each will run in a specific order/condition. However, we want to add some manual intervention to Tekton as a condition for the next step to be run, e.g. when we have finished the build task, before we want to run the deploy step, we will need a approve/reject button so that if we reject, it will not run the next task; otherwise if we approve it will continue to run the next task.

# Alternatives

# Additional context

**Comment by AlanGreene** [comment]
Hi @fpt-dylan-datnt305, thanks for the request.

This functionality is not natively supported by Tekton Pipelines, however there are some community custom tasks that support manual approval that can be used to achieve this.

See for example:
- https://github.com/openshift-pipelines/manual-approval-gate
- https://github.com/automatiko-io/automatiko-approval-task
  This one also provides a Tekton Dashboard extension listing the status of any pending approvals

Closing as there's nothing for the Tekton Dashboard to do here.
