### ISSUE TITLE
service account panelling in the UI

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#366]
Further to the management of secrets, we should look at managing service accounts, specifically as we will be wanting to patch the service accounts with the secrets and potentially (I guess) remove (unpatch) secrets from the service accounts.

Presumably we should also allow for the creation and deletion of service accounts.

**Comment by dibbles** [comment]
@kimholmes - for awareness @mnuttall thought this would indeed be useful.  I don't appear to have sufficient privileges to add labels

**Comment by mi-wang** [comment]
working on it!

**Comment by kimholmes** [comment]
Related:
https://github.com/tektoncd/experimental/issues/53
https://github.com/tektoncd/experimental/issues/38

**Comment by mi-wang** [comment]
Invision link:
https://ibm.invisionapp.com/share/J7NZ50VTXBZ

**Comment by kimholmes** [comment]
@dibbles Here is Michelle's updated design for Service Accounts:
https://ibm.invisionapp.com/share/QXNZ5IT8SR2#/screens

**Comment by mii-w** [comment]
Updated Invision Link:
https://ibm.invisionapp.com/share/QXNZ5IT8SR2

**Comment by dibbles** [comment]
@mii-w there could be multiple imagePullSecrets I think, therefore I think these would need to be in a table per the other secrets (i.e 2 table, one "Secrets" and one "ImagePullSecrets")

**Comment by kimholmes** [comment]
In our last design review, it was mentioned that we may not want to include the ability to "CREATE" service accounts. Can we confirm whether or not this is a requirement.
@dibbles @mnuttall

**Comment by mii-w** [comment]
Thank you for the feedback! Just came back from vacation! :)

![Screen Shot 2019-08-20 at 2 17 46 PM](https://user-images.githubusercontent.com/51759906/63373142-61aee880-c355-11e9-8752-a34912f88800.png)
![Screen Shot 2019-08-20 at 2 17 55 PM](https://user-images.githubusercontent.com/51759906/63373144-6378ac00-c355-11e9-931b-0bd5a4480345.png)
![Screen Shot 2019-08-20 at 2 18 00 PM](https://user-images.githubusercontent.com/51759906/63373149-66739c80-c355-11e9-9095-2a75801ba3fa.png)

**Comment by mii-w** [comment]
Service Account Main View
<img width="867" alt="Screen Shot 2019-08-23 at 10 35 53 AM" src="https://user-images.githubusercontent.com/51759906/63600615-e6864600-c591-11e9-867b-ebd524ce3b20.png">

Detailed view of specific Service Account
<img width="869" alt="Screen Shot 2019-08-23 at 10 36 03 AM" src="https://user-images.githubusercontent.com/51759906/63600712-13d2f400-c592-11e9-8f70-7db83bcdee55.png">

view YAML
<img width="628" alt="Screen Shot 2019-08-23 at 10 36 10 AM" src="https://user-images.githubusercontent.com/51759906/63600750-23523d00-c592-11e9-89ad-c9fe08ebd356.png">

Clicking Edit
<img width="632" alt="Screen Shot 2019-08-23 at 10 36 20 AM" src="https://user-images.githubusercontent.com/51759906/63600760-2baa7800-c592-11e9-9dea-ba6dd604dc7e.png">

Editing a Secret
<img width="627" alt="Screen Shot 2019-08-23 at 10 36 28 AM" src="https://user-images.githubusercontent.com/51759906/63600794-3a912a80-c592-11e9-82a5-6f6d0e7e42cb.png">

**Comment by ncskier** [comment]
Discussed this offline, and documenting here. The ServiceAccounts page should have the following responsibilities.

Users can:
- see the "secrets" and "image pull secrets" that have been patched to the ServiceAccount
- patch/unpatch existing Secrets

Users can NOT:
- create/delete ServiceAccounts

FYI @mii-w

**Comment by mii-w** [comment]
Update: 
<img width="934" alt="Screen Shot 2019-09-16 at 4 04 13 PM" src="https://user-images.githubusercontent.com/51759906/64989862-7fac3200-d89c-11e9-827b-578052b94ab0.png">
<img width="935" alt="Screen Shot 2019-09-16 at 4 04 24 PM" src="https://user-images.githubusercontent.com/51759906/64989867-820e8c00-d89c-11e9-9245-f398f9d3eefe.png">
<img width="1079" alt="Screen Shot 2019-09-16 at 4 04 42 PM" src="https://user-images.githubusercontent.com/51759906/64989870-8470e600-d89c-11e9-887c-b14688ef14eb.png">
<img width="1116" alt="Screen Shot 2019-09-16 at 4 06 00 PM" src="https://user-images.githubusercontent.com/51759906/64989873-86d34000-d89c-11e9-8901-b273a10f1ab0.png">

**Comment by ncskier** [comment]
Is https://github.com/tektoncd/dashboard/issues/733 a duplicate of this issue?

**Comment by dibbles** [comment]
looks like it to me - suggest closing one out

**Comment by carlos-logro** [comment]
this one has been merged and #733 looks to be the hi-fidelity designs so that one should stay open for now. 

/close
