### ISSUE TITLE
Dashboard framework

### ISSUE THREAD

**Issue by mii-w** [tektoncd/dashboard#368]
How can we keep the entire dashboard maintain a cohesive look and feel throughout entire experience?
_________________________________________________________________________________________________
How will the page be organized based on information shown? Is it categorized under global or within the page?
- filter bar
- create/import button

Currently there are 'Create' and 'Import' for different pages (Import Tekton Resources, Create Secret), how do we make the user experience cohesive and understandable?

**Comment by mi-wang** [comment]
I am unable to add assignees/labels :(

**Comment by mnuttall** [comment]
Hi @mii-w can you try writing '/assign' in a comment please? What labels would you like added?

**Comment by mii-w** [comment]
> Hi @mii-w can you try writing '/assign' in a comment please? What labels would you like added?

I am sorry, I did not see this sooner. I wanted to add the design label.

**Comment by mii-w** [comment]
Current thoughts on organizing the page framework:
<img width="754" alt="Screen Shot 2019-09-16 at 4 23 03 PM" src="https://user-images.githubusercontent.com/51759906/64990766-745a0600-d89e-11e9-836a-b3b52607f494.png">

Opened left menu:
<img width="915" alt="Screen Shot 2019-09-16 at 4 23 41 PM" src="https://user-images.githubusercontent.com/51759906/64990774-7623c980-d89e-11e9-82e0-e81c640c0174.png">

Import Page:
<img width="811" alt="Screen Shot 2019-09-16 at 4 23 55 PM" src="https://user-images.githubusercontent.com/51759906/64990784-791eba00-d89e-11e9-9298-fe97b41262e1.png">
