### ISSUE TITLE
Generic sorting and filtering widgets

### ISSUE THREAD

**Issue by skaegi** [tektoncd/dashboard#37]
We need to support something similar to ...
![image](https://user-images.githubusercontent.com/541119/55988517-10d60780-5c72-11e9-9132-4da8adcc7273.png)

**Comment by kimholmes** [comment]
@skaegi That will baked into the final visual design. We'll be using components from the IBM Design Language.

**Comment by kimholmes** [comment]
Working on this user flow. Would love feedback:

**Default state:**
![TektonFilter1](https://user-images.githubusercontent.com/21316329/63121298-1326d600-bf72-11e9-8846-b5bb06a8651e.png)

**Hover state:**
![TektonFilter2](https://user-images.githubusercontent.com/21316329/63121318-1f129800-bf72-11e9-8a67-c185a454ad96.png)

**Click state:**
![TektonFilter3](https://user-images.githubusercontent.com/21316329/63121341-2df94a80-bf72-11e9-8888-6ef62c81cd44.jpg)

**Typing state. User can press enter or select from the dropdown:**
![TektonFilter4](https://user-images.githubusercontent.com/21316329/63121556-bd066280-bf72-11e9-8a5a-ebd8fd7dd85e.jpg)

**Filter added:**
![TektonFilter5](https://user-images.githubusercontent.com/21316329/63121607-ddceb800-bf72-11e9-9147-2d12ad1c8791.jpg)

**Comment by jessm12** [comment]
Thanks for these designs @kimholmes! 😄The current implementation that I have is filtering only on label (labelKey:labelValue) and there is no dropdown functionality. I think the dropdown could be a great enhancement to add to the filtering down the line.

One question I do have is would the intention be to populate these filters in the dropdown by doing a lookup on all Pipeline Runs to find all of the labels that are on them for example? A thought I would have there is that if you have hundreds of them this could be a lot of additional computation and there could be a large amount of matches that may overwhelm the space within the dropdown and that may well slow things down depending on your network/cluster.

Also, generally I think the filters would be in the form of key:value pairs so `branch:master` or `name:tekton` though there could be scope where we could accept some singular values if we are searching across multiple fields perhaps but it should probably be something as standardised as possible. I think this could definitely use further discussion over the design and technical considerations 😅

**Comment by AlanGreene** [comment]
Basic label-based filtering implemented. No current plan to add the more advanced filter dropdown from the designs above although we can revisit in future if we change how we're using the Kubernetes APIs to give us more flexibility in this area.
