### ISSUE TITLE
HTTPS support - via Ingress

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#370]
Given that extensions and the dashboard do/could deal with confidential data (i.e secrets), then we should be communicating over https rather than http.

**Comment by a-roberts** [comment]
Some ideas, notes and questions for how to implement this...

Users provide a certificate/keypair that we mount in and listenAndServeTLS on from our main Go restful server.

Could we provide scripting to make this easier? 
Would letsencrypt be of use? 
How do other dashboard-like services use it?
What yaml changes would be required to have it mounted in?
Users are required to manage the cert for the lifetime of their install - would need to document this clearly.

Are there any "built-in" certificates we could refer to based on target platforms we know about - could people refer to certs that exist and are available on, for example, IBM Cloud Private or OpenShift?

**Comment by akihikokuroda** [comment]
I assume that the user access to the dashboard via the ingress.  Is this about between the user and the ingress or the ingress to the dashboard?  The OpenShft ingress gets the default certificate signed by the OpenShift cluster by default.
  
https://docs.openshift.com/container-platform/4.1/authentication/certificates/replacing-default-ingress-certificate.html

**Comment by akihikokuroda** [comment]
For the OpenSift, the ingress must be created by the Ingress Operator instead of the kubernetes' way.  https://docs.openshift.com/container-platform/4.1/networking/ingress-operator.html

**Comment by mnuttall** [comment]
@akihikokuroda will we get this for free as part of the work you're doing to make he Dashboard installable as an addon via the Tekton Operator?

**Comment by mnuttall** [comment]
If picking this up after #388 but before we have Ingress-via-Operator, follow the docs in Aki's link above to add OpenShift-HTTPS-Ingress support to the interim Ingress added under 388.

**Comment by akihikokuroda** [comment]
I couldn't make the TLS work with the ingress for the dashboard so far but I could make it work with the route in the OpenShift.  

`oc create -f route.yaml` 

contents of the route.yaml is:
```
apiVersion: v1
kind: Route
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
spec: 
  host: tekton-dashboard.9.37.222.145.nip.io
  to:
    kind: Service
    name: tekton-dashboard
  tls:
    termination: edge
```
For this TLS, the certificate signed by the OpenShift cluster is used.
![certificate1](https://user-images.githubusercontent.com/16141898/62299610-43835600-b443-11e9-9914-5eb7037f9316.png)
![certificate2](https://user-images.githubusercontent.com/16141898/62299626-48e0a080-b443-11e9-81c5-15e39d6ae68b.png)
Is this acceptable solution for now?

**Comment by carlos-logro** [comment]
@a-roberts @mnuttall 

with the help of @akihikokuroda & @vtereso i managed to replace the the current CA with a HTTPS one in OpenShift. here are the steps I took:

*pre-requisites*
1) Tekton-pipelines installed in OpenShift
2) dashboard installed in OpenShift
3) dashboard cloned

*Steps:*
1) delete the current route if one is created
`oc delete route <{route name}> -n tekton-pipelines`

2) create a private key for the CA & add passphrase
**Make sure name is lowercase alphanumeric, . or -. Must start & end with alphanumeric characters**
`openssl genrsa -des3 -out <{name-of-private-key}>.pem 2048`

3) generate the root CA 
** fill the information being asked, if you want to leave it black type . & enter**
`openssl req -x509 -new -nodes -key <{name-of-private-key}>.pem -sha256 -days 1825 -out <{certificate-name}>.pem`

4) for some reason the key wasn't being parsed when trying to create it with oc so this command fixes it
`openssl rsa -in <{name-of-private-key}>.pem -out <{name-of-private-key}>.pem`

5) create the secret
`oc create secret tls <{certificate-secret-name}> \
     --cert=<{/path/to/certificate}> \
     --key=<{/path/to/key}> \
     -n tekton-pipelines`

6) edit basic ingress yaml file:
**I hardcoded the host file**
before: 
```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
spec:
  rules:
  - host: replacemeingress.nip.io
    http:
      paths:
      - backend:
          serviceName: tekton-dashboard
          servicePort: 9097```
after:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
spec:
  tls:
  - hosts:
    - tekton-dashboard.<{ipi}>.nip.io
    secretName: <{certificate-secret-name}>
  rules:
  - host: tekton-dashboard.<{ipi}>.nip.io
    http:
      paths:
      - backend:
          serviceName: tekton-dashboard
          servicePort: 9097
```

7) apply the yaml file:
`kubectl apply -f ingress/basic-dashboard-ingress.yaml`

8) Done. Your know suppose to access the host with https://tekton-dashboard.<{ipi}>.nip.io

**Comment by carlos-logro** [comment]
<img width="501" alt="Screen Shot 2019-08-01 at 4 12 25 PM" src="https://user-images.githubusercontent.com/49996607/62324332-4304b280-b477-11e9-9904-1e72a554c03d.png">

**Comment by a-roberts** [comment]
Thanks Carlos for the above, we have Aki's work that's on OpenShift too using their certificate so I'm wondering if we can repurpose what you've documented above as part of a "local" story (I would like us all to be using https locally instead of just on OpenShift really, especially for demos).

While OpenShift 3.11 is our only real platform of importance rn for Kabanero, I still think having it secure locally is very much desired.
