### ISSUE TITLE
Add custom resource extensions

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/dashboard#371]
### Resource type extensions

Extensions shouldn't need to be pieces of UI in other services. One use case would be to have a rendering of a custom resource in the cluster. To do this extensions should be defined as their own resources. These resources will be read on start up and tell the dashboard the have a rendering for these under extensions. They will be exposed under the get extensions endpoint. One caveat to this would be rbac. When a user wants to register a CRD as an extension it would also need a role allowing the dashboard SA to access the resources. A user will be expected to create the appropriate role binding on the cluster.

**Comment by AlanGreene** [comment]
Initial implementation delivered and documented, closing. Enhancements can be handled in a separate issue.
