### ISSUE TITLE
Use InlineNotification for rebuild notification

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#372]
# Expected Behavior
The rebuild notification can now be an inline one with an onClick event for the action that links to the new PipelineRun - this is desirable as it'll be full div width as opposed to just a toast that appears at the top of the page covering only a fifth of it

The subtitle will say the existing text

Have a play at http://react.carbondesignsystem.com/?path=/story/notifications--inline

# Actual Behavior
![image](https://user-images.githubusercontent.com/12814972/61780742-f4ae3e80-adfa-11e9-8811-4357eb8781f5.png)

# Steps to Reproduce the Problem

1. Rebuild a PipelineRun

**Comment by jessm12** [comment]
Merged https://github.com/tektoncd/dashboard/pull/472
/close
