### ISSUE TITLE
Implement strategy for handling CVEs in dashboard code

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#378]
@dibbles and I have been considering our release strategy and came up with the following actions (some we can implement immediately as secure best practices). It'd be useful to get some feedback here and some of these tasks are directly actionable as well.

- Ensure PRs fail when npm audit fails (can action now)
- Ensure repository owners are emailed for CVEs: leverage GitHub email notifications to owners? @bobcatfish any thoughts? I have a few repositories that have a top-level package.json and get notified if any issues with modules come up. Can action now
- Consider our retest and release process (we don't yet have dashboard releases or extension releases): let's use the third digit when we need to periodically retest and release
- Admittedly outside the scope of the dashboard project, but for any supported pipelines - what images are they using and are they CVE free?

**Comment by AlanGreene** [comment]
I'd be reluctant to fail PR builds based on `npm audit` due to the number of false positives / reports that don't apply to specific use of flagged packages.

For notifications are you referring to GitHub Security Alerts? https://help.github.com/en/articles/about-security-alerts-for-vulnerable-dependencies

**Comment by a-roberts** [comment]
Hmm, good point, yeah they'll be treated on a case by case really so I'm not sure about definitely failing the build...

Yep, GitHub security alerts - so we need to see what has to be done for us to get them 🤔

**Comment by a-roberts** [comment]
Strategy's in place insofar as when we npm ci, if there are any module vulnerabilities we'll npm audit fix and then do a push, there's nothing actionable here now that I want to take so I'm closing this.
