### ISSUE TITLE
Implement consistency across UI tables

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#379]
<h1>Expected Behaviour</h1>
All of the tables within dashboard should have a consistent look in terms of style, colours and position on the page.

<h1>Actual Behaviour</h1>

![Screenshot 2019-07-25 at 14.42.55.png](https://images.zenhubusercontent.com/5d25b016e0bbdc62005f7da6/1c19350a-0a1d-411f-8ff1-c448a6af223f)

VS:

![Screenshot 2019-07-25 at 14.43.22.png](https://images.zenhubusercontent.com/5d25b016e0bbdc62005f7da6/7c157e8f-0829-43a9-9d03-6b0f5067fc76)

<h1>Steps to Reproduce the Problem</h1>
Install the dashboard, compare the pipelines panel and the secrets panel.

**Comment by a-roberts** [comment]
^^ PR merged so closing
