### ISSUE TITLE
Support for actions on dashboard resources

### ISSUE THREAD

**Issue by skaegi** [tektoncd/dashboard#38]
Resources described by the dashboard should also permit "Actions". For example "deleting" a PipelineRun or "creating" a new PipelineRun from a Pipeline. To start we might use the universal kebab similar to...
![image](https://user-images.githubusercontent.com/541119/55991877-331f5380-5c79-11e9-8221-0fda66958bec.png)

**Comment by a-roberts** [comment]
@skaegi this is another one we may want to now close I think, so for posterity and anyone who finds this, we support all kinds of actions for resources through our Tekton Dashboard and the Webhooks Extension now, and for any new functionality those should be new issues I reckon

Users are encouraged to take a look at our DEVELOPMENT.md doc to see the APIs we offer (and referring to Simon's specific example, one can definitely create PipelineRuns 😄 )

**Comment by AlanGreene** [comment]
@a-roberts we're currently implementing some of this (dropdown on resources to cancel / delete runs for example) in https://github.com/tektoncd/dashboard/pull/613

**Comment by AlanGreene** [comment]
Closing this as we've added some functionality addressing this (e.g. ability to stop / delete PipelineRuns).
We'll open new issues for additional functionality / design updates.
