### ISSUE TITLE
Sometimes tasks page doesnt auto update with pass / failure 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#385]
This appears to be intermittent as sometimes it happens and sometimes it doesn't 

Had a pipelinerun open on the tasks it was running 
It didnt update to say it had passed the tasks it was running and didnt update to the next step of the pipelinerun to deploy-simple

Also didnt update when it completely failed 

It appears to be stuck on podsinitialising / Status of Not Run

 ![Screenshot 2019-07-29 at 12.57.00.png](https://images.zenhubusercontent.com/5cfe69e3171db04ec3637b76/0a609c24-42e7-428c-b946-0ecb44f1d25e)

![Screenshot 2019-07-29 at 12.51.25 2.png](https://images.zenhubusercontent.com/5cfe69e3171db04ec3637b76/41b999b1-a0cd-4189-a1eb-1d07e0537dae)

![Screenshot 2019-07-29 at 12.59.37.png](https://images.zenhubusercontent.com/5cfe69e3171db04ec3637b76/811ff6e4-12ad-4c7e-8318-8397a1f8a1a5)

**Comment by AlanGreene** [comment]
Looks similar to https://github.com/tektoncd/dashboard/issues/383

**Comment by CarolynMabbott** [comment]
@AlanGreene 
I'm using:
Running on Minikube 
Latest dashboard / pipelines 
Accessing via Chrome 
Port forwarded the pod 
Kubernetes Client v = "v1.11.1"
Kubernetes Server v ="v1.15.0"
