### ISSUE TITLE
TestExtensionRegistration is still flaky

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#389]
# Expected Behavior
Our tests should be reliable and pass conistently

# Actual Behavior
See https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_dashboard/388/pull-tekton-dashboard-unit-tests/1156162276311437312/, timed out again

```
I0730 11:22:44.471] {"level":"debug","msg":"Extension Controller detected extension 'extension2' created"}
I0730 11:22:44.471] {"level":"info","msg":"Adding Extension extension2"}
I0730 11:22:44.471] {"level":"debug","msg":"Registering path: /v1/extensions/extension2"}
I0730 11:22:44.471] --- FAIL: TestExtensionRegistration (10.04s)
I0730 11:22:44.471]     routes_test.go:370: Checking extension registration
I0730 11:22:44.471]     routes_test.go:510: Timed out waiting for expected services to be registered
```

# Steps to Reproduce the Problem

1. Run our unit tests, perhaps repeatedly

# Additional Info

**Comment by AlanGreene** [comment]
Still an issue: https://github.com/tektoncd/dashboard/issues/433

**Comment by a-roberts** [comment]
Having a look at this now, my plan is to run it multiple times and potentially extend that timeout period again, recording duration times as well to see if we're really on the boundary and figuring out what takes potentially ages.

**Comment by a-roberts** [comment]
PR https://github.com/tektoncd/dashboard/pull/467

**Comment by a-roberts** [comment]
Merged so closing
