### ISSUE TITLE
Authentication: OIDC integration

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#396]
Further to #370 and #395 many users will wish to require a login to access the dashboard. 

Get this working first on OpenShift. It is not clear if Ingress/Routes can be configured to require and prompt for OIDC authentication, or if this must be performed by the dashboard itself.

**Comment by akihikokuroda** [comment]
Here is my understanding for OpenShift.  
1. OpenShift has the OAuth server but doesn't have the OIDC OP.
1. At lease one of the identity providers must be configured for the OAuth server (https://docs.openshift.com/container-platform/4.1/authentication/identity_providers/configuring-htpasswd-identity-provider.html)
1. The dashboard needs to implement the OAuth flow.

**Comment by akihikokuroda** [comment]
I found that this can be used to enable the login for the dashboard.
https://github.com/openshift/oauth-proxy
I could make the OpenShift login screen pop-up when I access to the dashboard.

**Comment by akihikokuroda** [comment]
The oauth-proxy works as the sidecar of the dashboard.  I'll update the deployment of the dashboard.  It will be only for the OpenShift.  I'll create another directory in the config directory and place the updated dashboard yaml file.

**Comment by akihikokuroda** [comment]
PR for this: https://github.com/tektoncd/dashboard/pull/406
The OpenSjhift doesn't have the OIDC provider.  It has the Oauth server.  This PR provides authentication to access the dashboard by utilizing the Oauth server.
