### ISSUE TITLE
Deleted pipelineruns / taskruns do not get removed from the dashboard unless manually refresh the page 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#397]
Deleted pipelineruns and taskruns do not automatically get removed from the dashboard even after switching to different tabs in the dashboard
The dashboard must be manually refreshed for these deleted pipelineruns / taskruns to be removed from the dashboard

This should be changed so that the pipelineruns / taskruns tab in the dashboard gets updated without the need to manually refresh the page

**Comment by AlanGreene** [comment]
These should be automatically removed and I verified in my environment that this does happen, I suspect this is similar / related to the other intermittent issues reported:
- https://github.com/tektoncd/dashboard/issues/385
- https://github.com/tektoncd/dashboard/issues/383

So far I have been unable to reproduce these myself, although I suspect the websocket connection is being dropped in some cases and I am working on an update to handle reconnects correctly.
