### ISSUE TITLE
Created PipelineRun isn't immediately displayed when made through UI

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#401]
# Expected Behavior
My new PipelineRun should immediately appear on the page

# Actual Behavior
If I create a PipelineRun using the form, I get notified where I can find my new PipelineRun's info. I'm on the PipelineRuns page and I have to refresh to see my new run.

# Steps to Reproduce the Problem

1. Create a PipelineRun
2. Observe no details visible yet
3. Refresh, observe they are

![image](https://user-images.githubusercontent.com/12814972/62534893-fbe53b80-b841-11e9-824d-403c0c6db27f.png)

![image](https://user-images.githubusercontent.com/12814972/62534904-00a9ef80-b842-11e9-91a0-b3654632e1ed.png)

**Comment by AlanGreene** [comment]
Refresh shouldn't be necessary, looks similar to https://github.com/tektoncd/dashboard/issues/397
