### ISSUE TITLE
Retrieving logs isn't reliable (at least for PipelineRuns)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#402]
# Expected Behavior
I should reliably be able to get the pod logs for, say, a PipelineRun

# Actual Behavior
![image](https://user-images.githubusercontent.com/12814972/62535728-102a3800-b844-11e9-93aa-b4b02e9f7130.png)

```
k logs pipeline0-run-1563965113813607200-pipeline0-task-rk8pk-pod-ffa940 -c build-step-kubectl-apply

task.tekton.dev/kaniko created
```

```
{"level":"debug","msg":"Upgrading connection to websocket..."}
{"level":"debug","msg":"In getAllExtensions"}
{"level":"debug","msg":"Extensions: [{Name:webhooks-extension URL:10.111.162.12 Port:8080 DisplayName:Webhooks BundleLocation:web/extension.0dbb4841.js}]"}
{"level":"debug","msg":"Forwarding to url : https://10.96.0.1:443/api/v1/namespaces"}
{"level":"debug","msg":"Forwarding to url : https://10.96.0.1:443/apis/tekton.dev/v1alpha1/clustertasks"}
{"level":"debug","msg":"Forwarding to url : https://10.96.0.1:443/apis/tekton.dev/v1alpha1/namespaces/tekton-pipelines/pipelineruns/pipeline0-run-1563965113813607200"}
{"level":"debug","msg":"Forwarding to url : https://10.96.0.1:443/apis/tekton.dev/v1alpha1/namespaces/tekton-pipelines/tasks"}
{"level":"debug","msg":"Forwarding to url : https://10.96.0.1:443/apis/tekton.dev/v1alpha1/namespaces/tekton-pipelines/taskruns"}
{"level":"debug","msg":"Forwarding to url : https://10.96.0.1:443/apis/dashboard.tekton.dev/v1alpha1/extensions"}
{"level":"error","msg":"websocket connection to client lost: websocket: close 1001 (going away)"}
{"level":"error","msg":"Error: the server rejected our request for an unknown reason"}
```

# Steps to Reproduce the Problem

1. Install the latest release of Tekton pipelines, the dashboard (from source) and the webhooks extension
2. Create a simple PipelineRun
3. Observe the lack of successful log retrieval 😢

**Comment by AlanGreene** [comment]
In your `k logs` command I see you're still using the `build-step-` container prefix. Is this a run that was created on an older Tekton version? If so this is expected behaviour.

The `build-` prefix was dropped in pipeline v0.5, so I'd expect to see `step-` for containers created on a recent version. The dashboard also checks for the container name in the step status to ensure we stay in sync with any future changes, and falls back to `step-<stepname>` if not found. However this does mean that logs for TaskRuns created before v0.5 are not accessible in the dashboard.

**Comment by a-roberts** [comment]
Phew, yeah the above was from Jess' set up and that's from an older run 😅 

I'll see if I can reproduce this now on the latest with my own set up, otherwise I'll close, thanks for taking a look

**Comment by a-roberts** [comment]
Closing, all is well with my set up using the latest Tekton and our code. At least anyone who encounters this can read the above and figure out why their logs may not be retrieved! Thanks Alan, closing
