### ISSUE TITLE
Rework /ingress for OpenShift

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#409]
Issue https://github.com/tektoncd/dashboard/issues/387 added a /ingress API which returns the 'host' value of an Ingress called 'tekton-dashboard' in the requested namespace. 

PR https://github.com/tektoncd/dashboard/pull/406 adds HTTPS and OAuth support, and creates a `Route` called `tekton-dashboard` - but not an `Ingress`. The 'Host/Port' field of the Route contains the information that we would want returned via the /ingress API. 

We could extend the getIngress() code to additionally handle Routes of the same name with a valid Host field. This would make /ingress a bad name for the API though -  '/externalEndpoint' might be better, or '/externalAccess'. We might decide to create a new endpoint and deprecate /ingress if we go down this route.

**Comment by akihikokuroda** [comment]
I'll create a new endpoint '/externalEndpoint'.  It will return an array of the endpoints.  The element of the array will have the URL and type of the endpoint.  The first element of the array is the default endpoint.

**Comment by mnuttall** [comment]
Hi @akihikokuroda thanks for picking this up. 
- Please can we make endpoint '/endpoints' - you're returning an array, and as per https://github.com/tektoncd/dashboard/blob/master/DEVELOPMENT.md we tend to use plurals. I should have thought of that when writing the issue. 
- Please be sure to contact the https://www.eclipse.org/codewind/ team who I believe are expecting to consume this API as early as next week. 

Thank you!

**Comment by akihikokuroda** [comment]
PR: https://github.com/tektoncd/dashboard/pull/414
