### ISSUE TITLE
Document API definitions

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#41]
Now that we have DEVELOPMENT.md we should document our APIs. We'll want return codes, paths, any errors that can happen, and bonus points for any json snippets!

**Comment by a-roberts** [comment]
/assign

I'll start on this, I have a bunch already written up from before we open sourced that I'll push as an initial commit to my branch and then let's look at making it awesome.

**Comment by AlanGreene** [comment]
In line with 'making it awesome' I think it would be useful to document the APIs as a Swagger / OpenAPI spec, new issue to track that https://github.com/tektoncd/dashboard/issues/42

**Comment by a-roberts** [comment]
Changes are now merged, closing 😄
