### ISSUE TITLE
Lock down supporting images in dashboard release

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#413]
The https://github.com/tektoncd/dashboard/releases/download/v0.1.0/openshift-tekton-dashboard.yaml contains some image coordinates that should be locked down. For example, 
 ```
      - name: oauth-proxy
        image: openshift/oauth-proxy:latest
 ```
and
 ```
  - name: kubectl-apply
    image: lachlanevenson/k8s-kubectl
 ```

Ideally we need a way (a script?) of determining the tags - ideally shas - of the currently supported supporting images levels at the point of producing a release. 

This work should ideally be performed as part of a more automated Dashboard release process. For 0.1.0 it may be sufficient to create and stage new versions of the release yaml files that contain the locked down shas.

**Comment by akihikokuroda** [comment]
I'll add sha for these 2 examples.  How about the dashboard image?

**Comment by akihikokuroda** [comment]
PR: https://github.com/tektoncd/dashboard/pull/418
adding sha for these 2 images

**Comment by mnuttall** [comment]
Hi @akihikokuroda beyond determining the SHAs for the current release, I wrote, 
> Ideally we need a way (a script?) of determining the tags - ideally shas - of the currently supported supporting images levels at the point of producing a release.

I think what we'd like is to have :version tags on the images in the yaml in git, and then :sha tags when we produce releases. Is there a way to efficiently pull the :tagged images and determine their SHAs via script? It obviously happens for the Tekton images but I'm not sure where the code is that does that.

**Comment by akihikokuroda** [comment]
Automated adding sha tag to external images: PR: https://github.com/tektoncd/dashboard/pull/434
