### ISSUE TITLE
Possibility to view / describe Tekton resources

### ISSUE THREAD

**Issue by sdaschner** [tektoncd/dashboard#417]
It would be very helpful if there was a way to see the details of resources, such as tasks or pipelines, similar to the Kubernetes dashboard.

Right now, for example, when selecting a task, we only have the information for the specific taskruns available, not the general description of that task, unless I'm missing something.

This might be related to #38, with actions such as delete/edit/view YAML, etc.

**Comment by AlanGreene** [comment]
Hi @sdaschner, thanks for raising this issue. If you're looking for a raw YAML view of the Task / Pipeline resources, you can click on the info icon to the right of the entry on the list view.

![image](https://user-images.githubusercontent.com/2829095/62887524-547e7200-bd35-11e9-9514-b89f8a74c5d5.png)

![image](https://user-images.githubusercontent.com/2829095/62887684-a7f0c000-bd35-11e9-864f-497a3b806432.png)

This is currently available on the Pipelines, Tasks, and ClusterTasks views linked from the main navigation on the left.

**Comment by AlanGreene** [comment]
@sdaschner I hope the info above was helpful. If you had something else in mind we'd love to hear your thoughts. Closing this for now but we can reopen if needed.
