### ISSUE TITLE
Dashboard pod crashes

### ISSUE THREAD

**Issue by andgoldin** [tektoncd/dashboard#423]
# Expected Behavior

When following [Vic Iglesias](https://github.com/viglesiasce)'s [tekton workshop](https://github.com/viglesiasce/tekton-workshop), the dashboard remains running.

# Actual Behavior

After a short period of time, the browser displays the following:
```
Error: Could not connect to Cloud Shell on port 8080.
Ensure your server is listening on port 8080 and try again.
```

# Steps to Reproduce the Problem

1. Follow the instructions for the [Tekton Workshop in Qwiklabs](https://events.qwiklabs.com/classrooms/4752).
2. Follow the [Tekton workshop instructions in the README](https://github.com/viglesiasce/tekton-workshop/blob/master/README.md).
3. A short time after opening the web preview from the GCP console, the errors start appearing.

# Additional Info

The dashboard pod enters a CrashLoopBackOff state with the following stack trace:
```
{"level":"debug","msg":"Upgrading connection to websocket..."}
{"level":"error","msg":"Could not upgrade to websocket connection: websocket: request origin not allowed by Upgrader.CheckOrigin"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xffb8b0]
goroutine 166 [running]:
github.com/tektoncd/dashboard/vendor/github.com/gorilla/websocket.(*Conn).SetPongHandler(0x0, 0xc000817c60)
        /workspace/go/src/github.com/tektoncd/dashboard/vendor/github.com/gorilla/websocket/conn.go:1124 +0x20
github.com/tektoncd/dashboard/pkg/websocket.readControl(0x0, 0xc000210ac0, 0xc000817c20)
        /workspace/go/src/github.com/tektoncd/dashboard/pkg/websocket/websocket.go:58 +0x75
created by github.com/tektoncd/dashboard/pkg/websocket.WriteOnlyWebsocket
        /workspace/go/src/github.com/tektoncd/dashboard/pkg/websocket/websocket.go:44 +0x66
```

**Comment by a-roberts** [comment]
Hey @aldgodlin, thanks for reporting this and glad we made it into a workshop! We've never seen this issue on openshift, minishift or docker desktop, when you say "a short time", how long are we talking? I'm keen to go for the reproduce given access to a cluster

@vtereso FYI, there's a juicy looking error here too

**Comment by vtereso** [comment]
@a-roberts I'll make a quick patch regarding the panic.

**Comment by a-roberts** [comment]
Thanks Vincent, willing to give this a go! @andgoldin can you please run with this once you get a chance? It's a really benign change so I'll get it merged and hopefully gets you further - please let us know how you do progress
