### ISSUE TITLE
Rebuild doesn't copy labels from the PipelineRun that is being rebuilt

### ISSUE THREAD

**Issue by jessm12** [tektoncd/dashboard#424]
# Expected Behavior
All labels from the original `PipelineRun` are copied onto any rebuild of it 
# Actual Behavior
The labels are not copied. I noticed this problem particularly when using the webhooks-extension and trying to delete all `PipelineRuns` for a given webhook as the rebuilds were not also deleted due to them not having the relevant labels. 
# Steps to Reproduce the Problem

1. Create a `PipelineRun` with labels via the webhooks-extension or otherwise 
2. Rebuild the `PipelineRun` using the rebuild button 
3. Check the labels on the rebuilt PipelineRun - they have not been copied over

**Comment by a-roberts** [comment]
See https://github.com/tektoncd/dashboard/blob/master/pkg/endpoints/pipeline.go#L567, I thought I had handled this, should have added a test case and working code! 😭

**Comment by jessm12** [comment]
https://github.com/tektoncd/dashboard/pull/445 the fix 😄

**Comment by jessm12** [comment]
Merged so closing 🚀 
/close
