### ISSUE TITLE
Support Tekton Pipelines 0.6.0

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#437]
Tekton Pipelines 0.6.0 is incompatible with the current dashboard 
There are a number of breaking changes such as triggers and changes to the file github.com/tektoncd/dashboard/vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1

**Comment by a-roberts** [comment]
Carolyn's actively working this, we've fixed the parameter passing now for created PipelineRuns and removed the trigger type, the next step is to focus on remaining errors in pipeline.go. Carolyn's suggested we create a new 0.2.0 release that supports Tekton Pipelines 0.6 while keeping our 0.1.x line as the one supporting Tekton 0.5.2.

We'd obviously need to test the compatibility with the webhooks extension too and hopefully not need to create a new release of that (although I'll be surprised if this isn't the case).

**Comment by a-roberts** [comment]
This is merged so closing, creating a new release for it can be done outside of this issue
