### ISSUE TITLE
Investigate ko for building

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#44]
While adding https://github.com/tektoncd/dashboard/pull/27 @vdemeester asked a question in a review comment:  `Out of curiosity, what doesn't work with ko ?`, and I've honestly not tried using `ko` before with this project.

Prove we can use `ko` to build and push and update DEVELOPMENT.md if so.

For tektoncd/pipeline I see lots of kodata folders (e.g. [here](https://github.com/tektoncd/pipeline/tree/master/cmd/controller)).

It would be very cool to recommend doing a `ko apply` and it'll just build and deploy our containers; at the least for now we can make sure it builds and deploys the backend using what's at `install`.

Useful resources:
- #ko channel at https://knative.slack.com
- https://github.com/google/ko

We've had success building and pushing knative repositories and tektoncd/pipeline both locally and to public Dockerhub, including updating the readme for tektoncd/pipeline to use a local registry. It's likely we can be more inline with what's done for tektoncd/pipeline and if so let's advocate that.

**Comment by skaegi** [comment]
Let's make this a priority as it lets other devs try the dashboard out easily. We also want to make it very easy to grab the latest pipeline and mix with the latest dashboard.

I'm working on #14 and need something to mix the front-end with the back-end and will take a look at using ko but feel free to assign to yourself and do this just for the back-end if you're ready.

**Comment by a-roberts** [comment]
Yeah, I'm gonna look at this now (I've been working on a compatibility tester using Travis and the runs take *ages*). https://triggermesh.com/2019/03/07/go-binaries-kubernetes-ko/ this actually looks really easy: notice the gopath style image location.

/assign

**Comment by a-roberts** [comment]
I was stumped as I didn't realise the folder needed to be called `config`: we were using `config` to store frontend config files!

I've got `ko apply -f config` working fine now, pushing to my Dockerhub, so I'm updating our docs now and the webpack const definition to read from config_frontend instead of config for the json.

**Comment by a-roberts** [comment]
Merged a couple days ago, closing 🎉
