### ISSUE TITLE
Top-level GUI layout 

### ISSUE THREAD

**Issue by pkruithofjr** [tektoncd/dashboard#45]
Posting a proposed image of the Top-level GUI layout to begin iterating on a design.  

![k8s-bw](https://user-images.githubusercontent.com/10145212/56058007-4ccea280-5d2e-11e9-87f2-fb2fca16e20c.png)

**Comment by dibbles** [comment]
I think it would be worth clarifying what this issue is for/how it differs from #35

**Comment by mnuttall** [comment]
Closing this in favour of #35.
