### ISSUE TITLE
Extension development sample fails.

### ISSUE THREAD

**Issue by stobias123** [tektoncd/dashboard#450]
# Expected Behavior
Run through docs on extension, create resources.

# Actual Behavior
The example service/image deployed return the error 

```
Failed to fetch dynamically imported module: http://localhost:9097/v1/extensions/dashboard-extension//bundle
```

# Steps to Reproduce the Problem
```
kubectl apply -f docs/samples/extension/config/tekton-extension-sample-service.yaml \
              -f docs/samples/extension/config/tekton-extension-sample.yaml
```

Click `tekton_dashboard_extension` link

```
 stobias > webhooks-extension >> master $ curl http://localhost:9097/extensions/dashboard-extension/

404 page not found
```

**Comment by a-roberts** [comment]
I'll have a look at this now on Docker Desktop

**Comment by a-roberts** [comment]
Reproduced the problem, PR at https://github.com/tektoncd/dashboard/pull/483

**Comment by a-roberts** [comment]
@stobias123 changes now merged into master so closing this, thanks for reporting it!
