### ISSUE TITLE
Dashboard information architecture

### ISSUE THREAD

**Issue by pkruithofjr** [tektoncd/dashboard#46]
Here is a first pass at the information architecture for the dashboard.  Please provide feedback. 

Tekton
- Pipeline
- PipelineRun
- PipelineResource
- Task
- TaskRun

Namespace

Extension Category 1 [from Service metadata] Knative Eventing
- Extension topic 1
- Extension topic 2

Extension Category 2 [from Service metadata] Native worker agent
- Extension topic 1
- Extension topic 2

**Comment by dibbles** [comment]
I think it would be worth clarifying what this issue is for/how it differs from #35

**Comment by mnuttall** [comment]
Closing in favour of #35
