### ISSUE TITLE
Import resource errors under race condition

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#469]
# Expected Behavior

Import of pipeline resources should create pipelineresources, create pipelinerun, execute successfully.

# Actual Behavior

Although the dashboard log has the resources being created in order, presumably due to some async nature, the resources are not always created in k8s in the correct order, in such a situation the pipeline run then fails stating that the pipelineresource does not exist.

# Steps to Reproduce the Problem

1. Import pipeline resources

# Additional Info

![Screenshot 2019-09-03 at 09 51 58](https://user-images.githubusercontent.com/22838162/64158512-86648f00-ce30-11e9-9226-2f02730b751c.png)

**Comment by a-roberts** [comment]
Note that the create pipelinerun code is changing to use the frontend/K8s proxy API now, so for whoever picks this up take a look at ImportResources.js. 

There's a resource creation.then block and then the creation of the PipelineRun occurs. 

We should make sure the resource exists first (potentially waiting a second before we go to create the run) or implement a poll/wait for loop - I can't think of a cleaner way to implement this rn. 

FWIW the failure rate seems to be quite low, I've yet to reproduce this in 10+ runs but may be on a faster system than Duane (I think using OpenShift on our Fyre cluster). Carlos' frontend code: https://github.com/tektoncd/dashboard/blob/cfd07f7a4b65fb5884b2ed372d2f81a90c970eea/src/containers/ImportResources/ImportResources.js

**Comment by a-roberts** [comment]
Note that Carlos' code isn't merged yet so this still can't/shouldn't be picked up yet

**Comment by a-roberts** [comment]
Carlos' stuff is merged, note that I'm sure this isn't specific to our Tekton Dashboard code either, seeing this testing our latest everything on OpenShift 3.11:

```
[root@requite1 foo]# k get pipelineresource | grep newhook
newhook-docker-image-dvmv6                 3m
newhook-git-source-hjjgw                   3m
[root@requite1 foo]# k get pipelineresource --all-namespaces | grep newhook
tekton-pipelines   newhook-docker-image-dvmv6                 3m
tekton-pipelines   newhook-git-source-hjjgw                   3m

[root@requite1 foo]# k get pipelinerun
NAME                       SUCCEEDED   REASON               STARTTIME   COMPLETIONTIME
newhook-1568812173-ht82k   False       CouldntGetResource   3m          3m

[root@requite1 foo]# k get pipelinerun -o yaml | grep hjjgw
        name: newhook-git-source-hjjgw
        couldn''t retrieve referenced input PipelineResource "newhook-git-source-hjjgw":
        pipelineresource.tekton.dev "newhook-git-source-hjjgw" not found'
```

Resulting in 

![image](https://user-images.githubusercontent.com/12814972/65151784-b01bd980-da1e-11e9-89fd-54cbd394ff5e.png)

**Comment by a-roberts** [comment]
Likely could be fixed utilising https://github.com/tektoncd/pipeline/pull/1324

**Comment by CarolynMabbott** [comment]
This cant be done yet as it requires us to be on master of tekton pipelines or next release to get that change needed to have the resourceSpec in the pipelines yaml

**Comment by a-roberts** [comment]
@ncskier @mnuttall  FYI too, we should discuss whether we want these changes going into master or not - I personally think they should and our master should always work with master, but I'm wary about our upcoming release for Kabanero and I'd like us to get bug fixes in without needing to maintain multiple branches... hmm.

**Comment by anneqm** [comment]
@a-roberts @dibbles is this still an issue now that #688 is closed?

**Comment by a-roberts** [comment]
Being addressed now as part of https://github.com/tektoncd/dashboard/issues/1257 so let's close in favour of that where it's being worked
