### ISSUE TITLE
Run any pipeline endpoint

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#47]
The purpose of this issue is to provide an endpoint that creates a PipelineRun for any existing Pipeline, and to discuss how to go about implementing this endpoint.

The Pull Request for issue https://github.com/tektoncd/dashboard/issues/24 is a good start to creating PipelineRuns. But it was limited to creating specific PipelineRuns for the `Pipeline templates within our templates repository` https://github.com/pipeline-hotel/example-pipelines (here's a reference to the comment: https://github.com/tektoncd/dashboard/pull/33#issuecomment-482502528)

Moving forward, the user should be able to start PipelineRuns for any Pipeline definition they have created. To do this, they must be able to specify the following (according to the Tekton docs https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md):
- pipelineRef
- trigger
- resources
- params
- serviceAccount
- timeout
- [nodeSelector]
- [affinity]

If we assume that the PipelineResources, Secrets, ServiceAccount, etc. that the PipelineRun uses already exist, then we do not need to do very much work to create the PipelineRun. All we have to do is convert the input JSON to the Go client [PipelineRun](https://godoc.org/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1#PipelineRun) (and [PipelineRunSpec](https://godoc.org/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1#PipelineRunSpec)), then create the PipelineRun resource. The input JSON would look very similar to a K8s JSON definition of a PipelineRun. With this approach, the user would create all the resources required for the PipelineRun individually.

If we create PipelineRuns in this simplified manner, then it frees up our code to focus on verification. We can add checks to verify that all the required resources specified by the PipelineRun actually do exist and play nicely with each other. For example, we could verify that if a PipelineRun uses a private Git PipelineResource, then the ServiceAccount must have a Secret with the proper annotation for `https://github.com` (and if it doesn't, then our UI can prompt the user to create & patch the secret).

This approach is different from that in issue https://github.com/tektoncd/dashboard/issues/24, which creates all the resources necessary for the PipelineRun, and then creates the PipelineRun, knowing that everything is set up properly. While it works well for specific Pipelines, I think it will be hard to extend to work for any type of Pipeline.

I think the approach of creating resources individually with an emphasis on verification that I outlined above will work well for creating general PipelineRuns. What do you think @jessm12 @a-roberts ? Is there an alternate implementation that you have in mind? @skaegi What are the front-end concerns  for this kind of PipelineRun endpoint?

**Comment by jessm12** [comment]
I agree this sounds good @ncskier! 😄 I like the comment about adding verification to make things easier and more robust. I do think that it would be possible to refactor and extract from/add to the code in the PR for issue https://github.com/tektoncd/dashboard/issues/24 to fit with this more general way of working. The bulk of the code that is there at the moment is dealing with the creation of resources and resource refs but if we take that step out of PipelineRun creation then it could be simplified and generalised greatly. So for example the code for the json to PipelineRun resource creation code is pretty much already there under `definePipelineRun`.

I think we want to decide whether it should be possible then to create PipelineResources through the UI, my thought was that perhaps this could be in a series of steps towards creating a PipelineRun, first being to select the Pipeline that you want to run, then defining and creating any resources if they are required (so simply providing a git repo and revision for example, maybe this could be pre-populated depending on the UI flow) and then to actually create the PipelineRun as the final step, the main thing here would then be providing params and the handful of other things that can be defined like ServiceAccount and timeout. 

The main difference with a more general approach would be dynamic resources and params for a PipelineRun. I think it may be important though going forward that we decide on a UI flow that will make the most sense and be user friendly that will allow us to create the most reasonable endpoints for the functionality we want to provide.

**Comment by vtereso** [comment]
I do like the idea of being able to intelligently apply Tekton/K8s resources (in the correct order) from some location so that everything is done for you sort of like Helm (Resources to PipelineRun), but I do think that being able to create CRDs as flexibly as possible is best (as long as it is valid).

**Comment by vtereso** [comment]
To document in this issue, there is an ongoing effort related to the experimental/eventing side of Tekton and once merged, this should more or less be available out of the box.

**Comment by ncskier** [comment]
This issue was covered/completed by issue https://github.com/tektoncd/dashboard/issues/108
