### ISSUE TITLE
PipelineRun link on status table does not work for openshift

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#476]
# Expected Behavior

The link in the status table on the pull request is supposed to navigate into the dashboard.

# Actual Behavior

The link is not the correct URL, it is using the default localhost rather than the openshift route.  Clearly the endpoints REST endpoint is going wrong somewhere - looks like the sink is getting a malformed URL response, possibly due to trying to access http at port 443

# Steps to Reproduce the Problem

1. Create webhooks on an openshift system
2. Create pull request on the repo
3. Click the link in the status table that is added into the pull request

# Additional Info

**Comment by a-roberts** [comment]
@dibbles fixed this as part of https://github.com/tektoncd/experimental/pull/214 which is now merged, closing
