### ISSUE TITLE
Dashboard doesn't allow secret creation containing 0, error message shows incorrect info

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#480]
I want to create secret Batman10 but I get the following error 

![Screenshot 2019-09-03 at 14.38.06.png](https://images.zenhubusercontent.com/5cfe69e3171db04ec3637b76/d13537d1-893f-41e8-99fa-a907b4498641)

It happens regardless of where the 0 is in the secret 

A user should be allowed to have a secret with 0 in the name

**Comment by a-roberts** [comment]
PR https://github.com/tektoncd/dashboard/pull/481

**Comment by a-roberts** [comment]
Fixed and merged so closing
