### ISSUE TITLE
TaskRun / PipelineRun view should show one step expanded by default

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#488]
# Expected Behavior
When following a link to a TaskRun / PipelineRun, the user should be presented with useful information without requiring additional action, specifically we should ensure that one step is expanded by default.

The most useful would likely be the first failed step (if any), otherwise the first step available.

# Actual Behavior
When the page loads the user is presented with a mostly empty experience on the right hand side. We present the overall status of the TaskRun / PipelineRun, and the tree view on the left shows the status summary (complete, failed, in progress, etc.) of the individual tasks, but we do not show the detailed status / logs for steps until the user selects one.

# Additional Info
When importing resources via the dashboard we provide a link to the corresponding PipelineRun in the success notification. It would be more useful to the user if following this link displayed the logs instead of the current collapsed view.

**Comment by AlanGreene** [comment]
We now expand the first step by default, so the remaining work is to identify the first failing step and select that if present.

Moving this issue back to the backlog to prioritise some other work. Anyone else feel free to pick it up in the meantime.

**Comment by kimholmes** [comment]
@AlanGreene Alan, we should keep this in mind for the new diagram design work. Sounds like it will contain to this new design as well. 
<img width="301" alt="image" src="https://user-images.githubusercontent.com/21316329/67134080-2195a600-f1de-11e9-91a5-d043a0d202a4.png">

**Comment by carlos-logro** [comment]
merged so closing
/close
