### ISSUE TITLE
On-boarding Guide for New Users

### ISSUE THREAD

**Issue by adunderwood** [tektoncd/dashboard#496]
# Expected Behavior

I would like to look into creating an on-boarding guide for new users. The github documentation is very good and well-maintained but what I am hoping for is to find and address a quick win for the user so that they understand quickly what they can use the dashboard for. Something that when they first fire up the product they can see it in action. 

Important note: I am not proposing one of those guided tours that comes up as an overlay and points out what the buttons do. This would just be like a how-to guide that we could publish in various places 

# Actual Behavior

It bites you on the hand (gently) when you try to pet it.

# Steps to Reproduce the Problem

Install the dashboard and try to use it.

# Additional Info

Possible first tasks:

- Walk the user through importing the example pipelines and describe what the examples do. This task engages pipeline zero, which gives us an opportunity to explain what is happening. Right now it takes the user to the pipeline watch page (diagram) which isn’t very self-explanatory. 

- If the user has a pipeline YAML file available, walk them through importing the YAML file and using the pipeline

- If they don’t, give instructions for how to create one, even if it’s just a link to the existing documentation

- Point out features that the dashboard has that they can’t get from anywhere else except the dashboard

- Create a webhook, which there is already a guide for and is very good but it's an extension and requires a separate installation

**Comment by vtereso** [comment]
Maybe this could see some overlap with the website that is underway. Last WG ([video link](https://drive.google.com/file/d/1pGPbK4M3Z3yMjgeNmVWSARIP6VccZ-ah/view)), some tutorial based stuff was demonstrated.
