### ISSUE TITLE
Tekton cat should say meow when clicked on

### ISSUE THREAD

**Issue by adunderwood** [tektoncd/dashboard#498]
# Expected Behavior

Cats say meow.

# Actual Behavior

The cat does not meow.

# Steps to Reproduce the Problem

1. Click on or hover over the Tekton cat 
2. Observe no meow

# Additional Info

This is a very serious issue that should be addressed with the most urgent response time. 

Honestly just a tooltip on hover that says "meow" would solve the problem.

**Comment by dibbles** [comment]
repeated clicking should make it hiss ....
