### ISSUE TITLE
Patch more than one service account to each secret

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#505]
### Expected Behaviour ###
We should be able to patch more than one service account when creating a secret within the secrets panel. 

### Actual Behaviour ###
The secrets modal only allows for patching one service account per secret created.

**Comment by CarolynMabbott** [comment]
Will need to complete #320 before this can be started, PR for 320 is almost done

**Comment by a-roberts** [comment]
👍 I see this being a very common use case (e.g. if teams are sharing the same Docker repo and wants to use the same credentials, or pulling from the same GitHub)

> Will need to complete #320 before this can be started, PR for 320 is almost done

This could instead be done as part of the service account panelling effort and thus would be worked on as part of https://github.com/tektoncd/dashboard/issues/366, so to confirm is the suggestion here to allow the multiple addition secret accounts to use like we do for server URLs instead or in addition to that?

See 
![image](https://user-images.githubusercontent.com/12814972/64600412-fa63e180-d3b2-11e9-878d-65be86d3c30a.png) for ref, we could add the - and + buttons again thus allowing multiple service accounts to be selected.

**Comment by kimholmes** [comment]
In a previous design review, it was stated that the requirement should be to let the user patch Service Accounts only during Secret Creation. So, here is the proposed user flow:
![CreateSecret1](https://user-images.githubusercontent.com/21316329/64717244-e6db7800-d491-11e9-84ec-d005ba481cad.png)
![CreateSecret2](https://user-images.githubusercontent.com/21316329/64717295-08d4fa80-d492-11e9-843c-faa24ee70cc3.png)
![CreateSecret3](https://user-images.githubusercontent.com/21316329/64717299-0b375480-d492-11e9-88d6-e873e5fe9850.png)

Secret Detail. The detail view of an individual Secret would show how each Service Account is patched to the Secret (by Secret or by Image Pull Secret).

**Comment by ncskier** [comment]
@kimholmes thanks for adding your designs 🙂 

Since this issue is only about patching a Secret to multiple ServiceAccounts, I think that the only relevant design would be this one: https://user-images.githubusercontent.com/21316329/64717299-0b375480-d492-11e9-88d6-e873e5fe9850.png 👍 

Also, I think we only patch the Secret as a normal secret at the moment (not as an ImagePullSecret), so we won't need those options in the mockup for this issue (@Megan-Wright or @CarolynMabbott please let me know if I am wrong about this).

**Comment by kimholmes** [comment]
@ncskier Thanks! I'll plan to add issues where we can track new issues.

**Comment by mii-w** [comment]
<img width="928" alt="Screen Shot 2019-09-16 at 4 32 50 PM" src="https://user-images.githubusercontent.com/51759906/64991322-ab7ce700-d89f-11e9-8261-440d69861229.png">
<img width="926" alt="Screen Shot 2019-09-16 at 4 32 59 PM" src="https://user-images.githubusercontent.com/51759906/64991324-acae1400-d89f-11e9-9ec1-80159035771b.png">

**Comment by ncskier** [comment]
@mii-w I don't think the wording "Patch Service Accounts onto "SecretName" is exactly accurate; it also sounds sort of confusing. This view is adding a Secret to a number of ServiceAccounts (the ServiceAccount contains the name of the Secret). So, I think a better title would be something like: `Add Secret to Service Accounts` or `Add to Service Accounts` (if you don't like the word `add`, then maybe `attach`). If you want to keep the word "patch," then `Patch Secret to Service Accounts` or `Patch to Service Accounts`.

**Comment by kimholmes** [comment]
FYI - This is the latest version of this screen:
![6  Secrets_Finish](https://user-images.githubusercontent.com/21316329/67133641-c5ca1d80-f1db-11e9-8740-408305655db2.png)

**Comment by mnuttall** [comment]
Carlos: review scheduled with Alan over webex.

**Comment by a-roberts** [comment]
Now merged so closing
