### ISSUE TITLE
Notification for deleting secrets

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#506]
### Expected Behaviour ###
A notification should appear on deleting a secret to confirm that the secret has been deleted.
### Actual Behaviour ### 
When a secret is deleted via the dashboard there is no notification.

**Comment by vtereso** [comment]
This is also being tracked here: https://github.com/tektoncd/dashboard/issues/269.

**Comment by a-roberts** [comment]
Merged so closing
