### ISSUE TITLE
TestExtensionRegistration is still (still!) flaky

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#513]
# Expected Behavior
It should reliably pass
# Actual Behavior

See https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_dashboard/512/pull-tekton-dashboard-unit-tests/1171461781227311105/
which mentions

```
I0910 16:42:29.890] {"level":"debug","msg":"Registering path: /v1/extensions/extension1/robots"}
I0910 16:42:29.890] {"level":"debug","msg":"Registering path: /v1/extensions/extension1/secrets"}
I0910 16:42:29.890] {"level":"debug","msg":"Registering path: /v1/extensions/extension1/pipelineruns"}
I0910 16:42:29.891] {"level":"debug","msg":"Extension Controller detected extension 'extension2' created"}
I0910 16:42:29.891] {"level":"info","msg":"Adding Extension extension2"}
I0910 16:42:29.891] {"level":"debug","msg":"Registering path: /v1/extensions/extension2"}
I0910 16:42:29.891] --- FAIL: TestExtensionRegistration (10.03s)
I0910 16:42:29.891]     routes_test.go:371: In TestExtensionRegistration
I0910 16:42:29.891]     routes_test.go:514: Timed out waiting for expected services to be registered
I0910 16:42:29.892] FAIL
I0910 16:42:29.892] FAIL	github.com/tektoncd/dashboard/pkg/router	10.239s
I0910 16:42:29.892] ?   	github.com/tektoncd/dashboard/pkg/testutils	[no test files]
I0910 16:42:29.892] ?   	github.com/tektoncd/dashboard/pkg/utils	[no test files]
I0910 16:42:29.892] ?   	github.com/tektoncd/dashboard/pkg/websocket	[no test files]
I0910 16:42:30.276] ===========================
```

@Megan-Wright and I have already been in this test - I resolved a duplicate extension key issue (so there's only one being registered), and Megan's increased the timeout, yet we're still seeing a problem here.

# Steps to Reproduce the Problem

1. Run our unit tests (perhaps even locally, especially on Prow though)

**Comment by AlanGreene** [comment]
Another: https://storage.googleapis.com/tekton-prow/pr-logs/pull/tektoncd_dashboard/545/pull-tekton-dashboard-unit-tests/1176805492756844544/build-log.txt

**Comment by AlanGreene** [comment]
https://storage.googleapis.com/tekton-prow/pr-logs/pull/tektoncd_dashboard/613/pull-tekton-dashboard-unit-tests/1180113917184053249/build-log.txt

**Comment by a-roberts** [comment]
Still seeing this after a month https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_dashboard/641/pull-tekton-dashboard-unit-tests/1184052369046900736/

**Comment by carlos-logro** [comment]
/unassign 
after debug logs were merged, not closing just in case it the test keep flaking

**Comment by a-roberts** [comment]
We've not seen it in ages so I reckon we're good to close this, cheers @carlos-logro
