### ISSUE TITLE
Add a test for pipeline0 (into e2e tests or compatibility)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#518]
# Expected Behavior
We should have a test that kicks off pipeline0 and imports resources - this is the "backend" of our import resources functionality. Ideally on OpenShift as well as Prow 😄 

# Actual Behavior
We don't have this as part of https://github.com/tektoncd/dashboard/pull/425/files or https://github.com/tektoncd/dashboard/tree/master/test, which means that https://github.com/tektoncd/dashboard/issues/515 is only manually picked up by testing it ourselves on, say, OpenShift in this case, and thus pipeline0 (used to import resources) doesn't work.

Note that the actual cause is describe at https://github.com/tektoncd/dashboard/issues/515 (OpenShift specific, needing to add types specifically), but either way we currently have no automated protection against breaking changes in upcoming Tekton Pipeline releases - and we should.

**Comment by a-roberts** [comment]
Not a priority so this is going in the icebox

**Comment by eddycharly** [comment]
Pipeline0 was removed a while ago.
Shall we close the issue ?

**Comment by a-roberts** [comment]
Yep 😄
