### ISSUE TITLE
Dashboard webui not rendering on Firefox 60.9.0esr 

### ISSUE THREAD

**Issue by bconey** [tektoncd/dashboard#528]
# Expected Behavior
Dashboard should render on Firefox 60.9.0esr(64bit) on macOS Mojave Version 10.14.6 and show Pipelines, TaskRuns, etc.

# Actual Behavior
Tekton dashboard does render on the FireFox 60.9.0esr(64-bit) installed on macOS Mojave Version 10.14.6 - receiving error `Error loading Pipelines Forbidden` message when viewing the dashboard 

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/31766760/64966784-6c35a280-d86d-11e9-89be-0e80ca30e130.png">

# Steps to Reproduce the Problem

1. On macbook with installation of Firefox 60.9.0esr, open browser to Tekton dashboard 
2.
3.

# Additional Info

**Comment by a-roberts** [comment]
Thanks @bconey for reporting this, what platform did you install this on so we can rule out any RBAC issues? Any errors reported from the Tekton Dashboard pod?

@dibbles has observed this too I think and had to clean out a bunch of Firefox related data (obviously not ideal)

**Comment by bconey** [comment]
@a-roberts Installed on Openshift 3.11 and no errors were logged in the Tekton Dashboard pod's log at the time the page was rendered

**Comment by a-roberts** [comment]
Hmmmmm, so I've installed from source and did a `kubectl proxy` and I can see everything fine on my **laptop** using this Firefox 60 version

![image](https://user-images.githubusercontent.com/12814972/65970079-c33a9a80-e45d-11e9-906e-efdf9ddcc531.png)

Mac OS X 10.14.6.

I deployed the latest code onto my OpenShift 3.11 cluster too just now, added the security exception, logged in when prompted, and see Forbidden everywhere, with this browser version.

Specifically I did
- git clone
- kubectl apply -f config/openshift --validate=false
- modify tekton-dashboard deployment to use an image built on my laptop (I don't have a dev set up on the OpenShift machine)

With the **latest** Firefox version (69, not from ESR), I don't get this problem - accessing the exact same endpoint. I'm gonna check the release notes between versions, wondering if it's to do with not having an actual login token/cookie in use...

**Comment by a-roberts** [comment]
With Firefox 60 I don't see the cookie being passed in with the request (we get back 2x set-cookie in the response), in 69 it is set.

@AlanGreene any thoughts? We experienced cookie fun before...

**Comment by AlanGreene** [comment]
https://github.com/tektoncd/dashboard/pull/599 should fix this 🤞 Tested locally against your environment using a local proxy and it loads as expected.

**Comment by a-roberts** [comment]
![image](https://user-images.githubusercontent.com/12814972/66000182-ce5dec80-e496-11e9-861e-a80ad02bca31.png)

verified Alan's fix, merged so closing
