### ISSUE TITLE
Import resource does not work if pipeline0 not in target namespace

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#537]
# Expected Behavior

pipeline0 should only need to be in the install namespace, and should be able to import resources into a target namespace

# Actual Behavior

Error occurs: Unable to load PipelineRun details: CouldntGetPipeline
Pipeline default/pipeline0 can't be found:pipeline.tekton.dev "pipeline0" not found

# Steps to Reproduce the Problem

1. Import resources into an alternative namespace

# Additional Info

Pipeline0 is able to install into a target namespace, yet the front end dashboard code seems to be passing the target namespace as the location to create pipelineresources and the pipelinerun for pipeline0

**Comment by a-roberts** [comment]
Merged so closing
