### ISSUE TITLE
Validation of secrets created in dashboard

### ISSUE THREAD

**Issue by mtamboli** [tektoncd/dashboard#538]
# Expected Behavior
In Tekton Dashboard -> Creating secrets
It would be nice to have validation for the secrets entered. Currently, you can enter incorrect user/password or server URL and the secret is created successfully. It would be nice to have the option to validate them. It could also be a separate option after creation or at the time of submit.
Especially with the URL, it has happened that user had a typo in server URL which was hard to find https://githud.com instead of https://github.com. It will make things easier for debugging.
# Actual Behavior

No validations seems to be happening
1. I saw secrets being created with incorrect user/password/URL
![image](https://user-images.githubusercontent.com/29490950/65345239-c6a16c80-dba7-11e9-9817-9ea57107e277.png)

2. In one instance, when creating docker secret with below values: just got this error which is not useful at all. It did not have option to correct anything and all the entered information was lost.
![image](https://user-images.githubusercontent.com/29490950/65345312-f6e90b00-dba7-11e9-9d2c-71c80b4ddb7c.png)

![image](https://user-images.githubusercontent.com/29490950/65345344-0ec08f00-dba8-11e9-94ac-b57ee708ac69.png)

# Steps to Reproduce the Problem

1. Create Secrets from Tekton Dashboard
2.
3.

# Additional Info

**Comment by AlanGreene** [comment]
For 1, I don't think the dashboard should be responsible for validating that the credentials provided are correct. We should however ensure that any useful logs or other indicators are correctly surfaced to the user in case of tasks depending on these secrets failing. Some of this will be covered by https://github.com/tektoncd/dashboard/issues/572 and related issues.

For 2, https://github.com/tektoncd/dashboard/issues/611 should address this by ensuring the error is displayed in the modal, allowing the user to take corrective action without losing the input data.
