### ISSUE TITLE
Add ability to take default values when creating secret in tekton dashboard

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#543]
@tam512 commented on [Mon Sep 23 2019](https://github.com/tektoncd/experimental/issues/256)

# Expected Behavior
when create a new secret in the tekton dashboard, the `Server URL` text box shows greyed out url https://github.com.  If I want to use the same url, I need to retype the exact same url in the text box.  Please add the capability for users to take the default url or modify the existing default url.

# Actual Behavior
Below is the current server url when creating a new secret, users can't copy the existing url but need to type in the same url or new url  
![image](https://user-images.githubusercontent.com/22480038/65445499-f941a400-ddf7-11e9-9a1e-0bea0a4ca29b.png)

# Steps to Reproduce the Problem

1. in tekton daskboard, click Secrets > Add Secret to see the panel

# Additional Info

**Comment by dibbles** [comment]
Have moved this issue to dashboard repo.

**Comment by a-roberts** [comment]
Merge in progress so closing
