### ISSUE TITLE
Cannot scroll up/down on view of yaml on Google Chrome only

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#551]
Expected Behaviour
When viewing a pipeline's etc. YAML on the dashboard on google chrome I should be able to scroll up and down to view the entire code.

Actual Behaviour
I can scroll from side to side to view the extent of the YAML content but cannot scroll up and down, even though there is clearly more of the YAML that I am unable to see.

**Comment by AlanGreene** [comment]
Which Chrome version are you seeing this in? Are you on macOS / Windows?

Testing latest dashboard code (master) with Chrome 77.0.3865.90 on macOS I cannot reproduce this. I am able to scroll the entire right portion of the page vertically as expected.

![image](https://user-images.githubusercontent.com/2829095/65680704-68fd9c00-e04f-11e9-94f5-54f1d3b2acc6.png)

Are there any errors in the browser console when you reproduce this? What size is the browser window when this happens?

**Comment by Megan-Wright** [comment]
I'm using version 76.0.3809.132 on macOS

**Comment by Megan-Wright** [comment]
Covered in #581
