### ISSUE TITLE
Errors when creating a PipelineRun when namespace is not selected 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#552]
Get the error of `Error retrieving Pipeline information` when trying to create a PipelineRun on the dashboard. 
This appears to be because I haven't selected a namespace yet. 
Should it be where I can select a Pipeline and then it lists in the namespaces above what namespaces have this Pipeline?
Or should the Pipeline dropdown not be displayed until a namespace has been selected 

![Screenshot 2019-09-25 at 16.13.53.png](https://images.zenhubusercontent.com/5cfe69e3171db04ec3637b76/4dd540d9-085c-42f2-8c88-36cd73736ea7)

**Comment by dibbles** [comment]
Fixing under: https://github.com/tektoncd/dashboard/pull/564

**Comment by a-roberts** [comment]
https://github.com/tektoncd/dashboard/pull/564 now merged so closing, cheers @dibbles
