### ISSUE TITLE
Unclear error message on create PipelineRun

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#553]
I tried creating a PipelineRun and received the following error, it doesnt tell me anything about why the request is bad and why received a 404 

Also the logs don't give any helpful reasons why 

Maybe we could have better error checking / error responses when things go wrong 

![Screenshot 2019-09-25 at 16.23.31.png](https://images.zenhubusercontent.com/5cfe69e3171db04ec3637b76/1b09f692-8c46-4e51-8f16-1218fe22d54a)

![Screenshot 2019-09-25 at 16.25.05.png](https://images.zenhubusercontent.com/5cfe69e3171db04ec3637b76/a412f3ca-1546-48d5-bf48-394db963c51a)

**Comment by carlos-logro** [comment]
manage to replicate the problem but up to now I haven't come up with a solution. This error message I believe is coming from Kubernetes when it couldn't process the values I gave. (In my case I added random values for both `pathToResourceFiles` & `apply-directory` ) Nowhere is the frontend nor backend this string or similar is being sent or initialized.

**Comment by a-roberts** [comment]
Thanks for taking a look @carlos-logro, this doesn't have to be in the 0.2.0 release

There is at least some validation, e.g:

![image](https://user-images.githubusercontent.com/12814972/66031274-f848fa80-e4fa-11e9-8208-59351cc71440.png)

and it's not quite as bad as the lack of secret creation error reporting, so happy to punt on this

**Comment by a-roberts** [comment]
Can't reproduce this any more - tried with the following

1) invalid inputs as Carlos suggested
2) selecting a Git PipelineResource then deleting it using the command line, then clicking to Create - we get an error instead

```
PipelineRun tekton-pipelines/pipeline0-run-1572948719746 can't be Run; it tries to bind Resources that don't exist: Couldn't retrieve PipelineResource: couldn't retrieve referenced input PipelineResource "git-sourcen26gd": pipelineresource.tekton.dev "git-sourcen26gd" not found
```

I've noticed we get back that 404 error when the proxy when there's invalid data, but in this case I can't get it to occur from this page.

If we're going to look into surfacing errors from the proxy better, that's going to be a separate issue and it's not something we should ever be hitting unless we as developers are sending over invalid data.
