### ISSUE TITLE
Timeout box in Create PipelineRun should have validation 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#554]
# Expected Behavior

When i try and type something into timeout that is not a valid option it tells me that its not valid 

# Actual Behavior

I can type meow into the the timeout and it responds with a 404 error instead of a error where cannot press submit

# Steps to Reproduce the Problem

1. Type meow into the timeout box on the create PipelineRun page
2. Observe no error 
3. Click submit and watch as 404 error appears in the console 

# Additional Info

**Comment by dibbles** [comment]
https://github.com/tektoncd/dashboard/pull/578

**Comment by a-roberts** [comment]
Merged so closing
