### ISSUE TITLE
Timeout in Create PipelineRun does not work 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#555]
# Expected Behavior

Adding a timeout to the Create PipelineRun works. Works if you have a timeout of 0 but any other number fails

# Actual Behavior

Adding a timeout to Create PipelineRun brings up an error of 
```
Error creating PipelineRun

an error on the server ("unknown") has prevented the request from succeeding (error code 404)
```
Also brings up an error `{"level":"error","msg":"Error: an error on the server (\"unknown\") has prevented the request from succeeding"}` in the dashboard logs 

# Steps to Reproduce the Problem

1. Try and create a PipelineRun on the Create PipelineRun page
2. Add a timeout in the box
3. Watch it bring up an error 

# Additional Info

![Screenshot 2019-09-25 at 16 36 32](https://user-images.githubusercontent.com/32342288/65616280-b5df6500-dfb2-11e9-84b2-795fcf2804cc.png)

<img width="1116" alt="Screenshot 2019-09-25 at 16 37 13" src="https://user-images.githubusercontent.com/32342288/65616319-c2fc5400-dfb2-11e9-905b-ccbb90d06eea.png">

**Comment by dibbles** [comment]
Technically this is incorrect input, so have clarified input under https://github.com/tektoncd/dashboard/pull/574 .... I think the issue should be left open to add extra field validation for this value

**Comment by dibbles** [comment]
extra validation done under issue 554 - this can be closed
