### ISSUE TITLE
Console errors when looking at  pipelinerun logs in dashboard

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#556]
# Expected Behavior

There are no console errors or log errors when watching logs for a failed pipelinerun 

# Actual Behavior
There are console errors and log errors when watching logs for a failed pipelinerun (May also be on a working pipelinerun, will check to confirm)

# Steps to Reproduce the Problem

1. Create a pipelinrun which will fail 
2. Click on the task straight away 
3. Watch the console logs in inspect and tail the logs for the dashboard
4. Observe errors in both 

# Additional Info
There are console errors when the dashboard is trying to get the logs but the logs may not exist yet

![Screenshot 2019-09-25 at 17 10 05](https://user-images.githubusercontent.com/32342288/65619043-58014c00-dfb7-11e9-81ad-e0ef2426fa2e.png)

The logs also show the error `{"level":"error","msg":"Error: the server rejected our request for an unknown reason"}` but unsure if this is because of failing pipelinerun or other reasons

**Comment by AlanGreene** [comment]
404s are expected if you're attempting to view logs for a step that hasn't begun to execute yet (as in the case of a PipelineRun/TaskRun that has just been created) since the container for that step will not be available.

These particular console errors are generated by the browser in response to a network error, they are not coming from our code.

Once the step begins and the container is created the 404s should stop. Feel free to reopen if this is not the case.

**Comment by CarolynMabbott** [comment]
This may not be a simple 404 error. I'm getting repeated 404 error message when staying on the page which are showing the same error message as above
Not refreshing the page or anything and im getting this 
```
36main.a0472730cbb850737bd2.js:1 GET http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/proxy/api/v1/namespaces/tekton-pipelines/pods/pipeline0-run-1569428123332-r-25800-pipeline0-task-26ls2-pod-e8f353/log?container=step-kubectl-apply 404 (Not Found)
```

The 36 main is just the number of error messgaes its currently at, it hasnt stopped increasing whilst im still on the page

**Comment by AlanGreene** [comment]
The log container polls every 4 seconds until the step is complete, so you will continue to see errors as long as the container is unavailable. Can you verify in your cluster whether the container exists or not?

**Comment by CarolynMabbott** [comment]
The pod running the pipelinerun is stuck in intit:Error 
`pipeline0-run-1569495787503-pipeline0-task-dd6cj-pod-38a637           0/2       Init:Error   0          45m`

The dashboard is showing:
```
Container status:
waiting:
  reason: PodInitializing
name: kubectl-apply
container: step-kubectl-apply
```

Although the pipelinerun has failed 
`pipeline0-run-1569495787503           False       Failed               46m         46m`

Checking the build describe of the pipelinerun is says it failed because `build failed for unspecified reasons.`
Checking the describe of the taskrun says it failed because `Warning  Failed  48m   taskrun-controller  build failed for unspecified reasons.`
