### ISSUE TITLE
No error displayed when trying to create a secret that already exists

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#557]
# Expected Behavior
Shouldnt able to create the same secret twice, shouldnt be able to click submit button and it goes through

# Actual Behavior
Can create the secret but returns 400 error 

# Steps to Reproduce the Problem

1. Create a secret or already have one existing
2. Try and recreate exact same secret
3. Receive 400 error 

# Additional Info
We already display the error in the log so we should be able to check before a user presses submit / or when a user presses submit and tell them it already exists

**Comment by a-roberts** [comment]
Fixed by the changes Carlos made while working https://github.com/tektoncd/dashboard/issues/559, closing (works by surfacing any error that we get back from the k8s client)

@Megan-Wright 😅
