### ISSUE TITLE
Number of characters in secret name can be 253 not less than 253

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#558]
# Expected Behavior
Can not have a secret name with 253 characters

# Actual Behavior
Can create a secret with 253 characters 

# Steps to Reproduce the Problem

1. Create a super long secret name with 253 characters (1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111121212121212121212121212121212121212111111113333333333)
2. Receive no errors 
3. Secret created and is useable 

# Additional Info

**Comment by a-roberts** [comment]
Merge in progress (lgtmed and approved) so closing
