### ISSUE TITLE
Error messages on secrets creation page are unhelpful 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#559]
# Expected Behavior
An error message tells me what is wrong 

# Actual Behavior
Error message tells me Bad Request with no information 

# Steps to Reproduce the Problem

1. Create a duplicate secret on the secrets page
2. Watch as an error appears saying Error Bad Request 

# Additional Info
This is when creating a duplicate secret, other bad error messages also exist in the secrets creation page

**Comment by a-roberts** [comment]
Merged so closing
