### ISSUE TITLE
Task's step(s) showing as success even if they are not

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/dashboard#56]
If a step fails (using `tektoncd/pipeline@master`), dashboard might report it as success even though it is not (hence the task status and the pipeline status in the following screenshot)

![2019-04-16-191519](https://user-images.githubusercontent.com/6508/56230364-5e8cae80-607c-11e9-9809-1fd20ce0943a.png)

Looking at the status, it didn't look at the correct status for the step (the step exited with 1, but the status reported 1)

The screenshot is taken on a run based on the following files : https://sbr.pm/technical/tekton-usage.html#org63ddf32

/kind bug

**Comment by AlanGreene** [comment]
Now that step name is included in task run status (https://github.com/tektoncd/pipeline/pull/657) it should be much easier to reliably match the step / status without relying on order and trying to account for init containers.

/assign

**Comment by AlanGreene** [comment]
@vdemeester issue should be resolved now, let me know if you still get any unexpected step status.
