### ISSUE TITLE
Secrets page will not allow a secret name with the name of "." or "-" or these at the start or end of the secret name

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#566]
# Expected Behavior
The secrets page says i can create a secret using any combination of characters, . or - 
I should be able to create a secret called "." or "-"
I should be able to have a secret called ".123", "-123", "123.", "123-"

# Actual Behavior
I can create a secret called "." or "-" or "123-"
When press submit i get a 400 Bad Request POST error 

# Steps to Reproduce the Problem

1. Create a secret called "." or "-" or "123-" or ".123" without the speech marks 
2. Watch the error in the console 
3.

# Additional Info

**Comment by AlanGreene** [comment]
Should probably be handled along with https://github.com/tektoncd/dashboard/issues/571 as it appears '.' is problematic.

**Comment by a-roberts** [comment]
Merge in progress (lgtmed and approved) so closing
