### ISSUE TITLE
PipelineRun init errors should be displayed in the Tekton Dashboard

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#572]
# Expected Behavior
When a pipelinerun fails it should update the pipelinerun properly 

# Actual Behavior
The pipelinerun fails and is stuck failing without logs  as the pod is stuck in initError state 
There are no logs to explain why it has failed 

# Additional Info

Not just applicable to this example, screenshot below 

![Screenshot 2019-09-26 at 17 22 54](https://user-images.githubusercontent.com/32342288/65706392-4b95f580-e082-11e9-8277-e1047b58495c.png)

**Comment by a-roberts** [comment]
I'm wondering if this can be used to remedy https://github.com/tektoncd/dashboard/issues/560

**Comment by mnuttall** [comment]
I'm not sure what's possible here - use this to investigate whether initialisation errors can be reliably detected, and meaningful messages extracted.

**Comment by AlanGreene** [comment]
We added code to handle some init error cases for https://github.com/tektoncd/dashboard/issues/200
This may need to be updated to include additional classes of error that aren't currently handled.

**Comment by EnriqueL8** [comment]
+ 1 on this feature

**Comment by AlanGreene** [comment]
We should do another review to make sure all cases are covered, and only then close this.

/remove-lifecycle rotten
/reopen

**Comment by AlanGreene** [comment]
I think it would be a good idea to consider this along with https://github.com/tektoncd/dashboard/issues/972 and https://github.com/tektoncd/dashboard/issues/1445 to ensure we provide a good experience and don't introduce too many different mechanisms for accessing errors / logs.

**Comment by AlanGreene** [comment]
Once #1814 is merged init step container details will always be displayed, not just in case of error.
