### ISSUE TITLE
Should not error on rebuild of a cancelled PipelineRun

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#577]
# Expected Behavior
Should not error when try to rebuild a cancelled PipelineRun 

# Actual Behavior
Rebuild a cancelled PipelineRun caused errors and did not run

# Steps to Reproduce the Problem

1. Create a PipelineRun and cancel it
2. Try to rebuild it 
3.

# Additional Info
Causes this error when tried to rebuild 
![Screenshot 2019-09-27 at 10 32 57](https://user-images.githubusercontent.com/32342288/65759144-37013e00-e112-11e9-9707-60a9900b7d2f.png)

This also causes the new PipelineRun to show up in the PipelineRuns page and has the status of it being cancelled even though it didnt run

**Comment by a-roberts** [comment]
Merged so closing
