### ISSUE TITLE
Associate credentials with service account

### ISSUE THREAD

**Issue by akihikokuroda** [tektoncd/dashboard#58]
Credential REST API provides CURD operation for the secrets.   The secrets must be patched into the service account used by the PipelineRun or TaskRun.  It must be done manually now.  This issue enhances the credential REST API to patch the service account automatically when the secret is created or deleted.

**Comment by akihikokuroda** [comment]
Please assign this to me.  Thanks!

**Comment by a-roberts** [comment]
@akihikokuroda thanks Aki for taking this on, I've pinged @vdemeester who's gonna be chasing up the assigning stuff as well as we're going to need a clear set of instructions (or just the right Prow policy?) for folks working on other repositories under our tekton org too, I'd like to then retrospectively assign others who have picked up issues), so leave that with us

**Comment by vdemeester** [comment]
@akihikokuroda @a-roberts so you can use `/assign` to assign yourself (and `/assign user` to assign someone). If the bot is not happy, no big deal at least we know who works on it for the time being :wink: 

/assign @akihikokuroda

**Comment by akihikokuroda** [comment]
PR: https://github.com/tektoncd/dashboard/pull/59
