### ISSUE TITLE
Cancelled TaskRuns Should have steps with finished or failed status

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/dashboard#580]
# Expected Behavior

Steps within a cancelled task run should not show as `running`

# Actual Behavior

They show as running

# Steps to Reproduce the Problem

1. Cancel a pipeline run while steps are in a running state. The Running state stays

# Additional Info

**Comment by AlanGreene** [comment]
Does https://github.com/tektoncd/pipeline/issues/1439 have any impact on this?

**Comment by Megan-Wright** [comment]
@steveodonovan are you still seeing this? I'm struggling to recreate it - when a pipelinerun is cancelled I'm seeing associated taskruns as cancelled as well.

**Comment by steveodonovan** [comment]
Forgot to close the issue. Fixed here https://github.com/tektoncd/dashboard/pull/592
