### ISSUE TITLE
Cant scroll downwards after creating a secret

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#581]
I created a secret on the secrets page in the dashboard 
Once i created the secret I could no longer scroll down, can scroll sideways but just not down or up 
This affects not just secret page but pipelinerun page, looking at pipeline definition (noted in #551 )
Can be sorted by refreshing the page but until you refresh you are unable to scroll down the page in anything 

Running this on:
master of dashboard
Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Happens on both my mac screen and my connected monitor

**Comment by AlanGreene** [comment]
`.bx--body--with-modal-open` is being left on the `<body>` tag which is setting `overflow: hidden`

looks like either Carbon or the SecretsModal isn't cleaning up properly

**Comment by a-roberts** [comment]
@AlanGreene had a look to see if there are any fixes going into Carbon and noticed https://github.com/carbon-design-system/carbon/issues/3945 (perhaps you did too), so yeah based on the closer's comments:
```
Avoid clobbering modal when it's closed (You can still clobber its content, though)
Cleaning-up bx--body--with-modal-open class manually
```

**Comment by AlanGreene** [comment]
No I hadn't seen that, seems like they're suggesting somehow the modal is being removed before it can clean up, not sure how that would happen though.

**Comment by a-roberts** [comment]
Merged so closing
