### ISSUE TITLE
Import resources page is missing validation (at least for GitHub repository URL)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#593]
# Expected Behavior
We should be checking for a valid GitHub repository URL

# Actual Behavior
![image](https://user-images.githubusercontent.com/12814972/65946513-37f5e080-e42e-11e9-89e4-a9a6c6a39d54.png)

# Steps to Reproduce the Problem

1. Import resources from somewhere that isn't even remotely a valid GitHub repository URL
2. Observe the PipelineRun's kicked off fine

# Additional Info
I'm sure we had validation at one point...did we not?!

**Comment by a-roberts** [comment]
Had a look through the history, https://github.com/tektoncd/dashboard/blob/9fb0fc9c5b72932d258c90d8d7db47c669f79775/src/containers/ImportResources/ImportResources.js for the initial commit, so simple URL validation is what I suggest we do here, e.g. http or https as a prefix and at least one slash (because a user could have their own GHE rolled out somewhere at a server url such as https://myserver.mycompany.com)

**Comment by a-roberts** [comment]
As we never had this anyway and it's a case of garbage in garbage out, removing the milestone mention as we want to release 0.2.0 today

**Comment by kimholmes** [comment]
See my comment in this issue about form validation. If you're using Carbon, you should get this function for free:
https://github.com/tektoncd/dashboard/issues/611

**Comment by a-roberts** [comment]
Merged so closing
