### ISSUE TITLE
Consider moving SecretsModal to Components instead of container

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#594]
SecretsModal should probably be in Components instead of Container
Not urgent or affecting functionality

**Comment by AlanGreene** [comment]
The components would need to be refactored to separate the UI from all of the API / store logic and then the pure UI pieces could be moved to the components package. All of the wiring pieces would remain in containers.

**Comment by a-roberts** [comment]
Now sitting under src/components so closing this
