### ISSUE TITLE
Modal does not clear on being displayed

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#603]
When i try and create a secret with a duplicate name it should show an error in the modal so therefore i can change the name in the modal 

Also when i creating a secret and it fails when i go to create a new secret it keeps all of the information in the create secret modal

**Comment by a-roberts** [comment]
The second part of this `and modal does not clear on being displayed` is a bug introduced by https://github.com/tektoncd/dashboard/pull/602, we should aim to fix this for 0.2.0

**Comment by a-roberts** [comment]
Will make a new issue for displaying secret creation errors to be in the modal, closing for the modal not being cleared on display issue (as that's merged)
