### ISSUE TITLE
Create PipelineRun is broken

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#607]
Create PipelineRun is broken 
Try to create a PipelineRun and the following error happens 
Does not matter whether a service account is selected or what pipeline is selected 

![Screenshot 2019-10-02 at 13.22.00.png](https://images.zenhubusercontent.com/5cfe69e3171db04ec3637b76/9f6c211e-bb7b-4ece-8b93-42ea15d50486)

**Comment by a-roberts** [comment]
Merged so closing
