### ISSUE TITLE
Secret creation errors should show in the modal

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#611]
# Expected Behavior
Display the notification on the modal so users can easily change values and try again

# Actual Behavior
The modal closes - it's often inconvenient to reinput data though, so why not display it on the form and suggest what went wrong (e.g. a failure creating it, so I might go on to choose a different namespace) - what's the standard practice?

# Steps to Reproduce the Problem

1. Create a secret  that's going to error
2. Observe where the error is displayed and that the modal's now vanished, prompting reinput of data

**Comment by kimholmes** [comment]
@a-roberts There is a pattern for this in Carbon. Here is a screenshot. I can send you the link in Slack.
![form_notification](https://user-images.githubusercontent.com/21316329/67132890-57379080-f1d8-11e9-8d18-fa8d70bdc258.png)

**Comment by kimholmes** [comment]
FYI - @Megan-Wright @AlanGreene The design team can provide a mock-up of this if helpful.

**Comment by kimholmes** [comment]
Please see #727 for the updated design for Secrets. Note that we removed the usage of modals. The screen should appear as a new page:
![Secrets_Create_New1](https://user-images.githubusercontent.com/21316329/68722377-43870c00-0583-11ea-8c24-f90d9242c334.png)

@AlanGreene I did see this when I tried to recreate the errors (I think your build):
![Secrets_Create_Modal](https://user-images.githubusercontent.com/21316329/68722488-a082c200-0583-11ea-8c6d-2597e3301871.png)

Is this a good example of the errors that could appear? If so, we can create an example in the new design that will address this.

**Comment by a-roberts** [comment]
@kimholmes Looks good, thanks for sharing - the error that appears as a notification appears when the request itself fails (for example when there's a secret that already exists with the same name in the name space).

We plan to get *this* in with tests before the above larger change, also if modals are being removed for secrets (going a bit meta) I assume the same principle applies for creating PipelineRuns manually and the access token create page for the extension.

**Comment by kimholmes** [comment]
@AlanGreene Ok. that makes sense now. And yes, it would be the same for the other scenarios as well. Thanks for the heads up.

**Comment by kimholmes** [comment]
@AlanGreene @Megan-Wright 
Here is the guideline (per Carbon).
1. The user has accidentally selected a namespace that already has a Secret by the same name. The user clicks "Create."
![SecretCreate1](https://user-images.githubusercontent.com/21316329/69065413-b95cfe80-09ed-11ea-9bd7-64dc50900ce8.png)

2. An error appears showing the field that must be corrected. If additional instruction is needed, an Error notification can also be used. Note that the "Create" button is disabled until the user inputs a correct value.
![SecretCreateError](https://user-images.githubusercontent.com/21316329/69065642-148ef100-09ee-11ea-910a-c3875ba5401a.png)

**Comment by kimholmes** [comment]
Correction to the above screen as per our discussion in Office Hours this week:
![SecretCreateError](https://user-images.githubusercontent.com/21316329/69354555-4b634200-0c4e-11ea-8afc-2b46dd8f309a.png)
