### ISSUE TITLE
Look into newly found DAP violations with Tekton Dashboard

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#625]
# Expected Behavior
There should be none

# Actual Behavior
I've ran the dynamic assessment plugin tool and noticed the findings I've attached here

# Steps to Reproduce the Problem

1. Run the latest Tekton Dashboard
2. I used the IBM DAP tool (any IBMer can access said tool and then launch the scan against the running website - apologies to non-IBMers, ping me if you want the account iD and token that you can use and I'll help)
3. Scan and observe findings

Here's the html report (you'll have to rename it from .gif to .html yourself, github doesn't like html uploads and I'm sure for good reason):

![TektonDashboard07October](https://user-images.githubusercontent.com/12814972/66298092-f14e2d80-e8e8-11e9-8e67-a47fe78ad6bf.gif)

For convenience if you don't like said file, here:

![image](https://user-images.githubusercontent.com/12814972/66298147-0c20a200-e8e9-11e9-836c-e89cf31de536.png)

**Comment by CarolynMabbott** [comment]
https://github.com/carbon-design-system/carbon/issues/4461

Issue made as cant add aria-labels required for DAP violations
