### ISSUE TITLE
PipelineRun and TaskRun pages are completely broken

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#630]
Expected Behaviour:
The PipelineRun and TaskRun pages should be working as normal

Actual Behaviour: 
I cannot access either of these pages - each appears blank in the browser and results in many console errors to do with react. 
Steps to Reproduce the Problem:
1. Navigate to either of the PipelineRun or TaskRun panels in the dashboard.

Additional Info:
<img width="561" alt="Screenshot 2019-10-08 at 15 23 25" src="https://user-images.githubusercontent.com/52741262/66404147-cbf01b00-e9df-11e9-890f-fae73863112f.png">

**Comment by CarolynMabbott** [comment]
Updated to latest master
Ran:
`npm ci`
`npm run build_ko`
`ko apply -f config`

Proxied it / port forwarded it and there was no issue 
Tried on multiple different machines and its fixed when the above it run 

Appears to be a dependency issue as went away when running above commands

**Comment by a-roberts** [comment]
Yeah, can't reproduce either: I could before `npm ci`ing and can't afterwards, closing 😅
