### ISSUE TITLE
PipelineRuns page fails to load

### ISSUE THREAD

**Issue by gpaul** [tektoncd/dashboard#635]
# Expected Behavior

The PipelineRuns page should load.

# Actual Behavior

I see a blank screen.

# Steps to Reproduce the Problem

1. Create a PipelineRun that has no .status.startTime, then load the Tekton Dashboard on the PipelineRuns page.

# Additional Info

I saw the following error message in the chrome debugger.
```
Aa @ vendors.07998c1fadf87f5e0aec.js:91
vendors.07998c1fadf87f5e0aec.js:91 Uncaught TypeError: Cannot read property 'startTime' of undefined
```

The PipelineRun we use has definition:
```
{
  "apiVersion": "tekton.dev/v1alpha1",
  "kind": "PipelineRun",
  "metadata": {
    "annotations": {
      "dashboard-url": "redact"
    },
    "creationTimestamp": "2019-10-09T16:40:19Z",
    "generation": 1,
    "labels": {
      "build": "redact",
      "commit": "redact",
      "owner": "redact",
      "repository": "redact"
    },
    "name": "redact",
    "namespace": "redact",
    "resourceVersion": "8403810",
    "selfLink": "redact",
    "uid": "redact"
  },
  "spec": {
    "pipelineRef": {
      "name": "redact"
    },
    "podTemplate": {},
    "resources": [
      {
        "name": "src-git",
        "resourceRef": {
          "name": "src-git-7qsrr"
        }
      },
      {
        "name": "redact",
        "resourceRef": {
          "name": "redact"
        }
      }
    ],
    "serviceAccount": "build-bot",
    "serviceAccounts": [
      {
        "serviceAccount": "image-digest-updater-account",
        "taskName": "update-image-digests-rnwhp"
      }
    ],
    "timeout": "1h0m0s"
  }
}
```

Presumably, it has been created but never started.

**Comment by a-roberts** [comment]
Hey @gpaul, this should be fixed on master but unfortunately master's got a massive problem being worked under https://github.com/tektoncd/dashboard/issues/630, do you get this issue with the 0.2.0 release we recently published?

**Comment by gpaul** [comment]
Oh! I haven't tried. I will have a look. Since this is a known issue that is already fixed I will go ahead and close this issue. Thanks for the hard work on this project.
