### ISSUE TITLE
PipelineRun component fatally errors if no name found during loadTaskRuns

### ISSUE THREAD

**Issue by carlos-logro** [tektoncd/dashboard#638]
# Expected Behavior
Suppose to render either showing error or details of the PipelineRun

# Actual Behavior
Page broken completely. 
Some logs show that the page had an error fetching the PipelineRun at the beginning but apparently it later succeeded although by that time the page was already broken. 
<img width="1680" alt="Screen Shot 2019-10-14 at 11 08 20 AM" src="https://user-images.githubusercontent.com/49996607/66761922-f542f800-ee72-11e9-9775-2a30319c91f9.png">

# Steps to Reproduce the Problem

1. Trigger PipelineRun via Webhook
2. Wait for PipelineRun to finish.
3. Click PipelineRun

# Additional Info
This is only happening with a successful PipelineRun that was triggered via webhook. I have another PipelineRun that was triggered when Importing Resources & I am able to see its details and logs.

**Comment by a-roberts** [comment]
I've been in this code before when I was in rebuild and I added hardening as sometimes the fields weren't yet coming back over the websocket, may need the same kind of fix (if it's null, just render nothing for now - just for the name - then eventually we get the data over the websocket and the component can be fulfilled)

**Comment by a-roberts** [comment]
Stuck behind https://github.com/tektoncd/experimental/issues/291 going for the reproduce on my alternative set up (OpenShift cluster, my Docker Desktop set is centred around Triggers so not compromising that as we're nearly done)

**Comment by a-roberts** [comment]
^^ actually all is well using the latest build (ko applying) so it might be an issue with the nightly images and I was using simple pipeline insecure. I can work on this.

**Comment by a-roberts** [comment]
I've done five PipelineRuns triggered from a webhook with no problems - for a case where I didn't even create a secret.

![image](https://user-images.githubusercontent.com/12814972/67000091-13a52f80-f0cf-11e9-9498-7c5f8b60ab15.png)

I would prefer for the steps to be red and not green - the build step, for example, failed with:

```
{"level":"error","ts":1571307049.0442152,"logger":"fallback-logger","caller":"git/git.go:35","msg":"Error running git [checkout1392b79839a984b0acff54a56dff1262ab1b5533]: exit status 128\nfatal: reference is not a tree: 
```

but that's a different issue entirely, quite possibly https://github.com/tektoncd/dashboard/issues/644

So I created a secret to make sure it's an entirely successful PipelineRun.

**Comment by a-roberts** [comment]
@carlos-logro I'm going to park this one in favour of OpenShift 4.2 support work for now, I've pinged you asking for more details on a reproduce - lemme know please

**Comment by a-roberts** [comment]
This remains parked so I'm officially unassigning myself, plenty of juicy info here though should anyone wish to take over (I'm swamped with OpenShift 4.2 work for an imminent release and it's proving challenging), I'll top of the backlog it too

**Comment by carlos-logro** [comment]
@a-roberts im pretty sure after the PR I have open is merged the issue will be fixed.

**Comment by carlos-logro** [comment]
My PR has been merged and thus unassigning myself. 
/unassign

**Comment by a-roberts** [comment]
Closing due to the PR being in and we reckon this is fixed
