### ISSUE TITLE
If the build step in tekton pipeline fails, tekton dashboard shows the push step as green

### ISSUE THREAD

**Issue by aadeshpa** [tektoncd/dashboard#644]
# Expected Behavior

- When the `build-bud` step in kabanero pipeline fails due to some reason, the `build-push` step never runs from kabanero pipelines perspective.
And same should be seen on the Tekton-Dashboard with red mark for `build-bud` step and `build-push` step.

# Actual Behavior

- When the `build-bud` step is failing the the pipelinerun, still the Tekton-Dashboard is showing that `build-push` step succeeded.

# Steps to Reproduce the Problem

1.  Create a webhook for java-microprofile project from the tekton dashboard.
2. Make some code changes with compile time errors , so the `build-bud` step fails.

# Additional Info

   From Kabanero pipelines perspective we created webhook for java-microprofile project in my github.ibm.com from the tekton dashboard.
    I made some code changes with compile time errors , so the `build-bud` step fails.

Results:

    

- As the pipelinerun failed, the tekton dashboard shows below screenshot.

<img width="1374" alt="Screen Shot 2019-10-15 at 1 05 31 PM" src="https://user-images.githubusercontent.com/53223993/66858310-036a4480-ef57-11e9-9831-e1d79c72eeab.png">

-  However when we investigated from the oc logs command we found below results

- Logs Snippet for build-bud container in the pod (which was as expected to build fail):-

`oc logs -f my-java-mp-webhook-1571152644-build-task-wndcp-pod-2f0e7d -c step-build-bud`
```
Downloaded from central: https://repo.maven.apache.org/maven2/com/google/collections/google-collections/1.0/google-collections-1.0.jar (640 kB at 1.2 MB/s)
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /project/user-app/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /project/user-app/src/main/java/dev/appsody/starter/StarterApplication.java:[8,5] <identifier> expected
[ERROR] /project/user-app/src/main/java/dev/appsody/starter/StarterApplication.java:[9,2] reached end of file while parsing
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  57.022 s
[INFO] Finished at: 2019-10-15T15:27:33Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project starter-app: Compilation failure: Compilation failure: 
[ERROR] /project/user-app/src/main/java/dev/appsody/starter/StarterApplication.java:[8,5] <identifier> expected
[ERROR] /project/user-app/src/main/java/dev/appsody/starter/StarterApplication.java:[9,2] reached end of file while parsing
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
subprocess exited with status 1
subprocess exited with status 1
error building at STEP "RUN mvn install -DskipTests": exit status 1
```

- When we checked the `build-push` container logs

`oc logs -f my-java-mp-webhook-1571152644-build-task-wndcp-pod-2f0e7d -c step-build-push`

Logs never returned anything which means the `build-push` step never ran since earlier step failed. :
```
[root@crofts1 common]# oc logs -f my-java-mp-webhook-1571152644-build-task-wndcp-pod-2f0e7d -c step-build-push
[root@crofts1 common]# 
```

**Comment by ncskier** [comment]
I raised an issue (https://github.com/tektoncd/pipeline/issues/1439) in the Pipelines repo about potentially terminating steps with an `Error` instead of `Complete` when a previous step fails with an `Error`.

Also, PR https://github.com/tektoncd/dashboard/pull/653 fixes this in the Dashboard by hiding steps that follow an error.
