### ISSUE TITLE
Codewind unable to access Tekton Dashboard and 403 seen on OpenShift

### ISSUE THREAD

**Issue by sujeilyfonseca** [tektoncd/dashboard#646]
**Codewind version:** 0.5.0 
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.2.0
**Kubernetes cluster:** OKD/Openshift

**Expected Behavior:**
Tekton Dashboard should appear when using its ingress domain. Codewind should detect it and provide its endpoint URL based on the yaml file provided.

<img width="1253" alt="Screen Shot 2019-10-16 at 5 03 00 PM" src="https://user-images.githubusercontent.com/49531960/66958762-e9a02e80-f036-11e9-9713-dc380f22e3fc.png">

**Actual Behavior:**
With the "Install on Openshift" instructions, the Tekton Panel works outside of Codewind, but not within the Codewind workspace.

<img width="496" alt="Screen Shot 2019-10-16 at 3 15 18 PM" src="https://user-images.githubusercontent.com/49531960/66958275-d345a300-f035-11e9-80a6-f594ca623093.png">

<img width="1084" alt="Screen Shot 2019-10-16 at 3 25 36 PM" src="https://user-images.githubusercontent.com/49531960/66958285-d6d92a00-f035-11e9-826f-48359ecff70b.png">

On the other side, with the general instructions, a Forbidden 403 error is obtained when trying to open the dashboard (inside or outside Codewind). 

The Dashboard works as expected following the general instructions but using an older version (v0.1.1). The current version is v0.2.0.

**Steps to Reproduce the Problem:**
1. Install Tekton Pipelines
2. Install Tekton Dashboard
3. Install Tekton on Codewind / Access the Tekton Dashboard outside Codewind

**YAML Files:**
Install Dashboard (v0.2.0): https://github.com/tektoncd/dashboard/releases/download/v0.2.0/release.yaml
Install on Openshift (v0.2.0): https://github.com/tektoncd/dashboard/releases/download/v0.2.0/openshift-tekton-dashboard.yaml
v0.1.1: https://github.com/tektoncd/dashboard/releases/download/v0.1.1/release.yaml

@jagraj

**Comment by a-roberts** [comment]
Hmm, so regarding:

> On the other side, with the general instructions, a Forbidden 403 error is obtained when trying to open the dashboard (inside or outside Codewind)

This was seen in Firefox 60 ESR and we fixed it for the 0.2.0 release.

I logged in to my OpenShift cluster, applied the yaml (0.2.0) mentioned above, and I hit the route successfully fine for the Tekton Dashboard.

And see the Route correctly mentioned at 
https://tekton-dashboard-tekton-pipelines.myip.com/v1/namespaces/tekton-pipelines/endpoints

with the value

```
[
 {
  "type": "Route",
  "url": "tekton-dashboard-tekton-pipelines.myip.com"
 }
]
```

I'm inclined to think it's a Codewind problem at this stage (the only clue I can give around the forbidden stuff is https://github.com/tektoncd/dashboard/issues/528 which we fixed).

@sujeilyfonseca can you elaborate further on

```
The Dashboard works as expected following the general instructions but using an older version (v0.1.1).
``` 
please? Are you saying you can get the endpoint for Codewind to use correctly for 0.1.1 but not for 0.2.0? And on a similar note do you get the 403 using (which browser?) 0.1.1 or 0.2.0 please?

**Comment by sujeilyfonseca** [comment]
Thanks for your prompt response! I will provide additional details to explain the problems better.

**OpenShift instructions:**
https://github.com/tektoncd/dashboard/releases/download/v0.2.0/openshift-tekton-dashboard.yaml
https://github.com/tektoncd/dashboard/releases/download/v0.1.1/openshift-tekton-dashboard.yaml

V0.2.0 and V0.1.1: Using the YAML files for Openshift clusters, the Tekton Dashboard works (route can be accessed independently), but Codewind does not identify it.
A month ago, we opened a problem against Codewind, but it was closed: https://github.com/eclipse/codewind/issues/291

Here are the error messages obtained from Codewind:
V0.2.0: 
- Unable to open Tekton dashboard from Codewind shortcut

V0.1.0: 
- Unexpected error getting Tekton Dashboard list 
- There was an error detecting the Tekton Dashboard installation on this cluster. Please install or re-install Tekton Dashboard on your cluster.

**General instructions:**
https://github.com/tektoncd/dashboard/releases/download/v0.1.1/release.yaml
https://github.com/tektoncd/dashboard/releases/download/v0.2.0/release.yaml

V0.2.0: Forbidden 403 error when attempting to open the dashboard within Codewind or independently.

V0.1.0: Works outside or within Codewind.

**Cluster Roles for Codewind:**
https://github.com/eclipse/codewind-che-plugin/blob/master/setup/install_che/codewind-tektonrole.yaml
https://github.com/eclipse/codewind-che-plugin/blob/master/setup/install_che/codewind-tektonbinding.yaml

**Browsers:**
Safari 13.0 (14608.1.49)
Firefox Quantum 69.0.3 (64-bit)

**Comment by a-roberts** [comment]
@CarolynMabbott is going to take a look at this

**Comment by CarolynMabbott** [comment]
@sujeilyfonseca Are you still getting the same problem above when using codewind?
 Have you tried using the latest release for both?

**Comment by sujeilyfonseca** [comment]
Yes, I used the latest version for both: Codewind 0.5.0 and Tekton Dashboard v0.2.0

**Comment by a-roberts** [comment]
Having a look too, wanting to cut the 0.2.1 release soon so checking there's anything we need to do on our side. Have a new 3.11 cluster to use.

**Comment by a-roberts** [comment]
https://github.com/eclipse/codewind-che-plugin/blob/24e9d471ea75f7e61c11746bc6b7c0cd312381fe/setup/install_che/codewind-tektonrole.yaml is looking pretty bare, @tetchels kindly helped by showing us and allowing us to use his cluster running Che and Codewind and we see the error:

```
[32m[25/10/19 15:19:24 /portal/modules/TektonUtils.js] [INFO][39m Looking for services in Tekton namespace 'tekton-pipelines'
[91m[25/10/19 15:19:24 /portal/modules/TektonUtils.js] [ERROR][39m Unexpected error determining Tekton API Service: {"code":403,"statusCode":403}
```

Definitely a Codewind issue and not to do with our install (our serviceaccount/role/binding etc isn't in use, and I've verified our endpoint serves the correct data in the expected format)

I'm gonna close this but recommend this be tracked over at https://github.com/eclipse/codewind/issues

@johnmcollier @tobespc FYI
