### ISSUE TITLE
Feature request: display the duration of TaskRuns and PipelineRuns

### ISSUE THREAD

**Issue by zgfh** [tektoncd/dashboard#650]
# Expected Behavior
we can see the time of taskrun and the time of piplinerun
# Actual Behavior
no time metrics
![image](https://user-images.githubusercontent.com/11729624/67074423-aa4f1a80-f1bb-11e9-9f79-a68f5c92b543.png)

**Comment by kimholmes** [comment]
Does this represent the amount of time it takes for the PipelineRun or TaskRun to complete? Can you elaborate on why this is important for the user?

**Comment by zgfh** [comment]
@kimholmes  yes, you can see the jenkins and argo, it is very important when you want to optimize build time , or find which task slow down the progress of pipline

**Comment by AlanGreene** [comment]
We don't currently display total times for PipelineRuns / TaskRuns, but I agree it would be useful to display these somewhere.

If you view the details of a PipelineRun / TaskRun and click on the status tab for a specific step of interest you can see the startedAt and finishedAt timestamps.

![image](https://user-images.githubusercontent.com/2829095/67203933-48cdbc80-f404-11e9-8fba-359e67d3852b.png)

It would be useful to display the elapsed time for these in a more user friendly way too.

@kimholmes fyi, the output of `kubectl get pipelineruns` shows start / completion time, leaving calculation of the difference up to the user, but this IMO is even worse as it shows rather coarse grained relative times (e.g. 'x days ago')

```
$ kubectl get pipelineruns                                                         
NAME                    SUCCEEDED   REASON               STARTTIME   COMPLETIONTIME
demo-condtional-pr      False       CouldntGetPipeline   44d         44d           
demo-pipeline-run-1     False       Failed               44d         44d           
output-pipeline-run     True        Succeeded            24d         24d
```

**Comment by zgfh** [comment]
@AlanGreene thanks for help

**Comment by a-roberts** [comment]
PR by Alan https://github.com/tektoncd/dashboard/issues/850 here, I've just reviewed it so should be merged shortly, thanks for this feature request let's consider it done 👍
