### ISSUE TITLE
Tooltip to stop a PipelineRun should say 'stop' instead of 'cancel' to avoid confusion

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#655]
Currently on the tooltip for a PipelineRun the options available are 'Cancel' and 'Delete'. If you click cancel, the modal displayed asks of you want to stop the current PipelineRun, which seems confusing as the options on the modal are then 'Cancel' or 'Stop PipelineRun'. Therefore the tooltip should be changed to say stop, for consistency.

Steps to Recreate the Issue:
1. Create a PipelineRun
2. Cancel the PipelineRun

**Comment by a-roberts** [comment]
Merged so closing
