### ISSUE TITLE
Feature request: run Task/Pipeline on certain node

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#662]
See https://github.com/tektoncd/pipeline/issues/1454 - a Tekton Pipelines user has asked if it's possible to do so through Tekton Pipelines themselves - the answer is yes

We offer a "create PipelineRun" page, and so it makes sense to enable this

https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#pod-template for TaskRun (we don't have a create TaskRun page) and https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#pod-template for PipelineRun

I'd like to see an example use case too, I'm thinking one might only wish to run Pipelines on nodes labelled "test".

**Comment by eddycharly** [comment]
Being the one that asked for it, i will look into it.

/assign
