### ISSUE TITLE
Publish 0.2.1 Tekton Dashboard and Webhooks Extension release

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#664]
A few important fixes we need

1: Tekton Condition getting (RBAC) in dashboard yaml
2: PullRequest monitor task in extension yaml

Any other fixes picked up along the way are most welcome!

This will be our OpenShift 4.2 release, I've tested and verified everything works with a buildah task and we need to do a lot less at install time actually.

For background see https://github.com/tektoncd/dashboard/issues/648 and https://github.com/tektoncd/experimental/pull/306/files.

**Comment by mnuttall** [comment]
We also need some documentation about 'if you want to use buildah and OpenShift 4.2 and push to the internal registry then this is what you need to know'.

**Comment by a-roberts** [comment]
This is on ice until we have all the fixes and features in that we would like.

Once this is done we can merge https://github.com/tektoncd/experimental/pull/306

**Comment by a-roberts** [comment]
Last PR to go in is https://github.com/tektoncd/dashboard/pull/678

**Comment by a-roberts** [comment]
@mnuttall's picked this up as my Kubernetes clusters were all screwed

Concretely I saw 

```
adams-mbp:webhooks-extension aroberts$ kci
Kubernetes master is running at https://kubernetes.docker.internal:6443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp: lookup kubernetes.docker.internal on <somenameserverip>:53: no such host
```

and the issue was, my /etc/hosts file wasn't permission 644'd

```
adams-mbp:dashboard aroberts$ ls -la /etc/hosts
-rw-------  1 root  wheel  232  1 Nov 10:03 /etc/hosts
adams-mbp:dashboard aroberts$ sudo chmod 644 /etc/hosts
adams-mbp:dashboard aroberts$ ls -la /etc/hosts
-rw-r--r--  1 root  wheel  232  1 Nov 10:03 /etc/hosts
```

^^ after making this change all is well. So if anyone has a naff cluster and they google that error, enjoy

**Comment by a-roberts** [comment]
Done, thanks @mnuttall for running with this in my time of dead clusters 🍈
