### ISSUE TITLE
Setup API, actions, and reducers to get Triggers resources

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#665]
This work is under epic https://github.com/tektoncd/dashboard/issues/509

Setup the API, actions, and reducers in the Dashboard to retrieve Triggers resources (`TriggerTemplate`, `TriggerBinding`, and `EventListener`) from the [proxy API](https://github.com/tektoncd/dashboard/blob/master/src/api/index.js#L84). Read the following specifications for more info about the API, actions, and reducers.

### API
Add the following functions to [`src/api/index.js`](https://github.com/tektoncd/dashboard/blob/master/src/api/index.js):
- `getTriggerTemplates()`
- `getTriggerTemplate()`
- `getTriggerBindings()`
- `getTriggerBinding()`
- `getEventListeners()`
- `getEventListener()`

Add tests in [`src/api/index.test.js`](https://github.com/tektoncd/dashboard/blob/master/src/api/index.test.js)

### Actions
Create the following files with actions for `FETCH_REQUEST`, `FETCH_SUCCESS`, and `FETCH_FAILURE`:
- `src/actions/triggerTemplates.js`
- `src/actions/triggerBindings.js`
- `src/actions/eventListeners.js`

Include tests in:
- `src/actions/triggerTemplates.test.js`
- `src/actions/triggerBindings.test.js`
- `src/actions/eventListeners.test.js`

### Reducers
Create the following files to define the state & reducers for each Triggers resource:
- `src/reducers/triggerTemplates.js`
- `src/reducers/triggerBindings.js`
- `src/reducers/eventListeners.js`

Include tests in:
- `src/reducers/triggerTemplates.test.js`
- `src/reducers/triggerBindings.test.js`
- `src/reducers/eventListeners.test.js`

# Additional Info
- Tekton Triggers README: https://github.com/tektoncd/triggers

**Comment by a-roberts** [comment]
PR https://github.com/tektoncd/dashboard/pull/686

**Comment by a-roberts** [comment]
Merged so closing, floodgates open
