### ISSUE TITLE
TriggerTemplates table paneling first pass

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#666]
This work is under epic https://github.com/tektoncd/dashboard/issues/509

# Expected Behavior
I expect to be able to view all of the [TriggerTemplate](https://github.com/tektoncd/triggers/blob/master/docs/triggertemplates.md) resources as a table in the Dashboard.

The columns of the table must include the following information about each TriggerTemplate:
- Name
- Namespace

Here is the latest wireframe from #509. Since this issue is a first pass at the paneling, it will not be as sophisticated as the wireframe; the filter, checkboxes, and date modified column in the wireframe should not be included in this initial implementation.
![tt-table](https://user-images.githubusercontent.com/16961496/67598295-2ce75500-f73b-11e9-8ee9-0b19607c8c7a.png)

# Actual Behavior
We have no paneling for TriggerTemplates.

# Additional Info
- TriggerTemplates README: [triggertemplates.md](https://github.com/tektoncd/triggers/blob/master/docs/triggertemplates.md)
- TriggerTemplates type definition: [trigger_template_types.yaml](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/trigger_template_types.go)
- TriggerTemplate example: [triggertemplate.yaml](https://github.com/tektoncd/triggers/blob/master/examples/triggertemplates/triggertemplate.yaml)

**Comment by a-roberts** [comment]
@carlos-logro I'm working on the details part of this, haven't rebased to use your table yet (but that looks good to me from the PR), and I have this so far

![image](https://user-images.githubusercontent.com/12814972/68584119-a2129400-0476-11ea-8267-ef752c7c0bd3.png)


If you've done more (this only took me < 30 minutes and I didn't implement tests) I'm happy to park this, I basically implemented it so I could review your table and try it, then figured: actually... to implement the **details** task, I may as well implement this. 

Either way, lemme know 😄

**Comment by a-roberts** [comment]
Merged so closing
