### ISSUE TITLE
TriggerBindings table paneling first pass

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#667]
This work is under epic https://github.com/tektoncd/dashboard/issues/509

# Expected Behavior
I expect to be able to view all of the [TriggerBinding](https://github.com/tektoncd/triggers/blob/master/docs/triggerbindings.md) resources as a table in the Dashboard.

The columns of the table must include the following information about each TriggerBinding:
- Name
- Namespace

Here is the latest wireframe from #509. Since this issue is a first pass at the paneling, it will not be as sophisticated as the wireframe; the filter, checkboxes, and date modified column in the wireframe should not be included in this initial implementation.
![tb-table](https://user-images.githubusercontent.com/16961496/67599298-c31c7a80-f73d-11e9-85c2-57d85a8de957.png)

# Actual Behavior
We have no paneling for TriggerBindings.

# Additional Info
- TriggerBindings README: [triggerbindings.md](https://github.com/tektoncd/triggers/blob/master/docs/triggerbindings.md)
- TriggerBindings type definition: [trigger_binding_types.yaml](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/trigger_binding_types.go)
- TriggerBinding example: [triggerbinding.yaml](https://github.com/tektoncd/triggers/blob/master/examples/triggerbindings/triggerbinding.yaml)

**Comment by mii-w** [comment]
![Screen Shot 2019-11-05 at 10 01 57 AM](https://user-images.githubusercontent.com/51759906/68222211-a80cfe80-ffb8-11e9-8b9d-0e61d22f2ecb.png)
![Screen Shot 2019-11-05 at 10 02 03 AM](https://user-images.githubusercontent.com/51759906/68222221-ab07ef00-ffb8-11e9-8887-41cd114cb182.png)

**Comment by a-roberts** [comment]
Merged so closing
