### ISSUE TITLE
EventListener table paneling first pass

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#668]
This work is under epic https://github.com/tektoncd/dashboard/issues/509

# Expected Behavior
I expect to be able to view all of the [EventListener](https://github.com/tektoncd/triggers/blob/master/docs/eventlisteners.md) resources as a table in the Dashboard.

The columns of the table must include the following information about each EventListener:
- Name
- ServiceAccount
- Namespace

Here is the latest wireframe. Since this issue is a first pass at the paneling, it will not be as sophisticated as the wireframe; the filter, checkboxes, and create button in the wireframe should not be included in this initial implementation. The purpose of this first pass is only to view the EventListeners, not to create, modify, or delete them.
<img width="737" alt="el-table" src="https://user-images.githubusercontent.com/16961496/68051334-90cec800-fcbd-11e9-9648-62cac5530a69.png">

# Actual Behavior
We have no paneling for EventListeners.

# Additional Info
- EventListeners README: [eventlisteners.md](https://github.com/tektoncd/triggers/blob/master/docs/eventlisteners.md)
- EventListener type definition: [event_listener_types.yaml](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/event_listener_types.go)
- EventListener example: [eventlistener.yaml](https://github.com/tektoncd/triggers/blob/master/examples/eventlisteners/eventlistener-interceptor.yaml)

**Comment by mii-w** [comment]
<img width="737" alt="Screen Shot 2019-11-01 at 11 07 23 AM" src="https://user-images.githubusercontent.com/51759906/68034330-da0c2100-fc97-11e9-9c1d-bba3c2da7f64.png">

opened left nav
<img width="737" alt="Screen Shot 2019-11-01 at 11 10 26 AM" src="https://user-images.githubusercontent.com/51759906/68034561-3f601200-fc98-11e9-92d6-b09a6f956f5c.png">

**Comment by a-roberts** [comment]
Merged so closing
