### ISSUE TITLE
TriggerTemplate details paneling first pass

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#669]
This work is under epic https://github.com/tektoncd/dashboard/issues/509

# Expected Behavior
I expect to be able to view the details of a [TriggerTemplate](https://github.com/tektoncd/triggers/blob/master/docs/triggertemplates.md) resource in the Dashboard.

This panel should have two [tabs](https://www.carbondesignsystem.com/components/tabs/code/), `Details` and `YAML`.
### YAML view
The `YAML` view should display the YAML definition of the TriggerTemplate resource (`kubectl get triggertemplate TT_NAME -oyaml`). The YAML should be formatted like a code snippet.

Here is the latest wireframe from #509 for the `YAML` view.
![tt-detail-yaml](https://user-images.githubusercontent.com/16961496/67604580-ef3df880-f749-11e9-8de1-6a9f70f5b405.png)

### Details view
The `Details` view should be a nicely formatted representation of the important information in the TriggerTemplate's YAML. The `Details` view must include the following information:
- Labels
- list of params with the following:
  - name
  - description
  - default
- list of resource templates with the following:
  - name
  - kind

Here is the latest wireframe from #509 for the `Details` view.
![tt-detail](https://user-images.githubusercontent.com/16961496/67604590-f82eca00-f749-11e9-8fd5-dc64e384b228.png)

# Actual Behavior
We have no paneling for viewing TriggerTemplate resource details.

# Additional Info
- TriggerTemplates README: [triggertemplates.md](https://github.com/tektoncd/triggers/blob/master/docs/triggertemplates.md)
- TriggerTemplates type definition: [trigger_template_types.yaml](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/trigger_template_types.go)
- TriggerTemplate example: [triggertemplate.yaml](https://github.com/tektoncd/triggers/blob/master/examples/triggertemplates/triggertemplate.yaml)

**Comment by mii-w** [comment]
![Screen Shot 2019-11-05 at 10 33 40 AM](https://user-images.githubusercontent.com/51759906/68222332-d7bc0680-ffb8-11e9-95b4-987125f5b82f.png)
![Screen Shot 2019-11-05 at 10 33 45 AM](https://user-images.githubusercontent.com/51759906/68222334-d985ca00-ffb8-11e9-90ca-f9985b5c31b4.png)
![Screen Shot 2019-11-05 at 10 41 56 AM](https://user-images.githubusercontent.com/51759906/68222372-e99da980-ffb8-11e9-9edd-b3fb12a8c2c6.png)

**Comment by a-roberts** [comment]
I'm working this, planned to implement something simple to review https://github.com/tektoncd/dashboard/pull/710 and this is where I want to really test Carlos' reusable component.

Have plenty of code for this already now.

**Comment by a-roberts** [comment]
Ok, implemented the overall view page and I'm now implementing the details part and incorporating the table from Carlos to help with that review

**Comment by a-roberts** [comment]
![image](https://user-images.githubusercontent.com/12814972/68602857-077a7b00-049f-11ea-93a6-a9db92c58fff.png)

I have this so far, working on making it so on click, we display the full template information as a prettified string.

**Comment by a-roberts** [comment]
Accordion implemented, should be one giant accordion item (row width) and not two so I'll look into that tomorrow. All data being retrieved and otherwise displayed correctly.

I'll add the full YAML view as well tomorrow.

![image](https://user-images.githubusercontent.com/12814972/68608238-4f52cf80-04aa-11ea-943b-7715c88fd512.png)

**Comment by mii-w** [comment]
we are looking into utilizing the space better so data can be clearly displayed and accessible to the user (prevent them to do endless scrolling) 

<img width="778" alt="Screen Shot 2019-11-11 at 2 51 58 PM" src="https://user-images.githubusercontent.com/51759906/68616398-f7f53500-0492-11ea-9e54-20e89ad8544c.png">
<img width="787" alt="Screen Shot 2019-11-11 at 2 52 04 PM" src="https://user-images.githubusercontent.com/51759906/68616407-f9bef880-0492-11ea-94be-230a040a4c38.png">

**Comment by mii-w** [comment]
Above wires were based off discussion with design team- another variation to consider
<img width="468" alt="Screen Shot 2019-11-11 at 5 08 00 PM" src="https://user-images.githubusercontent.com/51759906/68624963-04cf5400-04a6-11ea-98b9-036162b76479.png">
<img width="467" alt="Screen Shot 2019-11-11 at 5 08 05 PM" src="https://user-images.githubusercontent.com/51759906/68624967-06991780-04a6-11ea-87f6-1404609d8174.png">

**Comment by ncskier** [comment]
@mii-w while the Parameters are definitely important, it feels strange to have them take up the majority of the screen space.

**Comment by a-roberts** [comment]
Yeah I agree, it's unlikely the user will have sooooo many of them, I'll work on adding the details and yaml buttons now and adding this into a container

**Comment by mii-w** [comment]
> @mii-w while the Parameters are definitely important, it feels strange to have them take up the majority of the screen space in those designs.

I agree it seemed kind of odd.. what are your thoughts on this layout?
<img width="998" alt="Screen Shot 2019-11-12 at 10 30 59 AM" src="https://user-images.githubusercontent.com/51759906/68685175-b5d1ff00-0537-11ea-9c75-08da595bb774.png">

In regards to displaying the YAML, I think we should keep it consistent throughout all.
<img width="448" alt="Screen Shot 2019-11-12 at 10 39 35 AM" src="https://user-images.githubusercontent.com/51759906/68685849-bdde6e80-0538-11ea-9272-550a2f8e44d9.png">

**Comment by ncskier** [comment]
Sorry for the confusion about which design should be implemented. In an effort to clear things up, I've created a separate issue for iterating on the TriggerTemplate design work here: https://github.com/tektoncd/dashboard/issues/724

From our discussion today, it seemed like this design will be a good one for our "first pass"
![tt-details](https://user-images.githubusercontent.com/16961496/68709873-85548a00-0564-11ea-94ae-70e6f06f3366.png)
In the future, we can refine the implementation based on the work in https://github.com/tektoncd/dashboard/issues/724.

@mii-w does this sound alright?

**Comment by a-roberts** [comment]
Yep looks good

**Comment by a-roberts** [comment]
![image](https://user-images.githubusercontent.com/12814972/68754822-60612500-05ff-11ea-8999-c112f06a4613.png)

here's what I've got so far, I've not added any tests to this but plan to pick up something more urgent. Lemme know if there's anything noddy I should add, otherwise I'll resume this - add tests and make the PR.

**Comment by a-roberts** [comment]
Merged so closing 🎂
