### ISSUE TITLE
Surface "tekton" tagged credentials in the dashboard

### ISSUE THREAD

**Issue by skaegi** [tektoncd/dashboard#67]
For resources in the cluster like credentials that are tagged as associated with Tekton should be surfaced in the UI. Design coming...

**Comment by mnuttall** [comment]
Git credentials in particular need a `tekton.dev/git-n: https://github.com` type annotation. 

Docker secrets that are not of type kubernetes.io/dockerconfigjson also need annotating. 

- New panelling should allow users to create secrets (user/pass or token-based). 
- Docker secrets should be of type kubernetes.io/dockerconfigjson in the first instance. 
- Service accounts should be patched with Docker secrets.

**Comment by mnuttall** [comment]
@dibbles is helping to coordinate design efforts in this area so please work with him to pick up the latest thinking.

**Comment by carlos-logro** [comment]
I'm going to tackle this issue, can't assign it to me though!

**Comment by carlos-logro** [comment]
#185
