### ISSUE TITLE
TriggerBinding details paneling first pass

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#670]
This work is under epic https://github.com/tektoncd/dashboard/issues/509

# Expected Behavior
I expect to be able to view the details of a [TriggerBinding](https://github.com/tektoncd/triggers/blob/master/docs/triggerbindings.md) resource in the Dashboard.

This panel should have two [tabs](https://www.carbondesignsystem.com/components/tabs/code/), `Details` and `YAML`.
### YAML view
The `YAML` view should display the YAML definition of the TriggerBinding resource (`kubectl get triggerbinding TB_NAME -oyaml`). The YAML should be formatted like a code snippet.

Here is the latest wireframe from #509 for the `YAML` view.
![tb-detail-yaml](https://user-images.githubusercontent.com/16961496/67604199-f6b0d200-f748-11e9-8159-f55e67650772.png)

### Details view
The `Details` view should be a nicely formatted representation of the important information in the TriggerBinding's YAML. The `Details` view must include the following information:
- Labels
- list of params each with the following:
  - name
  - value

Here is the latest wireframe from #509 for the `Details` view.
![tb-detail](https://user-images.githubusercontent.com/16961496/67604219-04feee00-f749-11e9-9a3c-38015991c662.png)

# Actual Behavior
We have no paneling for viewing TriggerBinding resource details.

# Additional Info
- TriggerBindings README: [triggerbindings.md](https://github.com/tektoncd/triggers/blob/master/docs/triggerbindings.md)
- TriggerBindings type definition: [trigger_binding_types.yaml](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/trigger_binding_types.go)
- TriggerBinding example: [triggerbinding.yaml](https://github.com/tektoncd/triggers/blob/master/examples/triggerbindings/triggerbinding.yaml)

**Comment by mii-w** [comment]
![Screen Shot 2019-11-05 at 10 02 09 AM](https://user-images.githubusercontent.com/51759906/68222479-10f47680-ffb9-11e9-8f71-0bdd869a4384.png)
![Screen Shot 2019-11-05 at 10 44 08 AM](https://user-images.githubusercontent.com/51759906/68222613-4305d880-ffb9-11e9-8e30-0eb8b2b8cad1.png)

**Comment by mii-w** [comment]
<img width="784" alt="Screen Shot 2019-11-11 at 2 51 43 PM" src="https://user-images.githubusercontent.com/51759906/68616333-d85e0c80-0492-11ea-84af-0de20624e828.png">
<img width="782" alt="Screen Shot 2019-11-11 at 2 51 50 PM" src="https://user-images.githubusercontent.com/51759906/68616343-da27d000-0492-11ea-9c9a-6e198626837c.png">

**Comment by mii-w** [comment]
Above wires were based off discussion with design team- another variation to consider
<img width="471" alt="Screen Shot 2019-11-11 at 5 07 49 PM" src="https://user-images.githubusercontent.com/51759906/68624950-fc771900-04a5-11ea-87a7-4d1191a12519.png">
<img width="471" alt="Screen Shot 2019-11-11 at 5 07 53 PM" src="https://user-images.githubusercontent.com/51759906/68624954-fed97300-04a5-11ea-8107-f5ea1ce770b3.png">

**Comment by ncskier** [comment]
To avoid confusion between overlapping implementation and design iterations, I've created issue #725 to track the design work, and this issue (#670) will only handle the "first pass" implementation.

If you assign yourself to this issue, please coordinate with @mii-w about which design to implement for the "first pass."

**Comment by carlos-logro** [comment]
\assign

**Comment by mii-w** [comment]
<img width="766" alt="Screen Shot 2019-11-26 at 11 17 17 AM" src="https://user-images.githubusercontent.com/51759906/69651628-5d722580-103e-11ea-8b54-7cc61a229c63.png">
<img width="764" alt="Screen Shot 2019-11-26 at 11 17 25 AM" src="https://user-images.githubusercontent.com/51759906/69651635-5fd47f80-103e-11ea-97cf-3ea61012b624.png">

**Comment by a-roberts** [comment]
This is merged so closing
