### ISSUE TITLE
EventListener details paneling first pass

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#671]
This work is under epic https://github.com/tektoncd/dashboard/issues/509

# Expected Behavior
I expect to be able to view the details of an [EventListener](https://github.com/tektoncd/triggers/blob/master/docs/eventlisteners.md) resource in the Dashboard.

This panel should have two [tabs](https://www.carbondesignsystem.com/components/tabs/code/), `Details` and `YAML`.
### YAML view
The `YAML` view should display the YAML definition of the EventListener resource (`kubectl get eventlistener EL_NAME -oyaml`). The YAML should be formatted like a code snippet.

Here is the latest wireframe from #509 for the `YAML` view.
![el-details-yaml](https://user-images.githubusercontent.com/16961496/67602483-b4859180-f744-11e9-8069-f800445dffd8.png)

### Details view
The `Details` view should be a nicely formatted representation of the important information in the EventListener's YAML. The `Details` view must include the following information:
- Labels
- ServiceAccount
- list of triggers each with the following:
  -  name
  - TriggerTemplate (this should be a hyperlink to the [TriggerTemplate](https://github.com/tektoncd/dashboard/issues/669) details view)
  - TriggerBinding (this should be a hyperlink to the [TriggerBinding](https://github.com/tektoncd/dashboard/issues/670) details view)
  - list of params each with the following
    - name
    - value
  - Interceptor
    - ObjectRef
      - name
      - kind
      - namespace
    - list of headers each with the following:
      - name
      - value

Here is the latest wireframe from #509 for the `Details` view.
![el-details](https://user-images.githubusercontent.com/16961496/67602114-f2ce8100-f743-11e9-8242-2e5c74e82fe3.png)

# Actual Behavior
We have no paneling for viewing EventListener resource details.

# Additional Info
- EventListeners README: [eventlisteners.md](https://github.com/tektoncd/triggers/blob/master/docs/eventlisteners.md)
- EventListener type definition: [event_listener_types.yaml](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/event_listener_types.go)
- EventListener example: [eventlistener.yaml](https://github.com/tektoncd/triggers/blob/master/examples/eventlisteners/eventlistener-interceptor.yaml)

**Comment by mii-w** [comment]
![Screen Shot 2019-11-05 at 10 45 47 AM](https://user-images.githubusercontent.com/51759906/68222725-76e0fe00-ffb9-11e9-9ab9-875c4ea691ff.png)
![Screen Shot 2019-11-05 at 10 45 47 AM](https://user-images.githubusercontent.com/51759906/68222728-78122b00-ffb9-11e9-8a14-bea5a4692073.png)
![Screen Shot 2019-11-05 at 10 45 52 AM](https://user-images.githubusercontent.com/51759906/68222736-79dbee80-ffb9-11e9-94d8-b99871fe7006.png)
![Screen Shot 2019-11-05 at 10 45 57 AM](https://user-images.githubusercontent.com/51759906/68222742-7cd6df00-ffb9-11e9-8d53-cd69c4835bd1.png)

**Comment by mii-w** [comment]
<img width="787" alt="Screen Shot 2019-11-11 at 2 50 53 PM" src="https://user-images.githubusercontent.com/51759906/68616269-b6648a00-0492-11ea-9d2a-4a589d05db32.png">
<img width="781" alt="Screen Shot 2019-11-11 at 2 51 05 PM" src="https://user-images.githubusercontent.com/51759906/68616273-b82e4d80-0492-11ea-8025-18e65dd9b2ab.png">

**Comment by mii-w** [comment]
Above wires were based off discussion with design team- another variation to consider
<img width="474" alt="Screen Shot 2019-11-11 at 5 07 39 PM" src="https://user-images.githubusercontent.com/51759906/68624882-da7d9680-04a5-11ea-939f-a77b39b67496.png">
<img width="470" alt="Screen Shot 2019-11-11 at 5 07 44 PM" src="https://user-images.githubusercontent.com/51759906/68624891-dcdff080-04a5-11ea-9fd9-31c8b20d5ba7.png">

**Comment by ncskier** [comment]
@mii-w the split-window is interesting. Just to clarify, when the user selects another Trigger from the accordion list, will the right pane with `Parameters` and `Interceptor` change its content? Each Trigger has its own Interceptor & Parameters, so the YAML split-window view doesn't really make sense to me; I don't think we would want the `Parameters` and `Interceptor` window to still be there.

**Comment by kimholmes** [comment]
Agree with @ncskier. And for the layout, it will come out in the wash when we hand these to Carrie but we need to stick with the existing pattern re: the YAML should appear in a separate tab than the Details etc.

**Comment by mii-w** [comment]
yeah, I can see why it wouldn't make sense, because the Parameters and Interceptor are specific to a Trigger. I also flipped the order, Interceptor on top (to keep layout kind of consistent with resource templates and Parameters)
<img width="626" alt="Screen Shot 2019-11-12 at 10 36 02 AM" src="https://user-images.githubusercontent.com/51759906/68685580-56282380-0538-11ea-868c-52d3512ce32b.png">
<img width="630" alt="Screen Shot 2019-11-12 at 10 36 08 AM" src="https://user-images.githubusercontent.com/51759906/68685585-57f1e700-0538-11ea-898f-6e0ed3103662.png">

**Comment by ncskier** [comment]
To avoid confusion between overlapping implementation and design iterations, I've created issue #726 to track the design work, and this issue (#671) will only handle the "first pass" implementation.

If you assign yourself to this issue, please coordinate with @mii-w about which design to implement for the "first pass."

**Comment by a-roberts** [comment]
We want to get a 0.3 release for Triggers out this week and I reckon the above wireframe looks great, so someone please pick this up and let's get working on it (assigned to the backlog)

**Comment by mii-w** [comment]
<img width="1025" alt="Screen Shot 2019-11-26 at 11 12 50 AM" src="https://user-images.githubusercontent.com/51759906/69651247-c907c300-103d-11ea-87a1-51da50de2350.png">

**Comment by a-roberts** [comment]
Thanks @mii-w, so for anyone who picks this up we think the above would be an awesome thing to implement first

**Comment by a-roberts** [comment]
PR https://github.com/tektoncd/dashboard/pull/784

**Comment by a-roberts** [comment]
@AlanGreene has approved my PR but I've just added some more feedback in response to his and I'm done for the Christmas break now, thanks all - let's get this in (and I'd like to fix the flashing datatable on hover) later 😄

**Comment by a-roberts** [comment]
Merged, it's not perfect (initial approach was with accordions and they were awkward to use and style, then nested expandable datatables but this introduced horrible flashing behaviour and it's not something Carbon recommend or support) - either way we now have all the details pages, cheers all ⛱
