### ISSUE TITLE
Navigation to Triggers resource panels

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#672]
This work is under epic #509

# Expected Behavior
I expect there to be links in the left navigation menu that will take me to each Triggers resource page ([`TriggerTemplate`](https://github.com/tektoncd/dashboard/issues/666), [`TriggerBinding`](https://github.com/tektoncd/dashboard/issues/667), and [`EventListener`](https://github.com/tektoncd/dashboard/issues/668)).

Here is the latest wireframe from #509 for the navigation menu (EventListeners are selected in the example):
![nav-menu](https://user-images.githubusercontent.com/16961496/67605631-e4d12e00-f74c-11e9-9a2c-69fb3d938eed.png)

# Actual Behavior
There are no menu items in the left navigation menu for the Triggers resource pages (`TriggerTemplate`, `TriggerBinding`, and `EventListener`).

# Additional Info
- Tekton Triggers README: https://github.com/tektoncd/triggers

**Comment by mii-w** [comment]
I think it makes more sense to have Trigger Resources grouped together under the Tekton Resources category
![Screen Shot 2019-11-05 at 10 46 45 AM](https://user-images.githubusercontent.com/51759906/68222798-9415cc80-ffb9-11e9-8181-830a23de57c2.png)

**Comment by mii-w** [comment]
Because Triggers and Webhooks will work together - grouped together
<img width="241" alt="Screen Shot 2019-11-05 at 12 06 42 PM" src="https://user-images.githubusercontent.com/51759906/68229215-d690d680-ffc4-11e9-9595-67b725f39f4c.png">

**Comment by a-roberts** [comment]
We have this now 🎈 here's how it looks so far

![image](https://user-images.githubusercontent.com/12814972/69560820-3ebf5080-0fa4-11ea-827a-fd1d96233bfe.png)

For any changes e.g. groupings we can raise under a new issue, otherwise closing
