### ISSUE TITLE
Websocket keeps failing for unknown reasons  

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#680]
The websocket keeps failing and causing errors such as not refreshing the page / updating secrets page when deleting and adding secrets 

This happenned when was using npm start / port forward 

Scrrenshot below of the errors shown in the console (Not related to the uncaught in promise as this error happened constantly even when just refreshing a page):
![Screenshot 2019-10-29 at 16.27.25.png](https://images.zenhubusercontent.com/5cfe69e3171db04ec3637b76/0251d5e1-aa3e-4798-9663-5c46e26ec123)

Dashboard logs 
```
reconnecting-websocket-mjs.js?d096:483 WebSocket connection to 'ws://localhost:8000/v1/websockets/resources' failed: Unknown reason
eval @ reconnecting-websocket-mjs.js?d096:483
```

**Comment by AlanGreene** [comment]
@CarolynMabbott is this still happening? Is it only on dev builds or are you seeing it on a production build too? Is the cluster you're connecting to local or remote?

**Comment by CarolynMabbott** [comment]
I havent noticed it recently but might be due to some different factors to when i noticed this originally. It was happening on dev builds, havent checked production. Using Docker Desktop

**Comment by AlanGreene** [comment]
OK let's close it for now, we can always reopen if you do notice it happening again.

**Comment by CarolynMabbott** [comment]
This is still happening, running on 
Docker Desktop, npm start with port forward to 9097

**Comment by vtereso** [comment]
Do we know if the issue is on the back-end and/or the front-end?

**Comment by AlanGreene** [comment]
Is this still happening? Any pattern you can identify? e.g. only happens after running certain tasks / pipelines, happens at regular intervals, after a particular set of interactions in the UI...

The only times I've seen repeated disconnects like this are when a proxy / load balancer / ingress controller is killing long-lived connections, usually every 30 seconds or 1 minute.

The fact that you were seeing this running on docker desktop locally is definitely unexpected.

**Comment by eddycharly** [comment]
Any news on this one ?
Maybe we can close it for now and reopen if this happens again ?
