### ISSUE TITLE
Follow up with unpatching of service accounts: add tests (unit & integration)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#681]
Had to reduce test coverage to get https://github.com/tektoncd/dashboard/pull/678 in

Under this item add tests for unpatching service accounts and checking secrets are removed including across namespaces

In terms of unit tests, see:
comms.test.js
index.test.js
(get coverage back up to 90+, sitting at 89.9 atm)

In terms of integration tests:
create multiple secrets patched to multiple service accounts in multiple namespaces, delete via UI all at once

**Comment by CarolynMabbott** [comment]
So far attempts are located here: https://github.com/CarolynMabbott/dashboard/tree/testAttempts

One thing that should be done soon is remove my old unused code from comms.js 
Line 117 - 125 function patchRemoveSercretBody 
Line 136 - 143 function patchRemoveSecret

**Comment by eddycharly** [comment]
@CarolynMabbott are you still working on this ?

**Comment by CarolynMabbott** [comment]
Nope not working on this, unassigned myself last year
