### ISSUE TITLE
TestExtensionRegistration still (still) flaky (again (again (again)))

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#682]
See https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_dashboard/678/pull-tekton-dashboard-unit-tests/1189597155866710018/

There are lots of related issues and @carlos-logro added debug info so have a look and see if we can fix it last 😄 

```
I1030 17:41:33.698] {"level":"debug","msg":"Registering path: /v1/extensions/extension1/robots"}
I1030 17:41:33.698] {"level":"debug","msg":"Registering path: /v1/extensions/extension1/secrets"}
I1030 17:41:33.698] {"level":"debug","msg":"Extension Controller detected extension 'extension2' created"}
I1030 17:41:33.698] {"level":"info","msg":"Adding Extension extension2"}
I1030 17:41:33.698] {"level":"debug","msg":"Registering path: /v1/extensions/extension2/robots"}
I1030 17:41:33.699] {"level":"debug","msg":"Registering path: /v1/extensions/extension2/secrets"}
I1030 17:41:33.699] --- FAIL: TestExtensionRegistration (10.04s)
I1030 17:41:33.699]     routes_test.go:318: In TestExtensionRegistration
I1030 17:41:33.699]     routes_test.go:344: robots.secrets
I1030 17:41:33.699]     routes_test.go:461: waiting for registration
I1030 17:41:33.699]     routes_test.go:462: services:
I1030 17:41:33.699]     routes_test.go:463: start time: 2019-10-30 17:41:23.642775569 +0000 UTC m=+0.180869565
I1030 17:41:33.700]     routes_test.go:464: --- ---
I1030 17:41:33.700]     routes_test.go:478: counter: 1
I1030 17:41:33.700]     routes_test.go:479: time: 2019-10-30 17:41:23.64775723 +0000 UTC m=+0.185851255
I1030 17:41:33.700]     routes_test.go:483: extensionCreates:
I1030 17:41:33.700]     routes_test.go:484: 1
I1030 17:41:33.700]     routes_test.go:490: 
I1030 17:41:33.701]     routes_test.go:478: counter: 2
I1030 17:41:33.701]     routes_test.go:479: time: 2019-10-30 17:41:23.651183986 +0000 UTC m=+0.189278037
I1030 17:41:33.701]     routes_test.go:483: extensionCreates:
I1030 17:41:33.701]     routes_test.go:484: 2
I1030 17:41:33.701]     routes_test.go:490: 
I1030 17:41:33.701]     routes_test.go:470: Timed out waiting for expected services to be registered
```

**Comment by a-roberts** [comment]
> @a-roberts after comparing these logs from a passing test log we can see how it skipped (or maybe errored) deleting the extension from the first service:
> 
> Passing Logs from most recent PR (#678) in dashboard:
> https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_dashboard/678/pull-tekton-dashboard-unit-tests/1189600930589315072/?log#log
> 
> ```
> routes_test.go:461: waiting for registration
> I1030 17:57:17.764]     routes_test.go:462: services:�
> I1030 17:57:17.764]     routes_test.go:463: start time: 2019-10-30 17:57:11.100364971 +0000 UTC m=+0.266872445
> I1030 17:57:17.764]     routes_test.go:464: --- ---
> I1030 17:57:17.765]     routes_test.go:478: counter: 1
> I1030 17:57:17.765]     routes_test.go:479: time: 2019-10-30 17:57:11.104984276 +0000 UTC m=+0.271491793
> I1030 17:57:17.765]     routes_test.go:483: extensionCreates:
> I1030 17:57:17.765]     routes_test.go:484: 1
> I1030 17:57:17.765]     routes_test.go:490: 
> I1030 17:57:17.765]     routes_test.go:478: counter: 2
> I1030 17:57:17.765]     routes_test.go:479: time: 2019-10-30 17:57:11.105277266 +0000 UTC m=+0.271784735
> I1030 17:57:17.766]     routes_test.go:487: extensionDeletes:
> I1030 17:57:17.766]     routes_test.go:488: 1
> I1030 17:57:17.766]     routes_test.go:490: 
> I1030 17:57:17.766]     routes_test.go:478: counter: 3
> I1030 17:57:17.766]     routes_test.go:479: time: 2019-10-30 17:57:11.10834706 +0000 UTC m=+0.274854680
> I1030 17:57:17.766]     routes_test.go:483: extensionCreates:
> I1030 17:57:17.766]     routes_test.go:484: 2
> I1030 17:57:17.767]     routes_test.go:490: 
> I1030 17:57:17.767]     routes_test.go:478: counter: 4
> I1030 17:57:17.767]     routes_test.go:479: time: 2019-10-30 17:57:11.111640576 +0000 UTC m=+0.278148079
> I1030 17:57:17.767]     routes_test.go:483: extensionCreates:
> I1030 17:57:17.767]     routes_test.go:484: 3
> I1030 17:57:17.767]     routes_test.go:490: 
> I1030 17:57:17.767]     routes_test.go:478: counter: 5
> I1030 17:57:17.768]     routes_test.go:479: time: 2019-10-30 17:57:11.112842904 +0000 UTC m=+0.279350372
> I1030 17:57:17.768]     routes_test.go:487: extensionDeletes:
> I1030 17:57:17.768]     routes_test.go:488: 2
> I1030 17:57:17.768]     routes_test.go:490: 
> I1030 17:57:17.768]     routes_test.go:478: counter: 6
> I1030 17:57:17.768]     routes_test.go:479: time: 2019-10-30 17:57:11.116019361 +0000 UTC m=+0.282526831
> I1030 17:57:17.768]     routes_test.go:483: extensionCreates:
> I1030 17:57:17.768]     routes_test.go:484: 4
> I1030 17:57:17.769]     routes_test.go:490: 
> I1030 17:57:17.769]     routes_test.go:494: --- events captured ---
> I1030 17:57:17.769]     routes_test.go:498: final time: 2019-10-30 17:57:11.116146462 +0000 UTC m=+0.282653914
> I1030 17:57:17.769]     routes_test.go:499: final counter: 6
> I1030 17:57:17.769]     routes_test.go:500: extensionCreates:
> I1030 17:57:17.769]     routes_test.go:501: 4
> I1030 17:57:17.769]     routes_test.go:502: extensionDeletes:
> I1030 17:57:17.770]     routes_test.go:503: 2
> ```

I see, so perhaps we need to add waits inbetween each?

```
	services := append(extensionServices, nonExtensionServices...)
	subscriber, _ := endpoints.ResourcesBroadcaster.Subscribe()
	for _, svc := range services {
		// Create, Delete, then reCreate each service to test register/unregister
		_, err := r.K8sClient.CoreV1().Services(svc.Namespace).Create(&svc)
		if err != nil {
			t.Fatalf("Error creating service '%s': %v\n", svc.Name, err)
		}
		err = r.K8sClient.CoreV1().Services(svc.Namespace).Delete(svc.Name, &metav1.DeleteOptions{})
		if err != nil {
			t.Fatalf("Error deleting service '%s': %v\n", svc.Name, err)
		}
		_, err = r.K8sClient.CoreV1().Services(svc.Namespace).Create(&svc)
		if err != nil {
			t.Fatalf("Error recreating service '%s': %v\n", svc.Name, err)
		}
	}
```

These must be "fire and forget" calls insofar as they're not registered on the (fake...) Kube API server yet.

**Comment by AlanGreene** [comment]
Do we have next steps for this issue? It's still happening: https://storage.googleapis.com/tekton-prow/pr-logs/pull/tektoncd_dashboard/728/pull-tekton-dashboard-unit-tests/1198963244929126400/build-log.txt

**Comment by a-roberts** [comment]
Yeah it's up for anyone to take on, I think there are enough clues here so hopefully it is as simple as adding a "wait for this to be done" before doing the create/delete/recreate events - e.g with a loop that checks the resource is registered with the fake k8s client

**Comment by a-roberts** [comment]
Had enough of this failing so I'm doing a PR now to comment it out
