### ISSUE TITLE
Secrets created through the dashboard made with no username/password data (0.2.1 release)

### ISSUE THREAD

**Issue by tomfrenken** [tektoncd/dashboard#704]
# Expected Behavior
When I create a `secret` the `data` field shouldn't be empty.
# Actual Behavior
The `username` and `password` both have no value.

# Steps to Reproduce the Problem

1. Create secret through Dashboard
2. `kubectl secret/<secret-name> -o yaml`

# Additional Info
I already tried different browsers, incognito mode, reapplying the latest release, different service accounts and passwords as well as different server url's, the POST payload still looks like this:

```
{kind: "Secret", apiVersion: "v1",…}
apiVersion: "v1"
data: {password: "", username: ""}
kind: "Secret"
metadata: {name: "test2", namespace: "default", selfLink: "/api/v1/namespaces/default/secrets/test2",…}
annotations: {tekton.dev/git-0: "https://github.com"}
creationTimestamp: "2019-11-07T10:28:12Z"
labels: {serviceAccount: "steve"}
name: "test2"
namespace: "default"
resourceVersion: "491765"
selfLink: "/api/v1/namespaces/default/secrets/test2"
uid: "4d428143-0149-11ea-8eca-42010aa40012"
type: "kubernetes.io/basic-auth"
```

Here is my Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.9", GitCommit:"6c1e92d07f5717440f751666d4aad6943015d3cb", GitTreeState:"clean", BuildDate:"2019-10-11T23:14:17Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}
```

and here my image sha:

```
gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256:b985769636204f2d736e20dbafa27ff68ba07c218445925da094a2dd8ab07a6a
```

**Comment by a-roberts** [comment]
I had a look at this with Tom and couldn't reproduce this, we had a look in the inspector on Chrome and noticed our request to the proxy contained no username or password data.

Interestingly the server URL can be modified.

Interesting code is here https://github.com/tektoncd/dashboard/blob/master/src/components/SecretsModal/BasicAuthFields.js

**Comment by CarolynMabbott** [comment]
I have tried to reproduce this but couldn't using master or 0.2.1. 
The sha you linked to was created on the 14th October however Adams fix didnt go in until the 15th so it possible that you may not be using the code with the fix in

**Comment by tomfrenken** [comment]
Strange, I get the image when I run:
```
kubectl apply --filename https://github.com/tektoncd/dashboard/releases/download/v0.2.1/dashboard-latest-release.yaml
```
how do I receive an image with the change from Adam?

**Comment by CarolynMabbott** [comment]
Fixed now, you can run the above command again and you wont have the issue anymore in the 0.2.1 release

**Comment by tomfrenken** [comment]
Yub it's fixed now, thanks for fixing it!
