### ISSUE TITLE
Much more detailed getting started section

### ISSUE THREAD

**Issue by ffahri** [tektoncd/dashboard#71]
Currently at the getting started section just says build image and run it.
But if you visit the localhost:9097 url (port-forwarding) you cannot see anything.

You need to run npm install & npm start to access web ui locally

**Comment by a-roberts** [comment]
Hey @ffahri, you're right, please see [this relevant issue](https://github.com/tektoncd/dashboard/issues/14) and [this PR for it](https://github.com/tektoncd/dashboard/pull/78/files): this should give you everything you need.

I'm going to review said PR now and hopefully this makes things much clearer for you, feedback welcome

**Comment by a-roberts** [comment]
We merged the changes yesterday evening for this and we've verified you get the frontend now connected to the backend OK, @ffahri would you be so kind as to give this a try now please following our readme?

If you get the frontend ok can you then close this one off please? Thanks!

**Comment by ffahri** [comment]
Thanks i can access the dashboard as well but i think https://github.com/tektoncd/dashboard/issues/14 this will solve all of this. Thanks for the quick response and good work.
Closing this issue
