### ISSUE TITLE
Selecting a value from a drop-down field when using the keyboard is not user friendly

### ISSUE THREAD

**Issue by rnapoles-tktn** [tektoncd/dashboard#711]
Problem:
If I want to select a value from a drop-down field (namespace, service account) using the keyboard I have to press the down key many times. This is bad for accessibility. 

Expected behavior: 
Type the first letter of the namespace to jump to the first namesapce starting with that letter. Even better if I can type more than one letter to get as close as possible to the desired value.

Steps to reproduce:
Scenario1: 
In the Tekton UI from the left menu expand the Namespace drop-down. Try to select tekton-pipelines, or any existing namespace near the end of the list. 
Try to jump to the tekton-pipelines namespace by pressing the letter "t". Nothing happens. You have to press the down key many time until you reach the tekton-pipelines namespace near the end of the list.
Scneario 2:
In the tekton UI select Secrets
Clcik the "Add secret +" button
Expanding the Select Namespace drop-down. Try to select tekton-pipelines, or any existing namespace near the end of the list.  
Try to jump to the tekton-pipelines namespace by pressing the letter "t". Nothing happens. You have to press the down key many time until you reach the tekton-pipelines namespace near the end of the list.
Scenario3:
Select "Import Tekton resources from repository"
Try to select a Service Acount. Same behaviour as por Namespace drop-down

**Comment by AlanGreene** [comment]
This should be a relatively simple change to make, by switching the underlying component used by our TooltipDropdown from Carbon's Dropdown to [ComboBox](http://react.carbondesignsystem.com/?path=/story/combobox--default) and mapping its `label` prop to the ComboBox's `placeholder` prop. There may be some other minor tweaks required but that should cover most of it.

**Comment by CarolynMabbott** [comment]
ComboBox has a few issues in the current available release and doesnt have some needed prop features to be able to get this implemented yet 
When the next version of carbon is released with the fixes in will be able to implement this

**Comment by AlanGreene** [comment]
ComboBox implemented for Namespaces, Pipelines, PipelineResources, and ServiceAccounts dropdowns. This adds typeahead support displaying a filtered list of the available resources for selection.
