### ISSUE TITLE
Some field name captions are followed by colon

### ISSUE THREAD

**Issue by rnapoles-tktn** [tektoncd/dashboard#712]
Problem:
Some field name captions are followed by colon, but not all of them. In most cases a colon is NOT used.
In some cases there is inconsistency within the same dialog (Add secret dialog)

Expected behavior: 
For consistency we should use the same patter for all captions.

List of captions that include a colon:
PipelineRuns > Filters:
Secrets > Add Secret > Name: , Access To: , Username: , Password/Token: , Server URL:

**Comment by a-roberts** [comment]
Merge in progress so closing
