### ISSUE TITLE
The red x icon is used to delete URLs (when adding secrets) instead of a garbage can icon

### ISSUE THREAD

**Issue by rnapoles-tktn** [tektoncd/dashboard#715]
# Expected Behavior
The garbage can icon should be used to delete URLs in the Create secret dialog

# Actual Behavior
The red x icon is used to delete unwanted URLs. 
The red x icon should only be used to denote that something failed, like in the PipelineRuns UI and the TaskRuns UI

# Steps to Reproduce the Problem
1. Select Secrets > Add Secret
2. The red x icon is used for the Server URL to delete unwanted URLs
3. Create a secret and submit it to get it saved
4. The list of secrets is displayed
5. select one secret using the corresponding check-box 
6. a blue header is displayed with a Delete caption, followed by a garbage can icon and a Cancel button

# Additional Info
Suggestion: use the garbage can icon that is used to delete secrets

**Comment by a-roberts** [comment]
Merged so closing

**Comment by a-roberts** [comment]
Discussed on the design call actually, delete here

![image](https://user-images.githubusercontent.com/12814972/68688442-a4ecb200-0566-11ea-866a-3994979013e6.png)


does look real funky..
