### ISSUE TITLE
KeyValueList component unintuitive design

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#716]
# Expected Behavior
It should be intuitive to use all of the UI components in the Dashboard.

# Actual Behavior
The KeyValueList component, introduced in the Secrets modal, has some unintuitive behavior that should be addressed. Per @AlanGreene's [comment](https://github.com/tektoncd/dashboard/pull/699#issuecomment-551082566):
> I'd like to get some design input on the controls for adding/removing items from the list, in particular for removal... IMO having the remove button at the top of the list remove an item from the bottom of the list seems odd. Since this is a pattern we're starting to reuse in multiple places in the UI we should make sure we're not causing confusion.

<img width="441" alt="Screen Shot 2019-11-11 at 10 52 07 AM" src="https://user-images.githubusercontent.com/16961496/68600914-54475d00-0471-11ea-8a1f-35383ca7b84b.png">

# Additional Info
@kimholmes @mii-w do you have any input? 🙂

**Comment by kimholmes** [comment]
@ncskier 
Here is the design for "add annotation" in Secret creation:
![SecretAnnotation](https://user-images.githubusercontent.com/21316329/69075618-bb2fbd80-09ff-11ea-9835-cba0e70e7fe8.png)

1. The user can click on "Add Annotation to add another row below the current row:
![image](https://user-images.githubusercontent.com/21316329/69076124-cb946800-0a00-11ea-9748-8a2721b2b020.png)

2.![image](https://user-images.githubusercontent.com/21316329/69076619-dc91a900-0a01-11ea-9d15-2f0749072581.png)

- They can delete rows by clicking the (X) at the end of the row.
- For the hint text. Please see the specs here on the Carbon site:
https://www.carbondesignsystem.com/components/form/code
- The user can click in the field to type. If they delete their text, the hint text reappears.

**Comment by ncskier** [comment]
Thanks @kimholmes!

**Comment by ncskier** [comment]
@AlanGreene, looking at figure 2 there, I think we'll need to modify the `KeyValueList` shared component. There is a Dropdown in this instance, but the CreatePipelineRun modal will have a Text Input Field where the Dropdown is (https://github.com/tektoncd/dashboard/pull/699). What would be the best way to structure this shared component?

I think we could have the shared component handle the "add" and "remove" behavior, and it could use a prop to know what to render in the list (in figure 2, the prop would be the `Access to` Dropdown & `Server URL` Text Input Field). However, I don't know if there would be a problem tracking the data & error handling through the component. What do you think?
