### ISSUE TITLE
Keep namespace column when namespace is selected from the dropdown

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#717]
# Expected Behavior
When I filter the results in a table, I expect the columns to remain the same.

# Actual Behavior
In the Dashboard list views, when I change the selected namespace to filter by namespace, the columns change (the `Namespace` column disappears).
<img width="1299" alt="Screen Shot 2019-11-11 at 1 55 26 PM" src="https://user-images.githubusercontent.com/16961496/68613171-2c192780-048c-11ea-894e-8e09afd41a63.png">
<img width="1296" alt="Screen Shot 2019-11-11 at 1 55 36 PM" src="https://user-images.githubusercontent.com/16961496/68613175-2e7b8180-048c-11ea-815c-020d1530ec50.png">

# Steps to Reproduce the Problem

1. Go to any list view in the Dashboard (for example the PipelineRuns page)
2. Set the Namespace dropdown (in the left navigation menu) to `All Namespace`
3. Set the Namespace dropdown to `default` (or another namespace)
4. Notice the `Namespace` column has disappeared

# Additional Info
@kimholmes @mii-w thank you for pointing out this issue 🙂

**Comment by AlanGreene** [comment]
/assign

we need to keep the ability for 3rd parties to hide the namespace (IBM Cloud currently relies on this behaviour due to use of ephemeral namespaces), but agree that the dashboard should always show namespace for consistency
