### ISSUE TITLE
Enzyme needs to be integrated for testing purposes

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#720]
In order to test the functionality of the create secret modal we need to be able to use enzyme to set props on the modal. Specifically this is needed for testing that an error notification appears when a secret fails to be created, as there does not seem to be another way to test it as far as we can tell.

**Comment by AlanGreene** [comment]
Let's avoid adding enzyme if possible, I'm happy to help debug any issues with the tests in https://github.com/tektoncd/dashboard/pull/719
