### ISSUE TITLE
Text input fields only accept English characters, should accept characters of any of IBM's supported languages

### ISSUE THREAD

**Issue by rnapoles-tktn** [tektoncd/dashboard#723]
# Expected Behavior
User should be able to enter characters of any of the 10 languages supported by IBM's applications in characteds in input fileds

# Actual Behavior
Text input fields should allow users to enter non English characters.

# Additional Details
The following are the 10 languages traditionally supported by IBM applications:
- German
- Spanish 
- French
- Italian 
- Japanese
- Korean
- Portuguese
- Russian
- Traditional Chinese
- Simplifies Chinese

# Steps to reproduce
Try any of the following characters:
ÁÉÍÓÚáéíóúäëïöüÿâêîôûÇçàèùß
これは秘密です
이건 비밀이야
секрет
這是個秘密
这是个秘密

**Comment by AlanGreene** [comment]
kubernetes resource names can only contain a limited set of characters, specifically digits (0-9), lower case letters (a-z), `-`, and `.`. See https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names for details.

Similarly, labels and annotations have a restricted set of allowed characters (although slightly more permissive than resource names):
- [label syntax and character set](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)
- [annotation syntax and character set](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set)

@rnapoles-tktn can you provide examples of other fields in the dashboard that should accept additional characters but currently do not?

**Comment by AlanGreene** [comment]
Closing. I can't find any fields that should accept additional characters that do not.
If there are specific fields that need to be updated please add details and we can reopen this.
