### ISSUE TITLE
TriggerTemplate details paneling design

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#724]
This work is under epic https://github.com/tektoncd/dashboard/issues/509

I created this issue, because there was some confusion about what design from #669 should be implemented.

The purpose of this issue is to have a place to iterate on the TriggerTemplate panels separate from the implementation issues. This way, there will be less confusion about what design should be implemented.

The initial work for this issue was done under #669.

## Additional Info
- TriggerTemplates README: [triggertemplates.md](https://github.com/tektoncd/triggers/blob/master/docs/triggertemplates.md)
- TriggerTemplates type definition: [trigger_template_types.yaml](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/trigger_template_types.go)
- TriggerTemplate example: [triggertemplate.yaml](https://github.com/tektoncd/triggers/blob/master/examples/triggertemplates/triggertemplate.yaml)

**Comment by AlanGreene** [comment]
Remaining work tracked in https://github.com/tektoncd/dashboard/issues/937 for consistency across the trigger pages
