### ISSUE TITLE
TriggerBinding details paneling design

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#725]
This work is under epic https://github.com/tektoncd/dashboard/issues/509

The purpose of this issue is to have a place to iterate on the TriggerBinding panels separate from the implementation issues. This way, there will be less confusion about what design should be implemented.

The initial work for this issue was done under #670.

## Additional Info
- TriggerBindings README: [triggerbindings.md](https://github.com/tektoncd/triggers/blob/master/docs/triggerbindings.md)
- TriggerBindings type definition: [trigger_binding_types.yaml](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/trigger_binding_types.go)
- TriggerBinding example: [triggerbinding.yaml](https://github.com/tektoncd/triggers/blob/master/examples/triggerbindings/triggerbinding.yaml)

**Comment by AlanGreene** [comment]
Remaining work tracked in https://github.com/tektoncd/dashboard/issues/937 for consistency across the trigger pages
