### ISSUE TITLE
EventListener details paneling design

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#726]
This work is under epic https://github.com/tektoncd/dashboard/issues/509

The purpose of this issue is to have a place to iterate on the EventListener panels separate from the implementation issues. This way, there will be less confusion about what design should be implemented.

The initial work for this issue was done under #671.

## Additional Info
- EventListeners README: [eventlisteners.md](https://github.com/tektoncd/triggers/blob/master/docs/eventlisteners.md)
- EventListener type definition: [event_listener_types.yaml](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/event_listener_types.go)
- EventListener example: [eventlistener.yaml](https://github.com/tektoncd/triggers/blob/master/examples/eventlisteners/eventlistener-interceptor.yaml)

**Comment by AlanGreene** [comment]
Remaining work tracked in https://github.com/tektoncd/dashboard/issues/937 for consistency across the trigger pages
