### ISSUE TITLE
Dashboard UI Implementation for Secrets

### ISSUE THREAD

**Issue by kimholmes** [tektoncd/dashboard#727]
# Expected Behavior
The portion of the Dashboard UI for Secrets should use design patterns and components for Carbon 10 and reflect the user experience created through collaboration between Development, Design and User Research

# Actual Behavior
The actual behavior is found in the current implementation of the Dashboard UI

# Design Specs:
### Secrets Main List View
(Done)
<details>

Specs: https://kimholmes.github.io/Exported-Specs/Secrets/Secrets_Main/

![Secrets_Main](https://user-images.githubusercontent.com/21316329/68721248-c5753600-057f-11ea-8194-f656ab352d6e.png)

</details>

### Secrets - Create
(Done)
<details>

![Secrets_Create_NewFlow](https://user-images.githubusercontent.com/21316329/69458105-98bddd00-0d3c-11ea-929c-a91decd8357d.png)

Screen 1:
https://kimholmes.github.io/Exported-Specs/Secrets/Secrets_Create1/
Screen2:
https://kimholmes.github.io/Exported-Specs/Secrets/Secrets_Create/index.html#artboard2
Screen3:
https://kimholmes.github.io/Exported-Specs/Secrets/Secrets_Create/index.html#artboard1
Screen4: 
https://kimholmes.github.io/Exported-Specs/Secrets/Secrets_Create/index.html#artboard3

</details>

### **Secrets - Detail View**
Specs: https://kimholmes.github.io/Exported-Specs/Secrets/Secrets_Detail/Secrets_Detail1/
![Secrets_Detail ](https://user-images.githubusercontent.com/21316329/68722116-85638280-0582-11ea-98b1-572c5bbe6ae3.png)

**Edit Mode:**
Specs: https://kimholmes.github.io/Exported-Specs/Secrets/Secrets_Detail/Secrets_DetailEdit/
![Secrets_DetailEdit](https://user-images.githubusercontent.com/21316329/68722123-898fa000-0582-11ea-8840-cd1bb1c4bafc.png)

**Comment by kimholmes** [comment]
@AlanGreene

**Comment by ncskier** [comment]
@kimholmes how does a user remove an annotation with this design?

**Comment by kimholmes** [comment]
FYI - They may not keep the Image Pull Secrets

**Comment by ncskier** [comment]
For reference, here's the issue investigating the use of Image Pull Secrets: https://github.com/tektoncd/dashboard/issues/757

**Comment by kimholmes** [comment]
Updated the specs above with the changes to the annotation design in "Create" mode.

**Comment by carlos-logro** [comment]
Based on the issue that Alan referenced aboved, the wire frames should be updated to include the service account name.

**Comment by AlanGreene** [comment]
@carlos-logro I simply referenced the 2 currently open design issues related to service accounts and secrets so this request could be discussed/considered as part of that work.

There are some technical considerations we should be aware of, such as how we can identify which service accounts a given secret is patched onto? Currently the connection is one way, in the opposite direction (service account holds record of which secrets are patched onto it). Other than retrieving all service accounts and checking if the selected secret is patched onto any of them do we have a way of building this list? If not, is the overhead acceptable?

**Comment by carlos-logro** [comment]
I just checked this and I can confirm what you said about it being in an opposite direction. It can be done by building the list but its kinda inefficient given that we'll need to loop through the SAs, and during that loop iterate through each respective list of secrets. Finally we need to loop through the secrets to make the output for the table so in short to render the table properly three loops has to happen.

**Comment by carlos-logro** [comment]
@AlanGreene here is a draft approach:
*serviceAccounts fetched from store with reducer*
``` Javascript
const secretsFormatted = secrets.map(secret => {
      let annotations = '';
      if (secret.annotations !== undefined) {
        Object.keys(secret.annotations).forEach(function annotationSetup(key) {
          if (key.includes('tekton.dev')) {
            annotations += `${key}: ${secret.annotations[key]}\n`;
          }
        });
      }
      const secretSA = [];
      serviceAccounts.forEach(sa => {
        sa.secrets.forEach(saSecret => {
          if (saSecret.name === secret.name) {
            secretSA.push(sa.metadata.name);
          }
        });
      });
      const formattedSecret = {
        annotations,
        id: `${secret.namespace}:${secret.name}`,
        namespace: secret.namespace,
        name: secret.name,
        sa: secretSA.join(',')
      };

      return formattedSecret;
    });
```

**Comment by carrenelloyd** [comment]
@carlos-logro @kimholmes 

Redlines for Secrets posted here: https://ibm.invisionapp.com/share/MPNZNGNZJ3E

Original high-fis here: https://ibm.invisionapp.com/share/EMNZB7QKZAT

**Comment by AlanGreene** [comment]
No further work planned for either secrets or service accounts at the moment. We can revisit these designs in future if this changes.

/close
