### ISSUE TITLE
Secrets page fails to render with certain manually configured secrets

### ISSUE THREAD

**Issue by afeiszli** [tektoncd/dashboard#731]
# Expected Behavior

When I click on the 'Secrets' page, it should display information 

# Actual Behavior

When I click on the 'Secrets' page, it is blank.

# Steps to Reproduce the Problem

1. Install Kabanero on OCP 3.11
2. Go to the Tekton Dashboard
3. Click on the 'Secrets' page

# Additional Info
![image](https://user-images.githubusercontent.com/31018251/68769865-0d817080-05f3-11ea-9e65-5ed7df4943b5.png)

@a-roberts noted that it may be because I had already created secrets in the project that were causing the issue.

Additionally, I _have_ been able to access the secrets page if I first:

1. Go to the dashboard 
2. Select a namespace (rather than all namespaces) that does not have a manually configured secret
3. Click on 'Secrets'
4. Switch to my target namespace

**Comment by a-roberts** [comment]
We've reproduced this fine so working on the fix now

For posterity the reproduce is:

`oc create new-basicauth github.com --password=foo`, attempt to load the secrets page and see this

**Comment by a-roberts** [comment]
Merged now so closing
