### ISSUE TITLE
Dashboard UI Implementation for Service Accounts

### ISSUE THREAD

**Issue by kimholmes** [tektoncd/dashboard#733]
# Expected Behavior
The portion of the Dashboard UI for Secrets should use design patterns and components for Carbon 10 and reflect the user experience created through collaboration between Development, Design and User Research

# Actual Behavior
The actual behavior is found in the current implementation of the Dashboard UI

# Design Specs:
https://kimholmes.github.io/Exported-Specs/ServiceAccounts/ServiceAccounts/
Click the left nav to see specs on the following pages:
![image](https://user-images.githubusercontent.com/21316329/68775918-39a1ef00-05fd-11ea-99bc-6f29e739760e.png)

**Service Accounts Main List View**
![ServiceAccountsMain](https://user-images.githubusercontent.com/21316329/68776046-6eae4180-05fd-11ea-94b3-34462caca456.png)

**Service Accounts Detail**
![Service_Accounts_Details](https://user-images.githubusercontent.com/21316329/68776167-a3ba9400-05fd-11ea-96dc-184f624ade9c.png)

**Service Accounts Add Secret**
![ServiceAccounts_AddSecret](https://user-images.githubusercontent.com/21316329/68776201-b208b000-05fd-11ea-98b7-d48b71b7bcf2.png)

**Service Accounts YAML tab**
![Service_Accounts_YAML](https://user-images.githubusercontent.com/21316329/68776224-be8d0880-05fd-11ea-99ee-7c9a099d4339.png)

**Comment by kimholmes** [comment]
@AlanGreene

**Comment by carrenelloyd** [comment]
Link to high-fi specs: https://ibm.invisionapp.com/share/MPNZNGNZJ3E


![image](https://user-images.githubusercontent.com/53481064/73292428-0d474900-41d0-11ea-8b9a-7e911b665ebd.png)


![image](https://user-images.githubusercontent.com/53481064/73292460-16d0b100-41d0-11ea-8cca-d2cd2d81cf38.png)


![image](https://user-images.githubusercontent.com/53481064/73292511-2bad4480-41d0-11ea-8cf0-cb4e43192d32.png)

**Comment by AlanGreene** [comment]
No further work planned for either secrets or service accounts at the moment. We can revisit these designs in future if this changes.

/close
