### ISSUE TITLE
Install new pipelines from Git

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#75]
Extend the dashboard so that a user can specify the Git coordinates of new Pipeline, Task and other definitions that should be installed into the target namespace. We can use the API delivered under https://github.com/tektoncd/dashboard/issues/24 to run a simple `git clone / kubectl apply` pipeline to achieve this. 

In this first instance, any git credentials must be set up by the user separately. We can add in credential support once we've fleshed that out.

**Comment by mnuttall** [comment]
@dibbles is helping to coordinate design efforts in this area so please work with him to pick up the latest thinking.

**Comment by jessm12** [comment]
The below initial design that @dibbles created and posted under https://github.com/tektoncd/dashboard/issues/35#issuecomment-486177832 is where I am going to be starting from in working on this issue in terms of UI design and the proposed user flow

<img width="792" alt="Screen Shot 2019-04-24 at 16 06 39" src="https://user-images.githubusercontent.com/32932155/56671265-3ddfdc80-66ac-11e9-89cb-3d7a2cc06a83.png">


There will also be a requirement under this issue to handle the initial installation of 'Pipeline0' ie. the Pipeline to install/kubectl apply other Pipeline and Task resources from a Git repository

**Comment by jessm12** [comment]
Changes merged in: https://github.com/tektoncd/dashboard/pull/182 

/close
