### ISSUE TITLE
PipelineResources page changes to PipelineRun page when clicking all namespaces 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#758]
# Expected Behavior
I change namespace on the left and it stays on the page PipelineResources when i do the steps below

# Actual Behavior
When i change the namespace on the left to All Namespaces I expect it to stay on the pipeline resources page 

# Steps to Reproduce the Problem

1. Click on a pipelinerun 
2. Go to PipelineResources
3.  Change namespace on left to All Namespaces

# Additional Info
Seems to be only happening when do it in that specific order

**Comment by AlanGreene** [comment]
fyi: https://github.com/tektoncd/dashboard/issues/569#issuecomment-551144646
In the updated designs the namespace dropdown will not be displayed on the detail pages

**Comment by AlanGreene** [comment]
Fixed by https://github.com/tektoncd/dashboard/pull/768
