### ISSUE TITLE
TaskRun page changes to PipelineRun page when clicking all namespaces

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#759]
# Expected Behavior
I change namespace on the left and it stays on the page TaskRun when i do the steps below

# Actual Behavior
When i change the namespace on the left to All Namespaces it goes to PipelineRun page

# Steps to Reproduce the Problem

1. On TaskRuns click on the task (eg, pipeline0-task)
2. Change namespace on the left to All Namespaces
3.

# Additional Info
Happens when you do specific steps above

**Comment by AlanGreene** [comment]
fyi: https://github.com/tektoncd/dashboard/issues/569#issuecomment-551144646
In the updated designs the namespace dropdown will not be displayed on the detail pages

**Comment by CarolynMabbott** [comment]
It's not on a detail page, when you click on the task on the TaskRun page it sets the filter on the page to be the task you clicked on and changes the namespace on the left to that specific namespace. When you change the namespace on the left back to All Namespaces is when the change to PipelineRuns page happens

**Comment by AlanGreene** [comment]
by 'detail page' I mean any page displaying information on a single resource (not a list)

**Comment by AlanGreene** [comment]
Fixed by https://github.com/tektoncd/dashboard/pull/768
