### ISSUE TITLE
Credentials API needs to consider taking a service account as input

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#76]
When patching secrets onto the service account, we might want to think about the fact that the user should be able to choose/specify a service account.

One reason why we might want to do this and move away from an environment variable, is because I think that you will restrict access to repositories.... this might need to be validated, but I believe you cannot have multiple secrets on a service account where the annotation on the secrets are for the same git server. This would mean you would need to use an account that can access all repos you might be interested in using from the git server.

Might it not be the case that for security reasons, different users might have to use different service accounts patched with their own secrets/credentials?

**Comment by akihikokuroda** [comment]
I'll work for this.

**Comment by akihikokuroda** [comment]
I assume that this requires the association between the service account and the secret persisted.  Is it OK to have one config map that have a map of the service account and the secret?

**Comment by dibbles** [comment]
I'm not sure why you would need a config map .... I'm simply saying that during secret creation there should be an input field (possibly optional) for the service account to patch with the secret.

I don't believe we need to persist any information ... the information will end up persisted on the patched service account ..... ??? Maybe i'm not understanding your point.

**Comment by akihikokuroda** [comment]
The credential api supports the delete operation as well as create.  It needs to know the service account to unpatch when it deletes the secret.

**Comment by akihikokuroda** [comment]
Another way is that we can go through all service accounts for the namespace and unpatch the secret.  This may not be too bad.

**Comment by akihikokuroda** [comment]
How about putting the service account name in the label?

**Comment by akihikokuroda** [comment]
PR for this: https://github.com/tektoncd/dashboard/pull/107
