### ISSUE TITLE
other pages don't load when PageErrorBoundary is active

### ISSUE THREAD

**Issue by carlos-logro** [tektoncd/dashboard#761]
# Expected Behavior
I should be able to go to other pages in the dashboard even if one of them failed.

# Actual Behavior
When one of the pages breaks, dashboard redirects to PageErrorBoundary and stays there even when I choose to go to another page. Refresh is needed.

# Steps to Reproduce the Problem

1. Open Dashboard
2. Go to a page with broken code
3. View PageErrorBoundary notification
4. Click SideNav to go to another page
5. Nothing Happens

# Additional Info
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49996607/69252249-b21a2a00-0b80-11ea-96bc-c79b2db7f7c5.gif)

/assign @AlanGreene

**Comment by AlanGreene** [comment]
@carlos-logro this should be fixed on master now, thanks for catching and reporting it
