### ISSUE TITLE
Triggers resource tables have different style than other Dashboard tables

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#772]
# Expected Behavior
I expect everything in the Dashboard to have a consistent style. In particular, I expect the tables used in the Triggers views to match the visual style of the tables in the other Dashboard views.

# Actual Behavior
The Triggers tables have a style inconsistent with the rest of the Dashboard.

Here is a comparison showing the inconsistencies between the TriggerBindings table and the PipelineRuns table:
<img width="1274" alt="Screen Shot 2019-11-25 at 9 54 38 AM" src="https://user-images.githubusercontent.com/16961496/69553410-2c2a2480-0f6e-11ea-8e5e-6138aa527cfa.png">
<img width="1274" alt="Screen Shot 2019-11-25 at 9 54 50 AM" src="https://user-images.githubusercontent.com/16961496/69553420-30564200-0f6e-11ea-920e-e086ae512519.png">

**Comment by AlanGreene** [comment]
All list views should be updated to use Carbon DataTable for consistency and to make use of the action toolbar and other DataTable features. This will eliminate most of the style inconsistencies between the list views as we'll no longer be using the StructuredList styles.

We have a common [Table component](https://github.com/tektoncd/dashboard/blob/master/packages/components/src/components/Table/Table.js) now (thanks @carlos-logro) that should make this easier.

**Comment by AlanGreene** [comment]
Also see https://github.com/tektoncd/dashboard/issues/775 for updated designs of the Pipeline(Run)s and Task(Run)s pages.

**Comment by carlos-logro** [comment]
@Megan-Wright during the surfacing of the TriggerBindings details page I stumbled upon some nits that should be taken care of in this issue:

1) Table title has too many padding
<img width="712" alt="Screen Shot 2019-12-02 at 1 45 48 PM" src="https://user-images.githubusercontent.com/49996607/69987077-b04f4f80-150c-11ea-8f7a-71eefb83e125.png">

2) even when no batchActions or toolbar buttons are passed as props, the space for the element still shows up. 
<img width="736" alt="Screen Shot 2019-12-02 at 1 45 35 PM" src="https://user-images.githubusercontent.com/49996607/69987100-b8a78a80-150c-11ea-915c-927d99771962.png">

# How it should look:
<img width="704" alt="Screen Shot 2019-12-02 at 1 42 52 PM" src="https://user-images.githubusercontent.com/49996607/69987120-c8bf6a00-150c-11ea-954c-87837a861422.png">

Changes I did on my side:
1. in Table SCSS file: 
``` CSS
  .bx--data-table-header{
    padding-left: 0;
    padding-bottom: 0;
  }

  .bx--data-table-container{
    margin-top: 0;
  }
``` 

2. in Table.js
``` Javascript
{(toolbarButtons.length || batchActionButtons.length) !== 0 && (
  <TableToolbar>  [...]  </TableToolbar>
)}
```

cc: @a-roberts & @AlanGreene

**Comment by AlanGreene** [comment]
1. we should be using the Carbon styles as much as possible, and when overriding them ensuring we're doing so consistently across the whole dashboard, i.e. avoiding too many page-specific styles. I suspect that after removing the toolbar placeholder (see 2) it will look much better, as in the Carbon storybook.

    @kimholmes should we be following the Carbon guidelines for aligning the content based on the text (so the heading and the table content would be left aligned as in the first screenshot) or are we left-aligning the surrounding boxes instead?

2. the suggested change to skip rendering the toolbar components when the buttons arrays are empty looks good :+1:
