### ISSUE TITLE
Dashboard UI Implementation for Access Token Management

### ISSUE THREAD

**Issue by kimholmes** [tektoncd/dashboard#773]
# Expected Behavior
The portion of the Dashboard UI for Secrets should use design patterns and components for Carbon 10 and reflect the user experience created through collaboration between Development, Design and User Research

# Actual Behavior
The actual behavior is found in the current implementation of the Dashboard UI

# Design Specs
At the following site, please find these six pages with specs for Access Tokens:
https://kimholmes.github.io/Exported-Specs/AccessTokens/AccessTokenManagement/
Use the left nav to access the following pages:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/21316329/69558098-a5794580-0f75-11ea-8e00-3d75bc9d8082.png">

**AccessToken Main List View:**
![24_Access_Token_MGMT](https://user-images.githubusercontent.com/21316329/69558448-3d772f00-0f76-11ea-826a-a66f0bf10009.png)

**AccessToken Row Selected:**
![25_Access_Token_MGMT_Selected](https://user-images.githubusercontent.com/21316329/69558591-76170880-0f76-11ea-97c1-1e842d9f9d09.png)

**AccessToken - Delete Row Modal:**
![26_Access_Token_MGMT_Modal](https://user-images.githubusercontent.com/21316329/69558640-8c24c900-0f76-11ea-867b-52d57ef3ac43.png)

**AccessToken - Edit Mode:**
![27_Access_Token_MGMT_Edit](https://user-images.githubusercontent.com/21316329/69558692-a8c10100-0f76-11ea-8fe0-40caa38131f2.png)

**AccessToken - Save Edits:**
![28_Access_Token_MGMT_Save](https://user-images.githubusercontent.com/21316329/69558730-c0988500-0f76-11ea-8779-633189006b8f.png)

**AccessToken - Create Mode:**
![29_Access_Token_MGMT_Create](https://user-images.githubusercontent.com/21316329/69558748-cbebb080-0f76-11ea-9f63-c46b7f967da2.png)

**Comment by AlanGreene** [comment]
No further work planned for either secrets or service accounts at the moment. We can revisit these designs in future if this changes.

/close
