### ISSUE TITLE
Use serviceAccountName not serviceAccount for Tekton 0.9

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#774]
We use it here for example https://github.com/tektoncd/dashboard/blob/58e63b990a48db808fa925ddf968416c524e6509/src/api/index.js#L200 - should be serviceAccountName

Under this item check for any other references relying on the field being called `serviceAccount` for TaskRuns and PipelineRuns too.

If you find a way to have this work with both 0.8 and 0.9 that'd be great 😄

**Comment by a-roberts** [comment]
Note serviceAccountName works in 0.8 too

**Comment by afrittoli** [comment]
> Note serviceAccountName works in 0.8 too

Yes, we try to make backward incompatible changes over two releases:
- in v0.8.0 we added `serviceAccountName` and kept `serviceAccount` too
- in v0.9.0 we are removing `serviceAccount`
