### ISSUE TITLE
Dashboard UI Implementation for Pipelines and Tasks

### ISSUE THREAD

**Issue by kimholmes** [tektoncd/dashboard#775]
# Expected Behavior
The portion of the Dashboard UI for Secrets should use design patterns and components for Carbon 10 and reflect the user experience created through collaboration between Development, Design and User Research

# Actual Behavior
The actual behavior is found in the current implementation of the Dashboard UI

# Design Specs for Pipelines:
At the following site, please find these three pages with specs for Pipelines:
https://kimholmes.github.io/Exported-Specs/PipelinesAndTasks/Pipelines/
Use the left nav to access the following pages:
<img width="241" alt="image" src="https://user-images.githubusercontent.com/21316329/69561221-05261f80-0f7b-11ea-96cb-41780c428eaf.png">

**Pipeline Main List View:**
![Piplelines](https://user-images.githubusercontent.com/21316329/69561493-78c82c80-0f7b-11ea-9dda-768986dbbe3f.png)

**Pipeline Row Selected:**
![Piplelines_Selected](https://user-images.githubusercontent.com/21316329/69561523-87aedf00-0f7b-11ea-9e87-e167e2c7cdcc.png)

**Pipeline Filtered List:**
If the user clicks on a Pipeline in the above page, the result is a filtered list of PipelineRuns
![PipelineRuns_NonSelected](https://user-images.githubusercontent.com/21316329/69561628-ba58d780-0f7b-11ea-932f-956f3ede1e14.png)

# Design Specs for Tasks:
At the following site, please find these three pages with specs for Tasks:
https://kimholmes.github.io/Exported-Specs/PipelinesAndTasks/Tasks/
Use the left nav to access the following pages:
<img width="241" alt="image" src="https://user-images.githubusercontent.com/21316329/69561978-4834c280-0f7c-11ea-9eb0-5a8f8e668875.png">

**Tasks Main List View:**
![Tasks](https://user-images.githubusercontent.com/21316329/69562136-8df18b00-0f7c-11ea-97f9-72ff29dab34b.png)

**Tasks Row Selected:**
![TasksSelected](https://user-images.githubusercontent.com/21316329/69562211-afeb0d80-0f7c-11ea-9720-d255af124283.png)

**Tasks Filtered List:**
If the user clicks on a Task in the above page, the result is a filtered list of TaskRuns
![TaskRuns](https://user-images.githubusercontent.com/21316329/69562267-c85b2800-0f7c-11ea-80f9-6697b7fb585c.png)

**Comment by AlanGreene** [comment]
For the PipelineRun and TaskRun status columns should we include the existing status text as a tooltip on the icon / in some other way (or leave it out entirely)?

Sample status text (these come from the environment):
- All Tasks have completed executing
- PipelineRun "output-pipeline-run-r-5mljg" was cancelled
- TaskRun demo-pipeline-run-6-build-skaffold-app-k4wxt has failed
- All Steps have completed executing
- "step-build-and-push" exited with code 1 (image: "docker-pullable://gcr.io/kaniko-project/executor@sha256:d9fe474f80b73808dc12b54f45f5fc90f7856d9fc699d4a5e79d968a1aef1a72"); for logs run: kubectl -n tekton-pipelines logs demo-pipeline-run-6-build-skaffold-web-m7kcm-pod-5c73f8 -c step-build-and-push

These would be the same values we currently display in the Status column
![image](https://user-images.githubusercontent.com/2829095/69571190-67057a00-0fb9-11ea-9a85-b829e68ef40e.png)

**Comment by kimholmes** [comment]
@AlanGreene That's a very good question and my first intuition was to put those in a tooltip. Especially since they can be as long as the one in that last bullet. It seems like they do often have useful information. Do you agree? I am worried about the toolitp being too long though. We might need to allow a certain amount of characters and then cut it off.

**Comment by AlanGreene** [comment]
I didn't actually notice the tooltip in the first PipelineRuns image yesterday, looks like you'd already thought of it 😆

Truncating the text in the tooltip is fine, the user should have enough info to know whether it's interesting or not and can still get more information by navigating to the page for the failed run.

I suspect that most of the time the status text will be relatively short and fit a reasonable size limit. The longer ones probably aren't best read in a tooltip anyway so just including enough to indicate whether the failure is "interesting" should be fine.

**Comment by AlanGreene** [comment]
This issue is still valid. We're introducing batch delete for PipelineRuns and TaskRuns, and should have the same for both Pipeline and Tasks for consistency.

Items specific to TaskRuns are tracked in https://github.com/tektoncd/dashboard/issues/776
