### ISSUE TITLE
Steps displayed after a failed one are marked as "not-run"

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/dashboard#782]
# Expected Behavior
Steps are marked as pass/failed/not-run matching the actual status, regardless of their order.

# Actual Behavior
If one step fails, steps displayed after that are marked as not-run even if they were executed, and logs are displayed correctly.

This is probably a side effect to the fact that steps are not displayed in order of execution to begin with, nonetheless the UI should not rely on that to assume that a step was not run.

In my case, the step with a failure was the last one to be executed. See attached screenshot.
![image (2)](https://user-images.githubusercontent.com/2205608/69734271-9980b580-1126-11ea-8e90-88b6a42fbb09.png)

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by AlanGreene** [comment]
Backing out https://github.com/tektoncd/dashboard/pull/653 should resolve this now that tektoncd/pipeline correctly sets the status of these steps. We just need to make sure we're ok in terms of versions for our next planned kabanero supporting release.

**Comment by a-roberts** [comment]
> Backing out #653 should resolve this now that tektoncd/pipeline correctly sets the status of these steps. We just need to make sure we're ok in terms of versions for our next planned kabanero supporting release.

Happy for master of dashboard to (to our best ability) work with the latest version of Tekton Pipelines, so yeah anybody who picks this up should do the backout of the commit Al refers to

Worst case scenario for Kabanero is that we cherry pick any juicy commits and remember this one incase something does come up
