### ISSUE TITLE
Cannot install dashboard by kubectl apply -f

### ISSUE THREAD

**Issue by LinuxSuRen** [tektoncd/dashboard#79]
kubectl apply -f https://raw.githubusercontent.com/tektoncd/dashboard/...

error: unable to read URL "https://raw.githubusercontent.com/tektoncd/dashboard/...", server reported 400 Bad Request, status code=400

**Comment by a-roberts** [comment]
Hey @LinuxSuRen, we should make it clearer - that's part of our "Coming soon" objectives which is going to rely on https://github.com/tektoncd/dashboard/issues/81 being done (currently we do not have regular builds available, so it's rightfully failing as no such image exists there!)

For now you should do the steps just above to install the backend, and consult DEVELOPMENT.md for deploying the frontend yourself. 

We are working on improving said steps and the process as part of https://github.com/tektoncd/dashboard/pull/78 so this will all be much easier.

**Comment by LinuxSuRen** [comment]
Thanks for your response.
