### ISSUE TITLE
Should we replace our build/deploy process with a Tekton pipeline?

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#793]
Instead of requiring contributors to install plenty of tools, I bet we could move to having a Tekton pipeline that builds, tests, and optionally deploys the dashboard - and given that having Tekton itself installed as a pre-req to use the dashboard, that's not an entirely weird request.

Our build and deploy process could instead be `tkn` based.

Note that this may be a crazy idea that increases our build process big time 😄 I'm curious either way.

**Comment by eddycharly** [comment]
This will probably require the pipeline to run with admin permissions (to create clusterroles, service account, etc...).

Not sure this will make things easier.

We could easily use `docker exec` commands so that everything happens in containers so the only requirement is docker.

**Comment by a-roberts** [comment]
> This will probably require the pipeline to run with admin permissions (to create clusterroles, service account, etc...).
> 
> Not sure this will make things easier.
> 
> We could easily use `docker exec` commands so that everything happens in containers so the only requirement is docker.

I'm happy for it to just be the build process though (static content + Go), I'm basically trying to avoid people doing 

```
npm ci && dep ensure -v && npm run lint:fix && npm run bootstrap && npm run build_ko
```

after downloading a bunch of dependencies, setting up their GOPATH (we could switch to modules as other Tekton projects have), and then providing some output. 

I don't see a way for the Pipeline to "reach back" to the local file system however, to either show the built dashboard in a browser or to replace what's in one's own local file system (so an npm run start, is for that built webpack bundle). 

The audience I'm thinking of is, regular Tekton Pipeline users, but not regular web developers or Go developers. They want to build the latest source, perhaps to try/test some small change, and if we're advocating Tekton that's surely the best fit.

Your latter point on just using docker exec may be a more interesting though...I'm thinking more about lowering the barrier of entry is anything, so that's a good point.

**Comment by eddycharly** [comment]
I thought about something like (for frontend) : `docker run --rm -v ${PWD}:/work -w /work node:10-alpine npm ci && dep ensure -v && npm run lint:fix && npm run bootstrap && npm run build_ko`.

Didn't test it but it should produce all necessary files on disk without installing node, npm etc...

We could do the same thing for the backend, maybe i will try it later and let you know.

**Comment by eddycharly** [comment]
This works fine:
```shell
#!/bin/bash

echo "build frontend..."

docker run --rm -v ${PWD}:/work -w /work node:10 \
    npm install && \
    npm run bootstrap:ci && \
    npm run build_ko

echo "build backend..."

docker run -it --rm -v ${PWD}:/go/src/github.com/tektoncd/dashboard -w /go/src/github.com/tektoncd/dashboard golang:1.12-alpine \
    apk add curl git && \
    curl -fsSL -o ./dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 && \
    chmod +x /usr/local/bin/dep && \
    echo "dep" && \
    dep ensure -vendor-only && \
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o tekton_dashboard_backend ./cmd/dashboard
```

Starting the dev server is more complicated as it needs to access the forwarded port to the backend (this means the container needs to access a port on the host).
We can probably install kubectl in the pod and port-forward from there.

It's slow as hell on mac, I can hear the filesystem crying :(

**Comment by eddycharly** [comment]
Switching to go modules would be nice too !
