### ISSUE TITLE
Error loading PipelineRuns seen when a user creates a filter with too long a value

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#799]
For PipelineRuns for example, try to add a label e.g. hello:barrrrrrrbarrrrrrrbarrrrrrrbarrrrrrrbarrrrrrrbarrrrrrrbarrrrrrrbarrrrrrrbarrrrrrr

Then you'd see this error:

![image](https://user-images.githubusercontent.com/12814972/70072238-80787880-15ee-11ea-861d-6d01b163a963.png)

http://localhost:8000/#/namespaces/tekton-pipelines/pipelineruns?labelSelector=asd%3Dfoo%2Casdsadsadasdasd%3Dfoooooooooooooo%2Casdasd%3Dfooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooo

**Comment by AlanGreene** [comment]
Making the same request via kube proxy we get more details:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "unable to parse requirement: invalid label value: \"fooofooofooofooofooofooofooofooofooofooofooofooofooofooofooofooo\": at key: \"asdasd\": must be no more than 63 characters",
  "reason": "BadRequest",
  "code": 400
}
```

We need to make sure labels are limited to 63 characters wherever we allow their input.

**Comment by a-roberts** [comment]
Merged so closing, thanks @CarolynMabbott 😹
