### ISSUE TITLE
Adjust extension context root handling

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#80]
This issue proposes a slight change to the context root handling mechanism for extensions introduced under https://github.com/tektoncd/dashboard/pull/34. 

The initial design mounts a context root /foo in an extension onto /foo at the main dashboard. This could become a problem: extensions could clash with each other, or the main dashboard. Instead we propose that:
- Each extension is mounted onto /v1/extension/extension-name/ at the dashboard
- Requests to /v1/extension/extension-name/ are routed to / at the extension in question. / at the extension is always exposed in the expectation that many extensions will only need one endpoint. 
- If `tekton.dashboard.endpoints` is set to `foo` then /v1/extension/extension-name/foo is routed to /foo at the extension
- Multiple context roots can be specified by using the `.` character to separate them: e.g. if `tekton.dashboard.endpoints: foo.bar` then /v1/extension/extension-name/foo is routed to /foo and /v1/extension/extension-name/bar is routed to /bar at the extension.

**Comment by AlanGreene** [comment]
Given:
- extension `my-extension`
- annotation `tekton-dashboard-bundle-location: foo.2b36e73a.js`

The front end will load the JS file as:
`GET /v1/extension/my-extension/foo.2b36e73a.js`

**Comment by mnuttall** [comment]
The need to serve javascript from / means that the extension won't be able to serve REST APIs from / - `tekton.dashboard.endpoints` will always have to be set to a value. I don't think that's the end of the world.

**Comment by AlanGreene** [comment]
If it's easier to serve the JS from `/static` or similar that's fine too. It's a trivial change in the front end code.
