### ISSUE TITLE
Dashboard UI Implementation for Specs

### ISSUE THREAD

**Issue by carrenelloyd** [tektoncd/dashboard#805]
# Expected Behavior
As a user I need a UI that uses Carbon components and is consistent with other business applications that IBM produces. 

# Actual Behavior
The current implementation should use consistent components across all pages of the application. 

# Additional Info

### Heading and Breadcrumbs
A consistent heading and breadcrumbs can be used throughout all pages in Tekton. The use of existing code can be found here:
[The IDE Page Header Component with breadcrumbs and heading ](https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/production-ready-ide-navigation-components-ide-page-header-component--with-breadcrumb-and-heading)

### Button styles and placement
Buttons and actions can be anchored along the Heading or Page Title/breadcrumb area to the right side of the grid. In this case, shown below a Secondary (black), Ghost button (blue outline) and a Primary button have been used.
![image](https://user-images.githubusercontent.com/53481064/70175572-f9d2a280-16a4-11ea-85e9-e16ccc842d16.png)

The buttons are centered along the Page Title 
Layout-04 Token is used to separate the buttons above and below the Filter
![image](https://user-images.githubusercontent.com/53481064/70175905-8f6e3200-16a5-11ea-884c-96c557afe959.png)

Layout-04 Token is used below the button btwn the Tabbed area
![image](https://user-images.githubusercontent.com/53481064/70176212-191dff80-16a6-11ea-92f8-4e7ac94d42d8.png)

**Comment by AlanGreene** [comment]
We no longer use breadcrumbs in the Dashboard headers, and much of the common layout is handled by the application shell and the ResourceDetails component.

Button styles and placement for buttons (and other controls) in the header will need to be taken into account for https://github.com/tektoncd/dashboard/issues/1304

**Comment by AlanGreene** [comment]
Addressing this as part of https://github.com/tektoncd/dashboard/issues/1304
