### ISSUE TITLE
"Error:  the server reported a conflict" should state more information

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#806]
# Expected Behavior

Because the secrets panel does not list "all" secrets, when a conflict exists between the name of the secret I am trying to create and a secret already existing in kubernetes with that name (which might not be shown in the table).

The error should be "A secret already exists in the namespace $FOO with name $BAR"

# Actual Behavior

The error is simply "Error:  the server reported a conflict"

# Steps to Reproduce the Problem

1. Create a secret call "bob" manually (or using the webhooks extension) which does not have the tekton annotations
2. Go to the "secrets" panel and try and create a secret called "bob"

# Additional Info

**Comment by a-roberts** [comment]
Merged so closing
