### ISSUE TITLE
Error/Notification bar should be full page width

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#807]
# Expected Behavior

I expect the error notification bar when it appears to be as wide as the tables on the page (if not page width)

# Actual Behavior

The error bar appears to be some random width (about 70%)

# Steps to Reproduce the Problem

1.  Navigate to pipelineruns (having some pipelineruns created)
2. Delete a pipeline run using kubectl on the command line
3. Now try deleting the same pipeline run in the UI (note notification bar width)

# Additional Info

This is NOT unique to pipelineruns

**Comment by a-roberts** [comment]
Merged so closing
