### ISSUE TITLE
Relocate label util / component

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#813]
@carlos-logro follow up to https://github.com/tektoncd/dashboard/pull/810

If the label formatting util is going to be used in any of our published components (i.e. those in `packages/components`) this code will need to be moved to `packages/utils` so they can access it.

If it's only used in containers / other internal components it can stay as-is and this issue can be closed.

This might actually be useful as a component, since we'll likely want to display the label Tags on many of our resource types.

**Comment by a-roberts** [comment]
Yeah, I think that's reasonable, I'll work on making this change now and refactoring usages

**Comment by a-roberts** [comment]
Merged so closing
