### ISSUE TITLE
Cannot see ServiceAccount for Secret

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#816]
# Expected Behavior
After creating a Secret in the Dashboard and associating it with a ServiceAccount, I expect to be able to see what ServiceAccount has each of my Secrets.

# Actual Behavior
After creating a Secret in the Dashboard and associating it with a ServiceAccount, I cannot see what ServiceAccount the Secret is in. So, when I choose what ServiceAccount I want to use for my PipelineRun, I don't know which one has my Secret. Instead, I must use the `kubectl`.
![Screen Shot 2019-12-09 at 2 57 41 PM](https://user-images.githubusercontent.com/16961496/70469082-60d1cc00-1a96-11ea-9885-94be28e9019e.png)

# Steps to Reproduce the Problem

1. Create a Secret using the Dashboard
2. Forget what ServiceAccount you patched your Secret onto
3. Try to use the Dashboard to find what ServiceAccount you patched your Secret onto

**Comment by AlanGreene** [comment]
Related: https://github.com/tektoncd/dashboard/issues/733 and https://github.com/tektoncd/dashboard/issues/727

**Comment by a-roberts** [comment]
+1 on getting started for this, @enriquel8 from the Appsody project has expressed a keen interest in this too

**Comment by carlos-logro** [comment]
merged so closing
/close
