### ISSUE TITLE
DataTables isSortable function doesn't work for 'computed' values 

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#817]
# Expected Behaviour 
We should be able to have tables that can be sorted by various values. For example: PipelineRuns should be able to be sorted by name, namespace, pipeline, last transition time, etc.

# Actual Behaviour
When sorting is enabled for DataTables (which it isn't currently due to this problem), trying to sort by any column that has a 'computed' value - e.g. a link or a date/time doesn't work.

**Comment by steveodonovan** [comment]
> When sorting is enabled for DataTables (which it isn't currently due to this problem)

FYI, paging is also an important part of why this wasn't enabled. The apiserver does not support sorting natively. I suggest having this piece worked before enabling sorting
