### ISSUE TITLE
Rerun button should not create a new pipeline run

### ISSUE THREAD

**Issue by EnriqueL8** [tektoncd/dashboard#819]
# Expected Behavior
If I want to rerun a pipeline, it should rerun this existing one and not create a new one. I end up with a very large amount of pipeline runs after debugging erros.

# Actual Behavior
The rerun button creates a new pipeline run with a different generated name.

**Comment by AlanGreene** [comment]
@EnriqueL8 thanks for opening an issue, however this is working as intended.

In Tekton, a PipelineRun is a single instance of execution of a Pipeline definition. See https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md for some more info. Rerunning an existing PipelineRun via the dashboard is a shortcut to create a new PipelineRun with the same inputs.
