### ISSUE TITLE
Duplicate config YAML files are a pain

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#822]
# Expected Behavior
As a developer, I expect it to be easy to update the dashboard release and track changes to the pieces of the release.

# Actual Behavior
Right now it is confusing to update the release, because there are 3 files that are mostly duplicates of one another:
1. [`dev-tekton-dashboard.yaml`](https://github.com/tektoncd/dashboard/blob/master/config/dev-tekton-dashboard.yaml)
2. [`openshift-tekton-dashboard.yaml`](https://github.com/tektoncd/dashboard/blob/master/config/openshift/openshift-tekton-dashboard.yaml)
3. [`gcr-tekton-dashboard.yaml`](https://github.com/tektoncd/dashboard/blob/master/config/release/gcr-tekton-dashboard.yaml)

This makes it difficult to track changes to the release, and makes it easy to create inconsistencies between the YAML files. Ideally, there should be no duplicate release YAML code in the repo. Plus, it would be helpful if each k8s object in the release could have its own file (ex: https://github.com/tektoncd/pipeline/tree/master/config).

**Comment by mnuttall** [comment]
Resolved by https://github.com/tektoncd/dashboard/pull/941
