### ISSUE TITLE
Ensure dashboard correctly handles inline Pipeline specs

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#829]
# Expected Behavior
The dashboard should be capable of displaying PipelineRuns containing inline Pipeline specs.
Any code / UI relating to PipelineRuns should not make assumptions about having a standalone Pipeline definition (i.e. `pipelineRef`).

# Actual Behavior
The PipelineRuns component makes assumptions about the presence of `pipelineRun.spec.pipelineRef.name` which breaks the UI in the case of an inline Pipeline spec.

There may be other instances...

# Additional Info
We had a similar issue with TaskRuns (including a recent regression https://github.com/tektoncd/dashboard/issues/821), so we should make sure this is addressed consistently across the dashboard application.

**Comment by a-roberts** [comment]
Carlos' PR is merged for this so closing
