### ISSUE TITLE
De-duplicate dashboard config and update release process

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#839]
Further to tektoncd/experimental#403 and tektoncd/plumbing#156 we should refactor the config/ directory to de-duplicate the 'openshift' directory. 

Other things to do at the same time:
- Update our 'release 0' - nightly build - instructions to use a stable GCS url to pick up the latest config
- Split the RBAC permissions up so that we can generate a 'locked down' dashboard with no edit or delete powers.

**Comment by AlanGreene** [comment]
Related: https://github.com/tektoncd/dashboard/issues/822

**Comment by mnuttall** [comment]
https://github.com/tektoncd/dashboard/pull/941 is merged - we now have no duplicate yaml, and a read-only edition of the dashboard. I'll keep this issue open until I have nightly builds set up and  stable GCS URLs for the various dashboard install yamls.

**Comment by AlanGreene** [comment]
Are we OK to close this now or is there anything left?

**Comment by mnuttall** [comment]
Finished, closing.
