### ISSUE TITLE
PipelineRuns dashboard view has some styling issues

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/dashboard#840]
# Description

Seeing the icon for a pipeline run status appear on top of the status. Also the header above the overflow menu looks off. @Megan-Wright @AlanGreene Possibly related to the move to data tables? either of you aware ? Also seeing in the storybook

![Screenshot 2019-12-13 at 12 27 54](https://user-images.githubusercontent.com/18128367/70800783-06da4a80-1da5-11ea-9694-60c83877cb4a.png)

**Comment by Megan-Wright** [comment]
@steveodonovan Yep we were trying to get the move to data tables in ASAP due to it preventing other work from being done - so the styling is by no means perfect.. I'll have a go at fixing up the issues you've raised now 😸

**Comment by carlos-logro** [comment]
although its not the issue being tackled, I noticed this issue and included the simple solution in the PR #833
