### ISSUE TITLE
Implement pagination and sorting method

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#842]
# Expected Behavior
As a Tekton Dashboard user I should be able to sort/view records without suffering from poor performance (in terms of animations and rendering) so that I don't have a dreadful and frustrating experience

# Actual Behavior
No such sorting or pagination exists
# Steps to Reproduce the Problem

1. Deploy the dashboard and create many PipelineRuns
2. There's no pagination
3. If sorting were to be enabled we're confident performance would be dreadful

# Additional Info
To be investigated before https://github.com/tektoncd/dashboard/pull/833

**Comment by a-roberts** [comment]
Here's a good test case with over 3,000 PipelineResources: 

![image](https://user-images.githubusercontent.com/12814972/73942109-686eef00-48e6-11ea-96ad-c2180a9d8c8f.png)

From  https://dashboard.dogfooding.tekton.dev/#/pipelineruns (@afrittoli the contact who's set this up 🎈 ) so it's definitely something to look into

**Comment by AlanGreene** [comment]
https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks

The Kubernetes API supports chunking, which would allow us to limit the number of resources loaded in a single request.

If we just load the first (large, size TBD) chunk for each type, we could ensure a more responsive UI for these cases with many resources. Obviously this means the user doesn't have access to all resources in the UI unless the resources are labelled and the user knows the correct labels to filter on. I think we need to do some more brainstorming around this, both from a technical and design perspective.

**Comment by Megan-Wright** [comment]
I've had a look into this as well - chunking with the KubeAPI seems perfectly possible however carbon doesn't currently support easy integration between pagination and data tables using react, so not sure how easy this would be to do.

**Comment by AlanGreene** [comment]
This should also include ensuring the strings for the sorting headers are extracted for translation, see https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/DataTable/TableHeader.js and https://github.com/tektoncd/dashboard/blob/0fc671e44a103db1dcfde8b301c921fa3b8c918e/packages/components/src/components/Table/Table.js#L43 for reference.

**Comment by dankraemer** [comment]
Hi, just adding my two cents here. 
My team is migrating the CI/CD infrastructure to Tekton and the number of PipelineRuns is increasing fast.
We have noticed that the `PipelineRuns` page is getting slower, the main problem seems to be because it is retrieving all pipelineruns: 
![image](https://user-images.githubusercontent.com/3615003/87068760-705ff180-c1ec-11ea-8830-84f5f9930460.png)
