### ISSUE TITLE
Update how we identify the correct pod to use for logs

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#843]
See https://github.com/tektoncd/pipeline/issues/1689 and associated PR for details.

TL;DR:
`.status.podName` may be removed in future. We should consider updating our strategy to identify the correct pod, i.e. by using `labelSelector` with `tekton.dev/taskRun={taskRunName}`.

**Comment by AlanGreene** [comment]
fyi, no rush on this one currently as the change in pipelines was reverted due to a regression it caused for retries.

**Comment by Megan-Wright** [comment]
Ok, in that case I'm going to unassign myself since there's more urgent work I'm currently doing

**Comment by AlanGreene** [comment]
Not currently needed, we can reopen if this changes in a future pipelines version.

**Comment by AlanGreene** [comment]
Looks like this is being revisited

**Comment by AlanGreene** [comment]
Closing since there's no sign of this changing anytime soon. We can reopen if needed.
