### ISSUE TITLE
Ensure consistent styling across Trigger pages

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#844]
# Expected Behavior
We should have a set of consistent styles used across all of the Trigger pages, without duplication.

# Actual Behavior
https://github.com/tektoncd/dashboard/pull/797/files#r355993142

# Additional Info
We should remove page-specific styles where possible to ensure consistency and reduce maintenance overhead. Ideally most pages would have very little specific styling applied, instead relying on the Carbon styles and our common page/layout styles.

**Comment by a-roberts** [comment]
Note that this may be complete now (we've just merged the last of the triggers pages so, todo, have a good check)

**Comment by AlanGreene** [comment]
Closing as there are design issues covering remaining updates
