### ISSUE TITLE
Publish dashboard's storybook in public tekton

### ISSUE THREAD

**Issue by carrenelloyd** [tektoncd/dashboard#845]
# Expected Behavior
The current storybook should be publicly accessible to all developers so that users can inherit components and add new components they built easily as an open-source project. 

# Actual Behavior
The current storybook is private on Alan's local server 

# Steps to Reproduce the Problem

1. 
2.
3.

# Additional Info
Add styleguide section to storybook (try to keep to a minimum & mostly use components

**Comment by AlanGreene** [comment]
We have an npm script that builds and deploys the storybook. By default it will publish to the remote `origin` on branch `gh-pages` which will make it available at `https://<username>.github.io/dashboard`.

This is how I've been deploying it to my fork (https://alangreene.github.io/dashboard/) so far.

Should we publish the storybook on each merge (so it always represents `master`) or only on releases?
If only publishing on releases, should we support navigating storybooks from previous releases using https://github.com/buildit/storybook-addon-versions or a similar approach?

**Comment by AlanGreene** [comment]
I propose that as a first step we publish a single version of the storybook, representing the latest release. If it proves useful for others and there's demand for it, we can consider how we would surface multiple versions (latest release + latest nightly for example).

Any developer looking to contribute would run the storybook locally anyway so I don't think there's a need to publish on every merge to master.

As part of this we also need to consider how we're publishing the npm packages and the versioning scheme we use for them. i.e. do we only publish new npm packages with a full dashboard release? Do we publish them nightly? Should the major / minor version match the dashboard version for easier tracking?

If we're publishing new npm packages nightly, then the storybook should probably also be updated nightly so they're in sync, as the npm packages are how developers consume the components represented in the storybook.
