### ISSUE TITLE
Allow namespace selection

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/dashboard#86]
At the moment the dashboard will only show resources in the default namespace.

This effort is to track listing namespaces and selecting a namespace for the pipeline and task runs views

API `GET /v1/namespaces`

**Comment by ffahri** [comment]
Hey, isn't it much more nice to user give namespace for dashboard backend. So backend list resources by giving namespace variable. (like kube dashboard)

**Comment by steveodonovan** [comment]
@ffahri Yep thats the longer term plan. Haven't started this just yet though, might look to do that in the short term instead.

The design here includes the selection https://github.com/tektoncd/dashboard/issues/35
