### ISSUE TITLE
Check published dashboard containers don't run as root

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#865]
See https://github.com/tektoncd/dashboard/pull/862#pullrequestreview-339124743, @mnuttall and I suspect we need changes under the tekton directory as well so that published (through the Tekton pipeline we have) containers aren't running as root either

**Comment by jorgemoralespou** [comment]
Please, do consider this.

I work arounded it by adding to the deployment a:
```
securityContext:
  runAsUser: 1000
```

And the dashboard works fine, so it really doesn't need to run as root. Please consider fixing this as it's a one liner but also a security concern.

**Comment by a-roberts** [comment]
Hey @jorgemoralespou - thanks for the reminder on this one, I noticed recently there were talks around the pipelines component itself running as non-root too.
