### ISSUE TITLE
Warning required when patching service account with secret for duplicate git server

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#866]
# Expected Behavior

I "think" Tekton doesn't support a service account patched with two secrets (two different git userids) accessing the same git server.  Hence the annotation on the secrets both pointing to the same git server.

I would expect some sort of warning with confirmation button if I am patching a service account in such a way that it might cause me problems.

# Actual Behavior

You can patch a service account with multiple secrets annotated with the same git server annotation.

# Steps to Reproduce the Problem

1. Create secret1 with serverURL tekton.dev/git-0 = https://github.com and select service account foo
2. Create secret2 with serverURL tekton.dev/git-0 = https://github.com and select the same service account
3. No warnings are given
4. Create a webhook that access a repository only accessible by the user credentials in secret2
5. I believe the pipelinerun will not work 

# Additional Info

**Comment by AlanGreene** [comment]
This is still valid and would be a nice first issue for someone looking to contribute to the dashboard.

https://github.com/tektoncd/dashboard/blob/master/src/components/CreateSecret/ServiceAccountSelector.js would be a good place to start as it presents the UI to select the ServiceAccount being patched and already has some error handling. This could probably be expanded to add the warning described here.

**Comment by AlanGreene** [comment]
Already reached out to @ziheng on Slack to let him know about possible impact on this task. Posting here too.

Secrets functionality may be going away soon so this may no longer be required. Track discussions / plan at https://github.com/tektoncd/dashboard/issues/1930

**Comment by AlanGreene** [comment]
#1931 is merged, closing this as obsolete.
/close
