### ISSUE TITLE
Left nav not showing selected resource type when viewing a single trigger resource

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#868]
# Expected Behavior
The left nav should always show the selected resource type, as it does for Pipelines, runs, etc.
![image](https://user-images.githubusercontent.com/2829095/71893450-9fb17b00-3143-11ea-8da8-0f234f25dff9.png)

# Actual Behavior
Follow up from https://github.com/tektoncd/dashboard/pull/784#pullrequestreview-339181730

When viewing a list of trigger resources (i.e. EventListeners, TriggerBindings, TriggerTemplates) the nav item is selected as expected.
![image](https://user-images.githubusercontent.com/2829095/71893472-b22bb480-3143-11ea-96aa-80acdce68921.png)

When viewing a single trigger resource there is no nav item selected.
![image](https://user-images.githubusercontent.com/2829095/71893503-ca033880-3143-11ea-9029-8c9231626443.png)

# Additional Info
In SideNav.js, the `to` prop of the SideNavMenuItems should be wrapped in a call to `this.getPath` to ensure it accounts for the namespace in the URL.

Once this is done the nav items should be selected as expected, but there may be other changes required to ensure the namespace isn't doubled in the constructed URLs / API calls for example.

**Comment by carlos-logro** [comment]
merged so closing.
/close
