### ISSUE TITLE
Cant create pipelinerun on Openshift and Docker using a service account

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#875]
# Expected Behavior
Can create a pipelinerun using a service account 

# Actual Behavior
Can create a pipelinerun when not using a service account to run 
Cant create a pipelinerun when using a service account 

Applied to both create pipelinerun and import tekton resources 

The page where it goes to where it says 404 not found does exist and but when you go to the page it has pipelineruns there 
Can create pipelineruns with no service account selected 

# Steps to Reproduce the Problem

1. create a pipelinerun and select a service account to use
2.
3.

# Additional Info
This seems to happen when your dashboard is running on master and pipelines are on a old version like 0.7.0
Would be useful to have a nice warning come up telling you that the versions are incompatible preferably before you do anything on the dashboard as well as possibly when you attempt to create a pipelinerun

<img width="447" alt="Screenshot 2020-01-08 at 15 58 29" src="https://user-images.githubusercontent.com/32342288/71993939-d4026580-322f-11ea-993b-d27075bcd98a.png">

<img width="633" alt="Screenshot 2020-01-08 at 15 58 20" src="https://user-images.githubusercontent.com/32342288/71993940-d4026580-322f-11ea-8e3f-cc4f91b0d06b.png">

<img width="1409" alt="Screenshot 2020-01-08 at 15 59 53" src="https://user-images.githubusercontent.com/32342288/71994015-f1cfca80-322f-11ea-89bb-ec794480855a.png">

**Comment by a-roberts** [comment]
This was due to mismatching Tekton Pipeline and Dashboard versions, we're gonna make the error surfaced as part of https://github.com/tektoncd/dashboard/issues/779, closing
