### ISSUE TITLE
Clean up  PipelineRun component and TaskRun container code

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#885]
While working on PR https://github.com/tektoncd/dashboard/pull/878, I noticed a few things about the [PipelineRun](https://github.com/tektoncd/dashboard/blob/master/packages/components/src/components/PipelineRun/PipelineRun.js) component and [TaskRun](https://github.com/tektoncd/dashboard/blob/master/src/containers/TaskRun/TaskRun.js) container code that could be cleaned up/simplified.
1. The TaskRun container and PipelineRun component seem like they're doing very similar things, and I think there's some overlapping functionality/implementation in both of them that can be extracted into a shared component.
2. The [`stepsStatus()`](https://github.com/tektoncd/dashboard/blob/master/packages/utils/src/utils/index.js#L67) function has an unnecessary second parameter `taskRunStepsStatus`. The TaskRun's `status.steps` already has the status information for each step, so there shouldn't be a second list of statuses passed to the function. This second parameter is also mutated and returned as the [`stepStatus`](https://github.com/tektoncd/dashboard/blob/master/packages/utils/src/utils/index.js#L87). The `stepStatus` should be removed, because it is redundant since `step` already has everything in `stepStatus`. This refactoring will have slight a snowball effect, because the `stepStatus` is used in other components.
3. The `pipelineTaskName` should be renamed, because it is a property only found in PipelineRuns, but it is used in components that display TaskRuns. Since the TaskRuns do not have a `pipelineTaskName`, the property doesn’t make sense in those components.

## Additional Info
These are just some things I noticed, but there might be more to clean up/simplify.

**Comment by AlanGreene** [comment]
1. Where possible we should remove code that sorts / filters tasks or steps and instead rely on Pipelines to provide accurate information. This should allow us to simplify quite a bit in these 2 components and make it easier to extract common code.

2. There have been a number of changes made to the PipelineRun / TaskRun and their child components that may affect this.
It may be possible to remove `stepsStatus` and some of the code that relies on it entirely, but this would need to be tested carefully to ensure we're still covering all cases.

3. This would likely be addressed as part of the refactoring in 1, but something worth keeping an eye on to make sure similar naming doesn't leak out.

**Comment by AlanGreene** [comment]
PR #1814 starts to address these issues, and subsequent changes should be a lot simpler as a result.

1. now relies on Pipelines to provide correct step order in TaskRun.status (Pipelines 0.17+), but still maintains a small amount of code to sort TaskRuns. This can be revisited later.

2. `stepsStatus()` has been removed, and clearer separation between definitions and runtime data maintained across all components. This accounts for the majority of the changes in #1814

3. partly addressed, remainder can be resolved after #1814 is merged. That PR is already very large so I'd like to avoid adding more to it.
