### ISSUE TITLE
Test with and provide known operator install for OpenShift 4.3

### ISSUE THREAD

**Issue by anneqm** [tektoncd/dashboard#894]
for an upcoming release of Kabanero (0.6.0) we need to test with OpenShift 4.3, identify and resolve any gaps, and may need to provide an operator, similar to  OpenShift 4.2 issue https://github.com/tektoncd/dashboard/issues/648.

**Comment by a-roberts** [comment]
No work to be done on this one, we delivered 0.5.2 and Kabanero are picking it up, all tested well on OpenShift 4.3 so closing
