### ISSUE TITLE
Make URLs in logs clickable

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#895]
Being able to click on URLs in the log output would be very useful.

The ansi-to-react component we currently use to render the logs has support for this via the `linkify` prop but it has a number of bugs / limitations.

See https://github.com/tektoncd/dashboard/pull/873#issuecomment-574293426 for more.

**Comment by AlanGreene** [comment]
To consider:
- https://www.npmjs.com/package/react-linkify
- or use linkify-it directly: https://www.npmjs.com/package/linkify-it
- ...?

**Comment by a-roberts** [comment]
I raised a point about https://stackoverflow.com/questions/62771252/execute-maven-based-end-to-end-tests-and-display-result-in-tekton-dashboard/62791025#62791025 in Slack and @AlanGreene's linked to this issue as something we may want to revisit

**Comment by dictyo** [comment]
> I raised a point about https://stackoverflow.com/questions/62771252/execute-maven-based-end-to-end-tests-and-display-result-in-tekton-dashboard/62791025#62791025 in Slack and @AlanGreene's noticed and linked to this issue as something we may want to revisit (I've added a comment on that issue too so it's all in sync)

The creator of the ticket is on board, too :) Hi folks, thanks for your helpful reaction! As my knowledge of Tekton will get more I hope I'll be able to contribute a bit in return.

**Comment by AlanGreene** [comment]
This is in progress. We have a new LogFormat component which handles additional ANSI codes and also makes URLs clickable. It should be enabled for the next release.

/remove-lifecycle rotten
/reopen
