### ISSUE TITLE
Run web project tests in PR job

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/dashboard#90]
The pull request job does not run/report status for npm tests.

`npm run test:ci`

Similarly lint rules are not applied.

**Comment by AlanGreene** [comment]
As a start we should run:

```shell
npm ci # similar to `npm install` but ensures all versions from lock file
npm run test:ci
```

It would also be good to:
```shell
npm run build # will also fail on lint errors
```

**Comment by a-roberts** [comment]
PR for this is [here](https://github.com/tektoncd/dashboard/pull/115), stuck from progressing and details in the PR. I could just be one word away from being done with it (assuming no test failures), depends on what @vdemeester says (I think out for the RedHat summit atm).

**Comment by a-roberts** [comment]
Actually I'm running in a container with just our code, and I'm root in it, so I've continued.

https://prow.tekton.dev/log?job=pull-tekton-dashboard-tests&id=1124292059839074304 check it out.

```
I0503 12:39:22.797] Test Suites: 30 passed, 30 total
I0503 12:39:22.797] Tests:       157 passed, 157 total
I0503 12:39:22.797] Snapshots:   0 total
I0503 12:39:22.797] Time:        11.523s
I0503 12:39:22.797] Ran all test suites.
```

**Comment by a-roberts** [comment]
@vdemeester please take a look at how I'm using Prow, the tests run and pass but perhaps there's a neater way to install things?

**Comment by a-roberts** [comment]
Kindly merged and reviewed now by Alan, discussed on Slack (more details on the PR) about eventually using our own image for tests with deps in, and made an issue for that at https://github.com/tektoncd/dashboard/issues/116. 

Closing 😄
