### ISSUE TITLE
Flaky test extension problems (timeout deleting extension)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#902]
# Expected Behavior
Our unit tests should reliably pass

# Actual Behavior

```
I0116 11:06:46.485] --- FAIL: TestExtension (1.32s)
I0116 11:06:46.485]     --- FAIL: TestExtension/Empty_endpoints (1.08s)
I0116 11:06:46.486]         routes_test.go:444: Timed out waiting for extension deletion
I0116 11:06:46.486]     --- PASS: TestExtension/One_endpoint (0.08s)
I0116 11:06:46.486]     --- PASS: TestExtension/Two_endpoints (0.07s)
I0116 11:06:46.486]     --- PASS: TestExtension/Three_endpoint (0.10s)
I0116 11:06:46.487] === RUN   TestMarshalJSON_Extension
I0116 11:06:46.487] === RUN   TestMarshalJSON_Extension/Extension_1
I0116 11:06:46.487] --- PASS: TestMarshalJSON_Extension (0.00s)
I0116 11:06:46.487]     --- PASS: TestMarshalJSON_Extension/Extension_1 (0.00s)
I0116 11:06:46.487] FAIL
I0116 11:06:46.487] FAIL	github.com/tektoncd/dashboard/pkg/router	1.798s
I0116 11:06:46.488] ?   	github.com/tektoncd/dashboard/pkg/testutils	[no test files]
I0116 11:06:46.488] ?   	github.com/tektoncd/dashboard/pkg/utils	[no test files]
I0116 11:06:46.488] ?   	
```

seen with https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_dashboard/901/pull-tekton-dashboard-unit-tests/1217759636258557952/

# Steps to Reproduce the Problem

1. Run our unit tests for a PR on Prow (should be able to do this locally too)

# Additional Info
We have a long history with our extension testing 😿

**Comment by vtereso** [comment]
I have tracked it down to the informer event handler not being called (~4/100 times locally).

**Comment by vtereso** [comment]
I raised an issue regarding the informers: https://github.com/kubernetes/kubernetes/issues/87472#issuecomment-577881040. It was decided to comment out the test again.

**Comment by mnuttall** [comment]
Test disabled in another PR.
