### ISSUE TITLE
TaskRun running wheel does not appear immediately

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#909]
# Expected Behavior
I expect to see something indicating that my TaskRun has started running after it is created.

# Actual Behavior
I expect the running icon to appear in front of my TaskRun immediately. Instead, there is a delay of a few seconds before the icon appears.
![Screen Shot 2020-01-17 at 10 41 21 AM](https://user-images.githubusercontent.com/16961496/72625178-4f41d680-3916-11ea-8038-8e42ed278db3.png)
![Screen Shot 2020-01-17 at 10 41 27 AM](https://user-images.githubusercontent.com/16961496/72625307-8f08be00-3916-11ea-85e9-c6e0596f9125.png)

# Steps to Reproduce the Problem

1. Create a TaskRun
2. View the TaskRuns list page of the Dashboard

**Comment by AlanGreene** [comment]
hrmm yeah seeing this intermittently when my cluster is a bit slow. We could add another icon for this pending state, or use the same running spinner.

**Comment by AlanGreene** [comment]
Should be resolved now, we were missing an icon for the pending state before it actually starts running.
