### ISSUE TITLE
Dashboard should display real time updates to status of resources

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#91]
For example:
- when viewing a list of PipelineRuns:
  - new PipelineRuns should be added to the list dynamically
  - the status of the displayed PipelinesRuns should be updated in real time
- when viewing a single PipelineRun:
  - TaskRun / step status should be updated in realtime
  - logs should be updated in realtime
- etc.

The back end should provide a websocket connection which publishes events to the front end.

Code exists today providing a dedicated websocket service for pipelineruns, and I have a [test branch](https://github.com/AlanGreene/dashboard/commit/ec22e183adb641c949f4d5314e319163f99b3fb9) using that to dynamically update the PipelineRun list view in the front end.

The back end should provide a single websocket service through which all relevant events are sent, allowing the front end to maintain a single connection, rather than managing multiple parallel connections for various purposes.

**Comment by vtereso** [comment]
Currently there is a websocket that ONLY delivers Create/Update/Delete information on PipelineRuns, but it will be simple enough to send all the data through a single socket. What are all the events that we wish to send?

**Comment by AlanGreene** [comment]
Yes that's the one I've been using for testing/experiments so far and it's working great 👍 

We should probably approach this as a series of steps. I'd suggest:
1. move the existing PipelineRuns websocket from `/v1/websocket/pipelineruns` to `/v1/websocket`
1. enable front end support for real time updates of PipelineRuns (code mostly complete, just needs a little cleanup and tests) using that websocket
1. discuss / prioritise additional requirements for events that will be sent over that same single socket:
    - logs
    - TaskRuns
    - Pipelines
    - Tasks
    - PipelineResources
    - etc.

I don't think we have a full list of events we'd like / need just yet. As more details of the front end design begin to emerge next week we can start having more informed discussions around user expectations.

I'm open to suggestions on any / all of the points above.

**Comment by vtereso** [comment]
Have we completed 1/2?

**Comment by AlanGreene** [comment]
I don't think there's been any work done on this. We should discuss 'filtering / subscription to subset of event types' before we do anything in this area as we probably don't want the client dealing with a total firehose of all events from the cluster...
