### ISSUE TITLE
README.md - Wrong URLs in step 1 for both Install Dashboard and Install on OpenShift

### ISSUE THREAD

**Issue by rnapoles-tktn** [tektoncd/dashboard#913]
Problem:
404 error when executing:
kubectl apply --filename https://github.com/tektoncd/dashboard/releases/download/v0.4.0/dashboard-latest-release.yaml
or
kubectl apply --filename https://github.com/tektoncd/dashboard/releases/download/v0.4.0/dashboard-latest-openshift-tekton-dashboard-release.yaml --validate=false
 as the provided URLs do not exist.

Expected:
The correct URLs are:
https://github.com/tektoncd/dashboard/releases/download/v0.4.0/dashboard_latest_release.yaml
https://github.com/tektoncd/dashboard/releases/download/v0.4.0/dashboard_latest_openshift-tekton-dashboard-release.yaml
Note the use of underscores instead of dashes in the correct URLs.

**Comment by maelvls** [comment]
I proposed a fix in #917

**Comment by a-roberts** [comment]
Merge in progress, apologies all
