### ISSUE TITLE
Can not rebuild (rerun) PipelineRuns

### ISSUE THREAD

**Issue by anxinyf** [tektoncd/dashboard#916]
# Expected Behavior

Want to rerun the PipelineRun into Running status.

# Actual Behavior
After rerun a pipelinerun(origin pipelinerun is succeed) on dashboard, the new generated pipelinerun is missing .spec.serviceAccountName so that the pipelinerun is failed because of incorrect access rights.

**Comment by a-roberts** [comment]
Hey @anxinyf, can you share your dashboard and pipelines version please (I've just modified our issue template for future ref)? 

We've seen this before when the pipeline code we were referencing in our Gopkg.toml file only had `serviceAccount` not `serviceAccountName`, I'm wondering if it's an older PipelineRun you have too

**Comment by a-roberts** [comment]
This is a weird one, with master (ko applying) I noticed this error:

```
{"level":"debug","msg":"in RerunPipelineRun"}
{"level":"debug","msg":"Rerunning PipelineRun: buildah-pipeline-run-qx86k"}
{"level":"debug","msg":"Found the PipelineRun to rerun (buildah-pipeline-run-qx86k in namespace tekton-pipelines)"}
{"level":"debug","msg":"Rerunning a pipelinerun that's not already been rerun"}
{"level":"debug","msg":"Rerun PipelineRun name is: buildah-pipeline-run-qx86k-r-"}
{"level":"debug","msg":"Found existing label(s), adding reruns label"}
{"level":"error","msg":"an error occurred rerunning the PipelineRunbuildah-pipeline-run-qx86k in namespace tekton-pipelines: Internal error occurred: failed calling webhook \"webhook.tekton.dev\": Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/?timeout=30s: no endpoints available for service \"tekton-pipelines-webhook\""}
{"level":"error","msg":"Error: Internal error occurred: failed calling webhook \"webhook.tekton.dev\": Post https:tekton-pipelines-webhook.tekton-pipelines.svc:443?timeout=30s: no endpoints available forservice \"tekton-pipelines-webhook\""
```

With 0.4.1
```
{"level":"debug","msg":"in RerunPipelineRun"}
{"level":"debug","msg":"Rerunning PipelineRun: buildah-pipeline-run-h9xrb"}
{"level":"debug","msg":"Found the PipelineRun to rerun (buildah-pipeline-run-h9xrb in namespace tekton-pipelines)"}
{"level":"debug","msg":"Rerunning a pipelinerun that's not already been rerun"}
{"level":"debug","msg":"Rerun PipelineRun name is: buildah-pipeline-run-h9xrb-r-"}
{"level":"debug","msg":"Found existing label(s), adding reruns label"}
{"level":"debug","msg":"Rerun ok, name is: buildah-pipeline-run-h9xrb-r-k9fcc"}
{"level":"debug","msg":"PipelineRun Controller detected pipelineRun'buildah-pipeline-run-h9xrb-r-k9fcc' created"}
```

then
```
No TaskRuns found for this PipelineRun yet…
```
in the UI.

```
(base) adams-mbp:dashboard aroberts$ k get prNAME                                 SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
buildah-pipeline-run-h9xrb           True        Succeeded   3d3h     3d3h
buildah-pipeline-run-h9xrb-r-k9fcc
buildah-pipeline-run-lpm4h           False       Failed      3d4h     3d4h
buildah-pipeline-run-qx86k           True        Succeeded   3d3h     3d3h
buildah-pipeline-run-rr6k4           False       Failed      4d5h     4d5h
```

Notice the rebuilt run having no info. This should be looked into with both master and the 0.4.1 release, things don't look right...

**Comment by a-roberts** [comment]
I've checked this behaviour isn't seen on a clean 0.4.1 install
```
(base) adams-mbp:test aroberts$ kgp
NAME                                                                  READY   STATUS      RESTARTS   AGE
buildah-pipeline-run-g2xgf-build-simple-skk7b-pod-b52409              0/5     Pending     0          20m
buildah-pipeline-run-g2xgf-r-cqhzx-build-simple-565hk-pod-815fb8      0/5     Completed   0          65s
el-tekton-webhooks-eventlistener-6b65b6b7cd-62lr2                     1/1     Running     0          24m
pipeline0-run-1579614748753-pipeline0-task-5bs4m-pod-f07739           0/2     Completed   0          34m
pipeline0-run-1579614748753-r-zm9hn-pipeline0-task-d6kgq-pod-cbbc0f   0/2     Completed   0          27m
tekton-dashboard-6df4cb478-56rfs                                      2/2     Running     0          37m
tekton-webhooks-extension-validator-5d8dbffdc8-rmhbq                  1/1     Running     0          40m
webhooks-extension-84bb77f8bb-jvrzx                                   1/1     Running     0          40m
```

so @anxinyf please have a check with our latest 0.4.1 release and let us know more information about your environment 🤞

**Comment by a-roberts** [comment]
Really can't reproduce this on a supported config, @anxinyf let us know once you have more information on the reproduce please and we'll be happy to take a look

**Comment by anxinyf** [comment]
Sorry to reply so late.

The issue appeared in dashboard v0.3.0 when pipeline version was v0.8.0(from this version, serviceAccount to serviceAccountName).
And after I rerun a pipelinerun with spec.serviceAccountName, new pipelinerun is missing the serviceAccountName. But now I have upgraded dashboard version.

In pipeline version v0.8.0 or later and dashboard version v0.5.2, It's ok :)

**Comment by anxinyf** [comment]
@a-roberts Sorry to reply so late.

The issue appeared in dashboard v0.3.0 when pipeline version was v0.8.0(from this version, serviceAccount to serviceAccountName).
And after I rerun a successful pipelinerun with spec.serviceAccountName, new pipelinerun is missing the serviceAccountName and always failed for git access right. But now I have upgraded dashboard version.

In pipeline version v0.8.0 or later and dashboard version v0.5.2, It's ok :)
