### ISSUE TITLE
Publish latest yaml with latest image

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#921]
# Expected Behavior

Installing the latest dashboard image should use the latest yaml

# Actual Behavior

Latest images should be installable via a tekton bucket link as per the dashboard, and https://github.com/tektoncd/dashboard/pull/691#issuecomment-549633461. We've not wanted to make thhe GCS bucket API, but we should at least designate a permanent url for the latest build. The dashboard build logic may need to be updated to as to ensure that the latest yaml is generated and published to GCS. We'll need to publish latest.yaml for plain kube, and OpenShift.

**Comment by a-roberts** [comment]
@mnuttall does this issue change/become invalid based on @afrittoli's work now and thus can be closed? 🤔

**Comment by mnuttall** [comment]
Need to update readme for https://console.cloud.google.com/storage/browser/tekton-releases-nightly/dashboard/latest/
