### ISSUE TITLE
Dashboard tells me there is a new dashboard available 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#929]
# Expected behavior
Dashboard should tell me when a new update is available 
Sort of like an annoying pop up but with useful info

# Actual behavior
I have to manually check if there is a new dashboard available 

# Steps to reproduce the problem

1.
2.
3.

# Environment (e.g. Docker Desktop, OpenShift)

# Tekton Pipelines version (e.g. 0.9.2, 0.8.0, master)

# Tekton Triggers version (e.g. 0.2, 0.1, master)

# Tekton Dashboard version (e.g. 0.4.0, 0.3.0, master)

# Additional Info

**Comment by a-roberts** [comment]
Yeah, this would be cool - so how about in the corner mention that a new version of the dashboard is available and have a button that would then kube apply the latest image? Or, provide a command that lets the user do it trivially that they can copy and paste.
