### ISSUE TITLE
Username in secrets table are displayed encoded

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#974]
# Expected behavior
Username is correct 

# Actual behavior
Username is wrong 
Its the encoded name 

# Steps to reproduce the problem

1. Create secret
2. Look at secret on dashboard 
3.

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info

**Comment by a-roberts** [comment]
I really don't see this as desirable behaviour - if we wanted it to be obfuscated it would be properly done (encoding/decoding is trivial) so marking this as a bug

**Comment by a-roberts** [comment]
Have a two line fix for this, adding a test now

**Comment by a-roberts** [comment]
Fix merged so closing
