### ISSUE TITLE
Create Secrets modal doesnt auto use namespace on left

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#975]
# Expected behavior
Create Secrets modal uses namespace on left 

# Actual behavior
Have to select a namespace myself 

# Steps to reproduce the problem

1. Change namespace on left 
2. Open secrets modal 
3.

# Environment
- Kubernetes Platform:

Docker desktop 

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info

**Comment by AlanGreene** [comment]
I think this was intentional, @carlos-logro maybe you can remember? If we want to change this behaviour we should do it as part of https://github.com/tektoncd/dashboard/issues/727

**Comment by carlos-logro** [comment]
Yeah I don't remember discussing having to choose it from the left side. But sure, ill add it as part of that issue.

**Comment by AlanGreene** [comment]
hrmm I can't find the discussion now, but I'm pretty sure we decided that the namespace dropdown in the create secret dialog should be separate from the one in the nav.

It might make sense to have the namespace dropdown in the create UI default to the selected namespace from the nav, but I think it's still useful to allow the user to then select a different namespace without affecting other pages.

The updated designs only have the global namespaces dropdown on list views, so there would be no conflict in this case as the only namespace dropdown displayed when creating a secret would be the one in the create form.

**Comment by CarolynMabbott** [comment]
@AlanGreene I meant for the create secret modal
Should auto use the namespace on the left in the create modal but the user can change the namespace on either
It's just annoying on openshift where you have the namespace on the left selected as tekton-pipelines and then when creating a secret in the modal you have to scroll all the way down to the namespace in the create modal

**Comment by AlanGreene** [comment]
Yes I agree, that's what I meant by:
> It might make sense to have the namespace dropdown in the create UI default to the selected namespace from the nav

**Comment by AlanGreene** [comment]
Closing in favour of https://github.com/tektoncd/dashboard/issues/1304 which is tracking a single consistent approach to resolving these namespace-related issues.
