### ISSUE TITLE
Unpinned dependencies in a release

### ISSUE THREAD

**Issue by jgawor** [tektoncd/dashboard#978]
The https://github.com/tektoncd/dashboard/releases/download/v0.4.1/dashboard_latest_openshift-tekton-dashboard-release.yaml release has a couple of unpinned dependencies:
  1. ` image: openshift/oauth-proxy:latest`
  2. `image: lachlanevenson/k8s-kubectl:latest`

**Comment by a-roberts** [comment]
The deed is done - release images now pinned
