### ISSUE TITLE
404 returned at localhost:9097 on master

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#98]
Following install instructions in readme for master (at commit 170fa38f0bc2065a376aa272cf758a01dc31dcbb) ..... after portforwarding, we just get a 404 in the browser.

@AlanGreene ?

**Comment by dibbles** [comment]
hmmm - thought it might be because i did not change the web resource dir (not documented) ... but when changing to  value: /go/src/github.com/tektoncd/dashboard/web .... i get the favicon but no page content

**Comment by a-roberts** [comment]
Logging what I've done: followed DEVELOPMENT.md on the commit hash 816fde0a745cb402817469c8c024d1d926bc9884 which involved  npm install, npm run build_ko, ko apply -f config then a port-forward.

I repeated these steps on master too and all is ok

Discussed with @dibbles who's suggested it may be a problem in our main README.md. 

We are following the "non-ko" path which mentions docker building, replacing the image only in the yaml, then kubectl applying.

**Comment by dibbles** [comment]
Docs issue ... need to set web resource dir to ./web.

/assign

**Comment by steveodonovan** [comment]
See my comment here https://github.com/tektoncd/dashboard/pull/99#issuecomment-487550701

[Shouldn't need to set that value](https://github.com/tektoncd/dashboard/blob/master/Dockerfile#L34)

**Comment by a-roberts** [comment]
For anyone else following - we discussed this on Slack - we do indeed need it as we're not using `ko` for the "docker build, push, edit and kubectl apply" case. so we don't get the `/var/run/ko/web`files that's referenced in our deployment yaml.

Stephen raised a good question as to whether or not we want to have a separate deployment file now for Docker installs vs ko installs, and points out we will need such a file anyway when we have releases to reference.

This particular issue is fixed though so closing.
