### ISSUE TITLE
Clicking on service account brings up error

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#981]
# Expected behavior
I can click on a service account and it tells me info 

# Actual behavior
Get an error 
<img width="1149" alt="Screenshot 2020-01-30 at 11 58 22" src="https://user-images.githubusercontent.com/32342288/73448115-13683180-4358-11ea-8064-69282720a3be.png">

# Steps to reproduce the problem

1. Go to service account page 
2. Click on service account 
3.

# Environment
- Kubernetes Platform:

Openshift read only  

- Tekton Pipelines version:

0.10.0

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info

**Comment by a-roberts** [comment]
Yea, reproduced this on our 0.4.1 install too

**Comment by AlanGreene** [comment]
Is this only on specific service accounts or is it affecting all? I'm not seeing it in my dev environment at the moment

**Comment by a-roberts** [comment]
@AlanGreene in my case it's for anything and everything, I'm using OCP 4.2 (happy to share a cluster if you'd like to look into this one closer)

**Comment by a-roberts** [comment]
On OpenShift I've got the following secret patched to the SA default in kube-system:

```
(base) adams-mbp:dashboard aroberts$ k get secret default-dockercfg-2lk5b -o yaml -n kube-system
```
...
```
(base) adams-mbp:dashboard aroberts$ k get secret default-dockercfg-2lk5b -o yaml -n kube-system
apiVersion: v1
data:
  .dockercfg: omitted
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: b804a234-3c47-11ea-b749-00000a1012bb
    openshift.io/token-secret.name: default-token-q6v49
    openshift.io/token-secret.value: omitted
  creationTimestamp: "2020-01-21T12:24:04Z"
  name: default-dockercfg-2lk5b
  namespace: kube-system
  resourceVersion: "15210"
  selfLink: /api/v1/namespaces/kube-system/secrets/default-dockercfg-2lk5b
  uid: e9cdacc4-3c48-11ea-8b2a-00000a101ddb
type: kubernetes.io/dockercfg
```

notice the type.

If I add hardening and debug:

```
 if (serviceAccount.imagePullSecrets && !loading) {
      rowsForImgPull = serviceAccount.imagePullSecrets.map(({ name }) => {
        const foundSecret = secrets.find(secret => secret.name === name);
        let type = 'unknown-type';
        if (foundSecret) {
          console.log(`Found secret to get type of is: ${foundSecret}`);
          const { foundType } = foundSecret;
          console.log(`Found type is: ${type}`);
          if (foundType) {
            type = foundType;
          } else {
            console.log('No found type');
          }
        } else {
          console.log('No found secret');
        }
        return {
          id: name,
          name,
          type
        };
      });
    }
```

I get "No found secret" printed and thus "unknown-type" is displayed. I'm actually confused by the code we've got atm so I'll ponder.

**Comment by a-roberts** [comment]
Fix for this is now merged so closing
