### ISSUE TITLE
Update flow for Pipelines and Tasks

### ISSUE THREAD

**Issue by kimholmes** [tektoncd/dashboard#984]
# Expected behavior
The interactive flow for Pipelines and Tasks should follow the same pattern as it does for other resources. Instead of Resource > Filtered List, it should follow, Resource > Details/YAML
<img width="852" alt="image" src="https://user-images.githubusercontent.com/21316329/73389341-f8d38100-42a1-11ea-8a2a-24298f5aa468.png">

Use this issue to track the design for the contents of this panel:
![image](https://user-images.githubusercontent.com/21316329/73389407-17d21300-42a2-11ea-95a8-e92add5d84bf.png)

# Actual behavior
The current interactions takes the user to a filtered list of PipelineRuns and TaskRuns when the user clicks on the parent Pipeline or Task.
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/21316329/73388744-cc6b3500-42a0-11ea-873a-f767564367cd.png">

Filtered list:
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/21316329/73389084-6f23b380-42a1-11ea-8570-051bca2260c7.png">

**Comment by kimholmes** [comment]
Example of Pipeline diagram. Screenshot from Alan's storybook.
<img width="475" alt="image" src="https://user-images.githubusercontent.com/21316329/73469111-d39f4b00-4353-11ea-8ac1-10c290cb724f.png">

**Comment by mii-w** [comment]
### Pipeline Detail Flow
<img width="992" alt="1" src="https://user-images.githubusercontent.com/51759906/73758286-6bc47800-4738-11ea-883f-d5f8b2d020d9.png">
<img width="868" alt="2" src="https://user-images.githubusercontent.com/51759906/73758293-6e26d200-4738-11ea-8264-cfb6000a5e83.png">
<img width="873" alt="3" src="https://user-images.githubusercontent.com/51759906/73758302-6ff09580-4738-11ea-893b-5ca24c34523b.png">
Possible interaction options, 

1) 
<img width="945" alt="3a" src="https://user-images.githubusercontent.com/51759906/73758309-7252ef80-4738-11ea-9e85-4602296c8a6c.png">

2)
<img width="1016" alt="3b" src="https://user-images.githubusercontent.com/51759906/73758366-8139a200-4738-11ea-8bbe-1a0e84c36efb.png">
<img width="868" alt="4" src="https://user-images.githubusercontent.com/51759906/73758384-85fe5600-4738-11ea-8633-697d706b08ea.png">
<img width="868" alt="5" src="https://user-images.githubusercontent.com/51759906/73758391-88f94680-4738-11ea-80eb-3f6c3266a445.png">

### Tasks and TaskRuns Detail Flow
<img width="884" alt="Screen Shot 2020-02-04 at 10 22 11 AM" src="https://user-images.githubusercontent.com/51759906/73758428-97dff900-4738-11ea-8c3e-9124dad3cd46.png">
<img width="884" alt="Screen Shot 2020-02-04 at 10 22 18 AM" src="https://user-images.githubusercontent.com/51759906/73758441-9a425300-4738-11ea-9891-ba4b5d2920c7.png">
<img width="885" alt="Screen Shot 2020-02-04 at 10 22 26 AM" src="https://user-images.githubusercontent.com/51759906/73758448-9d3d4380-4738-11ea-90f0-4247606d48b0.png">
Possible interaction options, (same as pipeline/pipelinerun)

1) 
<img width="963" alt="Screen Shot 2020-02-04 at 10 23 22 AM" src="https://user-images.githubusercontent.com/51759906/73758506-b0501380-4738-11ea-9cdd-fcb63968a03b.png">

2)
<img width="956" alt="Screen Shot 2020-02-04 at 10 23 12 AM" src="https://user-images.githubusercontent.com/51759906/73758523-b514c780-4738-11ea-9257-299bae71df2e.png">
<img width="879" alt="Screen Shot 2020-02-04 at 10 22 34 AM" src="https://user-images.githubusercontent.com/51759906/73758536-b9d97b80-4738-11ea-8d76-e46c1efbedb6.png">
<img width="882" alt="Screen Shot 2020-02-04 at 10 22 42 AM" src="https://user-images.githubusercontent.com/51759906/73758544-bd6d0280-4738-11ea-8ac5-03f2350adcf0.png">

**Comment by AlanGreene** [comment]
This issue is still valid and has quite a bit of overlap with similar issues tracking general updates for consistency across resource types.

Batch actions (delete) for Pipelines and Tasks will follow the same functionality which is currently being implemented for PipelineRuns and TaskRuns and already in place for PipelineResources and Secrets.

Both Pipelines and Tasks now use the common ResourceDetails component to display the common metadata and YAML views already used by most other resource types. The 'details' tab will be expanded to include more information, likely including some form of visualisation as suggested in the designs here and consistent with the visualisation that will be provided on the PipelineRun and TaskRun details pages.
